In [1]:
import pandas as pd
import numpy as np
import pathfinder as pf

In [2]:
filename = "censo_1872-003_p1.csv"
folder = "planilhas"
path = pf.find_file(filename, folder)
df = pd.read_csv(path)

In [3]:
filename1 = "marcado.csv"
filename2 = "erosão_limiarização.csv"
filename3 = "conversor.csv"
folder = "resultados_ocr"

path = pf.find_file(filename1, folder)
df1 = pd.read_csv(path, header=None)

path = pf.find_file(filename2, folder)
df2 = pd.read_csv(path, header=None)

path = pf.find_file(filename3, folder)
df3 = pd.read_csv(path, header=None)

# Gêneros

In [4]:
sexos = df[['Unnamed: 0','Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3']]
sexos_header = sexos.iloc[1]
sexos.columns = sexos_header
sexos = sexos[2:]

sexos_header = sexos.iloc[0]
sexos.columns = sexos_header
sexos = sexos[1:]

columns_multiindex = pd.MultiIndex.from_tuples([
    #('Gêneros', 'Províncias e Município Neutro'),
    ('', 'Províncias e Município Neutro'),
    ('Gêneros', 'Homens'),
    ('Gêneros', 'Mulheres'),
    ('Gêneros', 'Total')
])

# Atribuindo o MultiIndex às colunas do DataFrame
sexos.columns = columns_multiindex

#print(sexos)
sexos

                                  Gêneros
   Províncias e Município Neutro   Homens Mulheres    Total
3                       Amazonas    30983     2564    56631
4                           Pará   128589    11919   247779
5                       Maranhão   141942    14215   284101
6                          Piauí    90322     8810   178427
7                          Ceará   350906    33886   689773
8            Rio Grande do Norte   112721    10823   220959
9                        Paraíba   179433    17526   354700
10                    Pernambuco   381565    37094   752511
11                       Alagoas   155584    15667   312268
12                       Sergipe    74739     7888   153620
13                         Bahia   630353    58143  1211792
14                Espírito Santo    29607    29871    59478
15              Município Neutro   133880    92153   226033
16                Rio de Janeiro   255806   234281   499087
17                     São Paulo   348304   332438   680742
18                        Paraná    59384    56858   116162
19                Santa Catarina    73088    71730   144818
20             Rio Grande do Sul   191022   176000   367022
21                  Minas Gerais   847592   821684  1669276
22                         Goiás    74968    74775   149743
23                   Mato Grosso    27991    25759    53750
24                         Total  4318699  4100973  8419672

In [5]:
tabela_manual_homens = pd.to_numeric(df.iloc[3:25, 1])


tabela_ocr_homens1 = pd.to_numeric(df1.iloc[:, 0])
diferenca_homens1 = tabela_manual_homens.values - tabela_ocr_homens1.values

tabela_ocr_homens2 = pd.to_numeric(df2.iloc[:, 0])
diferenca_homens2 = tabela_manual_homens.values - tabela_ocr_homens2.values

tabela_ocr_homens3 = pd.to_numeric(df3.iloc[:, 0])
diferenca_homens3 = tabela_manual_homens.values - tabela_ocr_homens3.values

In [6]:
tabela_manual_mulheres = pd.to_numeric(df.iloc[3:25, 2])


tabela_ocr_mulheres1 = pd.to_numeric(df1.iloc[:, 0])
diferenca_mulheres1 = tabela_manual_mulheres.values - tabela_ocr_mulheres1.values

tabela_ocr_mulheres2 = pd.to_numeric(df2.iloc[:, 0])
diferenca_mulheres2 = tabela_manual_mulheres.values - tabela_ocr_mulheres2.values

tabela_ocr_mulheres3 = pd.to_numeric(df3.iloc[:, 0])
diferenca_mulheres3 = tabela_manual_mulheres.values - tabela_ocr_mulheres3.values

In [7]:
tabela_manual_total = pd.to_numeric(df.iloc[3:25, 3])


tabela_ocr_total1 = pd.to_numeric(df1.iloc[:, 0])
diferenca_total1 = tabela_manual_total.values - tabela_ocr_total1.values

tabela_ocr_total2 = pd.to_numeric(df2.iloc[:, 0])
diferenca_total2 = tabela_manual_total.values - tabela_ocr_total2.values

tabela_ocr_total3 = pd.to_numeric(df3.iloc[:, 0])
diferenca_total3 = tabela_manual_total.values - tabela_ocr_total3.values

In [8]:
variancia_homens1 = np.var(diferenca_homens1)
variancia_homens2 = np.var(diferenca_homens2)
variancia_homens3 = np.var(diferenca_homens3)

# Cria um DataFrame com as variáveis como colunas
df_variancia_homens = pd.DataFrame([[variancia_homens1, variancia_homens2, variancia_homens3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
# Renomeia o índice
#df_variancia_homens = df_variancia_homens.rename_axis("Resultado")
df_variancia_homens.index = ["Variância (homens)"]
# Imprime a tabela
df_variancia_homens

                      Sem filtro      Filtro 1      Filtro 2
Variância (homens)  4.379285e+10  2.320923e+10  6.921637e+08

In [9]:
variancia_mulheres1 = np.var(diferenca_mulheres1)
variancia_mulheres2 = np.var(diferenca_mulheres2)
variancia_mulheres3 = np.var(diferenca_mulheres3)

df_variancia_mulheres = pd.DataFrame([[variancia_mulheres1, variancia_mulheres2, variancia_mulheres3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_variancia_mulheres.index = ["Variância (mulheres)"]
df_variancia_mulheres

                        Sem filtro      Filtro 1      Filtro 2
Variância (mulheres)  7.924478e+10  5.886062e+10  2.058806e+10

In [10]:
variancia_total1 = np.var(diferenca_total1)
variancia_total2 = np.var(diferenca_total2)
variancia_total3 = np.var(diferenca_total3)

df_variancia_total = pd.DataFrame([[variancia_total1, variancia_total2, variancia_total3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_variancia_total.index = ["Variância (total)"]
df_variancia_total

                     Sem filtro      Filtro 1      Filtro 2
Variância (total)  7.784838e+11  5.576987e+11  6.946859e+11

In [11]:
desvio_padrao_homens1 = np.std(diferenca_homens1)
desvio_padrao_homens2 = np.std(diferenca_homens2)
desvio_padrao_homens3 = np.std(diferenca_homens3)

df_desvio_padrao_homens = pd.DataFrame([[desvio_padrao_homens1, desvio_padrao_homens2, desvio_padrao_homens3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_desvio_padrao_homens.index = ["Desvio padrão (homens)"]
df_desvio_padrao_homens

                           Sem filtro       Filtro 1      Filtro 2
Desvio padrão (homens)  209267.401301  152345.753666  26309.003213

In [12]:
desvio_padrao_mulheres1 = np.std(diferenca_mulheres1)
desvio_padrao_mulheres2 = np.std(diferenca_mulheres2)
desvio_padrao_mulheres3 = np.std(diferenca_mulheres3)

df_desvio_padrao_mulheres = pd.DataFrame([[desvio_padrao_mulheres1, desvio_padrao_mulheres2, desvio_padrao_mulheres3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_desvio_padrao_mulheres.index = ["Desvio padrão (mulheres)"]
df_desvio_padrao_mulheres

                             Sem filtro       Filtro 1       Filtro 2
Desvio padrão (mulheres)  281504.496887  242612.084992  143485.398396

In [13]:
desvio_padrao_total1 = np.std(diferenca_total1)
desvio_padrao_total2 = np.std(diferenca_total2)
desvio_padrao_total3 = np.std(diferenca_total3)

df_desvio_padrao_total = pd.DataFrame([[desvio_padrao_total1, desvio_padrao_total2, desvio_padrao_total3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_desvio_padrao_total.index = ["Desvio padrão (total)"]
df_desvio_padrao_total

                          Sem filtro       Filtro 1       Filtro 2
Desvio padrão (total)  882317.303392  746792.252647  833478.218382

In [14]:
coeficiente_variacao_homens1 = desvio_padrao_homens1 / np.mean(diferenca_homens1) * 100
coeficiente_variacao_homens2 = desvio_padrao_homens2 / np.mean(diferenca_homens2) * 100
coeficiente_variacao_homens3 = desvio_padrao_homens3 / np.mean(diferenca_homens3) * 100

df_coeficiente_variacao_homens = pd.DataFrame([[coeficiente_variacao_homens1, coeficiente_variacao_homens2, coeficiente_variacao_homens3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_coeficiente_variacao_homens.index = ["Coeficiente de variação (homens)"]
df_coeficiente_variacao_homens

                                  Sem filtro    Filtro 1    Filtro 2
Coeficiente de variação (homens)  1386.30666 -269.174647  359.093745

In [15]:
coeficiente_variacao_mulheres1 = np.std(diferenca_mulheres1)
coeficiente_variacao_mulheres2 = np.std(diferenca_mulheres2)
coeficiente_variacao_mulheres3 = np.std(diferenca_mulheres3)

df_coeficiente_variacao_mulheres = pd.DataFrame([[coeficiente_variacao_mulheres1, coeficiente_variacao_mulheres2, coeficiente_variacao_mulheres3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_coeficiente_variacao_mulheres.index = ["Coeficiente de variação (mulheres)"]
df_coeficiente_variacao_mulheres

,Sem filtro,Filtro 1,Filtro 2
Coeficiente de variação (mulheres),281504.496887,242612.084992,143485.398396

In [16]:
coeficiente_variacao_total1 = np.std(diferenca_total1)
coeficiente_variacao_total2 = np.std(diferenca_total2)
coeficiente_variacao_total3 = np.std(diferenca_total3)

df_coeficiente_variacao_total = pd.DataFrame([[coeficiente_variacao_total1, coeficiente_variacao_total2, coeficiente_variacao_total3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_coeficiente_variacao_total.index = ["Coeficiente de variação (total)"]
df_coeficiente_variacao_total

                                    Sem filtro       Filtro 1       Filtro 2
Coeficiente de variação (total)  882317.303392  746792.252647  833478.218382

In [17]:
media_homens1 = np.std(diferenca_homens1)
media_homens2 = np.std(diferenca_homens2)
media_homens3 = np.std(diferenca_homens3)

df_media_homens = pd.DataFrame([[media_homens1, media_homens2, media_homens3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_media_homens.index = ["Média (homens)"]
df_media_homens

                   Sem filtro       Filtro 1      Filtro 2
Média (homens)  209267.401301  152345.753666  26309.003213

In [18]:
media_mulheres1 = np.std(diferenca_mulheres1)
media_mulheres2 = np.std(diferenca_mulheres2)
media_mulheres3 = np.std(diferenca_mulheres3)

df_media_mulheres = pd.DataFrame([[media_mulheres1, media_mulheres2, media_mulheres3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_media_mulheres.index = ["Média (mulheres)"]
df_media_mulheres

                     Sem filtro       Filtro 1       Filtro 2
Média (mulheres)  281504.496887  242612.084992  143485.398396

In [19]:
media_total1 = np.std(diferenca_total1)
media_total2 = np.std(diferenca_total2)
media_total3 = np.std(diferenca_total3)

df_media_total = pd.DataFrame([[media_total1, media_total2, media_total3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_media_total.index = ["Média (total)"]
df_media_total

                  Sem filtro       Filtro 1       Filtro 2
Média (total)  882317.303392  746792.252647  833478.218382

In [20]:
outlier_inferior_homens1 = media_homens1 - (3 * desvio_padrao_homens1)
outlier_superior_homens1 = media_homens1 + (3 * desvio_padrao_homens1)

outlier_inferior_homens2 = media_homens2 - (3 * desvio_padrao_homens2)
outlier_superior_homens2 = media_homens2 + (3 * desvio_padrao_homens2)

outlier_inferior_homens3 = media_homens3 - (3 * desvio_padrao_homens3)
outlier_superior_homens3 = media_homens3 + (3 * desvio_padrao_homens3)


df_outlier_homens = pd.DataFrame([
    [outlier_inferior_homens1, outlier_superior_homens1,
    outlier_inferior_homens2, outlier_superior_homens2,
    outlier_inferior_homens3, outlier_superior_homens3]
], index=pd.MultiIndex.from_tuples([
    ("",)
]), columns=pd.MultiIndex.from_tuples([
    ("Observação discrepante (homens)", "Sem filtro", "Outlier inferior"),
    ("Observação discrepante (homens)", "Sem filtro", "Outlier superior"),
    ("Observação discrepante (homens)", "Filtro 1", "Outlier inferior"),
    ("Observação discrepante (homens)", "Filtro 1", "Outlier superior"),
    ("Observação discrepante (homens)", "Filtro 2", "Outlier inferior"),
    ("Observação discrepante (homens)", "Filtro 2", "Outlier superior")
]))
df_outlier_homens

 Observação discrepante (homens)                                    \
                      Sem filtro                          Filtro 1
                Outlier inferior Outlier superior Outlier inferior
                  -418534.802602    837069.605204   -304691.507331


                          Filtro 2
 Outlier superior Outlier inferior Outlier superior
    609383.014663    -52618.006426    105236.012852

In [21]:
outlier_inferior_mulheres1 = media_mulheres1 - (3 * desvio_padrao_mulheres1)
outlier_superior_mulheres1 = media_mulheres1 + (3 * desvio_padrao_mulheres1)

outlier_inferior_mulheres2 = media_mulheres2 - (3 * desvio_padrao_mulheres2)
outlier_superior_mulheres2 = media_mulheres2 + (3 * desvio_padrao_mulheres2)

outlier_inferior_mulheres3 = media_mulheres3 - (3 * desvio_padrao_mulheres3)
outlier_superior_mulheres3 = media_mulheres3 + (3 * desvio_padrao_mulheres3)

df_outlier_mulheres = pd.DataFrame([
    [outlier_inferior_mulheres1, outlier_superior_mulheres1,
    outlier_inferior_mulheres2, outlier_superior_mulheres2,
    outlier_inferior_mulheres3, outlier_superior_mulheres3]
], index=pd.MultiIndex.from_tuples([
    ("",)
]), columns=pd.MultiIndex.from_tuples([
    ("Observação discrepante (mulheres)", "Sem filtro", "Outlier inferior"),
    ("Observação discrepante (mulheres)", "Sem filtro", "Outlier superior"),
    ("Observação discrepante (mulheres)", "Filtro 1", "Outlier inferior"),
    ("Observação discrepante (mulheres)", "Filtro 1", "Outlier superior"),
    ("Observação discrepante (mulheres)", "Filtro 2", "Outlier inferior"),
    ("Observação discrepante (mulheres)", "Filtro 2", "Outlier superior")
]))
df_outlier_mulheres

 Observação discrepante (mulheres)                                    \
                        Sem filtro                          Filtro 1
                  Outlier inferior Outlier superior Outlier inferior
                    -563008.993775     1.126018e+06   -485224.169985


                          Filtro 2
 Outlier superior Outlier inferior Outlier superior
    970448.339969   -286970.796792    573941.593583

In [22]:
outlier_inferior_total1 = media_total1 - (3 * desvio_padrao_total1)
outlier_superior_total1 = media_total1 + (3 * desvio_padrao_total1)

outlier_inferior_total2 = media_total2 - (3 * desvio_padrao_total2)
outlier_superior_total2 = media_total2 + (3 * desvio_padrao_total2)

outlier_inferior_total3 = media_total3 - (3 * desvio_padrao_total3)
outlier_superior_total3 = media_total3 + (3 * desvio_padrao_total3)

df_outlier_total = pd.DataFrame([
    [outlier_inferior_total1, outlier_superior_total1,
    outlier_inferior_total2, outlier_superior_total2,
    outlier_inferior_total3, outlier_superior_total3]
], index=pd.MultiIndex.from_tuples([
    ("",)
]), columns=pd.MultiIndex.from_tuples([
    ("Observação discrepante (total)", "Sem filtro", "Outlier inferior"),
    ("Observação discrepante (total)", "Sem filtro", "Outlier superior"),
    ("Observação discrepante (total)", "Filtro 1", "Outlier inferior"),
    ("Observação discrepante (total)", "Filtro 1", "Outlier superior"),
    ("Observação discrepante (total)", "Filtro 2", "Outlier inferior"),
    ("Observação discrepante (total)", "Filtro 2", "Outlier superior")
]))
df_outlier_total

 Observação discrepante (total)                                    \
                     Sem filtro                          Filtro 1
               Outlier inferior Outlier superior Outlier inferior
                  -1.764635e+06     3.529269e+06    -1.493585e+06


                          Filtro 2
 Outlier superior Outlier inferior Outlier superior
     2.987169e+06    -1.666956e+06     3.333913e+06

# Estados civis

In [23]:
estados_civis = df[['Unnamed: 0','Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9']]

estados_civis_header = estados_civis.iloc[2]
estados_civis.columns = estados_civis_header
estados_civis = estados_civis[3:]

columns_multiindex = pd.MultiIndex.from_tuples([
    #('Gêneros', 'Províncias e Município Neutro'),
    ('', '', 'Províncias e Município Neutro'),
    ('Estados civis', 'dos Homens', 'Solteiros'),
    ('Estados civis', 'dos Homens', 'Casados'),
    ('Estados civis', 'dos Homens', 'Viúvos'),
    ('Estados civis', 'das Mulheres', 'Solteiras'),
    ('Estados civis', 'das Mulheres', 'Casadas'),
    ('Estados civis', 'das Mulheres', 'Viúvas')
])

# Atribuindo o MultiIndex às colunas do DataFrame
estados_civis.columns = columns_multiindex

estados_civis

                                 Estados civis                                \
                                    dos Homens                  das Mulheres
   Províncias e Município Neutro     Solteiros  Casados  Viúvos    Solteiras
3                       Amazonas         24959     5105     919        19214
4                           Pará         94848    28935    4806        86825
5                       Maranhão        103283    33644    5015       102302
6                          Piauí         63294    23323    3705        59547
7                          Ceará        241692    99915    9299       224509
8            Rio Grande do Norte         80803    26832    5086        75915
9                        Paraíba        119403    53474    6556       112332
10                    Pernambuco        258936   111189   11440       240239
11                       Alagoas        102729    47865    4990        99772
12                       Sergipe         48013    24027    2699        50746
13                         Bahia        440556   160204   29593       398473
14                Espírito Santo         19415     9298     894        19251
15              Município Neutro        104036    25763    4081        64074
16                Rio de Janeiro        168391    71842   15573       148840
17                     São Paulo        234386    98864   15054       218684
18                        Paraná         37977    18649    2678        35006
19                Santa Catarina         49985    21351    1752        47122
20             Rio Grande do Sul        139899    45104    6019       124864
21                  Minas Gerais        572728   231947   42917       557389
22                         Goiás         51886    20696    2386        50125
23                   Mato Grosso         18227     7839    1925        17353
24                         Total       2975446  1165866  177387      2752582



    Casadas  Viúvas
3      4714    1720
4     26280    6085
5     32337    7520
6     23371    5187
7     99849   14509
8     26735    5588
9     53274    9661
10   111465   19242
11    46743   10169
12    24795    3340
13   151883   31083
14     9449    1171
15    20174    7905
16    68726   16715
17    96290   17464
18    18332    3520
19    20412    4196
20    41525    9611
21   217353   46942
22    20340    4310
23     6953    1453
24  1121000  227391

In [24]:
tabela_manual_solteiros = pd.to_numeric(df.iloc[3:25, 4])

tabela_ocr_solteiros1 = pd.to_numeric(df1.iloc[:, 3])
diferenca_solteiros1 = tabela_manual_solteiros.values - tabela_ocr_solteiros1.values

tabela_ocr_solteiros2 = pd.to_numeric(df2.iloc[:, 3])
diferenca_solteiros2 = tabela_manual_solteiros.values - tabela_ocr_solteiros2.values

tabela_ocr_solteiros3 = pd.to_numeric(df3.iloc[:, 3])
diferenca_solteiros3 = tabela_manual_solteiros.values - tabela_ocr_solteiros3.values

In [25]:
tabela_manual_casados = pd.to_numeric(df.iloc[3:25, 5])

tabela_ocr_casados1 = pd.to_numeric(df1.iloc[:, 4])
diferenca_casados1 = tabela_manual_casados.values - tabela_ocr_casados1.values

tabela_ocr_casados2 = pd.to_numeric(df2.iloc[:, 4])
diferenca_casados2 = tabela_manual_casados.values - tabela_ocr_casados2.values

tabela_ocr_casados3 = pd.to_numeric(df3.iloc[:, 4])
diferenca_casados3 = tabela_manual_casados.values - tabela_ocr_casados3.values

In [26]:
tabela_manual_viuvos = pd.to_numeric(df.iloc[3:25, 6])

tabela_ocr_viuvos1 = pd.to_numeric(df1.iloc[:, 5])
diferenca_viuvos1 = tabela_manual_viuvos.values - tabela_ocr_viuvos1.values

tabela_ocr_viuvos2 = pd.to_numeric(df2.iloc[:, 5])
diferenca_viuvos2 = tabela_manual_viuvos.values - tabela_ocr_viuvos2.values

tabela_ocr_viuvos3 = pd.to_numeric(df3.iloc[:, 5])
diferenca_viuvos3 = tabela_manual_viuvos.values - tabela_ocr_viuvos3.values

In [27]:
tabela_manual_solteiras = pd.to_numeric(df.iloc[3:25, 7])

tabela_ocr_solteiras1 = pd.to_numeric(df1.iloc[:, 6])
diferenca_solteiras1 = tabela_manual_solteiras.values - tabela_ocr_solteiras1.values

tabela_ocr_solteiras2 = pd.to_numeric(df2.iloc[:, 6])
diferenca_solteiras2 = tabela_manual_solteiras.values - tabela_ocr_solteiras2.values

tabela_ocr_solteiras3 = pd.to_numeric(df3.iloc[:, 6])
diferenca_solteiras3 = tabela_manual_solteiras.values - tabela_ocr_solteiras3.values

In [28]:
tabela_manual_casadas = pd.to_numeric(df.iloc[3:25, 8])

tabela_ocr_casadas1 = pd.to_numeric(df1.iloc[:, 7])
diferenca_casadas1 = tabela_manual_casadas.values - tabela_ocr_casadas1.values

tabela_ocr_casadas2 = pd.to_numeric(df2.iloc[:, 7])
diferenca_casadas2 = tabela_manual_casadas.values - tabela_ocr_casadas2.values

tabela_ocr_casadas3 = pd.to_numeric(df3.iloc[:, 7])
diferenca_casadas3 = tabela_manual_casadas.values - tabela_ocr_casadas3.values

In [29]:
tabela_manual_viuvas = pd.to_numeric(df.iloc[3:25, 9])

tabela_ocr_viuvas1 = pd.to_numeric(df1.iloc[:, 8])
diferenca_viuvas1 = tabela_manual_viuvas.values - tabela_ocr_viuvas1.values

tabela_ocr_viuvas2 = pd.to_numeric(df2.iloc[:, 8])
diferenca_viuvas2 = tabela_manual_viuvas.values - tabela_ocr_viuvas2.values

tabela_ocr_viuvas3 = pd.to_numeric(df3.iloc[:, 8])
diferenca_viuvas3 = tabela_manual_viuvas.values - tabela_ocr_viuvas3.values

In [30]:
variancia_solteiros1 = np.var(diferenca_solteiros1)
variancia_solteiros2 = np.var(diferenca_solteiros2)
variancia_solteiros3 = np.var(diferenca_solteiros3)

df_variancia_solteiros = pd.DataFrame([[variancia_solteiros1, variancia_solteiros2, variancia_solteiros3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_variancia_solteiros.index = ["Variância (solteiros)"]
df_variancia_solteiros

                       Sem filtro      Filtro 1      Filtro 2
Variância (solteiros)    3.902893  2.820334e+10  2.115180e+09

In [31]:
variancia_casados1 = np.var(diferenca_casados1)
variancia_casados2 = np.var(diferenca_casados2)
variancia_casados3 = np.var(diferenca_casados3)

df_variancia_casados = pd.DataFrame([[variancia_casados1, variancia_casados2, variancia_casados3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_variancia_casados.index = ["Variância (casados)"]
df_variancia_casados

                       Sem filtro      Filtro 1      Filtro 2
Variância (casados)  2.166190e+08  1.967243e+08  5.122927e+08

In [32]:
variancia_viuvos1 = np.var(diferenca_viuvos1)
variancia_viuvos2 = np.var(diferenca_viuvos2)
variancia_viuvos3 = np.var(diferenca_viuvos3)

df_variancia_viuvos = pd.DataFrame([[variancia_viuvos1, variancia_viuvos2, variancia_viuvos3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_variancia_viuvos.index = ["Variância (viúvos)"]
df_variancia_viuvos

                      Sem filtro      Filtro 1      Filtro 2
Variância (viúvos)  3.111253e+06  2.897686e+09  8.523235e+06

In [33]:
variancia_solteiras1 = np.var(diferenca_solteiras1)
variancia_solteiras2 = np.var(diferenca_solteiras2)
variancia_solteiras3 = np.var(diferenca_solteiras3)

df_variancia_solteiras = pd.DataFrame([[variancia_solteiras1, variancia_solteiras2, variancia_solteiras3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_variancia_solteiras.index = ["Variância (solteiras)"]
df_variancia_solteiras

                         Sem filtro      Filtro 1      Filtro 2
Variância (solteiras)  4.379005e+07  1.096054e+09  3.514389e+08

In [34]:
variancia_casadas1 = np.var(diferenca_casadas1)
variancia_casadas2 = np.var(diferenca_casadas2)
variancia_casadas3 = np.var(diferenca_casadas3)

df_variancia_casadas = pd.DataFrame([[variancia_casadas1, variancia_casadas2, variancia_casadas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_variancia_casadas.index = ["Variância (casadas)"]
df_variancia_casadas

                       Sem filtro      Filtro 1      Filtro 2
Variância (casadas)  5.515881e+06  2.236706e+10  4.338843e+06

In [35]:
variancia_viuvas1 = np.var(diferenca_viuvas1)
variancia_viuvas2 = np.var(diferenca_viuvas2)
variancia_viuvas3 = np.var(diferenca_viuvas3)

df_variancia_viuvas = pd.DataFrame([[variancia_viuvas1, variancia_viuvas2, variancia_viuvas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_variancia_viuvas.index = ["Variância (viúvas)"]
df_variancia_viuvas

                      Sem filtro      Filtro 1      Filtro 2
Variância (viúvas)  9.814798e+07  2.281530e+09  8.737456e+07

In [36]:
desvio_padrao_solteiros1 = np.std(diferenca_solteiros1)
desvio_padrao_solteiros2 = np.std(diferenca_solteiros2)
desvio_padrao_solteiros3 = np.std(diferenca_solteiros3)

df_desvio_padrao_solteiros = pd.DataFrame([[desvio_padrao_solteiros1, desvio_padrao_solteiros2, desvio_padrao_solteiros3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_desvio_padrao_solteiros.index = ["Desvio padrão (solteiros)"]
df_desvio_padrao_solteiros

                           Sem filtro      Filtro 1      Filtro 2
Desvio padrão (solteiros)    1.975574  167938.49864  45991.084538

In [37]:
desvio_padrao_casados1 = np.std(diferenca_casados1)
desvio_padrao_casados2 = np.std(diferenca_casados2)
desvio_padrao_casados3 = np.std(diferenca_casados3)

df_desvio_padrao_casados = pd.DataFrame([[desvio_padrao_casados1, desvio_padrao_casados2, desvio_padrao_casados3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_desvio_padrao_casados.index = ["Desvio padrão (casados)"]
df_desvio_padrao_casados

                           Sem filtro      Filtro 1      Filtro 2
Desvio padrão (casados)  14717.980549  14025.843484  22633.884591

In [38]:
desvio_padrao_viuvos1 = np.std(diferenca_viuvos1)
desvio_padrao_viuvos2 = np.std(diferenca_viuvos2)
desvio_padrao_viuvos3 = np.std(diferenca_viuvos3)

df_desvio_padrao_viuvos = pd.DataFrame([[desvio_padrao_viuvos1, desvio_padrao_viuvos2, desvio_padrao_viuvos3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_desvio_padrao_viuvos.index = ["Desvio padrão (viúvos)"]
df_desvio_padrao_viuvos

                         Sem filtro      Filtro 1     Filtro 2
Desvio padrão (viúvos)  1763.874471  53830.160414  2919.458068

In [39]:
desvio_padrao_solteiras1 = np.std(diferenca_solteiras1)
desvio_padrao_solteiras2 = np.std(diferenca_solteiras2)
desvio_padrao_solteiras3 = np.std(diferenca_solteiras3)

df_desvio_padrao_solteiras = pd.DataFrame([[desvio_padrao_solteiras1, desvio_padrao_solteiras2, desvio_padrao_solteiras3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_desvio_padrao_solteiras.index = ["Desvio padrão (solteiras)"]
df_desvio_padrao_solteiras

                            Sem filtro      Filtro 1     Filtro 2
Desvio padrão (solteiras)  6617.405379  33106.706833  18746.70338

In [40]:
desvio_padrao_casadas1 = np.std(diferenca_casadas1)
desvio_padrao_casadas2 = np.std(diferenca_casadas2)
desvio_padrao_casadas3 = np.std(diferenca_casadas3)

df_desvio_padrao_casadas = pd.DataFrame([[desvio_padrao_casadas1, desvio_padrao_casadas2, desvio_padrao_casadas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_desvio_padrao_casadas.index = ["Desvio padrão (casadas)"]
df_desvio_padrao_casadas

                          Sem filtro       Filtro 1     Filtro 2
Desvio padrão (casadas)  2348.591225  149556.206676  2082.988952

In [41]:
desvio_padrao_viuvas1 = np.std(diferenca_viuvas1)
desvio_padrao_viuvas2 = np.std(diferenca_viuvas2)
desvio_padrao_viuvas3 = np.std(diferenca_viuvas3)

df_desvio_padrao_viuvas = pd.DataFrame([[desvio_padrao_viuvas1, desvio_padrao_viuvas2, desvio_padrao_viuvas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_desvio_padrao_viuvas.index = ["Desvio padrão (viúvas)"]
df_desvio_padrao_viuvas

                         Sem filtro      Filtro 1     Filtro 2
Desvio padrão (viúvas)  9906.966409  47765.362402  9347.435841

In [42]:
coeficiente_variacao_solteiros1 = desvio_padrao_solteiros1 / np.mean(diferenca_solteiros1) * 100
coeficiente_variacao_solteiros2 = desvio_padrao_solteiros2 / np.mean(diferenca_solteiros2) * 100
coeficiente_variacao_solteiros3 = desvio_padrao_solteiros3 / np.mean(diferenca_solteiros3) * 100

df_coeficiente_variacao_solteiros = pd.DataFrame([[coeficiente_variacao_solteiros1, coeficiente_variacao_solteiros2, coeficiente_variacao_solteiros3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_coeficiente_variacao_solteiros.index = ["Coeficiente de variação (solteiros)"]
df_coeficiente_variacao_solteiros

                                     Sem filtro    Filtro 1    Filtro 2
Coeficiente de variação (solteiros) -255.662515 -1222.00513  320.318817

In [43]:
coeficiente_variacao_casados1 = desvio_padrao_casados1 / np.mean(diferenca_casados1) * 100
coeficiente_variacao_casados2 = desvio_padrao_casados2 / np.mean(diferenca_casados2) * 100
coeficiente_variacao_casados3 = desvio_padrao_casados3 / np.mean(diferenca_casados3) * 100

df_coeficiente_variacao_casados = pd.DataFrame([[coeficiente_variacao_casados1, coeficiente_variacao_casados2, coeficiente_variacao_casados3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_coeficiente_variacao_casados.index = ["Coeficiente de variação (casados)"]
df_coeficiente_variacao_casados

                                     Sem filtro    Filtro 1    Filtro 2
Coeficiente de variação (casados) -10976.121088  311.166799  323.058008

In [44]:
coeficiente_variacao_viuvos1 = desvio_padrao_viuvos1 / np.mean(diferenca_viuvos1) * 100
coeficiente_variacao_viuvos2 = desvio_padrao_viuvos2 / np.mean(diferenca_viuvos2) * 100
coeficiente_variacao_viuvos3 = desvio_padrao_viuvos3 / np.mean(diferenca_viuvos3) * 100

df_coeficiente_variacao_viuvos = pd.DataFrame([[coeficiente_variacao_viuvos1, coeficiente_variacao_viuvos2, coeficiente_variacao_viuvos3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_coeficiente_variacao_viuvos.index = ["Coeficiente de variação (viúvos)"]
df_coeficiente_variacao_viuvos

                                  Sem filtro     Filtro 1    Filtro 2
Coeficiente de variação (viúvos) -340.247596 -6617.106382  458.052186

In [45]:
coeficiente_variacao_solteiras1 = desvio_padrao_solteiras1 / np.mean(diferenca_solteiras1) * 100
coeficiente_variacao_solteiras2 = desvio_padrao_solteiras2 / np.mean(diferenca_solteiras2) * 100
coeficiente_variacao_solteiras3 = desvio_padrao_solteiras3 / np.mean(diferenca_solteiras3) * 100

df_coeficiente_variacao_solteiras = pd.DataFrame([[coeficiente_variacao_solteiras1, coeficiente_variacao_solteiras2, coeficiente_variacao_solteiras3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_coeficiente_variacao_solteiras.index = ["Coeficiente de variação (solteiras)"]
df_coeficiente_variacao_solteiras

                                     Sem filtro    Filtro 1    Filtro 2
Coeficiente de variação (solteiras)   -722.9623  639.827426  458.150938

In [46]:
coeficiente_variacao_casadas1 = desvio_padrao_casadas1 / np.mean(diferenca_casadas1) * 100
coeficiente_variacao_casadas2 = desvio_padrao_casadas2 / np.mean(diferenca_casadas2) * 100
coeficiente_variacao_casadas3 = desvio_padrao_casadas3 / np.mean(diferenca_casadas3) * 100

df_coeficiente_variacao_casadas = pd.DataFrame([[coeficiente_variacao_casadas1, coeficiente_variacao_casadas2, coeficiente_variacao_casadas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_coeficiente_variacao_casadas.index = ["Coeficiente de variação (casadas)"]
df_coeficiente_variacao_casadas

                                   Sem filtro    Filtro 1    Filtro 2
Coeficiente de variação (casadas) -878.724608 -625.821269 -458.257569

In [47]:
coeficiente_variacao_viuvas1 = desvio_padrao_viuvas1 / np.mean(diferenca_viuvas1) * 100
coeficiente_variacao_viuvas2 = desvio_padrao_viuvas2 / np.mean(diferenca_viuvas2) * 100
coeficiente_variacao_viuvas3 = desvio_padrao_viuvas3 / np.mean(diferenca_viuvas3) * 100

df_coeficiente_variacao_viuvas = pd.DataFrame([[coeficiente_variacao_viuvas1, coeficiente_variacao_viuvas2, coeficiente_variacao_viuvas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_coeficiente_variacao_viuvas.index = ["Coeficiente de variação (viúvas)"]
df_coeficiente_variacao_viuvas

                                  Sem filtro    Filtro 1    Filtro 2
Coeficiente de variação (viúvas)  287.947552  311.503383  230.124201

In [48]:
media_solteiros1 = np.std(diferenca_solteiros1)
media_solteiros2 = np.std(diferenca_solteiros2)
media_solteiros3 = np.std(diferenca_solteiros3)

df_media_solteiros = pd.DataFrame([[media_solteiros1, media_solteiros2, media_solteiros3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_media_solteiros.index = ["Média (solteiros)"]
df_media_solteiros

                   Sem filtro      Filtro 1      Filtro 2
Média (solteiros)    1.975574  167938.49864  45991.084538

In [49]:
media_casados1 = np.std(diferenca_casados1)
media_casados2 = np.std(diferenca_casados2)
media_casados3 = np.std(diferenca_casados3)

df_media_casados = pd.DataFrame([[media_casados1, media_casados2, media_casados3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_media_casados.index = ["Média (casados)"]
df_media_casados

                   Sem filtro      Filtro 1      Filtro 2
Média (casados)  14717.980549  14025.843484  22633.884591

In [50]:
media_viuvos1 = np.std(diferenca_viuvos1)
media_viuvos2 = np.std(diferenca_viuvos2)
media_viuvos3 = np.std(diferenca_viuvos3)

df_media_viuvos = pd.DataFrame([[media_viuvos1, media_viuvos2, media_viuvos3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_media_viuvos.index = ["Média (viúvos)"]
df_media_viuvos

                 Sem filtro      Filtro 1     Filtro 2
Média (viúvos)  1763.874471  53830.160414  2919.458068

In [51]:
media_solteiras1 = np.std(diferenca_solteiras1)
media_solteiras2 = np.std(diferenca_solteiras2)
media_solteiras3 = np.std(diferenca_solteiras3)

df_media_solteiras = pd.DataFrame([[media_solteiras1, media_solteiras2, media_solteiras3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_media_solteiras.index = ["Média (solteiras)"]
df_media_solteiras

                    Sem filtro      Filtro 1     Filtro 2
Média (solteiras)  6617.405379  33106.706833  18746.70338

In [52]:
media_casadas1 = np.std(diferenca_casadas1)
media_casadas2 = np.std(diferenca_casadas2)
media_casadas3 = np.std(diferenca_casadas3)

df_media_casadas = pd.DataFrame([[media_casadas1, media_casadas2, media_casadas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_media_casadas.index = ["Média (casadas)"]
df_media_casadas

                  Sem filtro       Filtro 1     Filtro 2
Média (casadas)  2348.591225  149556.206676  2082.988952

In [53]:
media_viuvas1 = np.std(diferenca_viuvas1)
media_viuvas2 = np.std(diferenca_viuvas2)
media_viuvas3 = np.std(diferenca_viuvas3)

df_media_viuvas = pd.DataFrame([[media_viuvas1, media_viuvas2, media_viuvas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_media_viuvas.index = ["Média (viúvas)"]
df_media_viuvas

                 Sem filtro      Filtro 1     Filtro 2
Média (viúvas)  9906.966409  47765.362402  9347.435841

In [54]:
outlier_inferior_solteiros1 = media_solteiros1 - (3 * desvio_padrao_solteiros1)
outlier_superior_solteiros1 = media_solteiros1 + (3 * desvio_padrao_solteiros1)

outlier_inferior_solteiros2 = media_solteiros2 - (3 * desvio_padrao_solteiros2)
outlier_superior_solteiros2 = media_solteiros2 + (3 * desvio_padrao_solteiros2)

outlier_inferior_solteiros3 = media_solteiros3 - (3 * desvio_padrao_solteiros3)
outlier_superior_solteiros3 = media_solteiros3 + (3 * desvio_padrao_solteiros3)


df_outlier_solteiros = pd.DataFrame([
    [outlier_inferior_solteiros1, outlier_superior_solteiros1,
    outlier_inferior_solteiros2, outlier_superior_solteiros2,
    outlier_inferior_solteiros3, outlier_superior_solteiros3]
], index=pd.MultiIndex.from_tuples([
    ("",)
]), columns=pd.MultiIndex.from_tuples([
    ("Observação discrepante (solteiros)", "Sem filtro", "Outlier inferior"),
    ("Observação discrepante (solteiros)", "Sem filtro", "Outlier superior"),
    ("Observação discrepante (solteiros)", "Filtro 1", "Outlier inferior"),
    ("Observação discrepante (solteiros)", "Filtro 1", "Outlier superior"),
    ("Observação discrepante (solteiros)", "Filtro 2", "Outlier inferior"),
    ("Observação discrepante (solteiros)", "Filtro 2", "Outlier superior")
]))
df_outlier_solteiros

 Observação discrepante (solteiros)                                    \
                         Sem filtro                          Filtro 1
                   Outlier inferior Outlier superior Outlier inferior
                          -3.951148         7.902296   -335876.997281


                          Filtro 2
 Outlier superior Outlier inferior Outlier superior
    671753.994561    -91982.169076    183964.338152

In [55]:
outlier_inferior_casados1 = media_casados1 - (3 * desvio_padrao_casados1)
outlier_superior_casados1 = media_casados1 + (3 * desvio_padrao_casados1)

outlier_inferior_casados2 = media_casados2 - (3 * desvio_padrao_casados2)
outlier_superior_casados2 = media_casados2 + (3 * desvio_padrao_casados2)

outlier_inferior_casados3 = media_casados3 - (3 * desvio_padrao_casados3)
outlier_superior_casados3 = media_casados3 + (3 * desvio_padrao_casados3)


df_outlier_casados = pd.DataFrame([
    [outlier_inferior_casados1, outlier_superior_casados1,
    outlier_inferior_casados2, outlier_superior_casados2,
    outlier_inferior_casados3, outlier_superior_casados3]
], index=pd.MultiIndex.from_tuples([
    ("",)
]), columns=pd.MultiIndex.from_tuples([
    ("Observação discrepante (casados)", "Sem filtro", "Outlier inferior"),
    ("Observação discrepante (casados)", "Sem filtro", "Outlier superior"),
    ("Observação discrepante (casados)", "Filtro 1", "Outlier inferior"),
    ("Observação discrepante (casados)", "Filtro 1", "Outlier superior"),
    ("Observação discrepante (casados)", "Filtro 2", "Outlier inferior"),
    ("Observação discrepante (casados)", "Filtro 2", "Outlier superior")
]))
df_outlier_casados

 Observação discrepante (casados)                                    \
                       Sem filtro                          Filtro 1
                 Outlier inferior Outlier superior Outlier inferior
                    -29435.961098     58871.922197    -28051.686968


                          Filtro 2
 Outlier superior Outlier inferior Outlier superior
     56103.373935    -45267.769181     90535.538363

In [56]:
outlier_inferior_viuvos1 = media_viuvos1 - (3 * desvio_padrao_viuvos1)
outlier_superior_viuvos1 = media_viuvos1 + (3 * desvio_padrao_viuvos1)

outlier_inferior_viuvos2 = media_viuvos2 - (3 * desvio_padrao_viuvos2)
outlier_superior_viuvos2 = media_viuvos2 + (3 * desvio_padrao_viuvos2)

outlier_inferior_viuvos3 = media_viuvos3 - (3 * desvio_padrao_viuvos3)
outlier_superior_viuvos3 = media_viuvos3 + (3 * desvio_padrao_viuvos3)


df_outlier_viuvos = pd.DataFrame([
    [outlier_inferior_viuvos1, outlier_superior_viuvos1,
    outlier_inferior_viuvos2, outlier_superior_viuvos2,
    outlier_inferior_viuvos3, outlier_superior_viuvos3]
], index=pd.MultiIndex.from_tuples([
    ("",)
]), columns=pd.MultiIndex.from_tuples([
    ("Observação discrepante (viúvos)", "Sem filtro", "Outlier inferior"),
    ("Observação discrepante (viúvos)", "Sem filtro", "Outlier superior"),
    ("Observação discrepante (viúvos)", "Filtro 1", "Outlier inferior"),
    ("Observação discrepante (viúvos)", "Filtro 1", "Outlier superior"),
    ("Observação discrepante (viúvos)", "Filtro 2", "Outlier inferior"),
    ("Observação discrepante (viúvos)", "Filtro 2", "Outlier superior")
]))
df_outlier_viuvos

 Observação discrepante (viúvos)                                    \
                      Sem filtro                          Filtro 1
                Outlier inferior Outlier superior Outlier inferior
                    -3527.748943      7055.497886   -107660.320829


                          Filtro 2
 Outlier superior Outlier inferior Outlier superior
    215320.641658     -5838.916137     11677.832274

In [57]:
outlier_inferior_solteiras1 = media_solteiras1 - (3 * desvio_padrao_solteiras1)
outlier_superior_solteiras1 = media_solteiras1 + (3 * desvio_padrao_solteiras1)

outlier_inferior_solteiras2 = media_solteiras2 - (3 * desvio_padrao_solteiras2)
outlier_superior_solteiras2 = media_solteiras2 + (3 * desvio_padrao_solteiras2)

outlier_inferior_solteiras3 = media_solteiras3 - (3 * desvio_padrao_solteiras3)
outlier_superior_solteiras3 = media_solteiras3 + (3 * desvio_padrao_solteiras3)


df_outlier_solteiras = pd.DataFrame([
    [outlier_inferior_solteiras1, outlier_superior_solteiras1,
    outlier_inferior_solteiras2, outlier_superior_solteiras2,
    outlier_inferior_solteiras3, outlier_superior_solteiras3]
], index=pd.MultiIndex.from_tuples([
    ("",)
]), columns=pd.MultiIndex.from_tuples([
    ("Observação discrepante (solteiras)", "Sem filtro", "Outlier inferior"),
    ("Observação discrepante (solteiras)", "Sem filtro", "Outlier superior"),
    ("Observação discrepante (solteiras)", "Filtro 1", "Outlier inferior"),
    ("Observação discrepante (solteiras)", "Filtro 1", "Outlier superior"),
    ("Observação discrepante (solteiras)", "Filtro 2", "Outlier inferior"),
    ("Observação discrepante (solteiras)", "Filtro 2", "Outlier superior")
]))
df_outlier_solteiras

 Observação discrepante (solteiras)                                    \
                         Sem filtro                          Filtro 1
                   Outlier inferior Outlier superior Outlier inferior
                      -13234.810757     26469.621514    -66213.413665


                          Filtro 2
 Outlier superior Outlier inferior Outlier superior
    132426.827331    -37493.406759     74986.813518

In [58]:
outlier_inferior_casadas1 = media_casadas1 - (3 * desvio_padrao_casadas1)
outlier_superior_casadas1 = media_casadas1 + (3 * desvio_padrao_casadas1)

outlier_inferior_casadas2 = media_casadas2 - (3 * desvio_padrao_casadas2)
outlier_superior_casadas2 = media_casadas2 + (3 * desvio_padrao_casadas2)

outlier_inferior_casadas3 = media_casadas3 - (3 * desvio_padrao_casadas3)
outlier_superior_casadas3 = media_casadas3 + (3 * desvio_padrao_casadas3)


df_outlier_casadas = pd.DataFrame([
    [outlier_inferior_casadas1, outlier_superior_casadas1,
    outlier_inferior_casadas2, outlier_superior_casadas2,
    outlier_inferior_casadas3, outlier_superior_casadas3]
], index=pd.MultiIndex.from_tuples([
    ("",)
]), columns=pd.MultiIndex.from_tuples([
    ("Observação discrepante (casadas)", "Sem filtro", "Outlier inferior"),
    ("Observação discrepante (casadas)", "Sem filtro", "Outlier superior"),
    ("Observação discrepante (casadas)", "Filtro 1", "Outlier inferior"),
    ("Observação discrepante (casadas)", "Filtro 1", "Outlier superior"),
    ("Observação discrepante (casadas)", "Filtro 2", "Outlier inferior"),
    ("Observação discrepante (casadas)", "Filtro 2", "Outlier superior")
]))
df_outlier_casadas

 Observação discrepante (casadas)                                    \
                       Sem filtro                          Filtro 1
                 Outlier inferior Outlier superior Outlier inferior
                     -4697.182451      9394.364901   -299112.413353


                          Filtro 2
 Outlier superior Outlier inferior Outlier superior
    598224.826705     -4165.977905      8331.955809

In [59]:
outlier_inferior_viuvas1 = media_viuvas1 - (3 * desvio_padrao_viuvas1)
outlier_superior_viuvas1 = media_viuvas1 + (3 * desvio_padrao_viuvas1)

outlier_inferior_viuvas2 = media_viuvas2 - (3 * desvio_padrao_viuvas2)
outlier_superior_viuvas2 = media_viuvas2 + (3 * desvio_padrao_viuvas2)

outlier_inferior_viuvas3 = media_viuvas3 - (3 * desvio_padrao_viuvas3)
outlier_superior_viuvas3 = media_viuvas3 + (3 * desvio_padrao_viuvas3)


df_outlier_viuvas = pd.DataFrame([
    [outlier_inferior_viuvas1, outlier_superior_viuvas1,
    outlier_inferior_viuvas2, outlier_superior_viuvas2,
    outlier_inferior_viuvas3, outlier_superior_viuvas3]
], index=pd.MultiIndex.from_tuples([
    ("",)
]), columns=pd.MultiIndex.from_tuples([
    ("Observação discrepante (viúvas)", "Sem filtro", "Outlier inferior"),
    ("Observação discrepante (viúvas)", "Sem filtro", "Outlier superior"),
    ("Observação discrepante (viúvas)", "Filtro 1", "Outlier inferior"),
    ("Observação discrepante (viúvas)", "Filtro 1", "Outlier superior"),
    ("Observação discrepante (viúvas)", "Filtro 2", "Outlier inferior"),
    ("Observação discrepante (viúvas)", "Filtro 2", "Outlier superior")
]))
df_outlier_viuvas

 Observação discrepante (viúvas)                                    \
                      Sem filtro                          Filtro 1
                Outlier inferior Outlier superior Outlier inferior
                   -19813.932818     39627.865636    -95530.724805


                          Filtro 2
 Outlier superior Outlier inferior Outlier superior
    191061.449609    -18694.871683     37389.743366

# Raças

In [60]:
racas = df[['Unnamed: 0','Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17']]

racas_header = racas.iloc[2]
racas.columns = racas_header
racas = racas[3:]

columns_multiindex = pd.MultiIndex.from_tuples([
    ('', '', 'Províncias e Município Neutro'),
    ('Raças', 'dos Homens', 'Brancos'),
    ('Raças', 'dos Homens', 'Pardos'),
    ('Raças', 'dos Homens', 'Pretos'),
    ('Raças', 'dos Homens', 'Caboclos'),
    ('Raças', 'das Mulheres', 'Brancas'),
    ('Raças', 'das Mulheres', 'Pardas'),
    ('Raças', 'das Mulheres', 'Pretas'),
    ('Raças', 'das Mulheres', 'Caboclas')
])

racas.columns = columns_multiindex

racas

                                      Raças                            \
                                 dos Homens
   Províncias e Município Neutro    Brancos   Pardos  Pretos Caboclos
3                       Amazonas       6911     4210     711    19151
4                           Pará      49663    46899    9200    22827
5                       Maranhão      52267    71662   12504     5509
6                          Piauí      22208    53474    7505     7135
7                          Ceará     136940   172841   14424    26701
8            Rio Grande do Norte      52835    42213   12202     5471
9                        Paraíba      73475    89921   11155     4882
10                    Pernambuco     149930   194897   30795     5943
11                       Alagoas      45343    98916    8220     3105
12                       Sergipe      24358    39524    9321     1536
13                         Bahia     178605   287131  137574    27043
14                Espírito Santo      13555     9648    3395     3009
15              Município Neutro      96255    22762   14198      665
16                Rio de Janeiro     160595    61542   29517     4152
17                     São Paulo     221260    76288   29512    21244
18                        Paraná      35936    15358    3292     4718
19                Santa Catarina      63502     5941    2199     1446
20             Rio Grande do Sul     136094    24487   17828    12613
21                  Minas Gerais     421861   302948  105507    17276
22                         Goiás      21152    42482    9088     2246
23                   Mato Grosso       9027    10827    3861     4276
24                         Total    1971772  1673971  472008   200948


   das Mulheres
        Brancas   Pardas  Pretas Caboclas
3          4300     3046     625    17677
4         42971    46828    7629    21762
5         51246    72699   12780     5434
6         21239    53191    7357     6318
7        131896   166325   14510    26136
8         49630    41877   11163     5568
9         71246    88675   10661     4685
10       141229   192954   30901     5862
11        43455   101283    8687     3259
12        25420    42059    9851     1551
13       152874   278573  127153    22839
14        13027    10881    3443     2520
15        55544    22083   14268      258
16       142680    59703   28198     3700
17       212172    75018   27027    18221
18        33762    15278    3449     4369
19        62440     5796    2048     1446
20       122273    24179   16444    13104
21       409126   295865  101647    15046
22        20777    43907    8087     2004
23         8210    10087    3214     4248
24      1815517  1650307  449142   186007

In [61]:
tabela_manual_brancos = pd.to_numeric(df.iloc[3:25, 10])

tabela_ocr_brancos1 = pd.to_numeric(df1.iloc[:, 9])
diferenca_brancos1 = tabela_manual_brancos.values - tabela_ocr_brancos1.values

tabela_ocr_brancos2 = pd.to_numeric(df2.iloc[:, 9])
diferenca_brancos2 = tabela_manual_brancos.values - tabela_ocr_brancos2.values

tabela_ocr_brancos3 = pd.to_numeric(df3.iloc[:, 9])
diferenca_brancos3 = tabela_manual_brancos.values - tabela_ocr_brancos3.values

In [62]:
tabela_manual_pardos = pd.to_numeric(df.iloc[3:25, 11])

tabela_ocr_pardos1 = pd.to_numeric(df1.iloc[:, 10])
diferenca_pardos1 = tabela_manual_pardos.values - tabela_ocr_pardos1.values

tabela_ocr_pardos2 = pd.to_numeric(df2.iloc[:, 10])
diferenca_pardos2 = tabela_manual_pardos.values - tabela_ocr_pardos2.values

tabela_ocr_pardos3 = pd.to_numeric(df3.iloc[:, 10])
diferenca_pardos3 = tabela_manual_pardos.values - tabela_ocr_pardos3.values

In [63]:
tabela_manual_pretos = pd.to_numeric(df.iloc[3:25, 12])

tabela_ocr_pretos1 = pd.to_numeric(df1.iloc[:, 11])
diferenca_pretos1 = tabela_manual_pretos.values - tabela_ocr_pretos1.values

tabela_ocr_pretos2 = pd.to_numeric(df2.iloc[:, 11])
diferenca_pretos2 = tabela_manual_pretos.values - tabela_ocr_pretos2.values

tabela_ocr_pretos3 = pd.to_numeric(df3.iloc[:, 11])
diferenca_pretos3 = tabela_manual_pretos.values - tabela_ocr_pretos3.values

In [64]:
tabela_manual_caboclos = pd.to_numeric(df.iloc[3:25, 13])

tabela_ocr_caboclos1 = pd.to_numeric(df1.iloc[:, 12])
diferenca_caboclos1 = tabela_manual_caboclos.values - tabela_ocr_caboclos1.values

tabela_ocr_caboclos2 = pd.to_numeric(df2.iloc[:, 12])
diferenca_caboclos2 = tabela_manual_caboclos.values - tabela_ocr_caboclos2.values

tabela_ocr_caboclos3 = pd.to_numeric(df3.iloc[:, 12])
diferenca_caboclos3 = tabela_manual_caboclos.values - tabela_ocr_caboclos3.values

In [65]:
tabela_manual_brancas = pd.to_numeric(df.iloc[3:25, 14])

tabela_ocr_brancas1 = pd.to_numeric(df1.iloc[:, 13])
diferenca_brancas1 = tabela_manual_brancas.values - tabela_ocr_brancas1.values

tabela_ocr_brancas2 = pd.to_numeric(df2.iloc[:, 13])
diferenca_brancas2 = tabela_manual_brancas.values - tabela_ocr_brancas2.values

tabela_ocr_brancas3 = pd.to_numeric(df3.iloc[:, 13])
diferenca_brancas3 = tabela_manual_brancas.values - tabela_ocr_brancas3.values

In [66]:
tabela_manual_pardas = pd.to_numeric(df.iloc[3:25, 15])

tabela_ocr_pardas1 = pd.to_numeric(df1.iloc[:, 14])
diferenca_pardas1 = tabela_manual_pardas.values - tabela_ocr_pardas1.values

tabela_ocr_pardas2 = pd.to_numeric(df2.iloc[:, 14])
diferenca_pardas2 = tabela_manual_pardas.values - tabela_ocr_pardas2.values

tabela_ocr_pardas3 = pd.to_numeric(df3.iloc[:, 14])
diferenca_pardas3 = tabela_manual_pardas.values - tabela_ocr_pardas3.values

In [67]:
tabela_manual_pretas = pd.to_numeric(df.iloc[3:25, 16])

tabela_ocr_pretas1 = pd.to_numeric(df1.iloc[:, 15])
diferenca_pretas1 = tabela_manual_pretas.values - tabela_ocr_pretas1.values

tabela_ocr_pretas2 = pd.to_numeric(df2.iloc[:, 15])
diferenca_pretas2 = tabela_manual_pretas.values - tabela_ocr_pretas2.values

tabela_ocr_pretas3 = pd.to_numeric(df3.iloc[:, 15])
diferenca_pretas3 = tabela_manual_pretas.values - tabela_ocr_pretas3.values

In [68]:
tabela_manual_caboclas = pd.to_numeric(df.iloc[3:25, 17])

tabela_ocr_caboclas1 = pd.to_numeric(df1.iloc[:, 16])
diferenca_caboclas1 = tabela_manual_caboclas.values - tabela_ocr_caboclas1.values

tabela_ocr_caboclas2 = pd.to_numeric(df2.iloc[:, 16])
diferenca_caboclas2 = tabela_manual_caboclas.values - tabela_ocr_caboclas2.values

tabela_ocr_caboclas3 = pd.to_numeric(df3.iloc[:, 16])
diferenca_caboclas3 = tabela_manual_caboclas.values - tabela_ocr_caboclas3.values

In [69]:
variancia_brancos1 = np.var(diferenca_brancos1)
variancia_brancos2 = np.var(diferenca_brancos2)
variancia_brancos3 = np.var(diferenca_brancos3)

df_variancia_brancos = pd.DataFrame([[variancia_brancos1, variancia_brancos2, variancia_brancos3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_variancia_brancos.index = ["Variância (brancos)"]
df_variancia_brancos

                       Sem filtro      Filtro 1      Filtro 2
Variância (brancos)  1.683667e+11  1.654029e+11  2.683242e+11

In [70]:
variancia_pardos1 = np.var(diferenca_pardos1)
variancia_pardos2 = np.var(diferenca_pardos2)
variancia_pardos3 = np.var(diferenca_pardos3)

df_variancia_pardos = pd.DataFrame([[variancia_pardos1, variancia_pardos2, variancia_pardos3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_variancia_pardos.index = ["Variância (pardos)"]
df_variancia_pardos

                      Sem filtro      Filtro 1      Filtro 2
Variância (pardos)  2.512352e+11  1.093794e+11  9.859588e+12

In [71]:
variancia_pretos1 = np.var(diferenca_pretos1)
variancia_pretos2 = np.var(diferenca_pretos2)
variancia_pretos3 = np.var(diferenca_pretos3)

df_variancia_pretos = pd.DataFrame([[variancia_pretos1, variancia_pretos2, variancia_pretos3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_variancia_pretos.index = ["Variância (pretos)"]
df_variancia_pretos

                      Sem filtro      Filtro 1      Filtro 2
Variância (pretos)  4.706702e+07  3.275934e+09  2.210678e+07

In [72]:
variancia_caboclos1 = np.var(diferenca_caboclos1)
variancia_caboclos2 = np.var(diferenca_caboclos2)
variancia_caboclos3 = np.var(diferenca_caboclos3)

df_variancia_caboclos = pd.DataFrame([[variancia_caboclos1, variancia_caboclos2, variancia_caboclos3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_variancia_caboclos.index = ["Variância (caboclos)"]
df_variancia_caboclos

                        Sem filtro      Filtro 1      Filtro 2
Variância (caboclos)  1.884273e+09  2.017203e+07  1.782484e+07

In [73]:
variancia_brancas1 = np.var(diferenca_brancas1)
variancia_brancas2 = np.var(diferenca_brancas2)
variancia_brancas3 = np.var(diferenca_brancas3)

df_variancia_brancas = pd.DataFrame([[variancia_brancas1, variancia_brancas2, variancia_brancas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_variancia_brancas.index = ["Variância (brancas)"]
df_variancia_brancas

                       Sem filtro      Filtro 1      Filtro 2
Variância (brancas)  1.766181e+08  1.156401e+13  1.814913e+09

In [74]:
variancia_pardas1 = np.var(diferenca_pardas1)
variancia_pardas2 = np.var(diferenca_pardas2)
variancia_pardas3 = np.var(diferenca_pardas3)

df_variancia_pardas = pd.DataFrame([[variancia_pardas1, variancia_pardas2, variancia_pardas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_variancia_pardas.index = ["Variância (pardas)"]
df_variancia_pardas

                      Sem filtro      Filtro 1      Filtro 2
Variância (pardas)  3.419912e+12  5.756958e+09  3.412674e+08

In [75]:
variancia_pretas1 = np.var(diferenca_pretas1)
variancia_pretas2 = np.var(diferenca_pretas2)
variancia_pretas3 = np.var(diferenca_pretas3)

df_variancia_pretas = pd.DataFrame([[variancia_pretas1, variancia_pretas2, variancia_pretas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_variancia_pretas.index = ["Variância (pretas)"]
df_variancia_pretas

                      Sem filtro      Filtro 1      Filtro 2
Variância (pretas)  8.945152e+09  1.730123e+08  1.245212e+07

In [76]:
variancia_caboclas1 = np.var(diferenca_caboclas1)
variancia_caboclas2 = np.var(diferenca_caboclas2)
variancia_caboclas3 = np.var(diferenca_caboclas3)

df_variancia_caboclas = pd.DataFrame([[variancia_caboclas1, variancia_caboclas2, variancia_caboclas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_variancia_caboclas.index = ["Variância (caboclas)"]
df_variancia_caboclas

                        Sem filtro      Filtro 1       Filtro 2
Variância (caboclas)  1.406674e+07  1.465598e+09  134297.520661

In [77]:
desvio_padrao_brancos1 = np.std(diferenca_brancos1)
desvio_padrao_brancos2 = np.std(diferenca_brancos2)
desvio_padrao_brancos3 = np.std(diferenca_brancos3)

df_desvio_padrao_brancos = pd.DataFrame([[desvio_padrao_brancos1, desvio_padrao_brancos2, desvio_padrao_brancos3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_desvio_padrao_brancos.index = ["Desvio padrão (brancos)"]
df_desvio_padrao_brancos

                            Sem filtro       Filtro 1       Filtro 2
Desvio padrão (brancos)  410325.130136  406697.605515  518000.192568

In [78]:
desvio_padrao_pardos1 = np.std(diferenca_pardos1)
desvio_padrao_pardos2 = np.std(diferenca_pardos2)
desvio_padrao_pardos3 = np.std(diferenca_pardos3)

df_desvio_padrao_pardos = pd.DataFrame([[desvio_padrao_pardos1, desvio_padrao_pardos2, desvio_padrao_pardos3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_desvio_padrao_pardos.index = ["Desvio padrão (pardos)"]
df_desvio_padrao_pardos

                           Sem filtro       Filtro 1      Filtro 2
Desvio padrão (pardos)  501233.652447  330725.546009  3.139998e+06

In [79]:
desvio_padrao_pretos1 = np.std(diferenca_pretos1)
desvio_padrao_pretos2 = np.std(diferenca_pretos2)
desvio_padrao_pretos3 = np.std(diferenca_pretos3)

df_desvio_padrao_pretos = pd.DataFrame([[desvio_padrao_pretos1, desvio_padrao_pretos2, desvio_padrao_pretos3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_desvio_padrao_pretos.index = ["Desvio padrão (pretos)"]
df_desvio_padrao_pretos

                        Sem filtro      Filtro 1     Filtro 2
Desvio padrão (pretos)  6860.54056  57235.779047  4701.784617

In [80]:
desvio_padrao_caboclos1 = np.std(diferenca_caboclos1)
desvio_padrao_caboclos2 = np.std(diferenca_caboclos2)
desvio_padrao_caboclos3 = np.std(diferenca_caboclos3)

df_desvio_padrao_caboclos = pd.DataFrame([[desvio_padrao_caboclos1, desvio_padrao_caboclos2, desvio_padrao_caboclos3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_desvio_padrao_caboclos.index = ["Desvio padrão (caboclos)"]
df_desvio_padrao_caboclos

                            Sem filtro     Filtro 1     Filtro 2
Desvio padrão (caboclos)  43408.212867  4491.328709  4221.946887

In [81]:
desvio_padrao_brancas1 = np.std(diferenca_brancas1)
desvio_padrao_brancas2 = np.std(diferenca_brancas2)
desvio_padrao_brancas3 = np.std(diferenca_brancas3)

df_desvio_padrao_brancas = pd.DataFrame([[desvio_padrao_brancas1, desvio_padrao_brancas2, desvio_padrao_brancas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_desvio_padrao_brancas.index = ["Desvio padrão (brancas)"]
df_desvio_padrao_brancas

                           Sem filtro      Filtro 1    Filtro 2
Desvio padrão (brancas)  13289.772724  3.400589e+06  42601.7939

In [82]:
desvio_padrao_pardas1 = np.std(diferenca_pardas1)
desvio_padrao_pardas2 = np.std(diferenca_pardas2)
desvio_padrao_pardas3 = np.std(diferenca_pardas3)

df_desvio_padrao_pardas = pd.DataFrame([[desvio_padrao_pardas1, desvio_padrao_pardas2, desvio_padrao_pardas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_desvio_padrao_pardas.index = ["Desvio padrão (pardas)"]
df_desvio_padrao_pardas

                          Sem filtro      Filtro 1      Filtro 2
Desvio padrão (pardas)  1.849300e+06  75874.617925  18473.424234

In [83]:
desvio_padrao_pretas1 = np.std(diferenca_pretas1)
desvio_padrao_pretas2 = np.std(diferenca_pretas2)
desvio_padrao_pretas3 = np.std(diferenca_pretas3)

df_desvio_padrao_pretas = pd.DataFrame([[desvio_padrao_pretas1, desvio_padrao_pretas2, desvio_padrao_pretas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_desvio_padrao_pretas.index = ["Desvio padrão (pretas)"]
df_desvio_padrao_pretas

                          Sem filtro      Filtro 1     Filtro 2
Desvio padrão (pretas)  94578.813562  13153.415819  3528.756553

In [84]:
desvio_padrao_caboclas1 = np.std(diferenca_caboclas1)
desvio_padrao_caboclas2 = np.std(diferenca_caboclas2)
desvio_padrao_caboclas3 = np.std(diferenca_caboclas3)

df_desvio_padrao_caboclas = pd.DataFrame([[desvio_padrao_caboclas1, desvio_padrao_caboclas2, desvio_padrao_caboclas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_desvio_padrao_caboclas.index = ["Desvio padrão (caboclas)"]
df_desvio_padrao_caboclas

                           Sem filtro     Filtro 1    Filtro 2
Desvio padrão (caboclas)  3750.564696  38283.13461  366.466261

In [85]:
coeficiente_variacao_brancos1 = desvio_padrao_brancos1 / np.mean(diferenca_brancos1) * 100
coeficiente_variacao_brancos2 = desvio_padrao_brancos2 / np.mean(diferenca_brancos2) * 100
coeficiente_variacao_brancos3 = desvio_padrao_brancos3 / np.mean(diferenca_brancos3) * 100

df_coeficiente_variacao_brancos = pd.DataFrame([[coeficiente_variacao_brancos1, coeficiente_variacao_brancos2, coeficiente_variacao_brancos3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_coeficiente_variacao_brancos.index = ["Coeficiente de variação (brancos)"]
df_coeficiente_variacao_brancos

                                   Sem filtro    Filtro 1     Filtro 2
Coeficiente de variação (brancos)  444.679228  240.613036  1324.683939

In [86]:
coeficiente_variacao_pardos1 = desvio_padrao_pardos1 / np.mean(diferenca_pardos1) * 100
coeficiente_variacao_pardos2 = desvio_padrao_pardos2 / np.mean(diferenca_pardos2) * 100
coeficiente_variacao_pardos3 = desvio_padrao_pardos3 / np.mean(diferenca_pardos3) * 100

df_coeficiente_variacao_pardos = pd.DataFrame([[coeficiente_variacao_pardos1, coeficiente_variacao_pardos2, coeficiente_variacao_pardos3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_coeficiente_variacao_pardos.index = ["Coeficiente de variação (pardos)"]
df_coeficiente_variacao_pardos

                                  Sem filtro    Filtro 1   Filtro 2
Coeficiente de variação (pardos)  -482.46658  334.853221 -463.62721

In [87]:
coeficiente_variacao_pretos1 = desvio_padrao_pretos1 / np.mean(diferenca_pretos1) * 100
coeficiente_variacao_pretos2 = desvio_padrao_pretos2 / np.mean(diferenca_pretos2) * 100
coeficiente_variacao_pretos3 = desvio_padrao_pretos3 / np.mean(diferenca_pretos3) * 100

df_coeficiente_variacao_pretos = pd.DataFrame([[coeficiente_variacao_pretos1, coeficiente_variacao_pretos2, coeficiente_variacao_pretos3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_coeficiente_variacao_pretos.index = ["Coeficiente de variação (pretos)"]
df_coeficiente_variacao_pretos

                                  Sem filtro    Filtro 1    Filtro 2
Coeficiente de variação (pretos)  405.240683 -560.338529  225.943648

In [88]:
coeficiente_variacao_caboclos1 = desvio_padrao_caboclos1 / np.mean(diferenca_caboclos1) * 100
coeficiente_variacao_caboclos2 = desvio_padrao_caboclos2 / np.mean(diferenca_caboclos2) * 100
coeficiente_variacao_caboclos3 = desvio_padrao_caboclos3 / np.mean(diferenca_caboclos3) * 100

df_coeficiente_variacao_caboclos = pd.DataFrame([[coeficiente_variacao_caboclos1, coeficiente_variacao_caboclos2, coeficiente_variacao_caboclos3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_coeficiente_variacao_caboclos.index = ["Coeficiente de variação (caboclos)"]
df_coeficiente_variacao_caboclos

                                    Sem filtro    Filtro 1    Filtro 2
Coeficiente de variação (caboclos) -529.230568  397.063418  406.578383

In [89]:
coeficiente_variacao_brancas1 = desvio_padrao_brancas1 / np.mean(diferenca_brancas1) * 100
coeficiente_variacao_brancas2 = desvio_padrao_brancas2 / np.mean(diferenca_brancas2) * 100
coeficiente_variacao_brancas3 = desvio_padrao_brancas3 / np.mean(diferenca_brancas3) * 100

df_coeficiente_variacao_brancas = pd.DataFrame([[coeficiente_variacao_brancas1, coeficiente_variacao_brancas2, coeficiente_variacao_brancas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_coeficiente_variacao_brancas.index = ["Coeficiente de variação (brancas)"]
df_coeficiente_variacao_brancas

                                   Sem filtro   Filtro 1    Filtro 2
Coeficiente de variação (brancas)  472.181847 -422.42967 -743.044727

In [90]:
coeficiente_variacao_pardas1 = desvio_padrao_pardas1 / np.mean(diferenca_pardas1) * 100
coeficiente_variacao_pardas2 = desvio_padrao_pardas2 / np.mean(diferenca_pardas2) * 100
coeficiente_variacao_pardas3 = desvio_padrao_pardas3 / np.mean(diferenca_pardas3) * 100

df_coeficiente_variacao_pardas = pd.DataFrame([[coeficiente_variacao_pardas1, coeficiente_variacao_pardas2, coeficiente_variacao_pardas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_coeficiente_variacao_pardas.index = ["Coeficiente de variação (pardas)"]
df_coeficiente_variacao_pardas

                                  Sem filtro    Filtro 1    Filtro 2
Coeficiente de variação (pardas) -477.330406  687.907356  302.234947

In [91]:
coeficiente_variacao_pretas1 = desvio_padrao_pretas1 / np.mean(diferenca_pretas1) * 100
coeficiente_variacao_pretas2 = desvio_padrao_pretas2 / np.mean(diferenca_pretas2) * 100
coeficiente_variacao_pretas3 = desvio_padrao_pretas3 / np.mean(diferenca_pretas3) * 100

df_coeficiente_variacao_pretas = pd.DataFrame([[coeficiente_variacao_pretas1, coeficiente_variacao_pretas2, coeficiente_variacao_pretas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_coeficiente_variacao_pretas.index = ["Coeficiente de variação (pretas)"]
df_coeficiente_variacao_pretas

                                  Sem filtro    Filtro 1    Filtro 2
Coeficiente de variação (pretas)  512.190738  439.459282  277.805132

In [92]:
coeficiente_variacao_caboclas1 = desvio_padrao_caboclas1 / np.mean(diferenca_caboclas1) * 100
coeficiente_variacao_caboclas2 = desvio_padrao_caboclas2 / np.mean(diferenca_caboclas2) * 100
coeficiente_variacao_caboclas3 = desvio_padrao_caboclas3 / np.mean(diferenca_caboclas3) * 100

df_coeficiente_variacao_caboclas = pd.DataFrame([[coeficiente_variacao_caboclas1, coeficiente_variacao_caboclas2, coeficiente_variacao_caboclas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_coeficiente_variacao_caboclas.index = ["Coeficiente de variação (caboclas)"]
df_coeficiente_variacao_caboclas

                                    Sem filtro    Filtro 1    Filtro 2
Coeficiente de variação (caboclas)  693.381708  262.840894 -806.225775

In [93]:
media_brancos1 = np.mean(diferenca_brancos1)
media_brancos2 = np.mean(diferenca_brancos2)
media_brancos3 = np.mean(diferenca_brancos3)

df_media_brancos = pd.DataFrame([[media_brancos1, media_brancos2, media_brancos3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_media_brancos.index = ["Média (brancos)"]
df_media_brancos

                   Sem filtro       Filtro 1      Filtro 2
Média (brancos)  92274.409091  169025.590909  39103.681818

In [94]:
media_pardos1 = np.mean(diferenca_pardos1)
media_pardos2 = np.mean(diferenca_pardos2)
media_pardos3 = np.mean(diferenca_pardos3)

df_media_pardos = pd.DataFrame([[media_pardos1, media_pardos2, media_pardos3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_media_pardos.index = ["Média (pardos)"]
df_media_pardos

                   Sem filtro      Filtro 1       Filtro 2
Média (pardos) -103889.818182  98767.318182 -677267.863636

In [95]:
media_pretos1 = np.mean(diferenca_pretos1)
media_pretos2 = np.mean(diferenca_pretos2)
media_pretos3 = np.mean(diferenca_pretos3)

df_media_pretos = pd.DataFrame([[media_pretos1, media_pretos2, media_pretos3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_media_pretos.index = ["Média (pretos)"]
df_media_pretos

                 Sem filtro  Filtro 1     Filtro 2
Média (pretos)  1692.954545  -10214.5  2080.954545

In [96]:
media_caboclos1 = np.mean(diferenca_caboclos1)
media_caboclos2 = np.mean(diferenca_caboclos2)
media_caboclos3 = np.mean(diferenca_caboclos3)

df_media_caboclos = pd.DataFrame([[media_caboclos1, media_caboclos2, media_caboclos3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_media_caboclos.index = ["Média (caboclos)"]
df_media_caboclos

                   Sem filtro     Filtro 1     Filtro 2
Média (caboclos) -8202.136364  1131.136364  1038.409091

In [97]:
media_brancas1 = np.mean(diferenca_brancas1)
media_brancas2 = np.mean(diferenca_brancas2)
media_brancas3 = np.mean(diferenca_brancas3)

df_media_brancas = pd.DataFrame([[media_brancas1, media_brancas2, media_brancas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_media_brancas.index = ["Média (brancas)"]
df_media_brancas

                  Sem filtro       Filtro 1     Filtro 2
Média (brancas)  2814.545455 -805007.181818 -5733.409091

In [98]:
media_pardas1 = np.mean(diferenca_pardas1)
media_pardas2 = np.mean(diferenca_pardas2)
media_pardas3 = np.mean(diferenca_pardas3)

df_media_pardas = pd.DataFrame([[media_pardas1, media_pardas2, media_pardas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_media_pardas.index = ["Média (pardas)"]
df_media_pardas

                   Sem filtro      Filtro 1     Filtro 2
Média (pardas) -387425.636364  11029.772727  6112.272727

In [99]:
media_pretas1 = np.mean(diferenca_pretas1)
media_pretas2 = np.mean(diferenca_pretas2)
media_pretas3 = np.mean(diferenca_pretas3)

df_media_pretas = pd.DataFrame([[media_pretas1, media_pretas2, media_pretas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_media_pretas.index = ["Média (pretas)"]
df_media_pretas

                  Sem filtro     Filtro 1     Filtro 2
Média (pretas)  18465.545455  2993.090909  1270.227273

In [100]:
media_caboclas1 = np.mean(diferenca_caboclas1)
media_caboclas2 = np.mean(diferenca_caboclas2)
media_caboclas3 = np.mean(diferenca_caboclas3)

df_media_caboclas = pd.DataFrame([[media_caboclas1, media_caboclas2, media_caboclas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_media_caboclas.index = ["Média (caboclas)"]
df_media_caboclas

                  Sem filtro      Filtro 1   Filtro 2
Média (caboclas)  540.909091  14565.136364 -45.454545

In [101]:
outlier_inferior_brancos1 = media_brancos1 - (3 * desvio_padrao_brancos1)
outlier_superior_brancos1 = media_brancos1 + (3 * desvio_padrao_brancos1)

outlier_inferior_brancos2 = media_brancos2 - (3 * desvio_padrao_brancos2)
outlier_superior_brancos2 = media_brancos2 + (3 * desvio_padrao_brancos2)

outlier_inferior_brancos3 = media_brancos3 - (3 * desvio_padrao_brancos3)
outlier_superior_brancos3 = media_brancos3 + (3 * desvio_padrao_brancos3)


df_outlier_brancos = pd.DataFrame([
    [outlier_inferior_brancos1, outlier_superior_brancos1,
    outlier_inferior_brancos2, outlier_superior_brancos2,
    outlier_inferior_brancos3, outlier_superior_brancos3]
], index=pd.MultiIndex.from_tuples([
    ("",)
]), columns=pd.MultiIndex.from_tuples([
    ("Observação discrepante (brancos)", "Sem filtro", "Outlier inferior"),
    ("Observação discrepante (brancos)", "Sem filtro", "Outlier superior"),
    ("Observação discrepante (brancos)", "Filtro 1", "Outlier inferior"),
    ("Observação discrepante (brancos)", "Filtro 1", "Outlier superior"),
    ("Observação discrepante (brancos)", "Filtro 2", "Outlier inferior"),
    ("Observação discrepante (brancos)", "Filtro 2", "Outlier superior")
]))
df_outlier_brancos

 Observação discrepante (brancos)                                    \
                       Sem filtro                          Filtro 1
                 Outlier inferior Outlier superior Outlier inferior
                    -1.138701e+06     1.323250e+06    -1.051067e+06


                          Filtro 2
 Outlier superior Outlier inferior Outlier superior
     1.389118e+06    -1.514897e+06     1.593104e+06

In [102]:
outlier_inferior_pardos1 = media_pardos1 - (3 * desvio_padrao_pardos1)
outlier_superior_pardos1 = media_pardos1 + (3 * desvio_padrao_pardos1)

outlier_inferior_pardos2 = media_pardos2 - (3 * desvio_padrao_pardos2)
outlier_superior_pardos2 = media_pardos2 + (3 * desvio_padrao_pardos2)

outlier_inferior_pardos3 = media_pardos3 - (3 * desvio_padrao_pardos3)
outlier_superior_pardos3 = media_pardos3 + (3 * desvio_padrao_pardos3)


df_outlier_pardos = pd.DataFrame([
    [outlier_inferior_pardos1, outlier_superior_pardos1,
    outlier_inferior_pardos2, outlier_superior_pardos2,
    outlier_inferior_pardos3, outlier_superior_pardos3]
], index=pd.MultiIndex.from_tuples([
    ("",)
]), columns=pd.MultiIndex.from_tuples([
    ("Observação discrepante (pardos)", "Sem filtro", "Outlier inferior"),
    ("Observação discrepante (pardos)", "Sem filtro", "Outlier superior"),
    ("Observação discrepante (pardos)", "Filtro 1", "Outlier inferior"),
    ("Observação discrepante (pardos)", "Filtro 1", "Outlier superior"),
    ("Observação discrepante (pardos)", "Filtro 2", "Outlier inferior"),
    ("Observação discrepante (pardos)", "Filtro 2", "Outlier superior")
]))
df_outlier_pardos

 Observação discrepante (pardos)                                    \
                      Sem filtro                          Filtro 1
                Outlier inferior Outlier superior Outlier inferior
                   -1.607591e+06     1.399811e+06   -893409.319846


                          Filtro 2
 Outlier superior Outlier inferior Outlier superior
     1.090944e+06    -1.009726e+07     8.742726e+06

In [103]:
outlier_inferior_pretos1 = media_pretos1 - (3 * desvio_padrao_pretos1)
outlier_superior_pretos1 = media_pretos1 + (3 * desvio_padrao_pretos1)

outlier_inferior_pretos2 = media_pretos2 - (3 * desvio_padrao_pretos2)
outlier_superior_pretos2 = media_pretos2 + (3 * desvio_padrao_pretos2)

outlier_inferior_pretos3 = media_pretos3 - (3 * desvio_padrao_pretos3)
outlier_superior_pretos3 = media_pretos3 + (3 * desvio_padrao_pretos3)


df_outlier_pretos = pd.DataFrame([
    [outlier_inferior_pretos1, outlier_superior_pretos1,
    outlier_inferior_pretos2, outlier_superior_pretos2,
    outlier_inferior_pretos3, outlier_superior_pretos3]
], index=pd.MultiIndex.from_tuples([
    ("",)
]), columns=pd.MultiIndex.from_tuples([
    ("Observação discrepante (pretos)", "Sem filtro", "Outlier inferior"),
    ("Observação discrepante (pretos)", "Sem filtro", "Outlier superior"),
    ("Observação discrepante (pretos)", "Filtro 1", "Outlier inferior"),
    ("Observação discrepante (pretos)", "Filtro 1", "Outlier superior"),
    ("Observação discrepante (pretos)", "Filtro 2", "Outlier inferior"),
    ("Observação discrepante (pretos)", "Filtro 2", "Outlier superior")
]))
df_outlier_pretos

 Observação discrepante (pretos)                                    \
                      Sem filtro                          Filtro 1
                Outlier inferior Outlier superior Outlier inferior
                   -18888.667134     22274.576224   -181921.837142


                          Filtro 2
 Outlier superior Outlier inferior Outlier superior
    161492.837142    -12024.399307     16186.308398

In [104]:
outlier_inferior_caboclos1 = media_caboclos1 - (3 * desvio_padrao_caboclos1)
outlier_superior_caboclos1 = media_caboclos1 + (3 * desvio_padrao_caboclos1)

outlier_inferior_caboclos2 = media_caboclos2 - (3 * desvio_padrao_caboclos2)
outlier_superior_caboclos2 = media_caboclos2 + (3 * desvio_padrao_caboclos2)

outlier_inferior_caboclos3 = media_caboclos3 - (3 * desvio_padrao_caboclos3)
outlier_superior_caboclos3 = media_caboclos3 + (3 * desvio_padrao_caboclos3)


df_outlier_caboclos = pd.DataFrame([
    [outlier_inferior_caboclos1, outlier_superior_caboclos1,
    outlier_inferior_caboclos2, outlier_superior_caboclos2,
    outlier_inferior_caboclos3, outlier_superior_caboclos3]
], index=pd.MultiIndex.from_tuples([
    ("",)
]), columns=pd.MultiIndex.from_tuples([
    ("Observação discrepante (caboclos)", "Sem filtro", "Outlier inferior"),
    ("Observação discrepante (caboclos)", "Sem filtro", "Outlier superior"),
    ("Observação discrepante (caboclos)", "Filtro 1", "Outlier inferior"),
    ("Observação discrepante (caboclos)", "Filtro 1", "Outlier superior"),
    ("Observação discrepante (caboclos)", "Filtro 2", "Outlier inferior"),
    ("Observação discrepante (caboclos)", "Filtro 2", "Outlier superior")
]))
df_outlier_caboclos

 Observação discrepante (caboclos)                                    \
                        Sem filtro                          Filtro 1
                  Outlier inferior Outlier superior Outlier inferior
                    -138426.774964    122022.502237    -12342.849763


                          Filtro 2
 Outlier superior Outlier inferior Outlier superior
     14605.122491    -11627.431569     13704.249751

In [105]:
outlier_inferior_brancas1 = media_brancas1 - (3 * desvio_padrao_brancas1)
outlier_superior_brancas1 = media_brancas1 + (3 * desvio_padrao_brancas1)

outlier_inferior_brancas2 = media_brancas2 - (3 * desvio_padrao_brancas2)
outlier_superior_brancas2 = media_brancas2 + (3 * desvio_padrao_brancas2)

outlier_inferior_brancas3 = media_brancas3 - (3 * desvio_padrao_brancas3)
outlier_superior_brancas3 = media_brancas3 + (3 * desvio_padrao_brancas3)


df_outlier_brancas = pd.DataFrame([
    [outlier_inferior_brancas1, outlier_superior_brancas1,
    outlier_inferior_brancas2, outlier_superior_brancas2,
    outlier_inferior_brancas3, outlier_superior_brancas3]
], index=pd.MultiIndex.from_tuples([
    ("",)
]), columns=pd.MultiIndex.from_tuples([
    ("Observação discrepante (brancas)", "Sem filtro", "Outlier inferior"),
    ("Observação discrepante (brancas)", "Sem filtro", "Outlier superior"),
    ("Observação discrepante (brancas)", "Filtro 1", "Outlier inferior"),
    ("Observação discrepante (brancas)", "Filtro 1", "Outlier superior"),
    ("Observação discrepante (brancas)", "Filtro 2", "Outlier inferior"),
    ("Observação discrepante (brancas)", "Filtro 2", "Outlier superior")
]))
df_outlier_brancas

 Observação discrepante (brancas)                                    \
                       Sem filtro                          Filtro 1
                 Outlier inferior Outlier superior Outlier inferior
                    -37054.772719     42683.863628    -1.100677e+07


                          Filtro 2
 Outlier superior Outlier inferior Outlier superior
     9.396760e+06   -133538.790791     122071.97261

In [106]:
outlier_inferior_pardas1 = media_pardas1 - (3 * desvio_padrao_pardas1)
outlier_superior_pardas1 = media_pardas1 + (3 * desvio_padrao_pardas1)

outlier_inferior_pardas2 = media_pardas2 - (3 * desvio_padrao_pardas2)
outlier_superior_pardas2 = media_pardas2 + (3 * desvio_padrao_pardas2)

outlier_inferior_pardas3 = media_pardas3 - (3 * desvio_padrao_pardas3)
outlier_superior_pardas3 = media_pardas3 + (3 * desvio_padrao_pardas3)


df_outlier_pardas = pd.DataFrame([
    [outlier_inferior_pardas1, outlier_superior_pardas1,
    outlier_inferior_pardas2, outlier_superior_pardas2,
    outlier_inferior_pardas3, outlier_superior_pardas3]
], index=pd.MultiIndex.from_tuples([
    ("",)
]), columns=pd.MultiIndex.from_tuples([
    ("Observação discrepante (pardas)", "Sem filtro", "Outlier inferior"),
    ("Observação discrepante (pardas)", "Sem filtro", "Outlier superior"),
    ("Observação discrepante (pardas)", "Filtro 1", "Outlier inferior"),
    ("Observação discrepante (pardas)", "Filtro 1", "Outlier superior"),
    ("Observação discrepante (pardas)", "Filtro 2", "Outlier inferior"),
    ("Observação discrepante (pardas)", "Filtro 2", "Outlier superior")
]))
df_outlier_pardas

 Observação discrepante (pardas)                                    \
                      Sem filtro                          Filtro 1
                Outlier inferior Outlier superior Outlier inferior
                   -5.935327e+06     5.160475e+06   -216594.081048


                          Filtro 2
 Outlier superior Outlier inferior Outlier superior
    238653.626502    -49307.999974     61532.545429

In [107]:
outlier_inferior_pretas1 = media_pretas1 - (3 * desvio_padrao_pretas1)
outlier_superior_pretas1 = media_pretas1 + (3 * desvio_padrao_pretas1)

outlier_inferior_pretas2 = media_pretas2 - (3 * desvio_padrao_pretas2)
outlier_superior_pretas2 = media_pretas2 + (3 * desvio_padrao_pretas2)

outlier_inferior_pretas3 = media_pretas3 - (3 * desvio_padrao_pretas3)
outlier_superior_pretas3 = media_pretas3 + (3 * desvio_padrao_pretas3)


df_outlier_pretas = pd.DataFrame([
    [outlier_inferior_pretas1, outlier_superior_pretas1,
    outlier_inferior_pretas2, outlier_superior_pretas2,
    outlier_inferior_pretas3, outlier_superior_pretas3]
], index=pd.MultiIndex.from_tuples([
    ("",)
]), columns=pd.MultiIndex.from_tuples([
    ("Observação discrepante (pretas)", "Sem filtro", "Outlier inferior"),
    ("Observação discrepante (pretas)", "Sem filtro", "Outlier superior"),
    ("Observação discrepante (pretas)", "Filtro 1", "Outlier inferior"),
    ("Observação discrepante (pretas)", "Filtro 1", "Outlier superior"),
    ("Observação discrepante (pretas)", "Filtro 2", "Outlier inferior"),
    ("Observação discrepante (pretas)", "Filtro 2", "Outlier superior")
]))
df_outlier_pretas

 Observação discrepante (pretas)                                    \
                      Sem filtro                          Filtro 1
                Outlier inferior Outlier superior Outlier inferior
                  -265270.895233    302201.986142    -36467.156549


                          Filtro 2
 Outlier superior Outlier inferior Outlier superior
     42453.338367     -9316.042387     11856.496932

In [108]:
outlier_inferior_caboclas1 = media_caboclas1 - (3 * desvio_padrao_caboclas1)
outlier_superior_caboclas1 = media_caboclas1 + (3 * desvio_padrao_caboclas1)

outlier_inferior_caboclas2 = media_caboclas2 - (3 * desvio_padrao_caboclas2)
outlier_superior_caboclas2 = media_caboclas2 + (3 * desvio_padrao_caboclas2)

outlier_inferior_caboclas3 = media_caboclas3 - (3 * desvio_padrao_caboclas3)
outlier_superior_caboclas3 = media_caboclas3 + (3 * desvio_padrao_caboclas3)


df_outlier_caboclas = pd.DataFrame([
    [outlier_inferior_caboclas1, outlier_superior_caboclas1,
    outlier_inferior_caboclas2, outlier_superior_caboclas2,
    outlier_inferior_caboclas3, outlier_superior_caboclas3]
], index=pd.MultiIndex.from_tuples([
    ("",)
]), columns=pd.MultiIndex.from_tuples([
    ("Observação discrepante (caboclas)", "Sem filtro", "Outlier inferior"),
    ("Observação discrepante (caboclas)", "Sem filtro", "Outlier superior"),
    ("Observação discrepante (caboclas)", "Filtro 1", "Outlier inferior"),
    ("Observação discrepante (caboclas)", "Filtro 1", "Outlier superior"),
    ("Observação discrepante (caboclas)", "Filtro 2", "Outlier inferior"),
    ("Observação discrepante (caboclas)", "Filtro 2", "Outlier superior")
]))
df_outlier_caboclas

 Observação discrepante (caboclas)                                    \
                        Sem filtro                          Filtro 1
                  Outlier inferior Outlier superior Outlier inferior
                     -10710.784996     11792.603178   -100284.267467


                          Filtro 2
 Outlier superior Outlier inferior Outlier superior
    129414.540194     -1144.853329      1053.944238

# Religião

In [109]:
religiao = df[['Unnamed: 0','Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21']]

religiao_header = religiao.iloc[2]
religiao.columns = religiao_header
religiao = religiao[3:]

columns_multiindex = pd.MultiIndex.from_tuples([
    ('', '', 'Províncias e Município Neutro'),
    ('Religião', 'dos Homens', 'Católicos'),
    ('Religião', 'dos Homens', 'Acatólicos'),
    ('Religião', 'das Mulheres', 'Católicas'),
    ('Religião', 'das Mulheres', 'Acatólicas')
])

religiao.columns = columns_multiindex

religiao

                                   Religião
                                 dos Homens            das Mulheres
   Províncias e Município Neutro  Católicos Acatólicos    Católicas Acatólicas
3                       Amazonas      30903         80        25641          7
4                           Pará     128396        193       119169         21
5                       Maranhão     141865         77       142100         59
6                          Piauí      90313          9        88105          0
7                          Ceará     350868         38       338857         10
8            Rio Grande do Norte     112717          4       108238          0
9                        Paraíba     179429          4       175266          1
10                    Pernambuco     381361        204       370906         40
11                       Alagoas     155557         27       156683          1
12                       Sergipe      74739          0        78881          0
13                         Bahia     630196        157       581384         55
14                Espírito Santo      29377        230        29687        184
15              Município Neutro     132552       1328        91553        600
16                Rio de Janeiro     255433        373       234066        215
17                     São Paulo     346326       1973       331217       1221
18                        Paraná      58755        549        56594        264
19                Santa Catarina      67635       5453        66742       4988
20             Rio Grande do Sul     187182       3840       173617       2383
21                  Minas Gerais     845840       1752       820290       1394
22                         Goiás      74967          1        74775          0
23                   Mato Grosso      27975         16        25749         10
24                         Total    4302386      16313      4089520      11453

In [110]:
tabela_manual_catolicos = pd.to_numeric(df.iloc[3:25, 18])

tabela_ocr_catolicos1 = pd.to_numeric(df1.iloc[:, 17])
diferenca_catolicos1 = tabela_manual_catolicos.values - tabela_ocr_catolicos1.values

tabela_ocr_catolicos2 = pd.to_numeric(df2.iloc[:, 17])
diferenca_catolicos2 = tabela_manual_catolicos.values - tabela_ocr_catolicos2.values

tabela_ocr_catolicos3 = pd.to_numeric(df3.iloc[:, 17])
diferenca_catolicos3 = tabela_manual_catolicos.values - tabela_ocr_catolicos3.values

In [111]:
tabela_manual_acatolicos = pd.to_numeric(df.iloc[3:25, 19])

tabela_ocr_acatolicos1 = pd.to_numeric(df1.iloc[:, 18])
diferenca_acatolicos1 = tabela_manual_acatolicos.values - tabela_ocr_acatolicos1.values

tabela_ocr_acatolicos2 = pd.to_numeric(df2.iloc[:, 18])
diferenca_acatolicos2 = tabela_manual_acatolicos.values - tabela_ocr_acatolicos2.values

tabela_ocr_acatolicos3 = pd.to_numeric(df3.iloc[:, 18])
diferenca_acatolicos3 = tabela_manual_acatolicos.values - tabela_ocr_acatolicos3.values

In [112]:
tabela_manual_catolicas = pd.to_numeric(df.iloc[3:25, 20])

tabela_ocr_catolicas1 = pd.to_numeric(df1.iloc[:, 19])
diferenca_catolicas1 = tabela_manual_catolicas.values - tabela_ocr_catolicas1.values

tabela_ocr_catolicas2 = pd.to_numeric(df2.iloc[:, 19])
diferenca_catolicas2 = tabela_manual_catolicas.values - tabela_ocr_catolicas2.values

tabela_ocr_catolicas3 = pd.to_numeric(df3.iloc[:, 19])
diferenca_catolicas3 = tabela_manual_catolicas.values - tabela_ocr_catolicas3.values

In [113]:
tabela_manual_acatolicas = pd.to_numeric(df.iloc[3:25, 21])

tabela_ocr_acatolicas1 = pd.to_numeric(df1.iloc[:, 20])
diferenca_acatolicas1 = tabela_manual_acatolicas.values - tabela_ocr_acatolicas1.values

tabela_ocr_acatolicas2 = pd.to_numeric(df2.iloc[:, 20])
diferenca_acatolicas2 = tabela_manual_acatolicas.values - tabela_ocr_acatolicas2.values

tabela_ocr_acatolicas3 = pd.to_numeric(df3.iloc[:, 20])
diferenca_acatolicas3 = tabela_manual_acatolicas.values - tabela_ocr_acatolicas3.values

In [114]:
variancia_catolicos1 = np.var(diferenca_catolicos1)
variancia_catolicos2 = np.var(diferenca_catolicos2)
variancia_catolicos3 = np.var(diferenca_catolicos3)

df_variancia_catolicos = pd.DataFrame([[variancia_catolicos1, variancia_catolicos2, variancia_catolicos3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_variancia_catolicos.index = ["Variância (católicos)"]
df_variancia_catolicos

                         Sem filtro      Filtro 1      Filtro 2
Variância (católicos)  9.114864e+11  7.113791e+11  8.000059e+11

In [115]:
variancia_acatolicos1 = np.var(diferenca_acatolicos1)
variancia_acatolicos2 = np.var(diferenca_acatolicos2)
variancia_acatolicos3 = np.var(diferenca_acatolicos3)

df_variancia_acatolicos = pd.DataFrame([[variancia_acatolicos1, variancia_acatolicos2, variancia_acatolicos3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_variancia_acatolicos.index = ["Variância (acatólicos)"]
df_variancia_acatolicos

                          Sem filtro      Filtro 1      Filtro 2
Variância (acatólicos)  1.211289e+07  1.238530e+07  1.234377e+07

In [116]:
variancia_catolicas1 = np.var(diferenca_catolicas1)
variancia_catolicas2 = np.var(diferenca_catolicas2)
variancia_catolicas3 = np.var(diferenca_catolicas3)

df_variancia_catolicas = pd.DataFrame([[variancia_catolicas1, variancia_catolicas2, variancia_catolicas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_variancia_catolicas.index = ["Variância (católicas)"]
df_variancia_catolicas

                         Sem filtro      Filtro 1      Filtro 2
Variância (católicas)  1.262500e+10  5.884893e+10  9.114000e+10

In [117]:
variancia_acatolicas1 = np.var(diferenca_acatolicas1)
variancia_acatolicas2 = np.var(diferenca_acatolicas2)
variancia_acatolicas3 = np.var(diferenca_acatolicas3)

df_variancia_acatolicas = pd.DataFrame([[variancia_acatolicas1, variancia_acatolicas2, variancia_acatolicas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_variancia_acatolicas.index = ["Variância (acatólicas)"]
df_variancia_acatolicas

                        Sem filtro      Filtro 1      Filtro 2
Variância (acatólicas)   15.663223  91791.084711  1.297689e+06

In [118]:
desvio_padrao_catolicos1 = np.std(diferenca_catolicos1)
desvio_padrao_catolicos2 = np.std(diferenca_catolicos2)
desvio_padrao_catolicos3 = np.std(diferenca_catolicos3)

df_desvio_padrao_catolicos = pd.DataFrame([[desvio_padrao_catolicos1, desvio_padrao_catolicos2, desvio_padrao_catolicos3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_desvio_padrao_catolicos.index = ["Desvio padrão (católicos)"]
df_desvio_padrao_catolicos

                              Sem filtro       Filtro 1      Filtro 2
Desvio padrão (católicos)  954717.943431  843432.908225  894430.46534

In [119]:
desvio_padrao_acatolicos1 = np.std(diferenca_acatolicos1)
desvio_padrao_acatolicos2 = np.std(diferenca_acatolicos2)
desvio_padrao_acatolicos3 = np.std(diferenca_acatolicos3)

df_desvio_padrao_acatolicos = pd.DataFrame([[desvio_padrao_acatolicos1, desvio_padrao_acatolicos2, desvio_padrao_acatolicos3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_desvio_padrao_acatolicos.index = ["Desvio padrão (acatólicos)"]
df_desvio_padrao_acatolicos

                             Sem filtro     Filtro 1     Filtro 2
Desvio padrão (acatólicos)  3480.357592  3519.275286  3513.369801

In [120]:
desvio_padrao_catolicas1 = np.std(diferenca_catolicas1)
desvio_padrao_catolicas2 = np.std(diferenca_catolicas2)
desvio_padrao_catolicas3 = np.std(diferenca_catolicas3)

df_desvio_padrao_catolicas = pd.DataFrame([[desvio_padrao_catolicas1, desvio_padrao_catolicas2, desvio_padrao_catolicas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_desvio_padrao_catolicas.index = ["Desvio padrão (católicas)"]
df_desvio_padrao_catolicas

                              Sem filtro       Filtro 1       Filtro 2
Desvio padrão (católicas)  112361.012676  242587.977922  301894.023484

In [121]:
desvio_padrao_acatolicas1 = np.std(diferenca_acatolicas1)
desvio_padrao_acatolicas2 = np.std(diferenca_acatolicas2)
desvio_padrao_acatolicas3 = np.std(diferenca_acatolicas3)

df_desvio_padrao_acatolicas = pd.DataFrame([[desvio_padrao_acatolicas1, desvio_padrao_acatolicas2, desvio_padrao_acatolicas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_desvio_padrao_acatolicas.index = ["Desvio padrão (acatólicas)"]
df_desvio_padrao_acatolicas

                            Sem filtro    Filtro 1    Filtro 2
Desvio padrão (acatólicas)    3.957679  302.970435  1139.16152

In [122]:
coeficiente_variacao_catolicos1 = desvio_padrao_catolicos1 / np.mean(diferenca_catolicos1) * 100
coeficiente_variacao_catolicos2 = desvio_padrao_catolicos2 / np.mean(diferenca_catolicos2) * 100
coeficiente_variacao_catolicos3 = desvio_padrao_catolicos3 / np.mean(diferenca_catolicos3) * 100

df_coeficiente_variacao_catolicos = pd.DataFrame([[coeficiente_variacao_catolicos1, coeficiente_variacao_catolicos2, coeficiente_variacao_catolicos3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_coeficiente_variacao_catolicos.index = ["Coeficiente de variação (católicos)"]
df_coeficiente_variacao_catolicos

                                     Sem filtro    Filtro 1    Filtro 2
Coeficiente de variação (católicos)  678.023382  494.881277  436.630224

In [123]:
coeficiente_variacao_acatolicos1 = desvio_padrao_acatolicos1 / np.mean(diferenca_acatolicos1) * 100
coeficiente_variacao_acatolicos2 = desvio_padrao_acatolicos2 / np.mean(diferenca_acatolicos2) * 100
coeficiente_variacao_acatolicos3 = desvio_padrao_acatolicos3 / np.mean(diferenca_acatolicos3) * 100

df_coeficiente_variacao_acatolicos = pd.DataFrame([[coeficiente_variacao_acatolicos1, coeficiente_variacao_acatolicos2, coeficiente_variacao_acatolicos3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_coeficiente_variacao_acatolicos.index = ["Coeficiente de variação (acatólicos)"]
df_coeficiente_variacao_acatolicos

                                      Sem filtro    Filtro 1    Filtro 2
Coeficiente de variação (acatólicos)  543.960408  311.967347  236.945942

In [124]:
coeficiente_variacao_catolicas1 = desvio_padrao_catolicas1 / np.mean(diferenca_catolicas1) * 100
coeficiente_variacao_catolicas2 = desvio_padrao_catolicas2 / np.mean(diferenca_catolicas2) * 100
coeficiente_variacao_catolicas3 = desvio_padrao_catolicas3 / np.mean(diferenca_catolicas3) * 100

df_coeficiente_variacao_catolicas = pd.DataFrame([[coeficiente_variacao_catolicas1, coeficiente_variacao_catolicas2, coeficiente_variacao_catolicas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_coeficiente_variacao_catolicas.index = ["Coeficiente de variação (católicas)"]
df_coeficiente_variacao_catolicas

                                     Sem filtro    Filtro 1    Filtro 2
Coeficiente de variação (católicas) -525.488997  269.132382 -422.421413

In [125]:
coeficiente_variacao_catolicas1 = desvio_padrao_catolicas1 / np.mean(diferenca_catolicas1) * 100
coeficiente_variacao_catolicas2 = desvio_padrao_catolicas2 / np.mean(diferenca_catolicas2) * 100
coeficiente_variacao_catolicas3 = desvio_padrao_catolicas3 / np.mean(diferenca_catolicas3) * 100

df_coeficiente_variacao_catolicas = pd.DataFrame([[coeficiente_variacao_catolicas1, coeficiente_variacao_catolicas2, coeficiente_variacao_catolicas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_coeficiente_variacao_catolicas.index = ["Coeficiente de variação (católicas)"]
df_coeficiente_variacao_catolicas

                                     Sem filtro    Filtro 1    Filtro 2
Coeficiente de variação (católicas) -525.488997  269.132382 -422.421413

In [126]:
media_catolicos1 = np.mean(diferenca_catolicos1)
media_catolicos2 = np.mean(diferenca_catolicos2)
media_catolicos3 = np.mean(diferenca_catolicos3)

df_media_catolicos = pd.DataFrame([[media_catolicos1, media_catolicos2, media_catolicos3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_media_catolicos.index = ["Média (católicos)"]
df_media_catolicos

                   Sem filtro       Filtro 1  Filtro 2
Média (católicos)    140809.0  170431.363636  204848.5

In [127]:
media_acatolicos1 = np.mean(diferenca_acatolicos1)
media_acatolicos2 = np.mean(diferenca_acatolicos2)
media_acatolicos3 = np.mean(diferenca_acatolicos3)

df_media_acatolicos = pd.DataFrame([[media_acatolicos1, media_acatolicos2, media_acatolicos3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_media_acatolicos.index = ["Média (acatólicos)"]
df_media_acatolicos

                    Sem filtro     Filtro 1     Filtro 2
Média (acatólicos)  639.818182  1128.090909  1482.772727

In [128]:
media_catolicas1 = np.mean(diferenca_catolicas1)
media_catolicas2 = np.mean(diferenca_catolicas2)
media_catolicas3 = np.mean(diferenca_catolicas3)

df_media_catolicas = pd.DataFrame([[media_catolicas1, media_catolicas2, media_catolicas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_media_catolicas.index = ["Média (católicas)"]
df_media_catolicas

                     Sem filtro      Filtro 1  Filtro 2
Média (católicas) -21382.181818  90137.045455  -71467.5

In [129]:
media_acatolicas1 = np.mean(diferenca_acatolicas1)
media_acatolicas2 = np.mean(diferenca_acatolicas2)
media_acatolicas3 = np.mean(diferenca_acatolicas3)

df_media_acatolicas = pd.DataFrame([[media_acatolicas1, media_acatolicas2, media_acatolicas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_media_acatolicas.index = ["Média (acatólicas)"]
df_media_acatolicas

                    Sem filtro   Filtro 1    Filtro 2
Média (acatólicas)    0.863636  76.227273  520.590909

In [130]:
outlier_inferior_catolicos1 = media_catolicos1 - (3 * desvio_padrao_catolicos1)
outlier_superior_catolicos1 = media_catolicos1 + (3 * desvio_padrao_catolicos1)

outlier_inferior_catolicos2 = media_catolicos2 - (3 * desvio_padrao_catolicos2)
outlier_superior_catolicos2 = media_catolicos2 + (3 * desvio_padrao_catolicos2)

outlier_inferior_catolicos3 = media_catolicos3 - (3 * desvio_padrao_catolicos3)
outlier_superior_catolicos3 = media_catolicos3 + (3 * desvio_padrao_catolicos3)


df_outlier_catolicos = pd.DataFrame([
    [outlier_inferior_catolicos1, outlier_superior_catolicos1,
    outlier_inferior_catolicos2, outlier_superior_catolicos2,
    outlier_inferior_catolicos3, outlier_superior_catolicos3]
], index=pd.MultiIndex.from_tuples([
    ("",)
]), columns=pd.MultiIndex.from_tuples([
    ("Observação discrepante (católicos)", "Sem filtro", "Outlier inferior"),
    ("Observação discrepante (católicos)", "Sem filtro", "Outlier superior"),
    ("Observação discrepante (católicos)", "Filtro 1", "Outlier inferior"),
    ("Observação discrepante (católicos)", "Filtro 1", "Outlier superior"),
    ("Observação discrepante (católicos)", "Filtro 2", "Outlier inferior"),
    ("Observação discrepante (católicos)", "Filtro 2", "Outlier superior")
]))
df_outlier_catolicos

 Observação discrepante (católicos)                                    \
                         Sem filtro                          Filtro 1
                   Outlier inferior Outlier superior Outlier inferior
                      -2.723345e+06     3.004963e+06    -2.359867e+06


                          Filtro 2
 Outlier superior Outlier inferior Outlier superior
     2.700730e+06    -2.478443e+06     2.888140e+06

In [131]:
outlier_inferior_acatolicos1 = media_acatolicos1 - (3 * desvio_padrao_acatolicos1)
outlier_superior_acatolicos1 = media_acatolicos1 + (3 * desvio_padrao_acatolicos1)

outlier_inferior_acatolicos2 = media_acatolicos2 - (3 * desvio_padrao_acatolicos2)
outlier_superior_acatolicos2 = media_acatolicos2 + (3 * desvio_padrao_acatolicos2)

outlier_inferior_acatolicos3 = media_acatolicos3 - (3 * desvio_padrao_acatolicos3)
outlier_superior_acatolicos3 = media_acatolicos3 + (3 * desvio_padrao_acatolicos3)


df_outlier_acatolicos = pd.DataFrame([
    [outlier_inferior_acatolicos1, outlier_superior_acatolicos1,
    outlier_inferior_acatolicos2, outlier_superior_acatolicos2,
    outlier_inferior_acatolicos3, outlier_superior_acatolicos3]
], index=pd.MultiIndex.from_tuples([
    ("",)
]), columns=pd.MultiIndex.from_tuples([
    ("Observação discrepante (acatólicos)", "Sem filtro", "Outlier inferior"),
    ("Observação discrepante (acatólicos)", "Sem filtro", "Outlier superior"),
    ("Observação discrepante (acatólicos)", "Filtro 1", "Outlier inferior"),
    ("Observação discrepante (acatólicos)", "Filtro 1", "Outlier superior"),
    ("Observação discrepante (acatólicos)", "Filtro 2", "Outlier inferior"),
    ("Observação discrepante (acatólicos)", "Filtro 2", "Outlier superior")
]))
df_outlier_acatolicos

 Observação discrepante (acatólicos)                                    \
                          Sem filtro                          Filtro 1
                    Outlier inferior Outlier superior Outlier inferior
                        -9801.254594     11080.890957     -9429.734948


                          Filtro 2
 Outlier superior Outlier inferior Outlier superior
     11685.916766     -9057.336675      12022.88213

In [132]:
outlier_inferior_catolicas1 = media_catolicas1 - (3 * desvio_padrao_catolicas1)
outlier_superior_catolicas1 = media_catolicas1 + (3 * desvio_padrao_catolicas1)

outlier_inferior_catolicas2 = media_catolicas2 - (3 * desvio_padrao_catolicas2)
outlier_superior_catolicas2 = media_catolicas2 + (3 * desvio_padrao_catolicas2)

outlier_inferior_catolicas3 = media_catolicas3 - (3 * desvio_padrao_catolicas3)
outlier_superior_catolicas3 = media_catolicas3 + (3 * desvio_padrao_catolicas3)


df_outlier_catolicas = pd.DataFrame([
    [outlier_inferior_catolicas1, outlier_superior_catolicas1,
    outlier_inferior_catolicas2, outlier_superior_catolicas2,
    outlier_inferior_catolicas3, outlier_superior_catolicas3]
], index=pd.MultiIndex.from_tuples([
    ("",)
]), columns=pd.MultiIndex.from_tuples([
    ("Observação discrepante (católicas)", "Sem filtro", "Outlier inferior"),
    ("Observação discrepante (católicas)", "Sem filtro", "Outlier superior"),
    ("Observação discrepante (católicas)", "Filtro 1", "Outlier inferior"),
    ("Observação discrepante (católicas)", "Filtro 1", "Outlier superior"),
    ("Observação discrepante (católicas)", "Filtro 2", "Outlier inferior"),
    ("Observação discrepante (católicas)", "Filtro 2", "Outlier superior")
]))
df_outlier_catolicas

 Observação discrepante (católicas)                                    \
                         Sem filtro                          Filtro 1
                   Outlier inferior Outlier superior Outlier inferior
                     -358465.219845    315700.856209   -637626.888312


                          Filtro 2
 Outlier superior Outlier inferior Outlier superior
    817900.979221   -977149.570453    834214.570453

In [133]:
outlier_inferior_acatolicas1 = media_acatolicas1 - (3 * desvio_padrao_acatolicas1)
outlier_superior_acatolicas1 = media_acatolicas1 + (3 * desvio_padrao_acatolicas1)

outlier_inferior_acatolicas2 = media_acatolicas2 - (3 * desvio_padrao_acatolicas2)
outlier_superior_acatolicas2 = media_acatolicas2 + (3 * desvio_padrao_acatolicas2)

outlier_inferior_acatolicas3 = media_acatolicas3 - (3 * desvio_padrao_acatolicas3)
outlier_superior_acatolicas3 = media_acatolicas3 + (3 * desvio_padrao_acatolicas3)


df_outlier_acatolicas = pd.DataFrame([
    [outlier_inferior_acatolicas1, outlier_superior_acatolicas1,
    outlier_inferior_acatolicas2, outlier_superior_acatolicas2,
    outlier_inferior_acatolicas3, outlier_superior_acatolicas3]
], index=pd.MultiIndex.from_tuples([
    ("",)
]), columns=pd.MultiIndex.from_tuples([
    ("Observação discrepante (acatólicas)", "Sem filtro", "Outlier inferior"),
    ("Observação discrepante (acatólicas)", "Sem filtro", "Outlier superior"),
    ("Observação discrepante (acatólicas)", "Filtro 1", "Outlier inferior"),
    ("Observação discrepante (acatólicas)", "Filtro 1", "Outlier superior"),
    ("Observação discrepante (acatólicas)", "Filtro 2", "Outlier inferior"),
    ("Observação discrepante (acatólicas)", "Filtro 2", "Outlier superior")
]))
df_outlier_acatolicas

 Observação discrepante (acatólicas)                                    \
                          Sem filtro                          Filtro 1
                    Outlier inferior Outlier superior Outlier inferior
                          -11.009401        12.736673      -832.684033


                          Filtro 2
 Outlier superior Outlier inferior Outlier superior
       985.138579     -2896.893651       3938.07547

# Nacionalidades

In [134]:
nacionalidade = df[['Unnamed: 0','Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25']]

nacionalidade_header = nacionalidade.iloc[2]
nacionalidade.columns = nacionalidade_header
nacionalidade = nacionalidade[3:]

columns_multiindex = pd.MultiIndex.from_tuples([
    ('', '', 'Províncias e Município Neutro'),
    ('Nacionalidades', 'dos Homens', 'Brasileiros'),
    ('Nacionalidades', 'dos Homens', 'Estrangeiros'),
    ('Nacionalidades', 'das Mulheres', 'Brasileiras'),
    ('Nacionalidades', 'das Mulheres', 'Estrangeiras')
])

nacionalidade.columns = columns_multiindex

nacionalidade

                                 Nacionalidades                            \
                                     dos Homens              das Mulheres
   Províncias e Município Neutro    Brasileiros Estrangeiros  Brasileiras
3                       Amazonas          29223         1760        25222
4                           Pará         123365         5224       118437
5                       Maranhão         139413         2529       141191
6                          Piauí          90022          300        88001
7                          Ceará         349805         1101       338475
8            Rio Grande do Norte         112305          416       108078
9                        Paraíba         178940          493       175102
10                    Pernambuco         373530         8035       368621
11                       Alagoas         154606          978       156321
12                       Sergipe          74352          387        78723
13                         Bahia         622447         7906       577229
14                Espírito Santo          28190         1417        29359
15              Município Neutro          77872        56008        74851
16                Rio de Janeiro         225843        29963       225860
17                     São Paulo         336473        11831       327702
18                        Paraná          57224         2080        56049
19                Santa Catarina          64731         8357        65241
20             Rio Grande do Sul         166042        24980       164522
21                  Minas Gerais         833175        14417       817692
22                         Goiás          74818          150        74698
23                   Mato Grosso          26986         1005        25455
24                         Total        4139362       179337      4036829



   Estrangeiras
3           426
4           753
5           968
6           104
7           392
8           160
9           165
10         2325
11          363
12          158
13         4210
14          512
15        17302
16         8421
17         4736
18          809
19         6489
20        11478
21         3992
22           77
23          304
24        64144

In [135]:
tabela_manual_brasileiros = pd.to_numeric(df.iloc[3:25, 22])

tabela_ocr_brasileiros1 = pd.to_numeric(df1.iloc[:, 21])
diferenca_brasileiros1 = tabela_manual_brasileiros.values - tabela_ocr_brasileiros1.values

tabela_ocr_brasileiros2 = pd.to_numeric(df2.iloc[:, 21])
diferenca_brasileiros2 = tabela_manual_brasileiros.values - tabela_ocr_brasileiros2.values

tabela_ocr_brasileiros3 = pd.to_numeric(df3.iloc[:, 21])
diferenca_brasileiros3 = tabela_manual_brasileiros.values - tabela_ocr_brasileiros3.values

In [136]:
tabela_manual_estrangeiros = pd.to_numeric(df.iloc[3:25, 23])

tabela_ocr_estrangeiros1 = pd.to_numeric(df1.iloc[:, 22])
diferenca_estrangeiros1 = tabela_manual_estrangeiros.values - tabela_ocr_estrangeiros1.values

tabela_ocr_estrangeiros2 = pd.to_numeric(df2.iloc[:, 22])
diferenca_estrangeiros2 = tabela_manual_estrangeiros.values - tabela_ocr_estrangeiros2.values

tabela_ocr_estrangeiros3 = pd.to_numeric(df3.iloc[:, 22])
diferenca_estrangeiros3 = tabela_manual_estrangeiros.values - tabela_ocr_estrangeiros3.values

In [137]:
tabela_manual_brasileiras = pd.to_numeric(df.iloc[3:25, 24])

tabela_ocr_brasileiras1 = pd.to_numeric(df1.iloc[:, 23])
diferenca_brasileiras1 = tabela_manual_brasileiras.values - tabela_ocr_brasileiras1.values

tabela_ocr_brasileiras2 = pd.to_numeric(df2.iloc[:, 23])
diferenca_brasileiras2 = tabela_manual_brasileiras.values - tabela_ocr_brasileiras2.values

tabela_ocr_brasileiras3 = pd.to_numeric(df3.iloc[:, 23])
diferenca_brasileiras3 = tabela_manual_brasileiras.values - tabela_ocr_brasileiras3.values

In [138]:
tabela_manual_estrangeiras = pd.to_numeric(df.iloc[3:25, 25])

tabela_ocr_estrangeiras1 = pd.to_numeric(df1.iloc[:, 24])
diferenca_estrangeiras1 = tabela_manual_estrangeiras.values - tabela_ocr_estrangeiras1.values

tabela_ocr_estrangeiras2 = pd.to_numeric(df2.iloc[:, 24])
diferenca_estrangeiras2 = tabela_manual_estrangeiras.values - tabela_ocr_estrangeiras2.values

tabela_ocr_estrangeiras3 = pd.to_numeric(df3.iloc[:, 24])
diferenca_estrangeiras3 = tabela_manual_estrangeiras.values - tabela_ocr_estrangeiras3.values

In [139]:
variancia_brasileiros1 = np.var(diferenca_brasileiros1)
variancia_brasileiros2 = np.var(diferenca_brasileiros2)
variancia_brasileiros3 = np.var(diferenca_brasileiros3)

df_variancia_brasileiros = pd.DataFrame([[variancia_brasileiros1, variancia_brasileiros2, variancia_brasileiros3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_variancia_brasileiros.index = ["Variância (brasileiros)"]
df_variancia_brasileiros

                           Sem filtro      Filtro 1      Filtro 2
Variância (brasileiros)  1.354523e+11  1.707784e+10  5.259956e+11

In [140]:
variancia_estrangeiros1 = np.var(diferenca_estrangeiros1)
variancia_estrangeiros2 = np.var(diferenca_estrangeiros2)
variancia_estrangeiros3 = np.var(diferenca_estrangeiros3)

df_variancia_estrangeiros = pd.DataFrame([[variancia_estrangeiros1, variancia_estrangeiros2, variancia_estrangeiros3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_variancia_estrangeiros.index = ["Variância (estrangeiros)"]
df_variancia_estrangeiros

                            Sem filtro      Filtro 1      Filtro 2
Variância (estrangeiros)  4.412875e+06  1.369559e+09  1.470230e+09

In [141]:
variancia_brasileiras1 = np.var(diferenca_brasileiras1)
variancia_brasileiras2 = np.var(diferenca_brasileiras2)
variancia_brasileiras3 = np.var(diferenca_brasileiras3)

df_variancia_brasileiras = pd.DataFrame([[variancia_brasileiras1, variancia_brasileiras2, variancia_brasileiras3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_variancia_brasileiras.index = ["Variância (brasileiras)"]
df_variancia_brasileiras

                           Sem filtro      Filtro 1      Filtro 2
Variância (brasileiras)  7.760837e+11  8.627650e+11  4.112681e+11

In [142]:
variancia_estrangeiras1 = np.var(diferenca_estrangeiras1)
variancia_estrangeiras2 = np.var(diferenca_estrangeiras2)
variancia_estrangeiras3 = np.var(diferenca_estrangeiras3)

df_variancia_estrangeiras = pd.DataFrame([[variancia_estrangeiras1, variancia_estrangeiras2, variancia_estrangeiras3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_variancia_estrangeiras.index = ["Variância (estrangeiras)"]
df_variancia_estrangeiras

                            Sem filtro      Filtro 1      Filtro 2
Variância (estrangeiras)  2.900310e+07  1.806847e+08  1.806847e+08

In [143]:
desvio_padrao_brasileiros1 = np.std(diferenca_brasileiros1)
desvio_padrao_brasileiros2 = np.std(diferenca_brasileiros2)
desvio_padrao_brasileiros3 = np.std(diferenca_brasileiros3)

df_desvio_padrao_brasileiros = pd.DataFrame([[desvio_padrao_brasileiros1, desvio_padrao_brasileiros2, desvio_padrao_brasileiros3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_desvio_padrao_brasileiros.index = ["Desvio padrão (brasileiros)"]
df_desvio_padrao_brasileiros

                                Sem filtro       Filtro 1       Filtro 2
Desvio padrão (brasileiros)  368038.389854  130682.197842  725255.551588

In [144]:
desvio_padrao_estrangeiros1 = np.std(diferenca_estrangeiros1)
desvio_padrao_estrangeiros2 = np.std(diferenca_estrangeiros2)
desvio_padrao_estrangeiros3 = np.std(diferenca_estrangeiros3)

df_desvio_padrao_estrangeiros = pd.DataFrame([[desvio_padrao_estrangeiros1, desvio_padrao_estrangeiros2, desvio_padrao_estrangeiros3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_desvio_padrao_estrangeiros.index = ["Desvio padrão (estrangeiros)"]
df_desvio_padrao_estrangeiros

                               Sem filtro      Filtro 1      Filtro 2
Desvio padrão (estrangeiros)  2100.684362  37007.554797  38343.582632

In [145]:
desvio_padrao_brasileiras1 = np.std(diferenca_brasileiras1)
desvio_padrao_brasileiras2 = np.std(diferenca_brasileiras2)
desvio_padrao_brasileiras3 = np.std(diferenca_brasileiras3)

df_desvio_padrao_brasileiras = pd.DataFrame([[desvio_padrao_brasileiras1, desvio_padrao_brasileiras2, desvio_padrao_brasileiras3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_desvio_padrao_brasileiras.index = ["Desvio padrão (brasileiras)"]
df_desvio_padrao_brasileiras

                                Sem filtro       Filtro 1       Filtro 2
Desvio padrão (brasileiras)  880956.105645  928851.448928  641301.857328

In [146]:
desvio_padrao_estrangeiras1 = np.std(diferenca_estrangeiras1)
desvio_padrao_estrangeiras2 = np.std(diferenca_estrangeiras2)
desvio_padrao_estrangeiras3 = np.std(diferenca_estrangeiras3)

df_desvio_padrao_estrangeiras = pd.DataFrame([[desvio_padrao_estrangeiras1, desvio_padrao_estrangeiras2, desvio_padrao_estrangeiras3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_desvio_padrao_estrangeiras.index = ["Desvio padrão (estrangeiras)"]
df_desvio_padrao_estrangeiras

                               Sem filtro     Filtro 1     Filtro 2
Desvio padrão (estrangeiras)  5385.452448  13441.90272  13441.90272

In [147]:
coeficiente_variacao_brasileiros1 = desvio_padrao_brasileiros1 / np.mean(diferenca_brasileiros1) * 100
coeficiente_variacao_brasileiros2 = desvio_padrao_brasileiros2 / np.mean(diferenca_brasileiros2) * 100
coeficiente_variacao_brasileiros3 = desvio_padrao_brasileiros3 / np.mean(diferenca_brasileiros3) * 100

df_coeficiente_variacao_brasileiros = pd.DataFrame([[coeficiente_variacao_brasileiros1, coeficiente_variacao_brasileiros2, coeficiente_variacao_brasileiros3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_coeficiente_variacao_brasileiros.index = ["Coeficiente de variação (brasileiros)"]
df_coeficiente_variacao_brasileiros

                                       Sem filtro    Filtro 1    Filtro 2
Coeficiente de variação (brasileiros) -274.761579  308.058833 -730.233754

In [148]:
coeficiente_variacao_estrangeiros1 = desvio_padrao_estrangeiros1 / np.mean(diferenca_estrangeiros1) * 100
coeficiente_variacao_estrangeiros2 = desvio_padrao_estrangeiros2 / np.mean(diferenca_estrangeiros2) * 100
coeficiente_variacao_estrangeiros3 = desvio_padrao_estrangeiros3 / np.mean(diferenca_estrangeiros3) * 100

df_coeficiente_variacao_estrangeiros = pd.DataFrame([[coeficiente_variacao_estrangeiros1, coeficiente_variacao_estrangeiros2, coeficiente_variacao_estrangeiros3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_coeficiente_variacao_estrangeiros.index = ["Coeficiente de variação (estrangeiros)"]
df_coeficiente_variacao_estrangeiros

                                        Sem filtro    Filtro 1    Filtro 2
Coeficiente de variação (estrangeiros)   303.38775  352.902051  352.858991

In [149]:
coeficiente_variacao_brasileiras1 = desvio_padrao_brasileiras1 / np.mean(diferenca_brasileiras1) * 100
coeficiente_variacao_brasileiras2 = desvio_padrao_brasileiras2 / np.mean(diferenca_brasileiras2) * 100
coeficiente_variacao_brasileiras3 = desvio_padrao_brasileiras3 / np.mean(diferenca_brasileiras3) * 100

df_coeficiente_variacao_brasileiras = pd.DataFrame([[coeficiente_variacao_brasileiras1, coeficiente_variacao_brasileiras2, coeficiente_variacao_brasileiras3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_coeficiente_variacao_brasileiras.index = ["Coeficiente de variação (brasileiras)"]
df_coeficiente_variacao_brasileiras

                                       Sem filtro    Filtro 1    Filtro 2
Coeficiente de variação (brasileiras)  842.392158  438.812347  304.884716

In [150]:
coeficiente_variacao_estrangeiras1 = desvio_padrao_estrangeiras1 / np.mean(diferenca_estrangeiras1) * 100
coeficiente_variacao_estrangeiras2 = desvio_padrao_estrangeiras2 / np.mean(diferenca_estrangeiras2) * 100
coeficiente_variacao_estrangeiras3 = desvio_padrao_estrangeiras3 / np.mean(diferenca_estrangeiras3) * 100

df_coeficiente_variacao_estrangeiras = pd.DataFrame([[coeficiente_variacao_estrangeiras1, coeficiente_variacao_estrangeiras2, coeficiente_variacao_estrangeiras3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_coeficiente_variacao_estrangeiras.index = ["Coeficiente de variação (estrangeiras)"]
df_coeficiente_variacao_estrangeiras

                                        Sem filtro    Filtro 1    Filtro 2
Coeficiente de variação (estrangeiras) -882.203677  230.514046  230.514046

In [151]:
media_brasileiros1 = np.mean(diferenca_brasileiros1)
media_brasileiros2 = np.mean(diferenca_brasileiros2)
media_brasileiros3 = np.mean(diferenca_brasileiros3)

df_media_brasileiros = pd.DataFrame([[media_brasileiros1, media_brasileiros2, media_brasileiros3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_media_brasileiros.index = ["Média (brasileiros)"]
df_media_brasileiros

                        Sem filtro      Filtro 1      Filtro 2
Média (brasileiros) -133948.272727  42421.181818 -99318.272727

In [152]:
media_estrangeiros1 = np.mean(diferenca_estrangeiros1)
media_estrangeiros2 = np.mean(diferenca_estrangeiros2)
media_estrangeiros3 = np.mean(diferenca_estrangeiros3)

df_media_estrangeiros = pd.DataFrame([[media_estrangeiros1, media_estrangeiros2, media_estrangeiros3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_media_estrangeiros.index = ["Média (estrangeiros)"]
df_media_estrangeiros

                      Sem filtro      Filtro 1      Filtro 2
Média (estrangeiros)  692.409091  10486.636364  10866.545455

In [153]:
media_brasileiras1 = np.mean(diferenca_brasileiras1)
media_brasileiras2 = np.mean(diferenca_brasileiras2)
media_brasileiras3 = np.mean(diferenca_brasileiras3)

df_media_brasileiras = pd.DataFrame([[media_brasileiras1, media_brasileiras2, media_brasileiras3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_media_brasileiras.index = ["Média (brasileiras)"]
df_media_brasileiras

                        Sem filtro       Filtro 1       Filtro 2
Média (brasileiras)  104577.909091  211673.954545  210342.409091

In [154]:
media_estrangeiras1 = np.mean(diferenca_estrangeiras1)
media_estrangeiras2 = np.mean(diferenca_estrangeiras2)
media_estrangeiras3 = np.mean(diferenca_estrangeiras3)

df_media_estrangeiras = pd.DataFrame([[media_estrangeiras1, media_estrangeiras2, media_estrangeiras3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_media_estrangeiras.index = ["Média (estrangeiras)"]
df_media_estrangeiras

                      Sem filtro     Filtro 1     Filtro 2
Média (estrangeiras) -610.454545  5831.272727  5831.272727

In [155]:
outlier_inferior_brasileiros1 = media_brasileiros1 - (3 * desvio_padrao_brasileiros1)
outlier_superior_brasileiros1 = media_brasileiros1 + (3 * desvio_padrao_brasileiros1)

outlier_inferior_brasileiros2 = media_brasileiros2 - (3 * desvio_padrao_brasileiros2)
outlier_superior_brasileiros2 = media_brasileiros2 + (3 * desvio_padrao_brasileiros2)

outlier_inferior_brasileiros3 = media_brasileiros3 - (3 * desvio_padrao_brasileiros3)
outlier_superior_brasileiros3 = media_brasileiros3 + (3 * desvio_padrao_brasileiros3)


df_outlier_brasileiros = pd.DataFrame([
    [outlier_inferior_brasileiros1, outlier_superior_brasileiros1,
    outlier_inferior_brasileiros2, outlier_superior_brasileiros2,
    outlier_inferior_brasileiros3, outlier_superior_brasileiros3]
], index=pd.MultiIndex.from_tuples([
    ("",)
]), columns=pd.MultiIndex.from_tuples([
    ("Observação discrepante (brasileiros)", "Sem filtro", "Outlier inferior"),
    ("Observação discrepante (brasileiros)", "Sem filtro", "Outlier superior"),
    ("Observação discrepante (brasileiros)", "Filtro 1", "Outlier inferior"),
    ("Observação discrepante (brasileiros)", "Filtro 1", "Outlier superior"),
    ("Observação discrepante (brasileiros)", "Filtro 2", "Outlier inferior"),
    ("Observação discrepante (brasileiros)", "Filtro 2", "Outlier superior")
]))
df_outlier_brasileiros

 Observação discrepante (brasileiros)                                    \
                           Sem filtro                          Filtro 1
                     Outlier inferior Outlier superior Outlier inferior
                        -1.238063e+06    970166.896835   -349625.411709


                          Filtro 2
 Outlier superior Outlier inferior Outlier superior
    434467.775345    -2.275085e+06     2.076448e+06

In [156]:
outlier_inferior_estrangeiros1 = media_estrangeiros1 - (3 * desvio_padrao_estrangeiros1)
outlier_superior_estrangeiros1 = media_estrangeiros1 + (3 * desvio_padrao_estrangeiros1)

outlier_inferior_estrangeiros2 = media_estrangeiros2 - (3 * desvio_padrao_estrangeiros2)
outlier_superior_estrangeiros2 = media_estrangeiros2 + (3 * desvio_padrao_estrangeiros2)

outlier_inferior_estrangeiros3 = media_estrangeiros3 - (3 * desvio_padrao_estrangeiros3)
outlier_superior_estrangeiros3 = media_estrangeiros3 + (3 * desvio_padrao_estrangeiros3)


df_outlier_estrangeiros = pd.DataFrame([
    [outlier_inferior_estrangeiros1, outlier_superior_estrangeiros1,
    outlier_inferior_estrangeiros2, outlier_superior_estrangeiros2,
    outlier_inferior_estrangeiros3, outlier_superior_estrangeiros3]
], index=pd.MultiIndex.from_tuples([
    ("",)
]), columns=pd.MultiIndex.from_tuples([
    ("Observação discrepante (estrangeiros)", "Sem filtro", "Outlier inferior"),
    ("Observação discrepante (estrangeiros)", "Sem filtro", "Outlier superior"),
    ("Observação discrepante (estrangeiros)", "Filtro 1", "Outlier inferior"),
    ("Observação discrepante (estrangeiros)", "Filtro 1", "Outlier superior"),
    ("Observação discrepante (estrangeiros)", "Filtro 2", "Outlier inferior"),
    ("Observação discrepante (estrangeiros)", "Filtro 2", "Outlier superior")
]))
df_outlier_estrangeiros

 Observação discrepante (estrangeiros)                                    \
                            Sem filtro                          Filtro 1
                      Outlier inferior Outlier superior Outlier inferior
                          -5609.643994      6994.462176   -100536.028027


                          Filtro 2
 Outlier superior Outlier inferior Outlier superior
    121509.300754   -104164.202442    125897.293351

In [157]:
outlier_inferior_brasileiras1 = media_brasileiras1 - (3 * desvio_padrao_brasileiras1)
outlier_superior_brasileiras1 = media_brasileiras1 + (3 * desvio_padrao_brasileiras1)

outlier_inferior_brasileiras2 = media_brasileiras2 - (3 * desvio_padrao_brasileiras2)
outlier_superior_brasileiras2 = media_brasileiras2 + (3 * desvio_padrao_brasileiras2)

outlier_inferior_brasileiras3 = media_brasileiras3 - (3 * desvio_padrao_brasileiras3)
outlier_superior_brasileiras3 = media_brasileiras3 + (3 * desvio_padrao_brasileiras3)


df_outlier_brasileiras = pd.DataFrame([
    [outlier_inferior_brasileiras1, outlier_superior_brasileiras1,
    outlier_inferior_brasileiras2, outlier_superior_brasileiras2,
    outlier_inferior_brasileiras3, outlier_superior_brasileiras3]
], index=pd.MultiIndex.from_tuples([
    ("",)
]), columns=pd.MultiIndex.from_tuples([
    ("Observação discrepante (brasileiras)", "Sem filtro", "Outlier inferior"),
    ("Observação discrepante (brasileiras)", "Sem filtro", "Outlier superior"),
    ("Observação discrepante (brasileiras)", "Filtro 1", "Outlier inferior"),
    ("Observação discrepante (brasileiras)", "Filtro 1", "Outlier superior"),
    ("Observação discrepante (brasileiras)", "Filtro 2", "Outlier inferior"),
    ("Observação discrepante (brasileiras)", "Filtro 2", "Outlier superior")
]))
df_outlier_brasileiras

 Observação discrepante (brasileiras)                                    \
                           Sem filtro                          Filtro 1
                     Outlier inferior Outlier superior Outlier inferior
                        -2.538290e+06     2.747446e+06    -2.574880e+06


                          Filtro 2
 Outlier superior Outlier inferior Outlier superior
     2.998228e+06    -1.713563e+06     2.134248e+06

In [158]:
outlier_inferior_estrangeiras1 = media_estrangeiras1 - (3 * desvio_padrao_estrangeiras1)
outlier_superior_estrangeiras1 = media_estrangeiras1 + (3 * desvio_padrao_estrangeiras1)

outlier_inferior_estrangeiras2 = media_estrangeiras2 - (3 * desvio_padrao_estrangeiras2)
outlier_superior_estrangeiras2 = media_estrangeiras2 + (3 * desvio_padrao_estrangeiras2)

outlier_inferior_estrangeiras3 = media_estrangeiras3 - (3 * desvio_padrao_estrangeiras3)
outlier_superior_estrangeiras3 = media_estrangeiras3 + (3 * desvio_padrao_estrangeiras3)


df_outlier_estrangeiras = pd.DataFrame([
    [outlier_inferior_estrangeiras1, outlier_superior_estrangeiras1,
    outlier_inferior_estrangeiras2, outlier_superior_estrangeiras2,
    outlier_inferior_estrangeiras3, outlier_superior_estrangeiras3]
], index=pd.MultiIndex.from_tuples([
    ("",)
]), columns=pd.MultiIndex.from_tuples([
    ("Observação discrepante (estrangeiras)", "Sem filtro", "Outlier inferior"),
    ("Observação discrepante (estrangeiras)", "Sem filtro", "Outlier superior"),
    ("Observação discrepante (estrangeiras)", "Filtro 1", "Outlier inferior"),
    ("Observação discrepante (estrangeiras)", "Filtro 1", "Outlier superior"),
    ("Observação discrepante (estrangeiras)", "Filtro 2", "Outlier inferior"),
    ("Observação discrepante (estrangeiras)", "Filtro 2", "Outlier superior")
]))
df_outlier_estrangeiras

 Observação discrepante (estrangeiras)                                    \
                            Sem filtro                          Filtro 1
                      Outlier inferior Outlier superior Outlier inferior
                         -16766.811888     15545.902798    -34494.435434


                          Filtro 2
 Outlier superior Outlier inferior Outlier superior
     46156.980888    -34494.435434     46156.980888

# Grau de instrução

In [159]:
instrucao = df[['Unnamed: 0','Instrução', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35']]

instrucao_header = instrucao.iloc[2]
instrucao.columns = instrucao_header
instrucao = instrucao[3:]

columns_multiindex = pd.MultiIndex.from_tuples([
    ('', '', '', 'Províncias e Município Neutro'),
    ('Instrução', '', 'Homens', 'Sabem ler e escrever'),
    ('Instrução', '', 'Homens', 'Analfabetos'),
    ('Instrução', '', 'Mulheres', 'Sabem ler e escrever'),
    ('Instrução', '', 'Mulheres', 'Analfabetas'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninos', 'Frequentam escolas'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninos', 'Não frequentam'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninos', 'Total'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninas', 'Frequentam escolas'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninas', 'Não frequentam'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninas', 'Total')
])

instrucao.columns = columns_multiindex

instrucao

                                            Instrução              \

                                               Homens
   Províncias e Município Neutro Sabem ler e escrever Analfabetos
3                       Amazonas                 6160       24823
4                           Pará                39718       88871
5                       Maranhão                44375       97567
6                          Piauí                17677       72645
7                          Ceará                58657      292249
8            Rio Grande do Norte                23602       39119
9                        Paraíba                29224      150209
10                    Pernambuco                92664      288901
11                       Alagoas                26046      129538
12                       Sergipe                18687       56052
13                         Bahia               161937      468416
14                Espírito Santo                 7229       22378
15              Município Neutro                65164       68714
16                Rio de Janeiro                69997      185809
17                     São Paulo                92977      255327
18                        Paraná                19014       40299
19                Santa Catarina                12927       59161
20             Rio Grande do Sul                 5592      134060
21                  Minas Gerais               145297      702295
22                         Goiás                15699       59299
23                   Mato Grosso                 7114       20877
24                         Total              1012097     3306602

                                                                      \
                                    População escolar de 6 a 15 anos
               Mulheres                                      Meninos
   Sabem ler e escrever Analfabetas               Frequentam escolas
3                  1453       24195                              824
4                 20677       98513                             5768
5                 24196      117963                             8739
6                 10093       78012                             1777
7                 20903      317964                            10021
8                 16220       92018                             2643
9                 11988      163279                             6630
10                54659      316287                            14069
11                15814      140870                             5455
12                10447       68434                             3402
13                37135      494304                            22260
14                 2503       27368                             1564
15                33992       58101                             5788
16                44603      189678                            12622
17                48090      284348                            15069
18                12802       44056                             2558
19                 7999       63731                             3100
20                38341      137659                             9947
21                78271      743413                            19968
22                 6987       67788                             2566
23                 3808       21951                              881
24               550981     3549992                           155651



                                     Meninas
   Não frequentam   Total Frequentam escolas Não frequentam   Total
3            5056    5880                371           3269    3640
4           25753   31521               3441          25020   28461
5           28142   36881               4844          29567   34411
6           15960   17737               1024          16968   17992
7           83808   93829               5399          85087   90486
8           18662   21305               2058          19857   21915
9           44061   50691               3894          45830   49724
10          82133   96202               9301          80960   90261
11          34261   39716               4028          34726   38754
12          14934   18336               1832          17333   19165
13         119426  141686              81743         113313  195056
14           5323    6887                722           5101    6823
15          10449   22237               4258          15019   19277
16          32019   44641               8194          33089   41283
17          71271   86340               8544          73915   82458
18           9666   12224               1866          10762   12628
19          15676   18776               2114          15473   17587
20          36222   46169               7947          33292   41239
21          66983  125012              11940         112824  124764
22          16864   19430               1240          16982   18222
23           5401    6282                338           6187    6525
24         786131  941782             165098         795574  960672

# Grau de instrução (adultos)

In [160]:
instrucao_adultos = df[['Unnamed: 0','Instrução', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29']]

instrucao_adultos_header = instrucao_adultos.iloc[2]
instrucao_adultos.columns = instrucao_adultos_header
instrucao_adultos = instrucao_adultos[3:]

columns_multiindex = pd.MultiIndex.from_tuples([
    ('', '', 'Províncias e Município Neutro'),
    ('Instrução', 'Homens', 'Sabem ler e escrever'),
    ('Instrução', 'Homens', 'Analfabetos'),
    ('Instrução', 'Mulheres', 'Sabem ler e escrever'),
    ('Instrução', 'Mulheres', 'Analfabetas')
])

instrucao_adultos.columns = columns_multiindex

instrucao_adultos

                                            Instrução              \
                                               Homens
   Províncias e Município Neutro Sabem ler e escrever Analfabetos
3                       Amazonas                 6160       24823
4                           Pará                39718       88871
5                       Maranhão                44375       97567
6                          Piauí                17677       72645
7                          Ceará                58657      292249
8            Rio Grande do Norte                23602       39119
9                        Paraíba                29224      150209
10                    Pernambuco                92664      288901
11                       Alagoas                26046      129538
12                       Sergipe                18687       56052
13                         Bahia               161937      468416
14                Espírito Santo                 7229       22378
15              Município Neutro                65164       68714
16                Rio de Janeiro                69997      185809
17                     São Paulo                92977      255327
18                        Paraná                19014       40299
19                Santa Catarina                12927       59161
20             Rio Grande do Sul                 5592      134060
21                  Minas Gerais               145297      702295
22                         Goiás                15699       59299
23                   Mato Grosso                 7114       20877
24                         Total              1012097     3306602


               Mulheres
   Sabem ler e escrever Analfabetas
3                  1453       24195
4                 20677       98513
5                 24196      117963
6                 10093       78012
7                 20903      317964
8                 16220       92018
9                 11988      163279
10                54659      316287
11                15814      140870
12                10447       68434
13                37135      494304
14                 2503       27368
15                33992       58101
16                44603      189678
17                48090      284348
18                12802       44056
19                 7999       63731
20                38341      137659
21                78271      743413
22                 6987       67788
23                 3808       21951
24               550981     3549992

In [161]:
tabela_manual_alfabetizados = pd.to_numeric(df.iloc[3:25, 26])

tabela_ocr_alfabetizados1 = pd.to_numeric(df1.iloc[:, 25])
diferenca_alfabetizados1 = tabela_manual_alfabetizados.values - tabela_ocr_alfabetizados1.values

tabela_ocr_alfabetizados2 = pd.to_numeric(df2.iloc[:, 25])
diferenca_alfabetizados2 = tabela_manual_alfabetizados.values - tabela_ocr_alfabetizados2.values

tabela_ocr_alfabetizados3 = pd.to_numeric(df3.iloc[:, 25])
diferenca_alfabetizados3 = tabela_manual_alfabetizados.values - tabela_ocr_alfabetizados3.values

In [162]:
tabela_manual_analfabetos = pd.to_numeric(df.iloc[3:26, 27])

tabela_ocr_analfabetos1 = pd.to_numeric(df1.iloc[:, 26])
diferenca_analfabetos1 = tabela_manual_analfabetos.values - tabela_ocr_analfabetos1.values

tabela_ocr_analfabetos2 = pd.to_numeric(df2.iloc[:, 26])
diferenca_analfabetos2 = tabela_manual_analfabetos.values - tabela_ocr_analfabetos2.values

tabela_ocr_analfabetos3 = pd.to_numeric(df3.iloc[:, 26])
diferenca_analfabetos3 = tabela_manual_analfabetos.values - tabela_ocr_analfabetos3.values

In [163]:
tabela_manual_alfabetizadas = pd.to_numeric(df.iloc[3:27, 28])

tabela_ocr_alfabetizadas1 = pd.to_numeric(df1.iloc[:, 27])
diferenca_alfabetizadas1 = tabela_manual_alfabetizadas.values - tabela_ocr_alfabetizadas1.values

tabela_ocr_alfabetizadas2 = pd.to_numeric(df2.iloc[:, 27])
diferenca_alfabetizadas2 = tabela_manual_alfabetizadas.values - tabela_ocr_alfabetizadas2.values

tabela_ocr_alfabetizadas3 = pd.to_numeric(df3.iloc[:, 27])
diferenca_alfabetizadas3 = tabela_manual_alfabetizadas.values - tabela_ocr_alfabetizadas3.values

In [164]:
tabela_manual_analfabetas = pd.to_numeric(df.iloc[3:28, 29])

tabela_ocr_analfabetas1 = pd.to_numeric(df1.iloc[:, 28])
diferenca_analfabetas1 = tabela_manual_analfabetas.values - tabela_ocr_analfabetas1.values

tabela_ocr_analfabetas2 = pd.to_numeric(df2.iloc[:, 28])
diferenca_analfabetas2 = tabela_manual_analfabetas.values - tabela_ocr_analfabetas2.values

tabela_ocr_analfabetas3 = pd.to_numeric(df3.iloc[:, 28])
diferenca_analfabetas3 = tabela_manual_analfabetas.values - tabela_ocr_analfabetas3.values

In [165]:
variancia_alfabetizados1 = np.var(diferenca_alfabetizados1)
variancia_alfabetizados2 = np.var(diferenca_alfabetizados2)
variancia_alfabetizados3 = np.var(diferenca_alfabetizados3)

df_variancia_alfabetizados = pd.DataFrame([[variancia_alfabetizados1, variancia_alfabetizados2, variancia_alfabetizados3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_variancia_alfabetizados.index = ["Variância (alfabetizados)"]
df_variancia_alfabetizados

                             Sem filtro      Filtro 1      Filtro 2
Variância (alfabetizados)  9.463873e+10  1.206178e+11  3.592342e+12

In [166]:
variancia_analfabetos1 = np.var(diferenca_analfabetos1)
variancia_analfabetos2 = np.var(diferenca_analfabetos2)
variancia_analfabetos3 = np.var(diferenca_analfabetos3)

df_variancia_analfabetos = pd.DataFrame([[variancia_analfabetos1, variancia_analfabetos2, variancia_analfabetos3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_variancia_analfabetos.index = ["Variância (analfabetos)"]
df_variancia_analfabetos

                           Sem filtro      Filtro 1      Filtro 2
Variância (analfabetos)  4.698817e+09  2.631321e+12  1.151909e+12

In [167]:
variancia_alfabetizadas1 = np.var(diferenca_alfabetizadas1)
variancia_alfabetizadas2 = np.var(diferenca_alfabetizadas2)
variancia_alfabetizadas3 = np.var(diferenca_alfabetizadas3)

df_variancia_alfabetizadas = pd.DataFrame([[variancia_alfabetizadas1, variancia_alfabetizadas2, variancia_alfabetizadas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_variancia_alfabetizadas.index = ["Variância (alfabetizadas)"]
df_variancia_alfabetizadas

                             Sem filtro      Filtro 1      Filtro 2
Variância (alfabetizadas)  1.324498e+10  2.539269e+10  1.549996e+10

In [168]:
variancia_analfabetas1 = np.var(diferenca_analfabetas1)
variancia_analfabetas2 = np.var(diferenca_analfabetas2)
variancia_analfabetas3 = np.var(diferenca_analfabetas3)

df_variancia_analfabetas = pd.DataFrame([[variancia_analfabetas1, variancia_analfabetas2, variancia_analfabetas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_variancia_analfabetas.index = ["Variância (analfabetas)"]
df_variancia_analfabetas

                           Sem filtro      Filtro 1      Filtro 2
Variância (analfabetas)  5.315430e+11  1.170247e+12  1.623001e+12

In [169]:
desvio_padrao_alfabetizados1 = np.std(diferenca_alfabetizados1)
desvio_padrao_alfabetizados2 = np.std(diferenca_alfabetizados2)
desvio_padrao_alfabetizados3 = np.std(diferenca_alfabetizados3)

df_desvio_padrao_alfabetizados = pd.DataFrame([[desvio_padrao_alfabetizados1, desvio_padrao_alfabetizados2, desvio_padrao_alfabetizados3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_desvio_padrao_alfabetizados.index = ["Desvio padrão (alfabetizados)"]
df_desvio_padrao_alfabetizados

                                  Sem filtro       Filtro 1      Filtro 2
Desvio padrão (alfabetizados)  307634.076823  347300.784343  1.895347e+06

In [170]:
desvio_padrao_analfabetos1 = np.std(diferenca_analfabetos1)
desvio_padrao_analfabetos2 = np.std(diferenca_analfabetos2)
desvio_padrao_analfabetos3 = np.std(diferenca_analfabetos3)

df_desvio_padrao_analfabetos = pd.DataFrame([[desvio_padrao_analfabetos1, desvio_padrao_analfabetos2, desvio_padrao_analfabetos3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_desvio_padrao_analfabetos.index = ["Desvio padrão (analfabetos)"]
df_desvio_padrao_analfabetos

                               Sem filtro      Filtro 1      Filtro 2
Desvio padrão (analfabetos)  68547.915065  1.622135e+06  1.073270e+06

In [171]:
desvio_padrao_alfabetizadas1 = np.std(diferenca_alfabetizadas1)
desvio_padrao_alfabetizadas2 = np.std(diferenca_alfabetizadas2)
desvio_padrao_alfabetizadas3 = np.std(diferenca_alfabetizadas3)

df_desvio_padrao_alfabetizadas = pd.DataFrame([[desvio_padrao_alfabetizadas1, desvio_padrao_alfabetizadas2, desvio_padrao_alfabetizadas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_desvio_padrao_alfabetizadas.index = ["Desvio padrão (alfabetizadas)"]
df_desvio_padrao_alfabetizadas

                                  Sem filtro       Filtro 1       Filtro 2
Desvio padrão (alfabetizadas)  115086.815797  159350.825138  124498.816444

In [172]:
desvio_padrao_analfabetas1 = np.std(diferenca_analfabetas1)
desvio_padrao_analfabetas2 = np.std(diferenca_analfabetas2)
desvio_padrao_analfabetas3 = np.std(diferenca_analfabetas3)

df_desvio_padrao_analfabetas = pd.DataFrame([[desvio_padrao_analfabetas1, desvio_padrao_analfabetas2, desvio_padrao_analfabetas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_desvio_padrao_analfabetas.index = ["Desvio padrão (analfabetas)"]
df_desvio_padrao_analfabetas

                               Sem filtro      Filtro 1      Filtro 2
Desvio padrão (analfabetas)  729069.96183  1.081779e+06  1.273970e+06

In [173]:
coeficiente_variacao_alfabetizados1 = desvio_padrao_alfabetizados1 / np.mean(diferenca_alfabetizados1) * 100
coeficiente_variacao_alfabetizados2 = desvio_padrao_alfabetizados2 / np.mean(diferenca_alfabetizados2) * 100
coeficiente_variacao_alfabetizados3 = desvio_padrao_alfabetizados3 / np.mean(diferenca_alfabetizados3) * 100

df_coeficiente_variacao_alfabetizados = pd.DataFrame([[coeficiente_variacao_alfabetizados1, coeficiente_variacao_alfabetizados2, coeficiente_variacao_alfabetizados3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_coeficiente_variacao_alfabetizados.index = ["Coeficiente de variação (alfabetizados)"]
df_coeficiente_variacao_alfabetizados

                                         Sem filtro    Filtro 1    Filtro 2
Coeficiente de variação (alfabetizados) -419.860758 -339.311691 -445.451103

In [174]:
coeficiente_variacao_analfabetos1 = desvio_padrao_analfabetos1 / np.mean(diferenca_analfabetos1) * 100
coeficiente_variacao_analfabetos2 = desvio_padrao_analfabetos2 / np.mean(diferenca_analfabetos2) * 100
coeficiente_variacao_analfabetos3 = desvio_padrao_analfabetos3 / np.mean(diferenca_analfabetos3) * 100

df_coeficiente_variacao_analfabetos = pd.DataFrame([[coeficiente_variacao_analfabetos1, coeficiente_variacao_analfabetos2, coeficiente_variacao_analfabetos3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_coeficiente_variacao_analfabetos.index = ["Coeficiente de variação (analfabetos)"]
df_coeficiente_variacao_analfabetos

                                       Sem filtro    Filtro 1    Filtro 2
Coeficiente de variação (analfabetos)  316.052531 -624.339268 -352.196583

In [175]:
coeficiente_variacao_alfabetizadas1 = desvio_padrao_alfabetizadas1 / np.mean(diferenca_alfabetizadas1) * 100
coeficiente_variacao_alfabetizadas2 = desvio_padrao_alfabetizadas2 / np.mean(diferenca_alfabetizadas2) * 100
coeficiente_variacao_alfabetizadas3 = desvio_padrao_alfabetizadas3 / np.mean(diferenca_alfabetizadas3) * 100

df_coeficiente_variacao_alfabetizadas = pd.DataFrame([[coeficiente_variacao_alfabetizadas1, coeficiente_variacao_alfabetizadas2, coeficiente_variacao_alfabetizadas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_coeficiente_variacao_alfabetizadas.index = ["Coeficiente de variação (alfabetizadas)"]
df_coeficiente_variacao_alfabetizadas

                                         Sem filtro     Filtro 1    Filtro 2
Coeficiente de variação (alfabetizadas)  442.569643  3626.029823 -295.072062

In [176]:
coeficiente_variacao_analfabetas1 = desvio_padrao_analfabetas1 / np.mean(diferenca_analfabetas1) * 100
coeficiente_variacao_analfabetas2 = desvio_padrao_analfabetas2 / np.mean(diferenca_analfabetas2) * 100
coeficiente_variacao_analfabetas3 = desvio_padrao_analfabetas3 / np.mean(diferenca_analfabetas3) * 100

df_coeficiente_variacao_analfabetas = pd.DataFrame([[coeficiente_variacao_analfabetas1, coeficiente_variacao_analfabetas2, coeficiente_variacao_analfabetas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_coeficiente_variacao_analfabetas.index = ["Coeficiente de variação (analfabetas)"]
df_coeficiente_variacao_analfabetas

                                       Sem filtro    Filtro 1    Filtro 2
Coeficiente de variação (analfabetas) -457.113308 -706.050289 -598.504488

In [177]:
media_alfabetizados1 = np.mean(diferenca_alfabetizados1)
media_alfabetizados2 = np.mean(diferenca_alfabetizados2)
media_alfabetizados3 = np.mean(diferenca_alfabetizados3)

df_media_alfabetizados = pd.DataFrame([[media_alfabetizados1, media_alfabetizados2, media_alfabetizados3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_media_alfabetizados.index = ["Média (alfabetizados)"]
df_media_alfabetizados

                       Sem filtro  Filtro 1       Filtro 2
Média (alfabetizados)    -73270.5 -102354.5 -425489.454545

In [178]:
media_analfabetos1 = np.mean(diferenca_analfabetos1)
media_analfabetos2 = np.mean(diferenca_analfabetos2)
media_analfabetos3 = np.mean(diferenca_analfabetos3)

df_media_analfabetos = pd.DataFrame([[media_analfabetos1, media_analfabetos2, media_analfabetos3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_media_analfabetos.index = ["Média (analfabetos)"]
df_media_analfabetos

                       Sem filtro       Filtro 1       Filtro 2
Média (analfabetos)  21688.772727 -259816.227273 -304736.181818

In [179]:
media_alfabetizadas1 = np.mean(diferenca_alfabetizadas1)
media_alfabetizadas2 = np.mean(diferenca_alfabetizadas2)
media_alfabetizadas3 = np.mean(diferenca_alfabetizadas3)

df_media_alfabetizadas = pd.DataFrame([[media_alfabetizadas1, media_alfabetizadas2, media_alfabetizadas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_media_alfabetizadas.index = ["Média (alfabetizadas)"]
df_media_alfabetizadas

                         Sem filtro     Filtro 1      Filtro 2
Média (alfabetizadas)  26004.227273  4394.636364 -42192.681818

In [180]:
media_analfabetas1 = np.mean(diferenca_analfabetas1)
media_analfabetas2 = np.mean(diferenca_analfabetas2)
media_analfabetas3 = np.mean(diferenca_analfabetas3)

df_media_analfabetas = pd.DataFrame([[media_analfabetas1, media_analfabetas2, media_analfabetas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_media_analfabetas.index = ["Média (analfabetas)"]
df_media_analfabetas

                        Sem filtro       Filtro 1       Filtro 2
Média (analfabetas) -159494.363636 -153215.636364 -212858.954545

In [181]:
outlier_inferior_alfabetizados1 = media_alfabetizados1 - (3 * desvio_padrao_alfabetizados1)
outlier_superior_alfabetizados1 = media_alfabetizados1 + (3 * desvio_padrao_alfabetizados1)

outlier_inferior_alfabetizados2 = media_alfabetizados2 - (3 * desvio_padrao_alfabetizados2)
outlier_superior_alfabetizados2 = media_alfabetizados2 + (3 * desvio_padrao_alfabetizados2)

outlier_inferior_alfabetizados3 = media_alfabetizados3 - (3 * desvio_padrao_alfabetizados3)
outlier_superior_alfabetizados3 = media_alfabetizados3 + (3 * desvio_padrao_alfabetizados3)


df_outlier_alfabetizados = pd.DataFrame([
    [outlier_inferior_alfabetizados1, outlier_superior_alfabetizados1,
    outlier_inferior_alfabetizados2, outlier_superior_alfabetizados2,
    outlier_inferior_alfabetizados3, outlier_superior_alfabetizados3]
], index=pd.MultiIndex.from_tuples([
    ("",)
]), columns=pd.MultiIndex.from_tuples([
    ("Observação discrepante (alfabetizados)", "Sem filtro", "Outlier inferior"),
    ("Observação discrepante (alfabetizados)", "Sem filtro", "Outlier superior"),
    ("Observação discrepante (alfabetizados)", "Filtro 1", "Outlier inferior"),
    ("Observação discrepante (alfabetizados)", "Filtro 1", "Outlier superior"),
    ("Observação discrepante (alfabetizados)", "Filtro 2", "Outlier inferior"),
    ("Observação discrepante (alfabetizados)", "Filtro 2", "Outlier superior")
]))
df_outlier_alfabetizados

 Observação discrepante (alfabetizados)                                    \
                             Sem filtro                          Filtro 1
                       Outlier inferior Outlier superior Outlier inferior
                         -996172.730469    849631.730469    -1.144257e+06


                          Filtro 2
 Outlier superior Outlier inferior Outlier superior
     939547.85303    -6.111532e+06     5.260553e+06

In [182]:
outlier_inferior_analfabetos1 = media_analfabetos1 - (3 * desvio_padrao_analfabetos1)
outlier_superior_analfabetos1 = media_analfabetos1 + (3 * desvio_padrao_analfabetos1)

outlier_inferior_analfabetos2 = media_analfabetos2 - (3 * desvio_padrao_analfabetos2)
outlier_superior_analfabetos2 = media_analfabetos2 + (3 * desvio_padrao_analfabetos2)

outlier_inferior_analfabetos3 = media_analfabetos3 - (3 * desvio_padrao_analfabetos3)
outlier_superior_analfabetos3 = media_analfabetos3 + (3 * desvio_padrao_analfabetos3)


df_outlier_analfabetos = pd.DataFrame([
    [outlier_inferior_analfabetos1, outlier_superior_analfabetos1,
    outlier_inferior_analfabetos2, outlier_superior_analfabetos2,
    outlier_inferior_analfabetos3, outlier_superior_analfabetos3]
], index=pd.MultiIndex.from_tuples([
    ("",)
]), columns=pd.MultiIndex.from_tuples([
    ("Observação discrepante (analfabetos)", "Sem filtro", "Outlier inferior"),
    ("Observação discrepante (analfabetos)", "Sem filtro", "Outlier superior"),
    ("Observação discrepante (analfabetos)", "Filtro 1", "Outlier inferior"),
    ("Observação discrepante (analfabetos)", "Filtro 1", "Outlier superior"),
    ("Observação discrepante (analfabetos)", "Filtro 2", "Outlier inferior"),
    ("Observação discrepante (analfabetos)", "Filtro 2", "Outlier superior")
]))
df_outlier_analfabetos

 Observação discrepante (analfabetos)                                    \
                           Sem filtro                          Filtro 1
                     Outlier inferior Outlier superior Outlier inferior
                       -183954.972469    227332.517923    -5.126220e+06


                          Filtro 2
 Outlier superior Outlier inferior Outlier superior
     4.606588e+06    -3.524547e+06     2.915075e+06

In [183]:
outlier_inferior_alfabetizadas1 = media_alfabetizadas1 - (3 * desvio_padrao_alfabetizadas1)
outlier_superior_alfabetizadas1 = media_alfabetizadas1 + (3 * desvio_padrao_alfabetizadas1)

outlier_inferior_alfabetizadas2 = media_alfabetizadas2 - (3 * desvio_padrao_alfabetizadas2)
outlier_superior_alfabetizadas2 = media_alfabetizadas2 + (3 * desvio_padrao_alfabetizadas2)

outlier_inferior_alfabetizadas3 = media_alfabetizadas3 - (3 * desvio_padrao_alfabetizadas3)
outlier_superior_alfabetizadas3 = media_alfabetizadas3 + (3 * desvio_padrao_alfabetizadas3)


df_outlier_alfabetizadas = pd.DataFrame([
    [outlier_inferior_alfabetizadas1, outlier_superior_alfabetizadas1,
    outlier_inferior_alfabetizadas2, outlier_superior_alfabetizadas2,
    outlier_inferior_alfabetizadas3, outlier_superior_alfabetizadas3]
], index=pd.MultiIndex.from_tuples([
    ("",)
]), columns=pd.MultiIndex.from_tuples([
    ("Observação discrepante (alfabetizadas)", "Sem filtro", "Outlier inferior"),
    ("Observação discrepante (alfabetizadas)", "Sem filtro", "Outlier superior"),
    ("Observação discrepante (alfabetizadas)", "Filtro 1", "Outlier inferior"),
    ("Observação discrepante (alfabetizadas)", "Filtro 1", "Outlier superior"),
    ("Observação discrepante (alfabetizadas)", "Filtro 2", "Outlier inferior"),
    ("Observação discrepante (alfabetizadas)", "Filtro 2", "Outlier superior")
]))
df_outlier_alfabetizadas

 Observação discrepante (alfabetizadas)                                    \
                             Sem filtro                          Filtro 1
                       Outlier inferior Outlier superior Outlier inferior
                         -319256.220118    371264.674663   -473657.839051


                          Filtro 2
 Outlier superior Outlier inferior Outlier superior
    482447.111778   -415689.131151    331303.767515

In [184]:
outlier_inferior_analfabetas1 = media_analfabetas1 - (3 * desvio_padrao_analfabetas1)
outlier_superior_analfabetas1 = media_analfabetas1 + (3 * desvio_padrao_analfabetas1)

outlier_inferior_analfabetas2 = media_analfabetas2 - (3 * desvio_padrao_analfabetas2)
outlier_superior_analfabetas2 = media_analfabetas2 + (3 * desvio_padrao_analfabetas2)

outlier_inferior_analfabetas3 = media_analfabetas3 - (3 * desvio_padrao_analfabetas3)
outlier_superior_analfabetas3 = media_analfabetas3 + (3 * desvio_padrao_analfabetas3)


df_outlier_analfabetas = pd.DataFrame([
    [outlier_inferior_analfabetas1, outlier_superior_analfabetas1,
    outlier_inferior_analfabetas2, outlier_superior_analfabetas2,
    outlier_inferior_analfabetas3, outlier_superior_analfabetas3]
], index=pd.MultiIndex.from_tuples([
    ("",)
]), columns=pd.MultiIndex.from_tuples([
    ("Observação discrepante (analfabetas)", "Sem filtro", "Outlier inferior"),
    ("Observação discrepante (analfabetas)", "Sem filtro", "Outlier superior"),
    ("Observação discrepante (analfabetas)", "Filtro 1", "Outlier inferior"),
    ("Observação discrepante (analfabetas)", "Filtro 1", "Outlier superior"),
    ("Observação discrepante (analfabetas)", "Filtro 2", "Outlier inferior"),
    ("Observação discrepante (analfabetas)", "Filtro 2", "Outlier superior")
]))
df_outlier_analfabetas

 Observação discrepante (analfabetas)                                    \
                           Sem filtro                          Filtro 1
                     Outlier inferior Outlier superior Outlier inferior
                        -2.346704e+06     2.027716e+06    -3.398554e+06


                          Filtro 2
 Outlier superior Outlier inferior Outlier superior
     3.092123e+06    -4.034770e+06     3.609052e+06

# Grau de instrução (jovens)

In [185]:
instrucao_jovens = df[['Unnamed: 0', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35']]

instrucao_jovens_header = instrucao_jovens.iloc[2]
instrucao_jovens.columns = instrucao_jovens_header
instrucao_jovens = instrucao_jovens[3:]

columns_multiindex = pd.MultiIndex.from_tuples([
    ('', '', '', 'Províncias e Município Neutro'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninos', 'Frequentam escolas'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninos', 'Não frequentam'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninos', 'Total'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninas', 'Frequentam escolas'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninas', 'Não frequentam'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninas', 'Total')
])

instrucao_jovens.columns = columns_multiindex

instrucao_jovens

                                                        Instrução  \
                                 População escolar de 6 a 15 anos
                                                          Meninos
   Províncias e Município Neutro               Frequentam escolas
3                       Amazonas                              824
4                           Pará                             5768
5                       Maranhão                             8739
6                          Piauí                             1777
7                          Ceará                            10021
8            Rio Grande do Norte                             2643
9                        Paraíba                             6630
10                    Pernambuco                            14069
11                       Alagoas                             5455
12                       Sergipe                             3402
13                         Bahia                            22260
14                Espírito Santo                             1564
15              Município Neutro                             5788
16                Rio de Janeiro                            12622
17                     São Paulo                            15069
18                        Paraná                             2558
19                Santa Catarina                             3100
20             Rio Grande do Sul                             9947
21                  Minas Gerais                            19968
22                         Goiás                             2566
23                   Mato Grosso                              881
24                         Total                           155651



                                     Meninas
   Não frequentam   Total Frequentam escolas Não frequentam   Total
3            5056    5880                371           3269    3640
4           25753   31521               3441          25020   28461
5           28142   36881               4844          29567   34411
6           15960   17737               1024          16968   17992
7           83808   93829               5399          85087   90486
8           18662   21305               2058          19857   21915
9           44061   50691               3894          45830   49724
10          82133   96202               9301          80960   90261
11          34261   39716               4028          34726   38754
12          14934   18336               1832          17333   19165
13         119426  141686              81743         113313  195056
14           5323    6887                722           5101    6823
15          10449   22237               4258          15019   19277
16          32019   44641               8194          33089   41283
17          71271   86340               8544          73915   82458
18           9666   12224               1866          10762   12628
19          15676   18776               2114          15473   17587
20          36222   46169               7947          33292   41239
21          66983  125012              11940         112824  124764
22          16864   19430               1240          16982   18222
23           5401    6282                338           6187    6525
24         786131  941782             165098         795574  960672

In [186]:
tabela_manual_meninos_alfabetizados = pd.to_numeric(df.iloc[3:25, 30])

tabela_ocr_meninos_alfabetizados1 = pd.to_numeric(df1.iloc[:, 29])
diferenca_meninos_alfabetizados1 = tabela_manual_meninos_alfabetizados.values - tabela_ocr_meninos_alfabetizados1.values

tabela_ocr_meninos_alfabetizados2 = pd.to_numeric(df2.iloc[:, 29])
diferenca_meninos_alfabetizados2 = tabela_manual_meninos_alfabetizados.values - tabela_ocr_meninos_alfabetizados2.values

tabela_ocr_meninos_alfabetizados3 = pd.to_numeric(df3.iloc[:, 29])
diferenca_meninos_alfabetizados3 = tabela_manual_meninos_alfabetizados.values - tabela_ocr_meninos_alfabetizados3.values

In [187]:
tabela_manual_meninos_analfabetos = pd.to_numeric(df.iloc[3:25, 31])

tabela_ocr_meninos_analfabetos1 = pd.to_numeric(df1.iloc[:, 30])
diferenca_meninos_analfabetos1 = tabela_manual_meninos_analfabetos.values - tabela_ocr_meninos_analfabetos1.values

tabela_ocr_meninos_analfabetos2 = pd.to_numeric(df2.iloc[:, 30])
diferenca_meninos_analfabetos2 = tabela_manual_meninos_analfabetos.values - tabela_ocr_meninos_analfabetos2.values

tabela_ocr_meninos_analfabetos3 = pd.to_numeric(df3.iloc[:, 30])
diferenca_meninos_analfabetos3 = tabela_manual_meninos_analfabetos.values - tabela_ocr_meninos_analfabetos3.values

In [188]:
tabela_manual_meninos_total = pd.to_numeric(df.iloc[3:25, 32])

tabela_ocr_meninos_total1 = pd.to_numeric(df1.iloc[:, 31])
diferenca_meninos_total1 = tabela_manual_meninos_total.values - tabela_ocr_meninos_total1.values

tabela_ocr_meninos_total2 = pd.to_numeric(df2.iloc[:, 31])
diferenca_meninos_total2 = tabela_manual_meninos_total.values - tabela_ocr_meninos_total2.values

tabela_ocr_meninos_total3 = pd.to_numeric(df3.iloc[:, 31])
diferenca_meninos_total3 = tabela_manual_meninos_total.values - tabela_ocr_meninos_total3.values

In [189]:
tabela_manual_meninas_alfabetizadas = pd.to_numeric(df.iloc[3:25, 33])

tabela_ocr_meninas_alfabetizadas1 = pd.to_numeric(df1.iloc[:, 32])
diferenca_meninas_alfabetizadas1 = tabela_manual_meninas_alfabetizadas.values - tabela_ocr_meninas_alfabetizadas1.values

tabela_ocr_meninas_alfabetizadas2 = pd.to_numeric(df2.iloc[:, 32])
diferenca_meninas_alfabetizadas2 = tabela_manual_meninas_alfabetizadas.values - tabela_ocr_meninas_alfabetizadas2.values

tabela_ocr_meninas_alfabetizadas3 = pd.to_numeric(df3.iloc[:, 32])
diferenca_meninas_alfabetizadas3 = tabela_manual_meninas_alfabetizadas.values - tabela_ocr_meninas_alfabetizadas3.values

In [190]:
tabela_manual_meninas_analfabetas = pd.to_numeric(df.iloc[3:25, 34])

tabela_ocr_meninas_analfabetas1 = pd.to_numeric(df1.iloc[:, 33])
diferenca_meninas_analfabetas1 = tabela_manual_meninas_analfabetas.values - tabela_ocr_meninas_analfabetas1.values

tabela_ocr_meninas_analfabetas2 = pd.to_numeric(df2.iloc[:, 33])
diferenca_meninas_analfabetas2 = tabela_manual_meninas_analfabetas.values - tabela_ocr_meninas_analfabetas2.values

tabela_ocr_meninas_analfabetas3 = pd.to_numeric(df3.iloc[:, 33])
diferenca_meninas_analfabetas3 = tabela_manual_meninas_analfabetas.values - tabela_ocr_meninas_analfabetas3.values

In [191]:
tabela_manual_meninas_total = pd.to_numeric(df.iloc[3:25, 35])

tabela_ocr_meninas_total1 = pd.to_numeric(df1.iloc[:, 34])
diferenca_meninas_total1 = tabela_manual_meninas_total.values - tabela_ocr_meninas_total1.values

tabela_ocr_meninas_total2 = pd.to_numeric(df2.iloc[:, 34])
diferenca_meninas_total2 = tabela_manual_meninas_total.values - tabela_ocr_meninas_total2.values

tabela_ocr_meninas_total3 = pd.to_numeric(df3.iloc[:, 34])
diferenca_meninas_total3 = tabela_manual_meninas_total.values - tabela_ocr_meninas_total3.values

In [192]:
variancia_meninos_alfabetizados1 = np.var(diferenca_meninos_alfabetizados1)
variancia_meninos_alfabetizados2 = np.var(diferenca_meninos_alfabetizados2)
variancia_meninos_alfabetizados3 = np.var(diferenca_meninos_alfabetizados3)

df_variancia_meninos_alfabetizados = pd.DataFrame([[variancia_meninos_alfabetizados1, variancia_meninos_alfabetizados2, variancia_meninos_alfabetizados3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_variancia_meninos_alfabetizados.index = ["Variância (meninos alfabetizados)"]
df_variancia_meninos_alfabetizados

                                      Sem filtro      Filtro 1      Filtro 2
Variância (meninos alfabetizados)  139221.702479  1.026446e+09  8.522549e+10

In [193]:
variancia_meninos_analfabetos1 = np.var(diferenca_meninos_analfabetos1)
variancia_meninos_analfabetos2 = np.var(diferenca_meninos_analfabetos2)
variancia_meninos_analfabetos3 = np.var(diferenca_meninos_analfabetos3)

df_variancia_meninos_analfabetos = pd.DataFrame([[variancia_meninos_analfabetos1, variancia_meninos_analfabetos2, variancia_meninos_analfabetos3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_variancia_meninos_analfabetos.index = ["Variância (meninos analfabetos)"]
df_variancia_meninos_analfabetos

                                   Sem filtro      Filtro 1      Filtro 2
Variância (meninos analfabetos)  5.114089e+11  2.634490e+10  2.904250e+10

In [194]:
variancia_meninos_total1 = np.var(diferenca_meninos_total1)
variancia_meninos_total2 = np.var(diferenca_meninos_total2)
variancia_meninos_total3 = np.var(diferenca_meninos_total3)

df_variancia_meninos_total = pd.DataFrame([[variancia_meninos_total1, variancia_meninos_total2, variancia_meninos_total3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_variancia_meninos_total.index = ["Variância (meninos total)"]
df_variancia_meninos_total

                             Sem filtro      Filtro 1      Filtro 2
Variância (meninos total)  2.437832e+08  7.666073e+10  3.827125e+10

In [195]:
variancia_meninas_alfabetizadas1 = np.var(diferenca_meninas_alfabetizadas1)
variancia_meninas_alfabetizadas2 = np.var(diferenca_meninas_alfabetizadas2)
variancia_meninas_alfabetizadas3 = np.var(diferenca_meninas_alfabetizadas3)

df_variancia_meninas_alfabetizadas = pd.DataFrame([[variancia_meninas_alfabetizadas1, variancia_meninas_alfabetizadas2, variancia_meninas_alfabetizadas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_variancia_meninas_alfabetizadas.index = ["Variância (meninas alfabetizadas)"]
df_variancia_meninas_alfabetizadas

                                     Sem filtro      Filtro 1      Filtro 2
Variância (meninas alfabetizadas)  5.184971e+08  3.023675e+08  2.093909e+07

In [196]:
variancia_meninas_analfabetas1 = np.var(diferenca_meninas_analfabetas1)
variancia_meninas_analfabetas2 = np.var(diferenca_meninas_analfabetas2)
variancia_meninas_analfabetas3 = np.var(diferenca_meninas_analfabetas3)

df_variancia_meninas_analfabetas = pd.DataFrame([[variancia_meninas_analfabetas1, variancia_meninas_analfabetas2, variancia_meninas_analfabetas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_variancia_meninas_analfabetas.index = ["Variância (meninas analfabetas)"]
df_variancia_meninas_analfabetas

                                   Sem filtro      Filtro 1      Filtro 2
Variância (meninas analfabetas)  2.787463e+10  2.754341e+10  5.286200e+10

In [197]:
variancia_meninas_total1 = np.var(diferenca_meninas_total1)
variancia_meninas_total2 = np.var(diferenca_meninas_total2)
variancia_meninas_total3 = np.var(diferenca_meninas_total3)

df_variancia_meninas_total = pd.DataFrame([[variancia_meninas_total1, variancia_meninas_total2, variancia_meninas_total3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_variancia_meninas_total.index = ["Variância (meninas total)"]
df_variancia_meninas_total

                             Sem filtro      Filtro 1      Filtro 2
Variância (meninas total)  4.527819e+07  3.945571e+10  4.775462e+10

In [198]:
desvio_padrao_meninos_alfabetizados1 = np.std(diferenca_meninos_alfabetizados1)
desvio_padrao_meninos_alfabetizados2 = np.std(diferenca_meninos_alfabetizados2)
desvio_padrao_meninos_alfabetizados3 = np.std(diferenca_meninos_alfabetizados3)

df_desvio_padrao_meninos_alfabetizados = pd.DataFrame([[desvio_padrao_meninos_alfabetizados1, desvio_padrao_meninos_alfabetizados2, desvio_padrao_meninos_alfabetizados3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_desvio_padrao_meninos_alfabetizados.index = ["Desvio padrão (meninos alfabetizados)"]
df_desvio_padrao_meninos_alfabetizados

                                       Sem filtro      Filtro 1     Filtro 2
Desvio padrão (meninos alfabetizados)  373.124245  32038.198244  291934.0533

In [199]:
desvio_padrao_meninos_analfabetos1 = np.std(diferenca_meninos_analfabetos1)
desvio_padrao_meninos_analfabetos2 = np.std(diferenca_meninos_analfabetos2)
desvio_padrao_meninos_analfabetos3 = np.std(diferenca_meninos_analfabetos3)

df_desvio_padrao_meninos_analfabetos = pd.DataFrame([[desvio_padrao_meninos_analfabetos1, desvio_padrao_meninos_analfabetos2, desvio_padrao_meninos_analfabetos3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_desvio_padrao_meninos_analfabetos.index = ["Desvio padrão (meninos analfabetos)"]
df_desvio_padrao_meninos_analfabetos

,Sem filtro,Filtro 1,Filtro 2
Desvio padrão (meninos analfabetos),715128.623685,162311.122611,170418.597263

In [200]:
desvio_padrao_meninos_total1 = np.std(diferenca_meninos_total1)
desvio_padrao_meninos_total2 = np.std(diferenca_meninos_total2)
desvio_padrao_meninos_total3 = np.std(diferenca_meninos_total3)

df_desvio_padrao_meninos_total = pd.DataFrame([[desvio_padrao_meninos_total1, desvio_padrao_meninos_total2, desvio_padrao_meninos_total3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_desvio_padrao_meninos_total.index = ["Desvio padrão (meninos total)"]
df_desvio_padrao_meninos_total

                                 Sem filtro       Filtro 1       Filtro 2
Desvio padrão (meninos total)  15613.558559  276876.736475  195630.393838

In [201]:
desvio_padrao_meninas_alfabetizadas1 = np.std(diferenca_meninas_alfabetizadas1)
desvio_padrao_meninas_alfabetizadas2 = np.std(diferenca_meninas_alfabetizadas2)
desvio_padrao_meninas_alfabetizadas3 = np.std(diferenca_meninas_alfabetizadas3)

df_desvio_padrao_meninas_alfabetizadas = pd.DataFrame([[desvio_padrao_meninas_alfabetizadas1, desvio_padrao_meninas_alfabetizadas2, desvio_padrao_meninas_alfabetizadas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_desvio_padrao_meninas_alfabetizadas.index = ["Desvio padrão (meninas alfabetizadas)"]
df_desvio_padrao_meninas_alfabetizadas

                                         Sem filtro      Filtro 1     Filtro 2
Desvio padrão (meninas alfabetizadas)  22770.531472  17388.718939  4575.925397

In [202]:
desvio_padrao_meninas_analfabetas1 = np.std(diferenca_meninas_analfabetas1)
desvio_padrao_meninas_analfabetas2 = np.std(diferenca_meninas_analfabetas2)
desvio_padrao_meninas_analfabetas3 = np.std(diferenca_meninas_analfabetas3)

df_desvio_padrao_meninas_analfabetas = pd.DataFrame([[desvio_padrao_meninas_analfabetas1, desvio_padrao_meninas_analfabetas2, desvio_padrao_meninas_analfabetas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_desvio_padrao_meninas_analfabetas.index = ["Desvio padrão (meninas analfabetas)"]
df_desvio_padrao_meninas_analfabetas

,Sem filtro,Filtro 1,Filtro 2
Desvio padrão (meninas analfabetas),166956.970688,165962.071069,229917.372708

In [203]:
desvio_padrao_meninas_total1 = np.std(diferenca_meninas_total1)
desvio_padrao_meninas_total2 = np.std(diferenca_meninas_total2)
desvio_padrao_meninas_total3 = np.std(diferenca_meninas_total3)

df_desvio_padrao_meninas_total = pd.DataFrame([[desvio_padrao_meninas_total1, desvio_padrao_meninas_total2, desvio_padrao_meninas_total3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_desvio_padrao_meninas_total.index = ["Desvio padrão (meninas total)"]
df_desvio_padrao_meninas_total

                                Sem filtro       Filtro 1       Filtro 2
Desvio padrão (meninas total)  6728.906823  198634.616601  218528.312156

In [204]:
coeficiente_variacao_meninos_alfabetizados1 = desvio_padrao_meninos_alfabetizados1 / np.mean(diferenca_meninos_alfabetizados1) * 100
coeficiente_variacao_meninos_alfabetizados2 = desvio_padrao_meninos_alfabetizados2 / np.mean(diferenca_meninos_alfabetizados2) * 100
coeficiente_variacao_meninos_alfabetizados3 = desvio_padrao_meninos_alfabetizados3 / np.mean(diferenca_meninos_alfabetizados3) * 100

df_coeficiente_variacao_meninos_alfabetizados = pd.DataFrame([[coeficiente_variacao_meninos_alfabetizados1, coeficiente_variacao_meninos_alfabetizados2, coeficiente_variacao_meninos_alfabetizados3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_coeficiente_variacao_meninos_alfabetizados.index = ["Coeficiente de variação (meninos alfabetizados)"]
df_coeficiente_variacao_meninos_alfabetizados

,Sem filtro,Filtro 1,Filtro 2
Coeficiente de variação (meninos alfabetizados),334.504213,301.750275,-462.373567

In [205]:
coeficiente_variacao_meninos_analfabetos1 = desvio_padrao_meninos_analfabetos1 / np.mean(diferenca_meninos_analfabetos1) * 100
coeficiente_variacao_meninos_analfabetos2 = desvio_padrao_meninos_analfabetos2 / np.mean(diferenca_meninos_analfabetos2) * 100
coeficiente_variacao_meninos_analfabetos3 = desvio_padrao_meninos_analfabetos3 / np.mean(diferenca_meninos_analfabetos3) * 100

df_coeficiente_variacao_meninos_analfabetos = pd.DataFrame([[coeficiente_variacao_meninos_analfabetos1, coeficiente_variacao_meninos_analfabetos2, coeficiente_variacao_meninos_analfabetos3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_coeficiente_variacao_meninos_analfabetos.index = ["Coeficiente de variação (meninos analfabetos)"]
df_coeficiente_variacao_meninos_analfabetos

,Sem filtro,Filtro 1,Filtro 2
Coeficiente de variação (meninos analfabetos),-556.427034,326.185266,473.431618

In [206]:
coeficiente_variacao_meninos_total1 = desvio_padrao_meninos_total1 / np.mean(diferenca_meninos_total1) * 100
coeficiente_variacao_meninos_total2 = desvio_padrao_meninos_total2 / np.mean(diferenca_meninos_total2) * 100
coeficiente_variacao_meninos_total3 = desvio_padrao_meninos_total3 / np.mean(diferenca_meninos_total3) * 100

df_coeficiente_variacao_meninos_total = pd.DataFrame([[coeficiente_variacao_meninos_total1, coeficiente_variacao_meninos_total2, coeficiente_variacao_meninos_total3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_coeficiente_variacao_meninos_total.index = ["Coeficiente de variação (meninos total)"]
df_coeficiente_variacao_meninos_total

                                          Sem filtro    Filtro 1    Filtro 2
Coeficiente de variação (meninos total) -1030.907228  5558.40401  395.669263

In [207]:
coeficiente_variacao_meninas_alfabetizadas1 = desvio_padrao_meninas_alfabetizadas1 / np.mean(diferenca_meninas_alfabetizadas1) * 100
coeficiente_variacao_meninas_alfabetizadas2 = desvio_padrao_meninas_alfabetizadas2 / np.mean(diferenca_meninas_alfabetizadas2) * 100
coeficiente_variacao_meninas_alfabetizadas3 = desvio_padrao_meninas_alfabetizadas3 / np.mean(diferenca_meninas_alfabetizadas3) * 100

df_coeficiente_variacao_meninas_alfabetizadas = pd.DataFrame([[coeficiente_variacao_meninas_alfabetizadas1, coeficiente_variacao_meninas_alfabetizadas2, coeficiente_variacao_meninas_alfabetizadas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_coeficiente_variacao_meninas_alfabetizadas.index = ["Coeficiente de variação (meninas alfabetizadas)"]
df_coeficiente_variacao_meninas_alfabetizadas

,Sem filtro,Filtro 1,Filtro 2
Coeficiente de variação (meninas alfabetizadas),-601.570349,272.853711,605.936913

In [208]:
coeficiente_variacao_meninas_analfabetas1 = desvio_padrao_meninas_analfabetas1 / np.mean(diferenca_meninas_analfabetas1) * 100
coeficiente_variacao_meninas_analfabetas2 = desvio_padrao_meninas_analfabetas2 / np.mean(diferenca_meninas_analfabetas2) * 100
coeficiente_variacao_meninas_analfabetas3 = desvio_padrao_meninas_analfabetas3 / np.mean(diferenca_meninas_analfabetas3) * 100

df_coeficiente_variacao_meninas_analfabetas = pd.DataFrame([[coeficiente_variacao_meninas_analfabetas1, coeficiente_variacao_meninas_analfabetas2, coeficiente_variacao_meninas_analfabetas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_coeficiente_variacao_meninas_analfabetas.index = ["Coeficiente de variação (meninas analfabetas)"]
df_coeficiente_variacao_meninas_analfabetas

,Sem filtro,Filtro 1,Filtro 2
Coeficiente de variação (meninas analfabetas),352.416446,322.729006,5775.8949

In [209]:
coeficiente_variacao_meninas_total1 = desvio_padrao_meninas_total1 / np.mean(diferenca_meninas_total1) * 100
coeficiente_variacao_meninas_total2 = desvio_padrao_meninas_total2 / np.mean(diferenca_meninas_total2) * 100
coeficiente_variacao_meninas_total3 = desvio_padrao_meninas_total3 / np.mean(diferenca_meninas_total3) * 100

df_coeficiente_variacao_meninas_total = pd.DataFrame([[coeficiente_variacao_meninas_total1, coeficiente_variacao_meninas_total2, coeficiente_variacao_meninas_total3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_coeficiente_variacao_meninas_total.index = ["Coeficiente de variação (meninas total)"]
df_coeficiente_variacao_meninas_total

                                         Sem filtro    Filtro 1    Filtro 2
Coeficiente de variação (meninas total)  333.963386  323.715724  616.270256

In [210]:
media_meninos_alfabetizados1 = np.mean(diferenca_meninos_alfabetizados1)
media_meninos_alfabetizados2 = np.mean(diferenca_meninos_alfabetizados2)
media_meninos_alfabetizados3 = np.mean(diferenca_meninos_alfabetizados3)

df_media_meninos_alfabetizados = pd.DataFrame([[media_meninos_alfabetizados1, media_meninos_alfabetizados2, media_meninos_alfabetizados3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_media_meninos_alfabetizados.index = ["Média (meninos alfabetizados)"]
df_media_meninos_alfabetizados

                               Sem filtro      Filtro 1      Filtro 2
Média (meninos alfabetizados)  111.545455  10617.454545 -63138.136364

In [211]:
media_meninos_analfabetos1 = np.mean(diferenca_meninos_analfabetos1)
media_meninos_analfabetos2 = np.mean(diferenca_meninos_analfabetos2)
media_meninos_analfabetos3 = np.mean(diferenca_meninos_analfabetos3)

df_media_meninos_analfabetos = pd.DataFrame([[media_meninos_analfabetos1, media_meninos_analfabetos2, media_meninos_analfabetos3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_media_meninos_analfabetos.index = ["Média (meninos analfabetos)"]
df_media_meninos_analfabetos

                                Sem filtro      Filtro 1      Filtro 2
Média (meninos analfabetos) -128521.545455  49760.409091  35996.454545

In [212]:
media_meninos_total1 = np.mean(diferenca_meninos_total1)
media_meninos_total2 = np.mean(diferenca_meninos_total2)
media_meninos_total3 = np.mean(diferenca_meninos_total3)

df_media_meninos_total = pd.DataFrame([[media_meninos_total1, media_meninos_total2, media_meninos_total3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_media_meninos_total.index = ["Média (meninos total)"]
df_media_meninos_total

                        Sem filtro     Filtro 1      Filtro 2
Média (meninos total) -1514.545455  4981.227273  49442.909091

In [213]:
media_meninas_alfabetizadas1 = np.mean(diferenca_meninas_alfabetizadas1)
media_meninas_alfabetizadas2 = np.mean(diferenca_meninas_alfabetizadas2)
media_meninas_alfabetizadas3 = np.mean(diferenca_meninas_alfabetizadas3)

df_media_meninas_alfabetizadas = pd.DataFrame([[media_meninas_alfabetizadas1, media_meninas_alfabetizadas2, media_meninas_alfabetizadas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_media_meninas_alfabetizadas.index = ["Média (meninas alfabetizadas)"]
df_media_meninas_alfabetizadas

                                Sem filtro     Filtro 1    Filtro 2
Média (meninas alfabetizadas) -3785.181818  6372.909091  755.181818

In [214]:
media_meninas_analfabetas1 = np.mean(diferenca_meninas_analfabetas1)
media_meninas_analfabetas2 = np.mean(diferenca_meninas_analfabetas2)
media_meninas_analfabetas3 = np.mean(diferenca_meninas_analfabetas3)

df_media_meninas_analfabetas = pd.DataFrame([[media_meninas_analfabetas1, media_meninas_analfabetas2, media_meninas_analfabetas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_media_meninas_analfabetas.index = ["Média (meninas analfabetas)"]
df_media_meninas_analfabetas

                               Sem filtro      Filtro 1     Filtro 2
Média (meninas analfabetas)  47374.909091  51424.590909  3980.636364

In [215]:
media_meninas_total1 = np.mean(diferenca_meninas_total1)
media_meninas_total2 = np.mean(diferenca_meninas_total2)
media_meninas_total3 = np.mean(diferenca_meninas_total3)

df_media_meninas_total = pd.DataFrame([[media_meninas_total1, media_meninas_total2, media_meninas_total3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_media_meninas_total.index = ["Média (meninas total)"]
df_media_meninas_total

                        Sem filtro      Filtro 1      Filtro 2
Média (meninas total)  2014.863636  61360.818182  35459.818182

In [216]:
outlier_inferior_meninos_alfabetizados1 = media_meninos_alfabetizados1 - (3 * desvio_padrao_meninos_alfabetizados1)
outlier_superior_meninos_alfabetizados1 = media_meninos_alfabetizados1 + (3 * desvio_padrao_meninos_alfabetizados1)

outlier_inferior_meninos_alfabetizados2 = media_meninos_alfabetizados2 - (3 * desvio_padrao_meninos_alfabetizados2)
outlier_superior_meninos_alfabetizados2 = media_meninos_alfabetizados2 + (3 * desvio_padrao_meninos_alfabetizados2)

outlier_inferior_meninos_alfabetizados3 = media_meninos_alfabetizados3 - (3 * desvio_padrao_meninos_alfabetizados3)
outlier_superior_meninos_alfabetizados3 = media_meninos_alfabetizados3 + (3 * desvio_padrao_meninos_alfabetizados3)


df_outlier_meninos_alfabetizados = pd.DataFrame([
    [outlier_inferior_meninos_alfabetizados1, outlier_superior_meninos_alfabetizados1,
    outlier_inferior_meninos_alfabetizados2, outlier_superior_meninos_alfabetizados2,
    outlier_inferior_meninos_alfabetizados3, outlier_superior_meninos_alfabetizados3]
], index=pd.MultiIndex.from_tuples([
    ("",)
]), columns=pd.MultiIndex.from_tuples([
    ("Observação discrepante (meninos alfabetizados)", "Sem filtro", "Outlier inferior"),
    ("Observação discrepante (meninos alfabetizados)", "Sem filtro", "Outlier superior"),
    ("Observação discrepante (meninos alfabetizados)", "Filtro 1", "Outlier inferior"),
    ("Observação discrepante (meninos alfabetizados)", "Filtro 1", "Outlier superior"),
    ("Observação discrepante (meninos alfabetizados)", "Filtro 2", "Outlier inferior"),
    ("Observação discrepante (meninos alfabetizados)", "Filtro 2", "Outlier superior")
]))
df_outlier_meninos_alfabetizados

 Observação discrepante (meninos alfabetizados)                   \
                                     Sem filtro
                               Outlier inferior Outlier superior
                                   -1007.827282      1230.918191


         Filtro 1                          Filtro 2
 Outlier inferior Outlier superior Outlier inferior Outlier superior
    -85497.140186    106732.049277   -938940.296263    812664.023536

In [217]:
outlier_inferior_meninos_analfabetos1 = media_meninos_analfabetos1 - (3 * desvio_padrao_meninos_analfabetos1)
outlier_superior_meninos_analfabetos1 = media_meninos_analfabetos1 + (3 * desvio_padrao_meninos_analfabetos1)

outlier_inferior_meninos_analfabetos2 = media_meninos_analfabetos2 - (3 * desvio_padrao_meninos_analfabetos2)
outlier_superior_meninos_analfabetos2 = media_meninos_analfabetos2 + (3 * desvio_padrao_meninos_analfabetos2)

outlier_inferior_meninos_analfabetos3 = media_meninos_analfabetos3 - (3 * desvio_padrao_meninos_analfabetos3)
outlier_superior_meninos_analfabetos3 = media_meninos_analfabetos3 + (3 * desvio_padrao_meninos_analfabetos3)


df_outlier_meninos_analfabetos = pd.DataFrame([
    [outlier_inferior_meninos_analfabetos1, outlier_superior_meninos_analfabetos1,
    outlier_inferior_meninos_analfabetos2, outlier_superior_meninos_analfabetos2,
    outlier_inferior_meninos_analfabetos3, outlier_superior_meninos_analfabetos3]
], index=pd.MultiIndex.from_tuples([
    ("",)
]), columns=pd.MultiIndex.from_tuples([
    ("Observação discrepante (meninos analfabetos)", "Sem filtro", "Outlier inferior"),
    ("Observação discrepante (meninos analfabetos)", "Sem filtro", "Outlier superior"),
    ("Observação discrepante (meninos analfabetos)", "Filtro 1", "Outlier inferior"),
    ("Observação discrepante (meninos analfabetos)", "Filtro 1", "Outlier superior"),
    ("Observação discrepante (meninos analfabetos)", "Filtro 2", "Outlier inferior"),
    ("Observação discrepante (meninos analfabetos)", "Filtro 2", "Outlier superior")
]))
df_outlier_meninos_analfabetos

 Observação discrepante (meninos analfabetos)                   \
                                   Sem filtro
                             Outlier inferior Outlier superior
                                -2.273907e+06     2.016864e+06


         Filtro 1                          Filtro 2
 Outlier inferior Outlier superior Outlier inferior Outlier superior
   -437172.958742    536693.776924   -475259.337245    547252.246336

In [218]:
outlier_inferior_meninos_total1 = media_meninos_total1 - (3 * desvio_padrao_meninos_total1)
outlier_superior_meninos_total1 = media_meninos_total1 + (3 * desvio_padrao_meninos_total1)

outlier_inferior_meninos_total2 = media_meninos_total2 - (3 * desvio_padrao_meninos_total2)
outlier_superior_meninos_total2 = media_meninos_total2 + (3 * desvio_padrao_meninos_total2)

outlier_inferior_meninos_total3 = media_meninos_total3 - (3 * desvio_padrao_meninos_total3)
outlier_superior_meninos_total3 = media_meninos_total3 + (3 * desvio_padrao_meninos_total3)


df_outlier_meninos_total = pd.DataFrame([
    [outlier_inferior_meninos_total1, outlier_superior_meninos_total1,
    outlier_inferior_meninos_total2, outlier_superior_meninos_total2,
    outlier_inferior_meninos_total3, outlier_superior_meninos_total3]
], index=pd.MultiIndex.from_tuples([
    ("",)
]), columns=pd.MultiIndex.from_tuples([
    ("Observação discrepante (meninos total)", "Sem filtro", "Outlier inferior"),
    ("Observação discrepante (meninos total)", "Sem filtro", "Outlier superior"),
    ("Observação discrepante (meninos total)", "Filtro 1", "Outlier inferior"),
    ("Observação discrepante (meninos total)", "Filtro 1", "Outlier superior"),
    ("Observação discrepante (meninos total)", "Filtro 2", "Outlier inferior"),
    ("Observação discrepante (meninos total)", "Filtro 2", "Outlier superior")
]))
df_outlier_meninos_total

 Observação discrepante (meninos total)                                    \
                             Sem filtro                          Filtro 1
                       Outlier inferior Outlier superior Outlier inferior
                          -48355.221132     45326.130223   -825648.982152


                          Filtro 2
 Outlier superior Outlier inferior Outlier superior
    835611.436697   -537448.272424    636334.090606

In [219]:
outlier_inferior_meninas_alfabetizadas1 = media_meninas_alfabetizadas1 - (3 * desvio_padrao_meninas_alfabetizadas1)
outlier_superior_meninas_alfabetizadas1 = media_meninas_alfabetizadas1 + (3 * desvio_padrao_meninas_alfabetizadas1)

outlier_inferior_meninas_alfabetizadas2 = media_meninas_alfabetizadas2 - (3 * desvio_padrao_meninas_alfabetizadas2)
outlier_superior_meninas_alfabetizadas2 = media_meninas_alfabetizadas2 + (3 * desvio_padrao_meninas_alfabetizadas2)

outlier_inferior_meninas_alfabetizadas3 = media_meninas_alfabetizadas3 - (3 * desvio_padrao_meninas_alfabetizadas3)
outlier_superior_meninas_alfabetizadas3 = media_meninas_alfabetizadas3 + (3 * desvio_padrao_meninas_alfabetizadas3)


df_outlier_meninas_alfabetizadas = pd.DataFrame([
    [outlier_inferior_meninas_alfabetizadas1, outlier_superior_meninas_alfabetizadas1,
    outlier_inferior_meninas_alfabetizadas2, outlier_superior_meninas_alfabetizadas2,
    outlier_inferior_meninas_alfabetizadas3, outlier_superior_meninas_alfabetizadas3]
], index=pd.MultiIndex.from_tuples([
    ("",)
]), columns=pd.MultiIndex.from_tuples([
    ("Observação discrepante (meninas alfabetizadas)", "Sem filtro", "Outlier inferior"),
    ("Observação discrepante (meninas alfabetizadas)", "Sem filtro", "Outlier superior"),
    ("Observação discrepante (meninas alfabetizadas)", "Filtro 1", "Outlier inferior"),
    ("Observação discrepante (meninas alfabetizadas)", "Filtro 1", "Outlier superior"),
    ("Observação discrepante (meninas alfabetizadas)", "Filtro 2", "Outlier inferior"),
    ("Observação discrepante (meninas alfabetizadas)", "Filtro 2", "Outlier superior")
]))
df_outlier_meninas_alfabetizadas

 Observação discrepante (meninas alfabetizadas)                   \
                                     Sem filtro
                               Outlier inferior Outlier superior
                                  -72096.776234     64526.412597


         Filtro 1                          Filtro 2
 Outlier inferior Outlier superior Outlier inferior Outlier superior
    -45793.247727     58539.065909    -12972.594373     14482.958009

In [220]:
outlier_inferior_meninas_analfabetas1 = media_meninas_analfabetas1 - (3 * desvio_padrao_meninas_analfabetas1)
outlier_superior_meninas_analfabetas1 = media_meninas_analfabetas1 + (3 * desvio_padrao_meninas_analfabetas1)

outlier_inferior_meninas_analfabetas2 = media_meninas_analfabetas2 - (3 * desvio_padrao_meninas_analfabetas2)
outlier_superior_meninas_analfabetas2 = media_meninas_analfabetas2 + (3 * desvio_padrao_meninas_analfabetas2)

outlier_inferior_meninas_analfabetas3 = media_meninas_analfabetas3 - (3 * desvio_padrao_meninas_analfabetas3)
outlier_superior_meninas_analfabetas3 = media_meninas_analfabetas3 + (3 * desvio_padrao_meninas_analfabetas3)


df_outlier_meninas_analfabetas = pd.DataFrame([
    [outlier_inferior_meninas_analfabetas1, outlier_superior_meninas_analfabetas1,
    outlier_inferior_meninas_analfabetas2, outlier_superior_meninas_analfabetas2,
    outlier_inferior_meninas_analfabetas3, outlier_superior_meninas_analfabetas3]
], index=pd.MultiIndex.from_tuples([
    ("",)
]), columns=pd.MultiIndex.from_tuples([
    ("Observação discrepante (meninas analfabetas)", "Sem filtro", "Outlier inferior"),
    ("Observação discrepante (meninas analfabetas)", "Sem filtro", "Outlier superior"),
    ("Observação discrepante (meninas analfabetas)", "Filtro 1", "Outlier inferior"),
    ("Observação discrepante (meninas analfabetas)", "Filtro 1", "Outlier superior"),
    ("Observação discrepante (meninas analfabetas)", "Filtro 2", "Outlier inferior"),
    ("Observação discrepante (meninas analfabetas)", "Filtro 2", "Outlier superior")
]))
df_outlier_meninas_analfabetas

 Observação discrepante (meninas analfabetas)                   \
                                   Sem filtro
                             Outlier inferior Outlier superior
                               -453496.002973    548245.821154


         Filtro 1                          Filtro 2
 Outlier inferior Outlier superior Outlier inferior Outlier superior
   -446461.622297    549310.804115   -685771.481762    693732.754489

In [221]:
outlier_inferior_meninas_total1 = media_meninas_total1 - (3 * desvio_padrao_meninas_total1)
outlier_superior_meninas_total1 = media_meninas_total1 + (3 * desvio_padrao_meninas_total1)

outlier_inferior_meninas_total2 = media_meninas_total2 - (3 * desvio_padrao_meninas_total2)
outlier_superior_meninas_total2 = media_meninas_total2 + (3 * desvio_padrao_meninas_total2)

outlier_inferior_meninas_total3 = media_meninas_total3 - (3 * desvio_padrao_meninas_total3)
outlier_superior_meninas_total3 = media_meninas_total3 + (3 * desvio_padrao_meninas_total3)


df_outlier_meninas_total = pd.DataFrame([
    [outlier_inferior_meninas_total1, outlier_superior_meninas_total1,
    outlier_inferior_meninas_total2, outlier_superior_meninas_total2,
    outlier_inferior_meninas_total3, outlier_superior_meninas_total3]
], index=pd.MultiIndex.from_tuples([
    ("",)
]), columns=pd.MultiIndex.from_tuples([
    ("Observação discrepante (meninas total)", "Sem filtro", "Outlier inferior"),
    ("Observação discrepante (meninas total)", "Sem filtro", "Outlier superior"),
    ("Observação discrepante (meninas total)", "Filtro 1", "Outlier inferior"),
    ("Observação discrepante (meninas total)", "Filtro 1", "Outlier superior"),
    ("Observação discrepante (meninas total)", "Filtro 2", "Outlier inferior"),
    ("Observação discrepante (meninas total)", "Filtro 2", "Outlier superior")
]))
df_outlier_meninas_total

 Observação discrepante (meninas total)                                    \
                             Sem filtro                          Filtro 1
                       Outlier inferior Outlier superior Outlier inferior
                          -18171.856831     22201.584104   -534543.031621


                          Filtro 2
 Outlier superior Outlier inferior Outlier superior
    657264.667985   -620125.118286     691044.75465

# Casas

In [222]:
casas = df[['Unnamed: 0','Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38']]

casas_header = casas.iloc[2]
casas.columns = casas_header
casas = casas[3:]

columns_multiindex = pd.MultiIndex.from_tuples([
    ('', 'Províncias e Município Neutro'),
    ('Casas', 'Habitadas'),
    ('Casas', 'Desabitadas'),
    ('Casas', 'Total')
])

casas.columns = columns_multiindex

casas

                                     Casas
   Províncias e Município Neutro Habitadas Desabitadas    Total
3                       Amazonas      7661         229     7890
4                           Pará     38978        2077    41055
5                       Maranhão     47166        1405    48571
6                          Piauí     29208         223    29431
7                          Ceará     99901        2989   102890
8            Rio Grande do Norte     36710         706    37416
9                        Paraíba     43767         522    44289
10                    Pernambuco    133920        4381   188301
11                       Alagoas     55894        2030    57924
12                       Sergipe     25542         567    26109
13                         Bahia    176032        5479   181511
14                Espírito Santo     10742        1079    11821
15              Município Neutro     29045        1873    80918
16                Rio de Janeiro     88698        2844    91542
17                     São Paulo     65778        1000    66778
18                        Paraná     18903         259    19162
19                Santa Catarina     19608         528    20136
20             Rio Grande do Sul     60199        1741    61940
21                  Minas Gerais    275611        3629   279240
22                         Goiás     25196         487    25683
23                   Mato Grosso      7501         102     7603
24                         Total   1296060       34150  1330210

In [223]:
tabela_manual_casas_habitadas = pd.to_numeric(df.iloc[3:25, 36])

tabela_ocr_casas_habitadas1 = pd.to_numeric(df1.iloc[:, 35])
diferenca_casas_habitadas1 = tabela_manual_casas_habitadas.values - tabela_ocr_casas_habitadas1.values

tabela_ocr_casas_habitadas2 = pd.to_numeric(df2.iloc[:, 35])
diferenca_casas_habitadas2 = tabela_manual_casas_habitadas.values - tabela_ocr_casas_habitadas2.values

tabela_ocr_casas_habitadas3 = pd.to_numeric(df3.iloc[:, 35])
diferenca_casas_habitadas3 = tabela_manual_casas_habitadas.values - tabela_ocr_casas_habitadas3.values

In [224]:
tabela_manual_casas_desabitadas = pd.to_numeric(df.iloc[3:25, 37])

tabela_ocr_casas_desabitadas1 = pd.to_numeric(df1.iloc[:, 36])
diferenca_casas_desabitadas1 = tabela_manual_casas_desabitadas.values - tabela_ocr_casas_desabitadas1.values

tabela_ocr_casas_desabitadas2 = pd.to_numeric(df2.iloc[:, 36])
diferenca_casas_desabitadas2 = tabela_manual_casas_desabitadas.values - tabela_ocr_casas_desabitadas2.values

tabela_ocr_casas_desabitadas3 = pd.to_numeric(df3.iloc[:, 36])
diferenca_casas_desabitadas3 = tabela_manual_casas_desabitadas.values - tabela_ocr_casas_desabitadas3.values

In [225]:
tabela_manual_casas_total = pd.to_numeric(df.iloc[3:25, 38])

tabela_ocr_casas_total1 = pd.to_numeric(df1.iloc[:, 37])
diferenca_casas_total1 = tabela_manual_casas_total.values - tabela_ocr_casas_total1.values

tabela_ocr_casas_total2 = pd.to_numeric(df2.iloc[:, 37])
diferenca_casas_total2 = tabela_manual_casas_total.values - tabela_ocr_casas_total2.values

tabela_ocr_casas_total3 = pd.to_numeric(df3.iloc[:, 37])
diferenca_casas_total3 = tabela_manual_casas_total.values - tabela_ocr_casas_total3.values

In [226]:
variancia_casas_habitadas1 = np.var(diferenca_casas_habitadas1)
variancia_casas_habitadas2 = np.var(diferenca_casas_habitadas2)
variancia_casas_habitadas3 = np.var(diferenca_casas_habitadas3)

df_variancia_casas_habitadas = pd.DataFrame([[variancia_casas_habitadas1, variancia_casas_habitadas2, variancia_casas_habitadas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_variancia_casas_habitadas.index = ["Variância (casas habitadas)"]
df_variancia_casas_habitadas

                               Sem filtro      Filtro 1      Filtro 2
Variância (casas habitadas)  1.259599e+08  1.878620e+10  7.689592e+10

In [227]:
variancia_casas_desabitadas1 = np.var(diferenca_casas_desabitadas1)
variancia_casas_desabitadas2 = np.var(diferenca_casas_desabitadas2)
variancia_casas_desabitadas3 = np.var(diferenca_casas_desabitadas3)

df_variancia_casas_desabitadas = pd.DataFrame([[variancia_casas_desabitadas1, variancia_casas_desabitadas2, variancia_casas_desabitadas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_variancia_casas_desabitadas.index = ["Variância (casas desabitadas)"]
df_variancia_casas_desabitadas

                                 Sem filtro      Filtro 1      Filtro 2
Variância (casas desabitadas)  1.087216e+08  4.793123e+07  1.379102e+06

In [228]:
variancia_casas_total1 = np.var(diferenca_casas_total1)
variancia_casas_total2 = np.var(diferenca_casas_total2)
variancia_casas_total3 = np.var(diferenca_casas_total3)

df_variancia_casas_total = pd.DataFrame([[variancia_casas_total1, variancia_casas_total2, variancia_casas_total3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_variancia_casas_total.index = ["Variância (casas total)"]
df_variancia_casas_total

                           Sem filtro      Filtro 1      Filtro 2
Variância (casas total)  3.632861e+08  7.158506e+11  6.400289e+10

In [229]:
desvio_padrao_casas_habitadas1 = np.std(diferenca_casas_habitadas1)
desvio_padrao_casas_habitadas2 = np.std(diferenca_casas_habitadas2)
desvio_padrao_casas_habitadas3 = np.std(diferenca_casas_habitadas3)

df_desvio_padrao_casas_habitadas = pd.DataFrame([[desvio_padrao_casas_habitadas1, desvio_padrao_casas_habitadas2, desvio_padrao_casas_habitadas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_desvio_padrao_casas_habitadas.index = ["Desvio padrão (casas habitadas)"]
df_desvio_padrao_casas_habitadas

                                   Sem filtro       Filtro 1       Filtro 2
Desvio padrão (casas habitadas)  11223.187674  137062.771901  277301.144239

In [230]:
desvio_padrao_casas_desabitadas1 = np.std(diferenca_casas_desabitadas1)
desvio_padrao_casas_desabitadas2 = np.std(diferenca_casas_desabitadas2)
desvio_padrao_casas_desabitadas3 = np.std(diferenca_casas_desabitadas3)

df_desvio_padrao_casas_desabitadas = pd.DataFrame([[desvio_padrao_casas_desabitadas1, desvio_padrao_casas_desabitadas2, desvio_padrao_casas_desabitadas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_desvio_padrao_casas_desabitadas.index = ["Desvio padrão (casas desabitadas)"]
df_desvio_padrao_casas_desabitadas

                                     Sem filtro     Filtro 1     Filtro 2
Desvio padrão (casas desabitadas)  10426.966241  6923.238429  1174.351864

In [231]:
desvio_padrao_casas_total1 = np.std(diferenca_casas_total1)
desvio_padrao_casas_total2 = np.std(diferenca_casas_total2)
desvio_padrao_casas_total3 = np.std(diferenca_casas_total3)

df_desvio_padrao_casas_total = pd.DataFrame([[desvio_padrao_casas_total1, desvio_padrao_casas_total2, desvio_padrao_casas_total3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_desvio_padrao_casas_total.index = ["Desvio padrão (casas total)"]
df_desvio_padrao_casas_total

                               Sem filtro       Filtro 1       Filtro 2
Desvio padrão (casas total)  19060.064987  846079.560175  252987.933171

In [232]:
coeficiente_variacao_casas_habitadas1 = desvio_padrao_casas_habitadas1 / np.mean(diferenca_casas_habitadas1) * 100
coeficiente_variacao_casas_habitadas2 = desvio_padrao_casas_habitadas2 / np.mean(diferenca_casas_habitadas2) * 100
coeficiente_variacao_casas_habitadas3 = desvio_padrao_casas_habitadas3 / np.mean(diferenca_casas_habitadas3) * 100

df_coeficiente_variacao_casas_habitadas = pd.DataFrame([[coeficiente_variacao_casas_habitadas1, coeficiente_variacao_casas_habitadas2, coeficiente_variacao_casas_habitadas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_coeficiente_variacao_casas_habitadas.index = ["Coeficiente de variação (casas habitadas)"]
df_coeficiente_variacao_casas_habitadas

,Sem filtro,Filtro 1,Filtro 2
Coeficiente de variação (casas habitadas),-825.068933,45833.424256,-375.227277

In [233]:
coeficiente_variacao_casas_desabitadas1 = desvio_padrao_casas_desabitadas1 / np.mean(diferenca_casas_desabitadas1) * 100
coeficiente_variacao_casas_desabitadas2 = desvio_padrao_casas_desabitadas2 / np.mean(diferenca_casas_desabitadas2) * 100
coeficiente_variacao_casas_desabitadas3 = desvio_padrao_casas_desabitadas3 / np.mean(diferenca_casas_desabitadas3) * 100

df_coeficiente_variacao_casas_desabitadas = pd.DataFrame([[coeficiente_variacao_casas_desabitadas1, coeficiente_variacao_casas_desabitadas2, coeficiente_variacao_casas_desabitadas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_coeficiente_variacao_casas_desabitadas.index = ["Coeficiente de variação (casas desabitadas)"]
df_coeficiente_variacao_casas_desabitadas

,Sem filtro,Filtro 1,Filtro 2
Coeficiente de variação (casas desabitadas),-467.977595,223.003288,517.025035

In [234]:
coeficiente_variacao_casas_total1 = desvio_padrao_casas_total1 / np.mean(diferenca_casas_total1) * 100
coeficiente_variacao_casas_total2 = desvio_padrao_casas_total2 / np.mean(diferenca_casas_total2) * 100
coeficiente_variacao_casas_total3 = desvio_padrao_casas_total3 / np.mean(diferenca_casas_total3) * 100

df_coeficiente_variacao_casas_total = pd.DataFrame([[coeficiente_variacao_casas_total1, coeficiente_variacao_casas_total2, coeficiente_variacao_casas_total3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_coeficiente_variacao_casas_total.index = ["Coeficiente de variação (casas total)"]
df_coeficiente_variacao_casas_total

                                       Sem filtro    Filtro 1    Filtro 2
Coeficiente de variação (casas total)  245.704308 -482.321474  299.120306

In [235]:
media_casas_habitadas1 = np.mean(diferenca_casas_habitadas1)
media_casas_habitadas2 = np.mean(diferenca_casas_habitadas2)
media_casas_habitadas3 = np.mean(diferenca_casas_habitadas3)

df_media_casas_habitadas = pd.DataFrame([[media_casas_habitadas1, media_casas_habitadas2, media_casas_habitadas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_media_casas_habitadas.index = ["Média (casas habitadas)"]
df_media_casas_habitadas

                          Sem filtro    Filtro 1      Filtro 2
Média (casas habitadas) -1360.272727  299.045455 -73902.181818

In [236]:
media_casas_desabitadas1 = np.mean(diferenca_casas_desabitadas1)
media_casas_desabitadas2 = np.mean(diferenca_casas_desabitadas2)
media_casas_desabitadas3 = np.mean(diferenca_casas_desabitadas3)

df_media_casas_desabitadas = pd.DataFrame([[media_casas_desabitadas1, media_casas_desabitadas2, media_casas_desabitadas3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_media_casas_desabitadas.index = ["Média (casas desabitadas)"]
df_media_casas_desabitadas

                            Sem filtro     Filtro 1    Filtro 2
Média (casas desabitadas) -2228.090909  3104.545455  227.136364

In [237]:
media_casas_total1 = np.mean(diferenca_casas_total1)
media_casas_total2 = np.mean(diferenca_casas_total2)
media_casas_total3 = np.mean(diferenca_casas_total3)

df_media_casas_total = pd.DataFrame([[media_casas_total1, media_casas_total2, media_casas_total3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_media_casas_total.index = ["Média (casas total)"]
df_media_casas_total

                      Sem filtro       Filtro 1      Filtro 2
Média (casas total)  7757.318182 -175418.181818  84577.318182

In [238]:
outlier_inferior_casas_habitadas1 = media_casas_habitadas1 - (3 * desvio_padrao_casas_habitadas1)
outlier_superior_casas_habitadas1 = media_casas_habitadas1 + (3 * desvio_padrao_casas_habitadas1)

outlier_inferior_casas_habitadas2 = media_casas_habitadas2 - (3 * desvio_padrao_casas_habitadas2)
outlier_superior_casas_habitadas2 = media_casas_habitadas2 + (3 * desvio_padrao_casas_habitadas2)

outlier_inferior_casas_habitadas3 = media_casas_habitadas3 - (3 * desvio_padrao_casas_habitadas3)
outlier_superior_casas_habitadas3 = media_casas_habitadas3 + (3 * desvio_padrao_casas_habitadas3)


df_outlier_casas_habitadas = pd.DataFrame([
    [outlier_inferior_casas_habitadas1, outlier_superior_casas_habitadas1,
    outlier_inferior_casas_habitadas2, outlier_superior_casas_habitadas2,
    outlier_inferior_casas_habitadas3, outlier_superior_casas_habitadas3]
], index=pd.MultiIndex.from_tuples([
    ("",)
]), columns=pd.MultiIndex.from_tuples([
    ("Observação discrepante (casas habitadas)", "Sem filtro", "Outlier inferior"),
    ("Observação discrepante (casas habitadas)", "Sem filtro", "Outlier superior"),
    ("Observação discrepante (casas habitadas)", "Filtro 1", "Outlier inferior"),
    ("Observação discrepante (casas habitadas)", "Filtro 1", "Outlier superior"),
    ("Observação discrepante (casas habitadas)", "Filtro 2", "Outlier inferior"),
    ("Observação discrepante (casas habitadas)", "Filtro 2", "Outlier superior")
]))
df_outlier_casas_habitadas

 Observação discrepante (casas habitadas)                                    \
                               Sem filtro                          Filtro 1
                         Outlier inferior Outlier superior Outlier inferior
                            -35029.835749     32309.290294    -410889.27025


                          Filtro 2
 Outlier superior Outlier inferior Outlier superior
    411487.361159   -905805.614534    758001.250898

In [239]:
outlier_inferior_casas_desabitadas1 = media_casas_desabitadas1 - (3 * desvio_padrao_casas_desabitadas1)
outlier_superior_casas_desabitadas1 = media_casas_desabitadas1 + (3 * desvio_padrao_casas_desabitadas1)

outlier_inferior_casas_desabitadas2 = media_casas_desabitadas2 - (3 * desvio_padrao_casas_desabitadas2)
outlier_superior_casas_desabitadas2 = media_casas_desabitadas2 + (3 * desvio_padrao_casas_desabitadas2)

outlier_inferior_casas_desabitadas3 = media_casas_desabitadas3 - (3 * desvio_padrao_casas_desabitadas3)
outlier_superior_casas_desabitadas3 = media_casas_desabitadas3 + (3 * desvio_padrao_casas_desabitadas3)


df_outlier_casas_desabitadas = pd.DataFrame([
    [outlier_inferior_casas_desabitadas1, outlier_superior_casas_desabitadas1,
    outlier_inferior_casas_desabitadas2, outlier_superior_casas_desabitadas2,
    outlier_inferior_casas_desabitadas3, outlier_superior_casas_desabitadas3]
], index=pd.MultiIndex.from_tuples([
    ("",)
]), columns=pd.MultiIndex.from_tuples([
    ("Observação discrepante (casas desabitadas)", "Sem filtro", "Outlier inferior"),
    ("Observação discrepante (casas desabitadas)", "Sem filtro", "Outlier superior"),
    ("Observação discrepante (casas desabitadas)", "Filtro 1", "Outlier inferior"),
    ("Observação discrepante (casas desabitadas)", "Filtro 1", "Outlier superior"),
    ("Observação discrepante (casas desabitadas)", "Filtro 2", "Outlier inferior"),
    ("Observação discrepante (casas desabitadas)", "Filtro 2", "Outlier superior")
]))
df_outlier_casas_desabitadas

 Observação discrepante (casas desabitadas)                                    \
                                 Sem filtro                          Filtro 1
                           Outlier inferior Outlier superior Outlier inferior
                              -33508.989632     29052.807814    -17665.169831


                          Filtro 2
 Outlier superior Outlier inferior Outlier superior
      23874.26074     -3295.919227      3750.191954

In [240]:
outlier_inferior_casas_total1 = media_casas_total1 - (3 * desvio_padrao_casas_total1)
outlier_superior_casas_total1 = media_casas_total1 + (3 * desvio_padrao_casas_total1)

outlier_inferior_casas_total2 = media_casas_total2 - (3 * desvio_padrao_casas_total2)
outlier_superior_casas_total2 = media_casas_total2 + (3 * desvio_padrao_casas_total2)

outlier_inferior_casas_total3 = media_casas_total3 - (3 * desvio_padrao_casas_total3)
outlier_superior_casas_total3 = media_casas_total3 + (3 * desvio_padrao_casas_total3)


df_outlier_casas_total = pd.DataFrame([
    [outlier_inferior_casas_total1, outlier_superior_casas_total1,
    outlier_inferior_casas_total2, outlier_superior_casas_total2,
    outlier_inferior_casas_total3, outlier_superior_casas_total3]
], index=pd.MultiIndex.from_tuples([
    ("",)
]), columns=pd.MultiIndex.from_tuples([
    ("Observação discrepante (casas total)", "Sem filtro", "Outlier inferior"),
    ("Observação discrepante (casas total)", "Sem filtro", "Outlier superior"),
    ("Observação discrepante (casas total)", "Filtro 1", "Outlier inferior"),
    ("Observação discrepante (casas total)", "Filtro 1", "Outlier superior"),
    ("Observação discrepante (casas total)", "Filtro 2", "Outlier inferior"),
    ("Observação discrepante (casas total)", "Filtro 2", "Outlier superior")
]))
df_outlier_casas_total

 Observação discrepante (casas total)                                    \
                           Sem filtro                          Filtro 1
                     Outlier inferior Outlier superior Outlier inferior
                        -49422.876779     64937.513143    -2.713657e+06


                          Filtro 2
 Outlier superior Outlier inferior Outlier superior
     2.362820e+06   -674386.481332    843541.117695

# Fogos

In [241]:
fogos = df[['Unnamed: 0', 'Unnamed: 39']]

fogos_header = fogos.iloc[2]
fogos.columns = fogos_header
fogos = fogos[3:]

fogos

2  Províncias e Município Neutro Número de fogos
3                       Amazonas            7811
4                           Pará           39521
5                       Maranhão           49282
6                          Piauí           30770
7                          Ceará          100207
8            Rio Grande do Norte           37320
9                        Paraíba           44438
10                    Pernambuco          134765
11                       Alagoas           60386
12                       Sergipe           24950
13                         Bahia          180307
14                Espírito Santo           10774
15              Município Neutro           44211
16                Rio de Janeiro           90232
17                     São Paulo           65960
18                        Paraná           22026
19                Santa Catarina           14457
20             Rio Grande do Sul           61394
21                  Minas Gerais          280660
22                         Goiás           25222
23                   Mato Grosso            7581
24                         Total         1332274

In [242]:
tabela_manual_fogos = pd.to_numeric(df.iloc[3:25, 39])

tabela_ocr_fogos1 = pd.to_numeric(df1.iloc[:, 38])
diferenca_fogos1 = tabela_manual_fogos.values - tabela_ocr_fogos1.values

tabela_ocr_fogos2 = pd.to_numeric(df2.iloc[:, 38])
diferenca_fogos2 = tabela_manual_fogos.values - tabela_ocr_fogos2.values

tabela_ocr_fogos3 = pd.to_numeric(df3.iloc[:, 38])
diferenca_fogos3 = tabela_manual_fogos.values - tabela_ocr_fogos3.values

In [243]:
variancia_fogos1 = np.var(diferenca_fogos1)
variancia_fogos2 = np.var(diferenca_fogos2)
variancia_fogos3 = np.var(diferenca_fogos3)

df_variancia_fogos = pd.DataFrame([[variancia_fogos1, variancia_fogos2, variancia_fogos3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_variancia_fogos.index = ["Variância (fogos)"]
df_variancia_fogos

                     Sem filtro      Filtro 1      Filtro 2
Variância (fogos)  4.091277e+10  7.382154e+10  1.175369e+11

In [244]:
desvio_padrao_fogos1 = np.std(diferenca_fogos1)
desvio_padrao_fogos2 = np.std(diferenca_fogos2)
desvio_padrao_fogos3 = np.std(diferenca_fogos3)

df_desvio_padrao_fogos = pd.DataFrame([[desvio_padrao_fogos1, desvio_padrao_fogos2, desvio_padrao_fogos3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_desvio_padrao_fogos.index = ["Desvio padrão (fogos)"]
df_desvio_padrao_fogos

                         Sem filtro       Filtro 1       Filtro 2
Desvio padrão (fogos)  202269.04802  271701.201008  342836.558569

In [245]:
coeficiente_variacao_fogos1 = desvio_padrao_fogos1 / np.mean(diferenca_fogos1) * 100
coeficiente_variacao_fogos2 = desvio_padrao_fogos2 / np.mean(diferenca_fogos2) * 100
coeficiente_variacao_fogos3 = desvio_padrao_fogos3 / np.mean(diferenca_fogos3) * 100

df_coeficiente_variacao_fogos = pd.DataFrame([[coeficiente_variacao_fogos1, coeficiente_variacao_fogos2, coeficiente_variacao_fogos3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_coeficiente_variacao_fogos.index = ["Coeficiente de variação (fogos)"]
df_coeficiente_variacao_fogos

                                 Sem filtro    Filtro 1     Filtro 2
Coeficiente de variação (fogos)  345.718763  224.331722  1610.585539

In [246]:
media_fogos1 = np.mean(diferenca_fogos1)
media_fogos2 = np.mean(diferenca_fogos2)
media_fogos3 = np.mean(diferenca_fogos3)

df_media_fogos = pd.DataFrame([[media_fogos1, media_fogos2, media_fogos3]], columns=["Sem filtro", "Filtro 1", "Filtro 2"])
df_media_fogos.index = ["Média (fogos)"]
df_media_fogos

                 Sem filtro       Filtro 1      Filtro 2
Média (fogos)  58506.818182  121115.818182  21286.454545

In [247]:
outlier_inferior_fogos1 = media_fogos1 - (3 * desvio_padrao_fogos1)
outlier_superior_fogos1 = media_fogos1 + (3 * desvio_padrao_fogos1)

outlier_inferior_fogos2 = media_fogos2 - (3 * desvio_padrao_fogos2)
outlier_superior_fogos2 = media_fogos2 + (3 * desvio_padrao_fogos2)

outlier_inferior_fogos3 = media_fogos3 - (3 * desvio_padrao_fogos3)
outlier_superior_fogos3 = media_fogos3 + (3 * desvio_padrao_fogos3)


df_outlier_fogos = pd.DataFrame([
    [outlier_inferior_fogos1, outlier_superior_fogos1,
    outlier_inferior_fogos2, outlier_superior_fogos2,
    outlier_inferior_fogos3, outlier_superior_fogos3]
], index=pd.MultiIndex.from_tuples([
    ("",)
]), columns=pd.MultiIndex.from_tuples([
    ("Observação discrepante (fogos)", "Sem filtro", "Outlier inferior"),
    ("Observação discrepante (fogos)", "Sem filtro", "Outlier superior"),
    ("Observação discrepante (fogos)", "Filtro 1", "Outlier inferior"),
    ("Observação discrepante (fogos)", "Filtro 1", "Outlier superior"),
    ("Observação discrepante (fogos)", "Filtro 2", "Outlier inferior"),
    ("Observação discrepante (fogos)", "Filtro 2", "Outlier superior")
]))
df_outlier_fogos

 Observação discrepante (fogos)                                    \
                     Sem filtro                          Filtro 1
               Outlier inferior Outlier superior Outlier inferior
                 -548300.325879    665313.962243   -693987.784843


                          Filtro 2
 Outlier superior Outlier inferior Outlier superior
    936219.421207    -1.007223e+06     1.049796e+06