In [1]:
import pandas as pd
import numpy as np
import pathfinder as pf

In [2]:
filename = "censo_1872-003_p1.csv"
folder = "planilhas"
path = pf.find_file(filename, folder)
df = pd.read_csv(path)
print(df.columns)

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')

In [3]:
filename = "erosão_limiarização.csv"
folder = "resultados_ocr"
path = pf.find_file(filename, folder)
df2 = pd.read_csv(path, header=None)
print(df2.columns)

Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')

In [4]:
#verdadeiros positivos
vp = 0
#falsos positivos
fp = 0
#verdadeiros negativos
vn = 0
#falsos negativos
fn = 0

# Gêneros

In [5]:
sexos = df[['Unnamed: 0','Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3']]
sexos_header = sexos.iloc[1]
sexos.columns = sexos_header
sexos = sexos[2:]

sexos_header = sexos.iloc[0]
sexos.columns = sexos_header
sexos = sexos[1:]

columns_multiindex = pd.MultiIndex.from_tuples([
    #('Gêneros', 'Províncias e Município Neutro'),
    ('', 'Províncias e Município Neutro'),
    ('Gêneros', 'Homens'),
    ('Gêneros', 'Mulheres'),
    ('Gêneros', 'Total')
])

# Atribuindo o MultiIndex às colunas do DataFrame
sexos.columns = columns_multiindex

#print(sexos)
sexos

                                  Gêneros
   Províncias e Município Neutro   Homens Mulheres    Total
3                       Amazonas    30983     2564    56631
4                           Pará   128589    11919   247779
5                       Maranhão   141942    14215   284101
6                          Piauí    90322     8810   178427
7                          Ceará   350906    33886   689773
8            Rio Grande do Norte   112721    10823   220959
9                        Paraíba   179433    17526   354700
10                    Pernambuco   381565    37094   752511
11                       Alagoas   155584    15667   312268
12                       Sergipe    74739     7888   153620
13                         Bahia   630353    58143  1211792
14                Espírito Santo    29607    29871    59478
15              Município Neutro   133880    92153   226033
16                Rio de Janeiro   255806   234281   499087
17                     São Paulo   348304   332438   680742
18                        Paraná    59384    56858   116162
19                Santa Catarina    73088    71730   144818
20             Rio Grande do Sul   191022   176000   367022
21                  Minas Gerais   847592   821684  1669276
22                         Goiás    74968    74775   149743
23                   Mato Grosso    27991    25759    53750
24                         Total  4318699  4100973  8419672

In [6]:
print(df.columns)
print(df.iloc[3:25, 1])
print(df2.columns)
print(df2.iloc[:, 0])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       30983
4      128589
5      141942
6       90322
7      350906
8      112721
9      179433
10     381565
11     155584
12      74739
13     630353
14      29607
15     133880
16     255806
17     348304
18      59384
19      73088
20     191022
21     847592
22      74968
23      27991
24    4318699
Name: Unnamed: 1, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0      300983
1      128589
2      145042
3       90822
4      350806
5      112721
6      170438
7      881585
8      155584
9           0
10     680858
11      29607
12     133880
13     255806
14     348804
15      59884
16      78088
17     191022
18     847502
19      74908
20      27091
21    4818600
Name: 0, dtype: int64

In [7]:
print(df.columns)
print(df.iloc[3:25, 2])
print(df2.columns)
print(df2.iloc[:, 1])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        2564
4       11919
5       14215
6        8810
7       33886
8       10823
9       17526
10      37094
11      15667
12       7888
13      58143
14      29871
15      92153
16     234281
17     332438
18      56858
19      71730
20     176000
21     821684
22      74775
23      25759
24    4100973
Name: Unnamed: 2, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0         2514
1        11919
2           42
3            0
4       188886
5        10823
6       117690
7        87004
8         1500
9            0
10           0
11       45187
12        2158
13           0
14      982458
15       60858
16       71730
17      176000
18       82168
19           0
20       25759
21    41009731
Name: 1, dtype: int64

In [8]:
print(df.columns)
print(df.iloc[3:25, 3])
print(df2.columns)
print(df2.iloc[:, 2])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       56631
4      247779
5      284101
6      178427
7      689773
8      220959
9      354700
10     752511
11     312268
12     153620
13    1211792
14      59478
15     226033
16     499087
17     680742
18     116162
19     144818
20     367022
21    1669276
22     149743
23      53750
24    8419672
Name: Unnamed: 3, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0           0
1         779
2         201
3         147
4      680778
5      220059
6      364700
7      742511
8      812208
9      153620
10          0
11          7
12      20093
13          0
14     630741
15     118162
16     144818
17    3070221
18       1276
19     140749
20      53760
21     810672
Name: 2, dtype: int64

In [9]:
tabela_manual_homens = pd.to_numeric(df.iloc[3:25, 1])
tabela_ocr_homens = pd.to_numeric(df2.iloc[:, 0])

diferenca_homens = tabela_manual_homens.values - tabela_ocr_homens.values
diferenca_homens

array([-270000,       0,   -3100,    -500,     100,       0,    8995,
       -500020,       0,   74739,  -50505,       0,       0,       0,
          -500,    -500,   -5000,       0,      90,      60,     900,
       -499901])

In [10]:
for i in range(tabela_manual_homens.size):
    if tabela_manual_homens.iloc[i] - tabela_ocr_homens.iloc[i] == 0 and tabela_manual_homens.iloc[i] != 0:
        vp += 1
    if tabela_manual_homens.iloc[i] - tabela_ocr_homens.iloc[i] != 0 and tabela_manual_homens.iloc[i] > 0 and tabela_ocr_homens.iloc[i] > 0:
        fp += 1
    if tabela_manual_homens.iloc[i] - tabela_ocr_homens.iloc[i] == 0 and tabela_manual_homens.iloc[i] == 0:
        vn += 1
    if tabela_manual_homens.iloc[i] > 0 and tabela_ocr_homens.iloc[i] == 0:
        fn += 1

print(vp, fp, vn, fn)

7 14 0 1

In [11]:
tabela_manual_mulheres = pd.to_numeric(df.iloc[3:25, 2])
tabela_ocr_mulheres = pd.to_numeric(df2.iloc[:, 1])

diferenca_mulheres = tabela_manual_mulheres.values - tabela_ocr_mulheres.values
diferenca_mulheres

array([       50,         0,     14173,      8810,   -155000,         0,
         -100164,    -49910,     14167,      7888,     58143,    -15316,
           89995,    234281,   -650020,     -4000,         0,         0,
          739516,     74775,         0, -36908758])

In [12]:
for i in range(tabela_manual_mulheres.size):
    if tabela_manual_mulheres.iloc[i] - tabela_ocr_mulheres.iloc[i] == 0 and tabela_manual_mulheres.iloc[i] != 0:
        vp += 1
    if tabela_manual_mulheres.iloc[i] - tabela_ocr_mulheres.iloc[i] != 0 and tabela_manual_mulheres.iloc[i] > 0 and tabela_ocr_mulheres.iloc[i] > 0:
        fp += 1
    if tabela_manual_mulheres.iloc[i] - tabela_ocr_mulheres.iloc[i] == 0 and tabela_manual_mulheres.iloc[i] == 0:
        vn += 1
    if tabela_manual_mulheres.iloc[i] > 0 and tabela_ocr_mulheres.iloc[i] == 0:
        fn += 1

print(vp, fp, vn, fn)

12 26 0 6

In [13]:
tabela_manual_total = pd.to_numeric(df.iloc[3:25, 3])
tabela_ocr_total = pd.to_numeric(df2.iloc[:, 2])

diferenca_total = tabela_manual_total.values - tabela_ocr_total.values
diferenca_total

array([   56631,   247000,   283900,   178280,     8995,      900,
         -10000,    10000,  -499940,        0,  1211792,    59471,
         205940,   499087,    50001,    -2000,        0, -2703199,
        1668000,     8994,      -10,  7609000])

In [14]:
for i in range(tabela_manual_total.size):
    if tabela_manual_total.iloc[i] - tabela_ocr_total.iloc[i] == 0 and tabela_manual_total.iloc[i] != 0:
        vp += 1
    if tabela_manual_total.iloc[i] - tabela_ocr_total.iloc[i] != 0 and tabela_manual_total.iloc[i] > 0 and tabela_ocr_total.iloc[i] > 0:
        fp += 1
    if tabela_manual_total.iloc[i] - tabela_ocr_total.iloc[i] == 0 and tabela_manual_total.iloc[i] == 0:
        vn += 1
    if tabela_manual_total.iloc[i] > 0 and tabela_ocr_total.iloc[i] == 0:
        fn += 1

print(vp, fp, vn, fn)

14 43 0 9

In [15]:
variancia_homens = np.var(diferenca_homens)
variancia_homens

23209228659.958675

In [16]:
variancia_mulheres = np.var(diferenca_mulheres)
variancia_mulheres

59195832203130.51

In [17]:
variancia_total = np.var(diferenca_total)
variancia_total

3026940264130.975

In [18]:
desvio_padrao_homens = np.std(diferenca_homens)
desvio_padrao_homens

152345.75366566237

In [19]:
desvio_padrao_mulheres = np.std(diferenca_mulheres)
desvio_padrao_mulheres

7693882.778099138

In [20]:
desvio_padrao_total = np.std(diferenca_total)
desvio_padrao_total

1739810.4103984938

In [21]:
coeficiente_variacao_homens = desvio_padrao_homens / np.mean(diferenca_homens) * 100
coeficiente_variacao_homens

-269.17464679888496

In [22]:
coeficiente_variacao_mulheres = desvio_padrao_mulheres / np.mean(diferenca_mulheres) * 100
coeficiente_variacao_mulheres

-461.95167134356893

In [23]:
coeficiente_variacao_total = desvio_padrao_total / np.mean(diferenca_total) * 100
coeficiente_variacao_total

430.89620448913604

In [24]:
print(f'Variância (homens): {variancia_homens}')
print(f'Desvio Padrão (homens): {desvio_padrao_homens}')
print(f'Coeficiente de Variação (homens): {coeficiente_variacao_homens}%')

Variância (homens): 23209228659.958675
Desvio Padrão (homens): 152345.75366566237
Coeficiente de Variação (homens): -269.17464679888496%

In [25]:
print(f'Variância (mulheres): {variancia_mulheres}')
print(f'Desvio Padrão (mulheres): {desvio_padrao_mulheres}')
print(f'Coeficiente de Variação (mulheres): {coeficiente_variacao_mulheres}%')

Variância (mulheres): 59195832203130.51
Desvio Padrão (mulheres): 7693882.778099138
Coeficiente de Variação (mulheres): -461.95167134356893%

In [26]:
print(f'Variância (total): {variancia_total}')
print(f'Desvio Padrão (total): {desvio_padrao_total}')
print(f'Coeficiente de Variação (total): {coeficiente_variacao_total}%')

Variância (total): 3026940264130.975
Desvio Padrão (total): 1739810.4103984938
Coeficiente de Variação (total): 430.89620448913604%

In [27]:
media_homens = np.mean(diferenca_homens)
media_homens

-56597.36363636364

In [28]:
media_mulheres = np.mean(diferenca_mulheres)
media_mulheres

-1665516.8181818181

In [29]:
media_total = np.mean(diferenca_total)
media_total

403765.54545454547

In [30]:
outlier_inferior_homens = media_homens - (3 * desvio_padrao_homens)
outlier_superior_homens = media_homens + (3 * desvio_padrao_homens)

print(outlier_inferior_homens, outlier_superior_homens)

-513634.62463335076 400439.89736062346

In [31]:
outlier_inferior_mulheres = media_mulheres - (3 * desvio_padrao_mulheres)
outlier_superior_mulheres = media_mulheres + (3 * desvio_padrao_mulheres)

print(outlier_inferior_mulheres, outlier_superior_mulheres)

-24747165.15247923 21416131.5161156

In [32]:
outlier_inferior_total = media_total - (3 * desvio_padrao_total)
outlier_superior_total = media_total + (3 * desvio_padrao_total)

print(outlier_inferior_total, outlier_superior_total)

-4815665.685740936 5623196.776650027

# Estados civis

In [33]:
estados_civis = df[['Unnamed: 0','Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9']]

estados_civis_header = estados_civis.iloc[2]
estados_civis.columns = estados_civis_header
estados_civis = estados_civis[3:]

columns_multiindex = pd.MultiIndex.from_tuples([
    #('Gêneros', 'Províncias e Município Neutro'),
    ('', '', 'Províncias e Município Neutro'),
    ('Estados civis', 'dos Homens', 'Solteiros'),
    ('Estados civis', 'dos Homens', 'Casados'),
    ('Estados civis', 'dos Homens', 'Viúvos'),
    ('Estados civis', 'das Mulheres', 'Solteiras'),
    ('Estados civis', 'das Mulheres', 'Casadas'),
    ('Estados civis', 'das Mulheres', 'Viúvas')
])

# Atribuindo o MultiIndex às colunas do DataFrame
estados_civis.columns = columns_multiindex

estados_civis

                                 Estados civis                                \
                                    dos Homens                  das Mulheres
   Províncias e Município Neutro     Solteiros  Casados  Viúvos    Solteiras
3                       Amazonas         24959     5105     919        19214
4                           Pará         94848    28935    4806        86825
5                       Maranhão        103283    33644    5015       102302
6                          Piauí         63294    23323    3705        59547
7                          Ceará        241692    99915    9299       224509
8            Rio Grande do Norte         80803    26832    5086        75915
9                        Paraíba        119403    53474    6556       112332
10                    Pernambuco        258936   111189   11440       240239
11                       Alagoas        102729    47865    4990        99772
12                       Sergipe         48013    24027    2699        50746
13                         Bahia        440556   160204   29593       398473
14                Espírito Santo         19415     9298     894        19251
15              Município Neutro        104036    25763    4081        64074
16                Rio de Janeiro        168391    71842   15573       148840
17                     São Paulo        234386    98864   15054       218684
18                        Paraná         37977    18649    2678        35006
19                Santa Catarina         49985    21351    1752        47122
20             Rio Grande do Sul        139899    45104    6019       124864
21                  Minas Gerais        572728   231947   42917       557389
22                         Goiás         51886    20696    2386        50125
23                   Mato Grosso         18227     7839    1925        17353
24                         Total       2975446  1165866  177387      2752582



    Casadas  Viúvas
3      4714    1720
4     26280    6085
5     32337    7520
6     23371    5187
7     99849   14509
8     26735    5588
9     53274    9661
10   111465   19242
11    46743   10169
12    24795    3340
13   151883   31083
14     9449    1171
15    20174    7905
16    68726   16715
17    96290   17464
18    18332    3520
19    20412    4196
20    41525    9611
21   217353   46942
22    20340    4310
23     6953    1453
24  1121000  227391

In [34]:
print(df.columns)
print(df.iloc[3:25, 4])
print(df2.columns)
print(df2.iloc[:, 3])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       24959
4       94848
5      103283
6       63294
7      241692
8       80803
9      119403
10     258936
11     102729
12      48013
13     440556
14      19415
15     104036
16     168391
17     234386
18      37977
19      49985
20     139899
21     572728
22      51886
23      18227
24    2975446
Name: Unnamed: 4, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0       21950
1         198
2      103288
3         204
4      241002
5      808083
6      119408
7      258036
8      102729
9       49018
10     440550
11     109415
12     104036
13         10
14      24386
15      81077
16      49985
17     139800
18     572728
19      51886
20          0
21    2975446
Name: 3, dtype: int64

In [35]:
print(df.columns)
print(df.iloc[3:25, 5])
print(df2.columns)
print(df2.iloc[:, 4])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        5105
4       28935
5       33644
6       23323
7       99915
8       26832
9       53474
10     111189
11      47865
12      24027
13     160204
14       9298
15      25763
16      71842
17      98864
18      18649
19      21351
20      45104
21     231947
22      20696
23       7839
24    1165866
Name: Unnamed: 5, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0        5105
1       23035
2           0
3       23323
4       99915
5       26892
6       53474
7      111189
8       47805
9       24087
10     160204
11       9298
12      25708
13      71842
14      98804
15      18649
16      21851
17      45104
18     231947
19      20696
20       7839
21    1105800
Name: 4, dtype: int64

In [36]:
print(df.columns)
print(df.iloc[3:25, 6])
print(df2.columns)
print(df2.iloc[:, 5])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        919
4       4806
5       5015
6       3705
7       9299
8       5086
9       6556
10     11440
11      4990
12      2699
13     29593
14       894
15      4081
16     15573
17     15054
18      2678
19      1752
20      6019
21     42917
22      2386
23      1925
24    177387
Name: Unnamed: 6, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0        919
1       4806
2       6015
3       8705
4       9299
5       5086
6       6556
7      11440
8       4900
9       2099
10    207798
11       894
12         0
13     16573
14     15054
15      2078
16      1752
17        19
18     42917
19     23836
20      1925
21         0
Name: 5, dtype: int64

In [37]:
print(df.columns)
print(df.iloc[3:25, 7])
print(df2.columns)
print(df2.iloc[:, 6])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       19214
4       86825
5      102302
6       59547
7      224509
8       75915
9      112332
10     240239
11      99772
12      50746
13     398473
14      19251
15      64074
16     148840
17     218684
18      35006
19      47122
20     124864
21     557389
22      50125
23      17353
24    2752582
Name: Unnamed: 7, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0       19214
1       80825
2      102302
3       50547
4      224509
5       75015
6      112382
7      240239
8       90772
9          74
10     308273
11      19251
12       4074
13     148810
14     218684
15      36006
16      47122
17     124864
18     657880
19      60125
20      17858
21    2752503
Name: 6, dtype: int64

In [38]:
print(df.columns)
print(df.iloc[3:25, 8])
print(df2.columns)
print(df2.iloc[:, 7])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        4714
4       26280
5       32337
6       23371
7       99849
8       26735
9       53274
10     111465
11      46743
12      24795
13     151883
14       9449
15      20174
16      68726
17      96290
18      18332
19      20412
20      41525
21     217353
22      20340
23       6953
24    1121000
Name: Unnamed: 8, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0           0
1       20280
2       32857
3       29871
4       99819
5       20735
6        5324
7        1165
8       40748
9       24795
10     151888
11       9149
12      20174
13      68726
14      96200
15      18832
16      20412
17      41526
18     917353
19      20840
20       6053
21    1121000
Name: 7, dtype: int64

In [39]:
print(df.columns)
print(df.iloc[3:25, 9])
print(df2.columns)
print(df2.iloc[:, 8])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       1720
4       6085
5       7520
6       5187
7      14509
8       5588
9       9661
10     19242
11     10169
12      3340
13     31083
14      1171
15      7905
16     16715
17     17464
18      3520
19      4196
20      9611
21     46942
22      4310
23      1453
24    227391
Name: Unnamed: 9, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0         0
1         0
2         0
3         0
4         0
5         0
6         0
7         0
8         0
9         0
10        0
11        0
12        0
13        0
14    17464
15     3520
16    41061
17     9611
18    40014
19     4310
20     1458
21        0
Name: 8, dtype: int64

In [40]:
tabela_manual_solteiros = pd.to_numeric(df.iloc[3:25, 4])
tabela_ocr_solteiros = pd.to_numeric(df2.iloc[:, 3])

diferenca_solteiros = tabela_manual_solteiros.values - tabela_ocr_solteiros.values
diferenca_solteiros

array([   3009,   94650,      -5,   63090,     690, -727280,      -5,
           900,       0,   -1005,       6,  -90000,       0,  168381,
        210000,  -43100,       0,      99,       0,       0,   18227,
             0])

In [41]:
for i in range(tabela_manual_solteiros.size):
    if tabela_manual_solteiros.iloc[i] - tabela_ocr_solteiros.iloc[i] == 0 and tabela_manual_solteiros.iloc[i] != 0:
        vp += 1
    if tabela_manual_solteiros.iloc[i] - tabela_ocr_solteiros.iloc[i] != 0 and tabela_manual_solteiros.iloc[i] > 0 and tabela_ocr_solteiros.iloc[i] > 0:
        fp += 1
    if tabela_manual_solteiros.iloc[i] - tabela_ocr_solteiros.iloc[i] == 0 and tabela_manual_solteiros.iloc[i] == 0:
        vn += 1
    if tabela_manual_solteiros.iloc[i] > 0 and tabela_ocr_solteiros.iloc[i] == 0:
        fn += 1

print(vp, fp, vn, fn)

20 58 0 10

In [42]:
tabela_manual_casados = pd.to_numeric(df.iloc[3:25, 5])
tabela_ocr_casados = pd.to_numeric(df2.iloc[:, 4])

diferenca_casados = tabela_manual_casados.values - tabela_ocr_casados.values
diferenca_casados

array([    0,  5900, 33644,     0,     0,   -60,     0,     0,    60,
         -60,     0,     0,    55,     0,    60,     0,  -500,     0,
           0,     0,     0, 60066])

In [43]:
for i in range(tabela_manual_casados.size):
    if tabela_manual_casados.iloc[i] - tabela_ocr_casados.iloc[i] == 0 and tabela_manual_casados.iloc[i] != 0:
        vp += 1
    if tabela_manual_casados.iloc[i] - tabela_ocr_casados.iloc[i] != 0 and tabela_manual_casados.iloc[i] > 0 and tabela_ocr_casados.iloc[i] > 0:
        fp += 1
    if tabela_manual_casados.iloc[i] - tabela_ocr_casados.iloc[i] == 0 and tabela_manual_casados.iloc[i] == 0:
        vn += 1
    if tabela_manual_casados.iloc[i] > 0 and tabela_ocr_casados.iloc[i] == 0:
        fn += 1

print(vp, fp, vn, fn)

33 66 0 11

In [44]:
tabela_manual_viuvos = pd.to_numeric(df.iloc[3:25, 6])
tabela_ocr_viuvos = pd.to_numeric(df2.iloc[:, 5])

diferenca_viuvos = tabela_manual_viuvos.values - tabela_ocr_viuvos.values
diferenca_viuvos

array([      0,       0,   -1000,   -5000,       0,       0,       0,
             0,      90,     600, -178205,       0,    4081,   -1000,
             0,     600,       0,    6000,       0,  -21450,       0,
        177387])

In [45]:
for i in range(tabela_manual_viuvos.size):
    if tabela_manual_viuvos.iloc[i] - tabela_ocr_viuvos.iloc[i] == 0 and tabela_manual_viuvos.iloc[i] != 0:
        vp += 1
    if tabela_manual_viuvos.iloc[i] - tabela_ocr_viuvos.iloc[i] != 0 and tabela_manual_viuvos.iloc[i] > 0 and tabela_ocr_viuvos.iloc[i] > 0:
        fp += 1
    if tabela_manual_viuvos.iloc[i] - tabela_ocr_viuvos.iloc[i] == 0 and tabela_manual_viuvos.iloc[i] == 0:
        vn += 1
    if tabela_manual_viuvos.iloc[i] > 0 and tabela_ocr_viuvos.iloc[i] == 0:
        fn += 1

print(vp, fp, vn, fn)

44 75 0 13

In [46]:
tabela_manual_solteiras = pd.to_numeric(df.iloc[3:25, 7])
tabela_ocr_solteiras = pd.to_numeric(df2.iloc[:, 6])

diferenca_solteiras = tabela_manual_solteiras.values - tabela_ocr_solteiras.values
diferenca_solteiras

array([      0,    6000,       0,    9000,       0,     900,     -50,
             0,    9000,   50672,   90200,       0,   60000,      30,
             0,   -1000,       0,       0, -100491,  -10000,    -505,
            79])

In [47]:
for i in range(tabela_manual_solteiras.size):
    if tabela_manual_solteiras.iloc[i] - tabela_ocr_solteiras.iloc[i] == 0 and tabela_manual_solteiras.iloc[i] != 0:
        vp += 1
    if tabela_manual_solteiras.iloc[i] - tabela_ocr_solteiras.iloc[i] != 0 and tabela_manual_solteiras.iloc[i] > 0 and tabela_ocr_solteiras.iloc[i] > 0:
        fp += 1
    if tabela_manual_solteiras.iloc[i] - tabela_ocr_solteiras.iloc[i] == 0 and tabela_manual_solteiras.iloc[i] == 0:
        vn += 1
    if tabela_manual_solteiras.iloc[i] > 0 and tabela_ocr_solteiras.iloc[i] == 0:
        fn += 1

print(vp, fp, vn, fn)

52 89 0 13

In [48]:
tabela_manual_casadas = pd.to_numeric(df.iloc[3:25, 8])
tabela_ocr_casadas = pd.to_numeric(df2.iloc[:, 7])

diferenca_casadas = tabela_manual_casadas.values - tabela_ocr_casadas.values
diferenca_casadas

array([   4714,    6000,    -520,   -6500,      30,    6000,   47950,
        110300,    5995,       0,      -5,     300,       0,       0,
            90,    -500,       0,      -1, -700000,    -500,     900,
             0])

In [49]:
for i in range(tabela_manual_casadas.size):
    if tabela_manual_casadas.iloc[i] - tabela_ocr_casadas.iloc[i] == 0 and tabela_manual_casadas.iloc[i] != 0:
        vp += 1
    if tabela_manual_casadas.iloc[i] - tabela_ocr_casadas.iloc[i] != 0 and tabela_manual_casadas.iloc[i] > 0 and tabela_ocr_casadas.iloc[i] > 0:
        fp += 1
    if tabela_manual_casadas.iloc[i] - tabela_ocr_casadas.iloc[i] == 0 and tabela_manual_casadas.iloc[i] == 0:
        vn += 1
    if tabela_manual_casadas.iloc[i] > 0 and tabela_ocr_casadas.iloc[i] == 0:
        fn += 1

print(vp, fp, vn, fn)

57 105 0 14

In [50]:
tabela_manual_viuvas = pd.to_numeric(df.iloc[3:25, 9])
tabela_ocr_viuvas = pd.to_numeric(df2.iloc[:, 8])

diferenca_viuvas = tabela_manual_viuvas.values - tabela_ocr_viuvas.values
diferenca_viuvas

array([  1720,   6085,   7520,   5187,  14509,   5588,   9661,  19242,
        10169,   3340,  31083,   1171,   7905,  16715,      0,      0,
       -36865,      0,   6928,      0,     -5, 227391])

In [51]:
for i in range(tabela_manual_viuvas.size):
    if tabela_manual_viuvas.iloc[i] - tabela_ocr_viuvas.iloc[i] == 0 and tabela_manual_viuvas.iloc[i] != 0:
        vp += 1
    if tabela_manual_viuvas.iloc[i] - tabela_ocr_viuvas.iloc[i] != 0 and tabela_manual_viuvas.iloc[i] > 0 and tabela_ocr_viuvas.iloc[i] > 0:
        fp += 1
    if tabela_manual_viuvas.iloc[i] - tabela_ocr_viuvas.iloc[i] == 0 and tabela_manual_viuvas.iloc[i] == 0:
        vn += 1
    if tabela_manual_viuvas.iloc[i] > 0 and tabela_ocr_viuvas.iloc[i] == 0:
        fn += 1

print(vp, fp, vn, fn)

61 108 0 29

In [52]:
variancia_solteiros = np.var(diferenca_solteiros)
variancia_solteiros

28203339325.572327

In [53]:
variancia_casados = np.var(diferenca_casados)
variancia_casados

196724285.4318182

In [54]:
variancia_viuvos = np.var(diferenca_viuvos)
variancia_viuvos

2897686170.25

In [55]:
variancia_solteiras = np.var(diferenca_solteiras)
variancia_solteiras

1096054037.307851

In [56]:
variancia_casadas = np.var(diferenca_casadas)
variancia_casadas

22367058955.42355

In [57]:
variancia_viuvas = np.var(diferenca_viuvas)
variancia_viuvas

2281529845.421488

In [58]:
desvio_padrao_solteiros = np.std(diferenca_solteiros)
desvio_padrao_solteiros

167938.49864034253

In [59]:
desvio_padrao_casados = np.std(diferenca_casados)
desvio_padrao_casados

14025.843483791561

In [60]:
desvio_padrao_viuvos = np.std(diferenca_viuvos)
desvio_padrao_viuvos

53830.160414492544

In [61]:
desvio_padrao_solteiras = np.std(diferenca_solteiras)
desvio_padrao_solteiras

33106.706832722746

In [62]:
desvio_padrao_casadas = np.std(diferenca_casadas)
desvio_padrao_casadas

149556.20667636482

In [63]:
desvio_padrao_viuvas = np.std(diferenca_viuvas)
desvio_padrao_viuvas

47765.3624022836

In [64]:
coeficiente_variacao_solteiros = desvio_padrao_solteiros / np.mean(diferenca_solteiros) * 100
coeficiente_variacao_solteiros

-1222.0051299641584

In [65]:
coeficiente_variacao_casados = desvio_padrao_casados / np.mean(diferenca_casados) * 100
coeficiente_variacao_casados

311.1667994185593

In [66]:
coeficiente_variacao_viuvos = desvio_padrao_viuvos / np.mean(diferenca_viuvos) * 100
coeficiente_variacao_viuvos

-6617.106381621701

In [67]:
coeficiente_variacao_solteiras = desvio_padrao_solteiras / np.mean(diferenca_solteiras) * 100
coeficiente_variacao_solteiras

639.8274259409676

In [68]:
coeficiente_variacao_casadas = desvio_padrao_casadas / np.mean(diferenca_casadas) * 100
coeficiente_variacao_casadas

-625.821268952562

In [69]:
coeficiente_variacao_viuvas = desvio_padrao_viuvas / np.mean(diferenca_viuvas) * 100
coeficiente_variacao_viuvas

311.50338314902274

In [70]:
print(f'Variância (solteiros): {variancia_solteiros}')
print(f'Desvio Padrão (solteiros): {desvio_padrao_solteiros}')
print(f'Coeficiente de Variação (solteiros): {coeficiente_variacao_solteiros}%')

Variância (solteiros): 28203339325.572327
Desvio Padrão (solteiros): 167938.49864034253
Coeficiente de Variação (solteiros): -1222.0051299641584%

In [71]:
print(f'Variância (casados): {variancia_casados}')
print(f'Desvio Padrão (casados): {desvio_padrao_casados}')
print(f'Coeficiente de Variação (casados): {coeficiente_variacao_casados}%')

Variância (casados): 196724285.4318182
Desvio Padrão (casados): 14025.843483791561
Coeficiente de Variação (casados): 311.1667994185593%

In [72]:
print(f'Variância (viúvos): {variancia_viuvos}')
print(f'Desvio Padrão (viúvos): {desvio_padrao_viuvos}')
print(f'Coeficiente de Variação (viúvos): {coeficiente_variacao_viuvos}%')

Variância (viúvos): 2897686170.25
Desvio Padrão (viúvos): 53830.160414492544
Coeficiente de Variação (viúvos): -6617.106381621701%

In [73]:
print(f'Variância (solteiras): {variancia_solteiras}')
print(f'Desvio Padrão (solteiras): {desvio_padrao_solteiras}')
print(f'Coeficiente de Variação (solteiras): {coeficiente_variacao_solteiras}%')

Variância (solteiras): 1096054037.307851
Desvio Padrão (solteiras): 33106.706832722746
Coeficiente de Variação (solteiras): 639.8274259409676%

In [74]:
print(f'Variância (casadas): {variancia_casadas}')
print(f'Desvio Padrão (casadas): {desvio_padrao_casadas}')
print(f'Coeficiente de Variação (casadas): {coeficiente_variacao_casadas}%')

Variância (casadas): 22367058955.42355
Desvio Padrão (casadas): 149556.20667636482
Coeficiente de Variação (casadas): -625.821268952562%

In [75]:
print(f'Variância (viúvas): {variancia_viuvas}')
print(f'Desvio Padrão (viúvas): {desvio_padrao_viuvas}')
print(f'Coeficiente de Variação (viúvas): {coeficiente_variacao_viuvas}%')

Variância (viúvas): 2281529845.421488
Desvio Padrão (viúvas): 47765.3624022836
Coeficiente de Variação (viúvas): 311.50338314902274%

In [76]:
media_solteiros = np.mean(diferenca_solteiros)
media_solteiros

-13742.863636363636

In [77]:
media_casados = np.mean(diferenca_casados)
media_casados

4507.5

In [78]:
media_viuvos = np.mean(diferenca_viuvos)
media_viuvos

-813.5

In [79]:
media_solteiras = np.mean(diferenca_solteiras)
media_solteiras

5174.318181818182

In [80]:
media_casadas = np.mean(diferenca_casadas)
media_casadas

-23897.590909090908

In [81]:
media_viuvas = np.mean(diferenca_viuvas)
media_viuvas

15333.818181818182

In [82]:
outlier_inferior_solteiros = media_solteiros - (3 * desvio_padrao_solteiros)
outlier_superior_solteiros = media_solteiros + (3 * desvio_padrao_solteiros)

print(outlier_inferior_solteiros, outlier_superior_solteiros)

-517558.35955739126 490072.63228466397

In [83]:
outlier_inferior_casados = media_casados - (3 * desvio_padrao_casados)
outlier_superior_casados = media_casados + (3 * desvio_padrao_casados)

print(outlier_inferior_casados, outlier_superior_casados)

-37570.03045137468 46585.03045137468

In [84]:
outlier_inferior_viuvos = media_viuvos - (3 * desvio_padrao_viuvos)
outlier_superior_viuvos = media_viuvos + (3 * desvio_padrao_viuvos)

print(outlier_inferior_viuvos, outlier_superior_viuvos)

-162303.98124347764 160676.98124347764

In [85]:
outlier_inferior_solteiras = media_solteiras - (3 * desvio_padrao_solteiras)
outlier_superior_solteiras = media_solteiras + (3 * desvio_padrao_solteiras)

print(outlier_inferior_solteiras, outlier_superior_solteiras)

-94145.80231635006 104494.43867998642

In [86]:
outlier_inferior_casadas = media_casadas - (3 * desvio_padrao_casadas)
outlier_superior_casadas = media_casadas + (3 * desvio_padrao_casadas)

print(outlier_inferior_casadas, outlier_superior_casadas)

-472566.21093818534 424771.0291200036

In [87]:
outlier_inferior_viuvas = media_viuvas - (3 * desvio_padrao_viuvas)
outlier_superior_viuvas = media_viuvas + (3 * desvio_padrao_viuvas)

print(outlier_inferior_viuvas, outlier_superior_viuvas)

-127962.26902503264 158629.905388669

# Raças

In [88]:
racas = df[['Unnamed: 0','Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17']]

columns_multiindex = pd.MultiIndex.from_tuples([
    ('', '', 'Províncias e Município Neutro'),
    ('Raças', 'dos Homens', 'Brancos'),
    ('Raças', 'dos Homens', 'Pardos'),
    ('Raças', 'dos Homens', 'Pretos'),
    ('Raças', 'dos Homens', 'Caboclos'),
    ('Raças', 'das Mulheres', 'Brancas'),
    ('Raças', 'das Mulheres', 'Pardas'),
    ('Raças', 'das Mulheres', 'Pretas'),
    ('Raças', 'das Mulheres', 'Caboclas')
])

racas.columns = columns_multiindex

racas

                                        Raças                             \
                                   dos Homens
    Províncias e Município Neutro     Brancos   Pardos  Pretos  Caboclos
0                             NaN       Raças      NaN     NaN       NaN
1                             NaN  dos Homens      NaN     NaN       NaN
2   Províncias e Município Neutro     Brancos   Pardos  Pretos  Caboclos
3                        Amazonas        6911     4210     711     19151
4                            Pará       49663    46899    9200     22827
5                        Maranhão       52267    71662   12504      5509
6                           Piauí       22208    53474    7505      7135
7                           Ceará      136940   172841   14424     26701
8             Rio Grande do Norte       52835    42213   12202      5471
9                         Paraíba       73475    89921   11155      4882
10                     Pernambuco      149930   194897   30795      5943
11                        Alagoas       45343    98916    8220      3105
12                        Sergipe       24358    39524    9321      1536
13                          Bahia      178605   287131  137574     27043
14                 Espírito Santo       13555     9648    3395      3009
15               Município Neutro       96255    22762   14198       665
16                 Rio de Janeiro      160595    61542   29517      4152
17                      São Paulo      221260    76288   29512     21244
18                         Paraná       35936    15358    3292      4718
19                 Santa Catarina       63502     5941    2199      1446
20              Rio Grande do Sul      136094    24487   17828     12613
21                   Minas Gerais      421861   302948  105507     17276
22                          Goiás       21152    42482    9088      2246
23                    Mato Grosso        9027    10827    3861      4276
24                          Total     1971772  1673971  472008    200948


    das Mulheres
         Brancas   Pardas  Pretas  Caboclas
0            NaN      NaN     NaN       NaN
1   das Mulheres      NaN     NaN       NaN
2        Brancas   Pardas  Pretas  Caboclas
3           4300     3046     625     17677
4          42971    46828    7629     21762
5          51246    72699   12780      5434
6          21239    53191    7357      6318
7         131896   166325   14510     26136
8          49630    41877   11163      5568
9          71246    88675   10661      4685
10        141229   192954   30901      5862
11         43455   101283    8687      3259
12         25420    42059    9851      1551
13        152874   278573  127153     22839
14         13027    10881    3443      2520
15         55544    22083   14268       258
16        142680    59703   28198      3700
17        212172    75018   27027     18221
18         33762    15278    3449      4369
19         62440     5796    2048      1446
20        122273    24179   16444     13104
21        409126   295865  101647     15046
22         20777    43907    8087      2004
23          8210    10087    3214      4248
24       1815517  1650307  449142    186007

In [89]:
print(df.columns)
print(df.iloc[3:25, 10])
print(df2.columns)
print(df2.iloc[:, 9])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        6911
4       49663
5       52267
6       22208
7      136940
8       52835
9       73475
10     149930
11      45343
12      24358
13     178605
14      13555
15      96255
16     160595
17     221260
18      35936
19      63502
20     136094
21     421861
22      21152
23       9027
24    1971772
Name: Unnamed: 10, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0         6
1       663
2     82257
3     29200
4      1300
5         0
6         0
7         0
8         0
9         0
10        0
11        0
12        0
13        0
14        0
15        0
16        0
17        0
18      125
19    21158
20    90271
21        1
Name: 9, dtype: int64

In [90]:
print(df.columns)
print(df.iloc[3:25, 11])
print(df2.columns)
print(df2.iloc[:, 10])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        4210
4       46899
5       71662
6       53474
7      172841
8       42213
9       89921
10     194897
11      98916
12      39524
13     287131
14       9648
15      22762
16      61542
17      76288
18      15358
19       5941
20      24487
21     302948
22      42482
23      10827
24    1673971
Name: Unnamed: 11, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0       4210
1      40899
2       1662
3          0
4     172841
5      42218
6          2
7     194897
8      98916
9      30525
10     98711
11      9646
12      2702
13       142
14     76288
15     15358
16        94
17         0
18    302048
19         4
20     10827
21     73071
Name: 10, dtype: int64

In [91]:
print(df.columns)
print(df.iloc[3:25, 12])
print(df2.columns)
print(df2.iloc[:, 11])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        711
4       9200
5      12504
6       7505
7      14424
8      12202
9      11155
10     30795
11      8220
12      9321
13    137574
14      3395
15     14198
16     29517
17     29512
18      3292
19      2199
20     17828
21    105507
22      9088
23      3861
24    472008
Name: Unnamed: 12, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0          0
1       9200
2      12504
3       7608
4        142
5      12908
6      11155
7      30795
8       8920
9        821
10    183574
11      3305
12         0
13    295171
14         1
15         0
16      2199
17        28
18    105507
19      9088
20      3801
21    472008
Name: 11, dtype: int64

In [92]:
print(df.columns)
print(df.iloc[3:25, 13])
print(df2.columns)
print(df2.iloc[:, 12])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3      19151
4      22827
5       5509
6       7135
7      26701
8       5471
9       4882
10      5943
11      3105
12      1536
13     27043
14      3009
15       665
16      4152
17     21244
18      4718
19      1446
20     12613
21     17276
22      2246
23      4276
24    200948
Name: Unnamed: 13, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0      19151
1      22827
2       5509
3       7135
4      20701
5       6471
6       4882
7       5013
8       8105
9       1536
10     27038
11         0
12       605
13      4152
14      1264
15      4718
16      1446
17     12618
18     17276
19      2246
20      4270
21    200048
Name: 12, dtype: int64

In [93]:
print(df.columns)
print(df.iloc[3:25, 14])
print(df2.columns)
print(df2.iloc[:, 13])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        4300
4       42971
5       51246
6       21239
7      131896
8       49630
9       71246
10     141229
11      43455
12      25420
13     152874
14      13027
15      55544
16     142680
17     212172
18      33762
19      62440
20     122273
21     409126
22      20777
23       8210
24    1815517
Name: Unnamed: 14, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0         4300
1        42971
2        51244
3        21239
4       131899
5            0
6            0
7      1412201
8        43455
9       254201
10      158874
11       18027
12        5544
13      142080
14      212179
15       83762
16       62410
17      122219
18      409120
19        2077
20        8219
21    18155171
Name: 13, dtype: int64

In [94]:
print(df.columns)
print(df.iloc[3:25, 15])
print(df2.columns)
print(df2.iloc[:, 14])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        3046
4       46828
5       72699
6       53191
7      166325
8       41877
9       88675
10     192954
11     101283
12      42059
13     278573
14      10881
15      22083
16      59703
17      75018
18      15278
19       5796
20      24179
21     295865
22      43907
23      10087
24    1650307
Name: Unnamed: 15, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0        8046
1       49828
2       72699
3       58191
4      160325
5       41877
6       88675
7      192054
8      101283
9       42059
10          2
11      10881
12      22083
13        703
14      75018
15      15278
16       5790
17          7
18     208865
19      43907
20      10087
21    1850301
Name: 14, dtype: int64

In [95]:
print(df.columns)
print(df.iloc[3:25, 16])
print(df2.columns)
print(df2.iloc[:, 15])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        625
4       7629
5      12780
6       7357
7      14510
8      11163
9      10661
10     30901
11      8687
12      9851
13    127153
14      3443
15     14268
16     28198
17     27027
18      3449
19      2048
20     16444
21    101647
22      8087
23      3214
24    449142
Name: Unnamed: 16, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0          0
1          0
2          0
3          0
4          0
5          0
6          0
7      80001
8       8687
9          0
10    121153
11       343
12     14248
13     28198
14      2027
15       344
16      2048
17     16414
18    101617
19         0
20      8214
21    449142
Name: 15, dtype: int64

In [96]:
print(df.columns)
print(df.iloc[3:25, 17])
print(df2.columns)
print(df2.iloc[:, 16])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3      17677
4      21762
5       5434
6       6318
7      26136
8       5568
9       4685
10      5862
11      3259
12      1551
13     22839
14      2520
15       258
16      3700
17     18221
18      4369
19      1446
20     13104
21     15046
22      2004
23      4248
24    186007
Name: Unnamed: 17, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0         0
1         0
2         0
3         0
4         0
5         0
6         0
7         0
8         0
9         0
10        0
11        0
12        0
13     8700
14    18221
15     4360
16      146
17    13104
18     5046
19     2004
20        0
21        0
Name: 16, dtype: int64

In [97]:
tabela_manual_brancos = pd.to_numeric(df.iloc[3:25, 10])
tabela_ocr_brancos = pd.to_numeric(df2.iloc[:, 9])

diferenca_brancos = tabela_manual_brancos.values - tabela_ocr_brancos.values
diferenca_brancos

array([   6905,   49000,  -29990,   -6992,  135640,   52835,   73475,
        149930,   45343,   24358,  178605,   13555,   96255,  160595,
        221260,   35936,   63502,  136094,  421736,      -6,  -81244,
       1971771])

In [98]:
for i in range(tabela_manual_brancos.size):
    if tabela_manual_brancos.iloc[i] - tabela_ocr_brancos.iloc[i] == 0 and tabela_manual_brancos.iloc[i] != 0:
        vp += 1
    if tabela_manual_brancos.iloc[i] - tabela_ocr_brancos.iloc[i] != 0 and tabela_manual_brancos.iloc[i] > 0 and tabela_ocr_brancos.iloc[i] > 0:
        fp += 1
    if tabela_manual_brancos.iloc[i] - tabela_ocr_brancos.iloc[i] == 0 and tabela_manual_brancos.iloc[i] == 0:
        vn += 1
    if tabela_manual_brancos.iloc[i] > 0 and tabela_ocr_brancos.iloc[i] == 0:
        fn += 1

print(vp, fp, vn, fn)

61 117 0 42

In [99]:
tabela_manual_pardos = pd.to_numeric(df.iloc[3:25, 11])
tabela_ocr_pardos = pd.to_numeric(df2.iloc[:, 10])

diferenca_pardos = tabela_manual_pardos.values - tabela_ocr_pardos.values
diferenca_pardos

array([      0,    6000,   70000,   53474,       0,      -5,   89919,
             0,       0,    8999,  188420,       2,   20060,   61400,
             0,       0,    5847,   24487,     900,   42478,       0,
       1600900])

In [100]:
for i in range(tabela_manual_pardos.size):
    if tabela_manual_pardos.iloc[i] - tabela_ocr_pardos.iloc[i] == 0 and tabela_manual_pardos.iloc[i] != 0:
        vp += 1
    if tabela_manual_pardos.iloc[i] - tabela_ocr_pardos.iloc[i] != 0 and tabela_manual_pardos.iloc[i] > 0 and tabela_ocr_pardos.iloc[i] > 0:
        fp += 1
    if tabela_manual_pardos.iloc[i] - tabela_ocr_pardos.iloc[i] == 0 and tabela_manual_pardos.iloc[i] == 0:
        vn += 1
    if tabela_manual_pardos.iloc[i] > 0 and tabela_ocr_pardos.iloc[i] == 0:
        fn += 1

print(vp, fp, vn, fn)

68 130 0 44

In [101]:
tabela_manual_pretos = pd.to_numeric(df.iloc[3:25, 12])
tabela_ocr_pretos = pd.to_numeric(df2.iloc[:, 11])

diferenca_pretos = tabela_manual_pretos.values - tabela_ocr_pretos.values
diferenca_pretos

array([    711,       0,       0,    -103,   14282,    -706,       0,
             0,    -700,    8500,  -46000,      90,   14198, -265654,
         29511,    3292,       0,   17800,       0,       0,      60,
             0])

In [102]:
for i in range(tabela_manual_pretos.size):
    if tabela_manual_pretos.iloc[i] - tabela_ocr_pretos.iloc[i] == 0 and tabela_manual_pretos.iloc[i] != 0:
        vp += 1
    if tabela_manual_pretos.iloc[i] - tabela_ocr_pretos.iloc[i] != 0 and tabela_manual_pretos.iloc[i] > 0 and tabela_ocr_pretos.iloc[i] > 0:
        fp += 1
    if tabela_manual_pretos.iloc[i] - tabela_ocr_pretos.iloc[i] == 0 and tabela_manual_pretos.iloc[i] == 0:
        vn += 1
    if tabela_manual_pretos.iloc[i] > 0 and tabela_ocr_pretos.iloc[i] == 0:
        fn += 1

print(vp, fp, vn, fn)

76 141 0 47

In [103]:
tabela_manual_caboclos = pd.to_numeric(df.iloc[3:25, 13])
tabela_ocr_caboclos = pd.to_numeric(df2.iloc[:, 12])

diferenca_caboclos = tabela_manual_caboclos.values - tabela_ocr_caboclos.values
diferenca_caboclos

array([    0,     0,     0,     0,  6000, -1000,     0,   930, -5000,
           0,     5,  3009,    60,     0, 19980,     0,     0,    -5,
           0,     0,     6,   900])

In [104]:
for i in range(tabela_manual_caboclos.size):
    if tabela_manual_caboclos.iloc[i] - tabela_ocr_caboclos.iloc[i] == 0 and tabela_manual_caboclos.iloc[i] != 0:
        vp += 1
    if tabela_manual_caboclos.iloc[i] - tabela_ocr_caboclos.iloc[i] != 0 and tabela_manual_caboclos.iloc[i] > 0 and tabela_ocr_caboclos.iloc[i] > 0:
        fp += 1
    if tabela_manual_caboclos.iloc[i] - tabela_ocr_caboclos.iloc[i] == 0 and tabela_manual_caboclos.iloc[i] == 0:
        vn += 1
    if tabela_manual_caboclos.iloc[i] > 0 and tabela_ocr_caboclos.iloc[i] == 0:
        fn += 1

print(vp, fp, vn, fn)

87 151 0 48

In [105]:
tabela_manual_brancas = pd.to_numeric(df.iloc[3:25, 14])
tabela_ocr_brancas = pd.to_numeric(df2.iloc[:, 13])

diferenca_brancas = tabela_manual_brancas.values - tabela_ocr_brancas.values
diferenca_brancas

array([        0,         0,         2,         0,        -3,     49630,
           71246,  -1270972,         0,   -228781,     -6000,     -5000,
           50000,       600,        -7,    -50000,        30,        54,
               6,     18700,        -9, -16339654])

In [106]:
for i in range(tabela_manual_brancas.size):
    if tabela_manual_brancas.iloc[i] - tabela_ocr_brancas.iloc[i] == 0 and tabela_manual_brancas.iloc[i] != 0:
        vp += 1
    if tabela_manual_brancas.iloc[i] - tabela_ocr_brancas.iloc[i] != 0 and tabela_manual_brancas.iloc[i] > 0 and tabela_ocr_brancas.iloc[i] > 0:
        fp += 1
    if tabela_manual_brancas.iloc[i] - tabela_ocr_brancas.iloc[i] == 0 and tabela_manual_brancas.iloc[i] == 0:
        vn += 1
    if tabela_manual_brancas.iloc[i] > 0 and tabela_ocr_brancas.iloc[i] == 0:
        fn += 1

print(vp, fp, vn, fn)

91 167 0 50

In [107]:
tabela_manual_pardas = pd.to_numeric(df.iloc[3:25, 15])
tabela_ocr_pardas = pd.to_numeric(df2.iloc[:, 14])

diferenca_pardas = tabela_manual_pardas.values - tabela_ocr_pardas.values
diferenca_pardas

array([  -5000,   -3000,       0,   -5000,    6000,       0,       0,
           900,       0,       0,  278571,       0,       0,   59000,
             0,       0,       6,   24172,   87000,       0,       0,
       -199994])

In [108]:
for i in range(tabela_manual_pardas.size):
    if tabela_manual_pardas.iloc[i] - tabela_ocr_pardas.iloc[i] == 0 and tabela_manual_pardas.iloc[i] != 0:
        vp += 1
    if tabela_manual_pardas.iloc[i] - tabela_ocr_pardas.iloc[i] != 0 and tabela_manual_pardas.iloc[i] > 0 and tabela_ocr_pardas.iloc[i] > 0:
        fp += 1
    if tabela_manual_pardas.iloc[i] - tabela_ocr_pardas.iloc[i] == 0 and tabela_manual_pardas.iloc[i] == 0:
        vn += 1
    if tabela_manual_pardas.iloc[i] > 0 and tabela_ocr_pardas.iloc[i] == 0:
        fn += 1

print(vp, fp, vn, fn)

102 178 0 50

In [109]:
tabela_manual_pretas = pd.to_numeric(df.iloc[3:25, 16])
tabela_ocr_pretas = pd.to_numeric(df2.iloc[:, 15])

diferenca_pretas = tabela_manual_pretas.values - tabela_ocr_pretas.values
diferenca_pretas

array([   625,   7629,  12780,   7357,  14510,  11163,  10661, -49100,
            0,   9851,   6000,   3100,     20,      0,  25000,   3105,
            0,     30,     30,   8087,  -5000,      0])

In [110]:
for i in range(tabela_manual_pretas.size):
    if tabela_manual_pretas.iloc[i] - tabela_ocr_pretas.iloc[i] == 0 and tabela_manual_pretas.iloc[i] != 0:
        vp += 1
    if tabela_manual_pretas.iloc[i] - tabela_ocr_pretas.iloc[i] != 0 and tabela_manual_pretas.iloc[i] > 0 and tabela_ocr_pretas.iloc[i] > 0:
        fp += 1
    if tabela_manual_pretas.iloc[i] - tabela_ocr_pretas.iloc[i] == 0 and tabela_manual_pretas.iloc[i] == 0:
        vn += 1
    if tabela_manual_pretas.iloc[i] > 0 and tabela_ocr_pretas.iloc[i] == 0:
        fn += 1

print(vp, fp, vn, fn)

106 187 0 59

In [111]:
tabela_manual_caboclas = pd.to_numeric(df.iloc[3:25, 17])
tabela_ocr_caboclas = pd.to_numeric(df2.iloc[:, 16])

diferenca_caboclas = tabela_manual_caboclas.values - tabela_ocr_caboclas.values
diferenca_caboclas

array([ 17677,  21762,   5434,   6318,  26136,   5568,   4685,   5862,
         3259,   1551,  22839,   2520,    258,  -5000,      0,      9,
         1300,      0,  10000,      0,   4248, 186007])

In [112]:
for i in range(tabela_manual_caboclas.size):
    if tabela_manual_caboclas.iloc[i] - tabela_ocr_caboclas.iloc[i] == 0 and tabela_manual_caboclas.iloc[i] != 0:
        vp += 1
    if tabela_manual_caboclas.iloc[i] - tabela_ocr_caboclas.iloc[i] != 0 and tabela_manual_caboclas.iloc[i] > 0 and tabela_ocr_caboclas.iloc[i] > 0:
        fp += 1
    if tabela_manual_caboclas.iloc[i] - tabela_ocr_caboclas.iloc[i] == 0 and tabela_manual_caboclas.iloc[i] == 0:
        vn += 1
    if tabela_manual_caboclas.iloc[i] > 0 and tabela_ocr_caboclas.iloc[i] == 0:
        fn += 1

print(vp, fp, vn, fn)

109 191 0 74

In [113]:
variancia_brancos = np.var(diferenca_brancos)
variancia_brancos

165402942331.33264

In [114]:
variancia_pardos = np.var(diferenca_pardos)
variancia_pardos

109379386783.21695

In [115]:
variancia_pretos = np.var(diferenca_pretos)
variancia_pretos

3275934403.159091

In [116]:
variancia_caboclos = np.var(diferenca_caboclos)
variancia_caboclos

20172033.572314043

In [117]:
variancia_brancas = np.var(diferenca_brancas)
variancia_brancas

11564006782397.148

In [118]:
variancia_pardas = np.var(diferenca_pardas)
variancia_pardas

5756957645.266528

In [119]:
variancia_pretas = np.var(diferenca_pretas)
variancia_pretas

173012347.71900824

In [120]:
variancia_caboclas = np.var(diferenca_caboclas)
variancia_caboclas

1465598395.5723143

In [121]:
desvio_padrao_brancos = np.std(diferenca_brancos)
desvio_padrao_brancos

406697.6055146288

In [122]:
desvio_padrao_pardos = np.std(diferenca_pardos)
desvio_padrao_pardos

330725.5460094018

In [123]:
desvio_padrao_pretos = np.std(diferenca_pretos)
desvio_padrao_pretos

57235.77904736766

In [124]:
desvio_padrao_caboclos = np.std(diferenca_caboclos)
desvio_padrao_caboclos

4491.328709002943

In [125]:
desvio_padrao_brancas = np.std(diferenca_brancas)
desvio_padrao_brancas

3400589.181656195

In [126]:
desvio_padrao_pardas = np.std(diferenca_pardas)
desvio_padrao_pardas

75874.61792501184

In [127]:
desvio_padrao_pretas = np.std(diferenca_pretas)
desvio_padrao_pretas

13153.415819436723

In [128]:
desvio_padrao_caboclas = np.std(diferenca_caboclas)
desvio_padrao_caboclas

38283.134610064444

In [129]:
coeficiente_variacao_brancos = desvio_padrao_brancos / np.mean(diferenca_brancos) * 100
coeficiente_variacao_brancos

240.61303577004972

In [130]:
coeficiente_variacao_pardos = desvio_padrao_pardos / np.mean(diferenca_pardos) * 100
coeficiente_variacao_pardos

334.8532207795475

In [131]:
coeficiente_variacao_pretos = desvio_padrao_pretos / np.mean(diferenca_pretos) * 100
coeficiente_variacao_pretos

-560.3385290260675

In [132]:
coeficiente_variacao_caboclos = desvio_padrao_caboclos / np.mean(diferenca_caboclos) * 100
coeficiente_variacao_caboclos

397.06341811559065

In [133]:
coeficiente_variacao_brancas = desvio_padrao_brancas / np.mean(diferenca_brancas) * 100
coeficiente_variacao_brancas

-422.42967000314894

In [134]:
coeficiente_variacao_pardas = desvio_padrao_pardas / np.mean(diferenca_pardas) * 100
coeficiente_variacao_pardas

687.9073558551278

In [135]:
coeficiente_variacao_pretas = desvio_padrao_pretas / np.mean(diferenca_pretas) * 100
coeficiente_variacao_pretas

439.4592820246749

In [136]:
coeficiente_variacao_caboclas = desvio_padrao_caboclas / np.mean(diferenca_caboclas) * 100
coeficiente_variacao_caboclas

262.8408938596892

In [137]:
print(f'Variância (brancos): {variancia_brancos}')
print(f'Desvio Padrão (brancos): {desvio_padrao_brancos}')
print(f'Coeficiente de Variação (brancos): {coeficiente_variacao_brancos}%')

Variância (brancos): 165402942331.33264
Desvio Padrão (brancos): 406697.6055146288
Coeficiente de Variação (brancos): 240.61303577004972%

In [138]:
print(f'Variância (pardos): {variancia_pardos}')
print(f'Desvio Padrão (pardos): {desvio_padrao_pardos}')
print(f'Coeficiente de Variação (pardos): {coeficiente_variacao_pardos}%')

Variância (pardos): 109379386783.21695
Desvio Padrão (pardos): 330725.5460094018
Coeficiente de Variação (pardos): 334.8532207795475%

In [139]:
print(f'Variância (pretos): {variancia_pretos}')
print(f'Desvio Padrão (pretos): {desvio_padrao_pretos}')
print(f'Coeficiente de Variação (pretos): {coeficiente_variacao_pretos}%')

Variância (pretos): 3275934403.159091
Desvio Padrão (pretos): 57235.77904736766
Coeficiente de Variação (pretos): -560.3385290260675%

In [140]:
print(f'Variância (caboclos): {variancia_caboclos}')
print(f'Desvio Padrão (caboclos): {desvio_padrao_caboclos}')
print(f'Coeficiente de Variação (caboclos): {coeficiente_variacao_caboclos}%')

Variância (caboclos): 20172033.572314043
Desvio Padrão (caboclos): 4491.328709002943
Coeficiente de Variação (caboclos): 397.06341811559065%

In [141]:
print(f'Variância (brancas): {variancia_brancas}')
print(f'Desvio Padrão (brancas): {desvio_padrao_brancas}')
print(f'Coeficiente de Variação (brancas): {coeficiente_variacao_brancas}%')

Variância (brancas): 11564006782397.148
Desvio Padrão (brancas): 3400589.181656195
Coeficiente de Variação (brancas): -422.42967000314894%

In [142]:
print(f'Variância (pardas): {variancia_pardas}')
print(f'Desvio Padrão (pardas): {desvio_padrao_pardas}')
print(f'Coeficiente de Variação (pardas): {coeficiente_variacao_pardas}%')

Variância (pardas): 5756957645.266528
Desvio Padrão (pardas): 75874.61792501184
Coeficiente de Variação (pardas): 687.9073558551278%

In [143]:
print(f'Variância (pretas): {variancia_pretas}')
print(f'Desvio Padrão (pretas): {desvio_padrao_pretas}')
print(f'Coeficiente de Variação (pretas): {coeficiente_variacao_pretas}%')

Variância (pretas): 173012347.71900824
Desvio Padrão (pretas): 13153.415819436723
Coeficiente de Variação (pretas): 439.4592820246749%

In [144]:
print(f'Variância (caboclas): {variancia_caboclas}')
print(f'Desvio Padrão (caboclas): {desvio_padrao_caboclas}')
print(f'Coeficiente de Variação (caboclas): {coeficiente_variacao_caboclas}%')

Variância (caboclas): 1465598395.5723143
Desvio Padrão (caboclas): 38283.134610064444
Coeficiente de Variação (caboclas): 262.8408938596892%

In [145]:
media_brancos = np.mean(diferenca_brancos)
media_brancos

169025.5909090909

In [146]:
media_pardos = np.mean(diferenca_pardos)
media_pardos

98767.31818181818

In [147]:
media_pretos = np.mean(diferenca_pretos)
media_pretos

-10214.5

In [148]:
media_caboclos = np.mean(diferenca_caboclos)
media_caboclos

1131.1363636363637

In [149]:
media_brancas = np.mean(diferenca_brancas)
media_brancas

-805007.1818181818

In [150]:
media_pardas = np.mean(diferenca_pardas)
media_pardas

11029.772727272728

In [151]:
media_pretas = np.mean(diferenca_pretas)
media_pretas

2993.090909090909

In [152]:
media_caboclas = np.mean(diferenca_caboclas)
media_caboclas

14565.136363636364

In [153]:
outlier_inferior_brancos = media_brancos - (3 * desvio_padrao_brancos)
outlier_superior_brancos = media_brancos + (3 * desvio_padrao_brancos)

print(outlier_inferior_brancos, outlier_superior_brancos)

-1051067.2256347956 1389118.4074529773

In [154]:
outlier_inferior_pardos = media_pardos - (3 * desvio_padrao_pardos)
outlier_superior_pardos = media_pardos + (3 * desvio_padrao_pardos)

print(outlier_inferior_pardos, outlier_superior_pardos)

-893409.3198463873 1090943.9562100235

In [155]:
outlier_inferior_pretos = media_pretos - (3 * desvio_padrao_pretos)
outlier_superior_pretos = media_pretos + (3 * desvio_padrao_pretos)

print(outlier_inferior_pretos, outlier_superior_pretos)

-181921.83714210297 161492.83714210297

In [156]:
outlier_inferior_caboclos = media_caboclos - (3 * desvio_padrao_caboclos)
outlier_superior_caboclos = media_caboclos + (3 * desvio_padrao_caboclos)

print(outlier_inferior_caboclos, outlier_superior_caboclos)

-12342.849763372464 14605.122490645192

In [157]:
outlier_inferior_brancas = media_brancas - (3 * desvio_padrao_brancas)
outlier_superior_brancas = media_brancas + (3 * desvio_padrao_brancas)

print(outlier_inferior_brancas, outlier_superior_brancas)

-11006774.726786766 9396760.363150403

In [158]:
outlier_inferior_pardas = media_pardas - (3 * desvio_padrao_pardas)
outlier_superior_pardas = media_pardas + (3 * desvio_padrao_pardas)

print(outlier_inferior_pardas, outlier_superior_pardas)

-216594.0810477628 238653.62650230827

In [159]:
outlier_inferior_pretas = media_pretas - (3 * desvio_padrao_pretas)
outlier_superior_pretas = media_pretas + (3 * desvio_padrao_pretas)

print(outlier_inferior_pretas, outlier_superior_pretas)

-36467.15654921926 42453.338367401084

In [160]:
outlier_inferior_caboclas = media_caboclas - (3 * desvio_padrao_caboclas)
outlier_superior_caboclas = media_caboclas + (3 * desvio_padrao_caboclas)

print(outlier_inferior_caboclas, outlier_superior_caboclas)

-100284.26746655696 129414.5401938297

# Religião

In [161]:
religiao = df[['Unnamed: 0','Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21']]

religiao_header = religiao.iloc[2]
religiao.columns = religiao_header
religiao = religiao[3:]

columns_multiindex = pd.MultiIndex.from_tuples([
    ('', '', 'Províncias e Município Neutro'),
    ('Religião', 'dos Homens', 'Católicos'),
    ('Religião', 'dos Homens', 'Acatólicos'),
    ('Religião', 'das Mulheres', 'Católicas'),
    ('Religião', 'das Mulheres', 'Acatólicas')
])

religiao.columns = columns_multiindex

religiao

                                   Religião
                                 dos Homens            das Mulheres
   Províncias e Município Neutro  Católicos Acatólicos    Católicas Acatólicas
3                       Amazonas      30903         80        25641          7
4                           Pará     128396        193       119169         21
5                       Maranhão     141865         77       142100         59
6                          Piauí      90313          9        88105          0
7                          Ceará     350868         38       338857         10
8            Rio Grande do Norte     112717          4       108238          0
9                        Paraíba     179429          4       175266          1
10                    Pernambuco     381361        204       370906         40
11                       Alagoas     155557         27       156683          1
12                       Sergipe      74739          0        78881          0
13                         Bahia     630196        157       581384         55
14                Espírito Santo      29377        230        29687        184
15              Município Neutro     132552       1328        91553        600
16                Rio de Janeiro     255433        373       234066        215
17                     São Paulo     346326       1973       331217       1221
18                        Paraná      58755        549        56594        264
19                Santa Catarina      67635       5453        66742       4988
20             Rio Grande do Sul     187182       3840       173617       2383
21                  Minas Gerais     845840       1752       820290       1394
22                         Goiás      74967          1        74775          0
23                   Mato Grosso      27975         16        25749         10
24                         Total    4302386      16313      4089520      11453

In [162]:
print(df.columns)
print(df.iloc[3:25, 18])
print(df2.columns)
print(df2.iloc[:, 17])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       30903
4      128396
5      141865
6       90313
7      350868
8      112717
9      179429
10     381361
11     155557
12      74739
13     630196
14      29377
15     132552
16     255433
17     346326
18      58755
19      67635
20     187182
21     845840
22      74967
23      27975
24    4302386
Name: Unnamed: 18, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0        908
1     128396
2     141865
3      90813
4     850868
5        717
6     179429
7     381861
8     155557
9          0
10    680196
11     29377
12    182552
13    255488
14    316326
15     58765
16     67685
17    187182
18    845840
19        77
20         0
21    301380
Name: 17, dtype: int64

In [163]:
print(df.columns)
print(df.iloc[3:25, 19])
print(df2.columns)
print(df2.iloc[:, 18])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        80
4       193
5        77
6         9
7        38
8         4
9         4
10      204
11       27
12        0
13      157
14      230
15     1328
16      373
17     1973
18      549
19     5453
20     3840
21     1752
22        1
23       16
24    16313
Name: Unnamed: 19, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0       80
1      198
2        0
3        9
4       38
5        0
6        4
7      204
8        7
9        0
10     157
11     280
12    1928
13       8
14    1074
15       0
16       5
17    3810
18       1
19       0
20       0
21       0
Name: 18, dtype: int64

In [164]:
print(df.columns)
print(df.iloc[3:25, 20])
print(df2.columns)
print(df2.iloc[:, 19])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       25641
4      119169
5      142100
6       88105
7      338857
8      108238
9      175266
10     370906
11     156683
12      78881
13     581384
14      29687
15      91553
16     234066
17     331217
18      56594
19      66742
20     173617
21     820290
22      74775
23      25749
24    4089520
Name: Unnamed: 20, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0       25041
1      119169
2      142100
3       88105
4      838857
5      108288
6      176200
7      370906
8      150083
9        8881
10          0
11      42987
12          1
13          0
14          0
15          0
16          1
17      17017
18       2020
19          0
20      25749
21    4080620
Name: 19, dtype: int64

In [165]:
print(df.columns)
print(df.iloc[3:25, 21])
print(df2.columns)
print(df2.iloc[:, 20])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3         7
4        21
5        59
6         0
7        10
8         0
9         1
10       40
11        1
12        0
13       55
14      184
15      600
16      215
17     1221
18      264
19     4988
20     2383
21     1394
22        0
23       10
24    11453
Name: Unnamed: 21, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0         7
1        21
2         6
3         0
4        10
5         0
6         0
7        40
8         1
9         0
10        0
11      184
12        0
13      215
14       12
15        0
16     4988
17     2388
18     1894
19        0
20       10
21    11453
Name: 20, dtype: int64

In [166]:
tabela_manual_catolicos = pd.to_numeric(df.iloc[3:25, 18])
tabela_ocr_catolicos = pd.to_numeric(df2.iloc[:, 17])

diferenca_catolicos = tabela_manual_catolicos.values - tabela_ocr_catolicos.values
diferenca_catolicos

array([  29995,       0,       0,    -500, -500000,  112000,       0,
          -500,       0,   74739,  -50000,       0,  -50000,     -55,
         30000,     -10,     -50,       0,       0,   74890,   27975,
       4001006])

In [167]:
for i in range(tabela_manual_catolicos.size):
    if tabela_manual_catolicos.iloc[i] - tabela_ocr_catolicos.iloc[i] == 0 and tabela_manual_catolicos.iloc[i] != 0:
        vp += 1
    if tabela_manual_catolicos.iloc[i] - tabela_ocr_catolicos.iloc[i] != 0 and tabela_manual_catolicos.iloc[i] > 0 and tabela_ocr_catolicos.iloc[i] > 0:
        fp += 1
    if tabela_manual_catolicos.iloc[i] - tabela_ocr_catolicos.iloc[i] == 0 and tabela_manual_catolicos.iloc[i] == 0:
        vn += 1
    if tabela_manual_catolicos.iloc[i] > 0 and tabela_ocr_catolicos.iloc[i] == 0:
        fn += 1

print(vp, fp, vn, fn)

116 204 0 76

In [168]:
tabela_manual_acatolicos = pd.to_numeric(df.iloc[3:25, 19])
tabela_ocr_acatolicos = pd.to_numeric(df2.iloc[:, 18])

diferenca_acatolicos = tabela_manual_acatolicos.values - tabela_ocr_acatolicos.values
diferenca_acatolicos

array([    0,    -5,    77,     0,     0,     4,     0,     0,    20,
           0,     0,   -50,  -600,   365,   899,   549,  5448,    30,
        1751,     1,    16, 16313])

In [169]:
for i in range(tabela_manual_acatolicos.size):
    if tabela_manual_acatolicos.iloc[i] - tabela_ocr_acatolicos.iloc[i] == 0 and tabela_manual_acatolicos.iloc[i] != 0:
        vp += 1
    if tabela_manual_acatolicos.iloc[i] - tabela_ocr_acatolicos.iloc[i] != 0 and tabela_manual_acatolicos.iloc[i] > 0 and tabela_ocr_acatolicos.iloc[i] > 0:
        fp += 1
    if tabela_manual_acatolicos.iloc[i] - tabela_ocr_acatolicos.iloc[i] == 0 and tabela_manual_acatolicos.iloc[i] == 0:
        vn += 1
    if tabela_manual_acatolicos.iloc[i] > 0 and tabela_ocr_acatolicos.iloc[i] == 0:
        fn += 1

print(vp, fp, vn, fn)

122 213 1 82

In [170]:
tabela_manual_catolicas = pd.to_numeric(df.iloc[3:25, 20])
tabela_ocr_catolicas = pd.to_numeric(df2.iloc[:, 19])

diferenca_catolicas = tabela_manual_catolicas.values - tabela_ocr_catolicas.values
diferenca_catolicas

array([    600,       0,       0,       0, -500000,     -50,    -934,
             0,    6600,   70000,  581384,  -13300,   91552,  234066,
        331217,   56594,   66741,  156600,  818270,   74775,       0,
          8900])

In [171]:
for i in range(tabela_manual_catolicas.size):
    if tabela_manual_catolicas.iloc[i] - tabela_ocr_catolicas.iloc[i] == 0 and tabela_manual_catolicas.iloc[i] != 0:
        vp += 1
    if tabela_manual_catolicas.iloc[i] - tabela_ocr_catolicas.iloc[i] != 0 and tabela_manual_catolicas.iloc[i] > 0 and tabela_ocr_catolicas.iloc[i] > 0:
        fp += 1
    if tabela_manual_catolicas.iloc[i] - tabela_ocr_catolicas.iloc[i] == 0 and tabela_manual_catolicas.iloc[i] == 0:
        vn += 1
    if tabela_manual_catolicas.iloc[i] > 0 and tabela_ocr_catolicas.iloc[i] == 0:
        fn += 1

print(vp, fp, vn, fn)

127 225 1 87

In [172]:
tabela_manual_acatolicas = pd.to_numeric(df.iloc[3:25, 21])
tabela_ocr_acatolicas = pd.to_numeric(df2.iloc[:, 20])

diferenca_acatolicas = tabela_manual_acatolicas.values - tabela_ocr_acatolicas.values
diferenca_acatolicas

array([   0,    0,   53,    0,    0,    0,    1,    0,    0,    0,   55,
          0,  600,    0, 1209,  264,    0,   -5, -500,    0,    0,    0])

In [173]:
for i in range(tabela_manual_acatolicas.size):
    if tabela_manual_acatolicas.iloc[i] - tabela_ocr_acatolicas.iloc[i] == 0 and tabela_manual_acatolicas.iloc[i] != 0:
        vp += 1
    if tabela_manual_acatolicas.iloc[i] - tabela_ocr_acatolicas.iloc[i] != 0 and tabela_manual_acatolicas.iloc[i] > 0 and tabela_ocr_acatolicas.iloc[i] > 0:
        fp += 1
    if tabela_manual_acatolicas.iloc[i] - tabela_ocr_acatolicas.iloc[i] == 0 and tabela_manual_acatolicas.iloc[i] == 0:
        vn += 1
    if tabela_manual_acatolicas.iloc[i] > 0 and tabela_ocr_acatolicas.iloc[i] == 0:
        fn += 1

print(vp, fp, vn, fn)

137 229 5 91

In [174]:
variancia_catolicos = np.var(diferenca_catolicos)
variancia_catolicos

711379070676.8677

In [175]:
variancia_acatolicos = np.var(diferenca_acatolicos)
variancia_acatolicos

12385298.537190085

In [176]:
variancia_catolicas = np.var(diferenca_catolicas)
variancia_catolicas

58848927032.31612

In [177]:
variancia_acatolicas = np.var(diferenca_acatolicas)
variancia_acatolicas

91791.08471074379

In [178]:
desvio_padrao_catolicos = np.std(diferenca_catolicos)
desvio_padrao_catolicos

843432.908224992

In [179]:
desvio_padrao_acatolicos = np.std(diferenca_acatolicos)
desvio_padrao_acatolicos

3519.275285792529

In [180]:
desvio_padrao_catolicas = np.std(diferenca_catolicas)
desvio_padrao_catolicas

242587.97792206463

In [181]:
desvio_padrao_acatolicas = np.std(diferenca_acatolicas)
desvio_padrao_acatolicas

302.9704353740539

In [182]:
coeficiente_variacao_catolicos = desvio_padrao_catolicos / np.mean(diferenca_catolicos) * 100
coeficiente_variacao_catolicos

494.88127667895697

In [183]:
coeficiente_variacao_acatolicos = desvio_padrao_acatolicos / np.mean(diferenca_acatolicos) * 100
coeficiente_variacao_acatolicos

311.96734743909917

In [184]:
coeficiente_variacao_catolicas = desvio_padrao_catolicas / np.mean(diferenca_catolicas) * 100
coeficiente_variacao_catolicas

269.1323824724181

In [185]:
coeficiente_variacao_acatolicas = desvio_padrao_acatolicas / np.mean(diferenca_acatolicas) * 100
coeficiente_variacao_acatolicas

397.45674288784653

In [186]:
print(f'Variância (católicos): {variancia_catolicos}')
print(f'Desvio Padrão (católicos): {desvio_padrao_catolicos}')
print(f'Coeficiente de Variação (católicos): {coeficiente_variacao_catolicos}%')

Variância (católicos): 711379070676.8677
Desvio Padrão (católicos): 843432.908224992
Coeficiente de Variação (católicos): 494.88127667895697%

In [187]:
print(f'Variância (acatólicos): {variancia_acatolicos}')
print(f'Desvio Padrão (acatólicos): {desvio_padrao_acatolicos}')
print(f'Coeficiente de Variação (acatólicos): {coeficiente_variacao_acatolicos}%')

Variância (acatólicos): 12385298.537190085
Desvio Padrão (acatólicos): 3519.275285792529
Coeficiente de Variação (acatólicos): 311.96734743909917%

In [188]:
print(f'Variância (católicas): {variancia_catolicas}')
print(f'Desvio Padrão (católicas): {desvio_padrao_catolicas}')
print(f'Coeficiente de Variação (católicas): {coeficiente_variacao_catolicas}%')

Variância (católicas): 58848927032.31612
Desvio Padrão (católicas): 242587.97792206463
Coeficiente de Variação (católicas): 269.1323824724181%

In [189]:
print(f'Variância (acatólicas): {variancia_acatolicas}')
print(f'Desvio Padrão (acatólicas): {desvio_padrao_acatolicas}')
print(f'Coeficiente de Variação (acatólicas): {coeficiente_variacao_acatolicas}%')

Variância (acatólicas): 91791.08471074379
Desvio Padrão (acatólicas): 302.9704353740539
Coeficiente de Variação (acatólicas): 397.45674288784653%

In [190]:
media_catolicos = np.mean(diferenca_catolicos)
media_catolicos

170431.36363636365

In [191]:
media_acatolicos = np.mean(diferenca_acatolicos)
media_acatolicos

1128.090909090909

In [192]:
media_catolicas = np.mean(diferenca_catolicas)
media_catolicas

90137.04545454546

In [193]:
media_acatolicas = np.mean(diferenca_acatolicas)
media_acatolicas

76.22727272727273

In [194]:
outlier_inferior_catolicos = media_catolicos - (3 * desvio_padrao_catolicos)
outlier_superior_catolicos = media_catolicos + (3 * desvio_padrao_catolicos)

print(outlier_inferior_catolicos, outlier_superior_catolicos)

-2359867.361038612 2700730.0883113397

In [195]:
outlier_inferior_acatolicos = media_acatolicos - (3 * desvio_padrao_acatolicos)
outlier_superior_acatolicos = media_acatolicos + (3 * desvio_padrao_acatolicos)

print(outlier_inferior_acatolicos, outlier_superior_acatolicos)

-9429.734948286678 11685.916766468494

In [196]:
outlier_inferior_catolicas = media_catolicas - (3 * desvio_padrao_catolicas)
outlier_superior_catolicas = media_catolicas + (3 * desvio_padrao_catolicas)

print(outlier_inferior_catolicas, outlier_superior_catolicas)

-637626.8883116485 817900.9792207393

In [197]:
outlier_inferior_acatolicas = media_acatolicas - (3 * desvio_padrao_acatolicas)
outlier_superior_acatolicas = media_acatolicas + (3 * desvio_padrao_acatolicas)

print(outlier_inferior_acatolicas, outlier_superior_acatolicas)

-832.684033394889 985.1385788494345

# Nacionalidades

In [198]:
nacionalidade = df[['Unnamed: 0','Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25']]

nacionalidade_header = nacionalidade.iloc[2]
nacionalidade.columns = nacionalidade_header
nacionalidade = nacionalidade[3:]

columns_multiindex = pd.MultiIndex.from_tuples([
    ('', '', 'Províncias e Município Neutro'),
    ('Nacionalidades', 'dos Homens', 'Brasileiros'),
    ('Nacionalidades', 'dos Homens', 'Estrangeiros'),
    ('Nacionalidades', 'das Mulheres', 'Brasileiras'),
    ('Nacionalidades', 'das Mulheres', 'Estrangeiras')
])

nacionalidade.columns = columns_multiindex

nacionalidade

                                 Nacionalidades                            \
                                     dos Homens              das Mulheres
   Províncias e Município Neutro    Brasileiros Estrangeiros  Brasileiras
3                       Amazonas          29223         1760        25222
4                           Pará         123365         5224       118437
5                       Maranhão         139413         2529       141191
6                          Piauí          90022          300        88001
7                          Ceará         349805         1101       338475
8            Rio Grande do Norte         112305          416       108078
9                        Paraíba         178940          493       175102
10                    Pernambuco         373530         8035       368621
11                       Alagoas         154606          978       156321
12                       Sergipe          74352          387        78723
13                         Bahia         622447         7906       577229
14                Espírito Santo          28190         1417        29359
15              Município Neutro          77872        56008        74851
16                Rio de Janeiro         225843        29963       225860
17                     São Paulo         336473        11831       327702
18                        Paraná          57224         2080        56049
19                Santa Catarina          64731         8357        65241
20             Rio Grande do Sul         166042        24980       164522
21                  Minas Gerais         833175        14417       817692
22                         Goiás          74818          150        74698
23                   Mato Grosso          26986         1005        25455
24                         Total        4139362       179337      4036829



   Estrangeiras
3           426
4           753
5           968
6           104
7           392
8           160
9           165
10         2325
11          363
12          158
13         4210
14          512
15        17302
16         8421
17         4736
18          809
19         6489
20        11478
21         3992
22           77
23          304
24        64144

In [199]:
print(df.columns)
print(df.iloc[3:25, 22])
print(df2.columns)
print(df2.iloc[:, 21])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       29223
4      123365
5      139413
6       90022
7      349805
8      112305
9      178940
10     373530
11     154606
12      74352
13     622447
14      28190
15      77872
16     225843
17     336473
18      57224
19      64731
20     166042
21     833175
22      74818
23      26986
24    4139362
Name: Unnamed: 22, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0       29228
1      122366
2      189413
3       90022
4      349805
5      112805
6       78940
7      373540
8      154006
9           0
10       2471
11      28190
12          0
13     225843
14     336173
15        572
16       4731
17     166012
18     838175
19      74818
20      28986
21    4139362
Name: 21, dtype: int64

In [200]:
print(df.columns)
print(df.iloc[3:25, 23])
print(df2.columns)
print(df2.iloc[:, 22])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       1760
4       5224
5       2529
6        300
7       1101
8        416
9        493
10      8035
11       978
12       387
13      7906
14      1417
15     56008
16     29963
17     11831
18      2080
19      8357
20     24980
21     14417
22       150
23      1005
24    179337
Name: Unnamed: 23, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0      1760
1         0
2      2598
3         0
4      1107
5       410
6       443
7      8035
8       978
9         0
10      906
11        7
12    50008
13    20063
14    11831
15     2080
16        3
17    24980
18     1417
19      160
20     1005
21      177
Name: 22, dtype: int64

In [201]:
print(df.columns)
print(df.iloc[3:25, 24])
print(df2.columns)
print(df2.iloc[:, 23])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       25222
4      118437
5      141191
6       88001
7      338475
8      108078
9      175102
10     368621
11     156321
12      78723
13     577229
14      29359
15      74851
16     225860
17     327702
18      56049
19      65241
20     164522
21     817692
22      74698
23      25455
24    4036829
Name: Unnamed: 24, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0         200
1      113437
2       11191
3       88001
4           0
5      108078
6     1751092
7           0
8      166321
9       78723
10     877229
11          0
12          0
13        225
14      27102
15       5019
16        524
17     164534
18          0
19          0
20      25155
21          0
Name: 23, dtype: int64

In [202]:
print(df.columns)
print(df.iloc[3:25, 25])
print(df2.columns)
print(df2.iloc[:, 24])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       426
4       753
5       968
6       104
7       392
8       160
9       165
10     2325
11      363
12      158
13     4210
14      512
15    17302
16     8421
17     4736
18      809
19     6489
20    11478
21     3992
22       77
23      304
24    64144
Name: Unnamed: 25, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
Name: 24, dtype: int64

In [203]:
tabela_manual_brasileiros = pd.to_numeric(df.iloc[3:25, 22])
tabela_ocr_brasileiros = pd.to_numeric(df2.iloc[:, 21])

diferenca_brasileiros = tabela_manual_brasileiros.values - tabela_ocr_brasileiros.values
diferenca_brasileiros

array([    -5,    999, -50000,      0,      0,   -500, 100000,    -10,
          600,  74352, 619976,      0,  77872,      0,    300,  56652,
        60000,     30,  -5000,      0,  -2000,      0])

In [204]:
for i in range(tabela_manual_brasileiros.size):
    if tabela_manual_brasileiros.iloc[i] - tabela_ocr_brasileiros.iloc[i] == 0 and tabela_manual_brasileiros.iloc[i] != 0:
        vp += 1
    if tabela_manual_brasileiros.iloc[i] - tabela_ocr_brasileiros.iloc[i] != 0 and tabela_manual_brasileiros.iloc[i] > 0 and tabela_ocr_brasileiros.iloc[i] > 0:
        fp += 1
    if tabela_manual_brasileiros.iloc[i] - tabela_ocr_brasileiros.iloc[i] == 0 and tabela_manual_brasileiros.iloc[i] == 0:
        vn += 1
    if tabela_manual_brasileiros.iloc[i] > 0 and tabela_ocr_brasileiros.iloc[i] == 0:
        fn += 1

print(vp, fp, vn, fn)

143 243 5 93

In [205]:
tabela_manual_estrangeiros = pd.to_numeric(df.iloc[3:25, 23])
tabela_ocr_estrangeiros = pd.to_numeric(df2.iloc[:, 22])

diferenca_estrangeiros = tabela_manual_estrangeiros.values - tabela_ocr_estrangeiros.values
diferenca_estrangeiros

array([     0,   5224,    -69,    300,     -6,      6,     50,      0,
            0,    387,   7000,   1410,   6000,   9900,      0,      0,
         8354,      0,  13000,    -10,      0, 179160])

In [206]:
for i in range(tabela_manual_estrangeiros.size):
    if tabela_manual_estrangeiros.iloc[i] - tabela_ocr_estrangeiros.iloc[i] == 0 and tabela_manual_estrangeiros.iloc[i] != 0:
        vp += 1
    if tabela_manual_estrangeiros.iloc[i] - tabela_ocr_estrangeiros.iloc[i] != 0 and tabela_manual_estrangeiros.iloc[i] > 0 and tabela_ocr_estrangeiros.iloc[i] > 0:
        fp += 1
    if tabela_manual_estrangeiros.iloc[i] - tabela_ocr_estrangeiros.iloc[i] == 0 and tabela_manual_estrangeiros.iloc[i] == 0:
        vn += 1
    if tabela_manual_estrangeiros.iloc[i] > 0 and tabela_ocr_estrangeiros.iloc[i] == 0:
        fn += 1

print(vp, fp, vn, fn)

150 255 5 96

In [207]:
tabela_manual_brasileiras = pd.to_numeric(df.iloc[3:25, 24])
tabela_ocr_brasileiras = pd.to_numeric(df2.iloc[:, 23])

diferenca_brasileiras = tabela_manual_brasileiras.values - tabela_ocr_brasileiras.values
diferenca_brasileiras

array([   25022,     5000,   130000,        0,   338475,        0,
       -1575990,   368621,   -10000,        0,  -300000,    29359,
          74851,   225635,   300600,    51030,    64717,      -12,
         817692,    74698,      300,  4036829])

In [208]:
for i in range(tabela_manual_brasileiras.size):
    if tabela_manual_brasileiras.iloc[i] - tabela_ocr_brasileiras.iloc[i] == 0 and tabela_manual_brasileiras.iloc[i] != 0:
        vp += 1
    if tabela_manual_brasileiras.iloc[i] - tabela_ocr_brasileiras.iloc[i] != 0 and tabela_manual_brasileiras.iloc[i] > 0 and tabela_ocr_brasileiras.iloc[i] > 0:
        fp += 1
    if tabela_manual_brasileiras.iloc[i] - tabela_ocr_brasileiras.iloc[i] == 0 and tabela_manual_brasileiras.iloc[i] == 0:
        vn += 1
    if tabela_manual_brasileiras.iloc[i] > 0 and tabela_ocr_brasileiras.iloc[i] == 0:
        fn += 1

print(vp, fp, vn, fn)

153 267 5 103

In [209]:
tabela_manual_estrangeiras = pd.to_numeric(df.iloc[3:25, 25])
tabela_ocr_estrangeiras = pd.to_numeric(df2.iloc[:, 24])

diferenca_estrangeiras = tabela_manual_estrangeiras.values - tabela_ocr_estrangeiras.values
diferenca_estrangeiras

array([  426,   753,   968,   104,   392,   160,   165,  2325,   363,
         158,  4210,   512, 17302,  8421,  4736,   809,  6489, 11478,
        3992,    77,   304, 64144])

In [210]:
for i in range(tabela_manual_estrangeiras.size):
    if tabela_manual_estrangeiras.iloc[i] - tabela_ocr_estrangeiras.iloc[i] == 0 and tabela_manual_estrangeiras.iloc[i] != 0:
        vp += 1
    if tabela_manual_estrangeiras.iloc[i] - tabela_ocr_estrangeiras.iloc[i] != 0 and tabela_manual_estrangeiras.iloc[i] > 0 and tabela_ocr_estrangeiras.iloc[i] > 0:
        fp += 1
    if tabela_manual_estrangeiras.iloc[i] - tabela_ocr_estrangeiras.iloc[i] == 0 and tabela_manual_estrangeiras.iloc[i] == 0:
        vn += 1
    if tabela_manual_estrangeiras.iloc[i] > 0 and tabela_ocr_estrangeiras.iloc[i] == 0:
        fn += 1

print(vp, fp, vn, fn)

153 267 5 125

In [211]:
variancia_brasileiros = np.var(diferenca_brasileiros)
variancia_brasileiros

17077836832.876038

In [212]:
variancia_estrangeiros = np.var(diferenca_estrangeiros)
variancia_estrangeiros

1369559112.049587

In [213]:
variancia_brasileiras = np.var(diferenca_brasileiras)
variancia_brasileiras

862765014176.1343

In [214]:
variancia_estrangeiras = np.var(diferenca_estrangeiras)
variancia_estrangeiras

180684748.74380162

In [215]:
desvio_padrao_brasileiros = np.std(diferenca_brasileiros)
desvio_padrao_brasileiros

130682.19784223112

In [216]:
desvio_padrao_estrangeiros = np.std(diferenca_estrangeiros)
desvio_padrao_estrangeiros

37007.55479695446

In [217]:
desvio_padrao_brasileiras = np.std(diferenca_brasileiras)
desvio_padrao_brasileiras

928851.4489282634

In [218]:
desvio_padrao_estrangeiras = np.std(diferenca_estrangeiras)
desvio_padrao_estrangeiras

13441.902720366697

In [219]:
coeficiente_variacao_brasileiros = desvio_padrao_brasileiros / np.mean(diferenca_brasileiros) * 100
coeficiente_variacao_brasileiros

308.0588334439575

In [220]:
coeficiente_variacao_estrangeiros = desvio_padrao_estrangeiros / np.mean(diferenca_estrangeiros) * 100
coeficiente_variacao_estrangeiros

352.9020508929105

In [221]:
coeficiente_variacao_brasileiras = desvio_padrao_brasileiras / np.mean(diferenca_brasileiras) * 100
coeficiente_variacao_brasileiras

438.8123474722551

In [222]:
coeficiente_variacao_estrangeiras = desvio_padrao_estrangeiras / np.mean(diferenca_estrangeiras) * 100
coeficiente_variacao_estrangeiras

230.51404640189836

In [223]:
print(f'Variância (brasileiros): {variancia_brasileiros}')
print(f'Desvio Padrão (brasileiros): {desvio_padrao_brasileiros}')
print(f'Coeficiente de Variação (brasileiros): {coeficiente_variacao_brasileiros}%')

Variância (brasileiros): 17077836832.876038
Desvio Padrão (brasileiros): 130682.19784223112
Coeficiente de Variação (brasileiros): 308.0588334439575%

In [224]:
print(f'Variância (estrangeiros): {variancia_estrangeiros}')
print(f'Desvio Padrão (estrangeiros): {desvio_padrao_estrangeiros}')
print(f'Coeficiente de Variação (estrangeiros): {coeficiente_variacao_estrangeiros}%')

Variância (estrangeiros): 1369559112.049587
Desvio Padrão (estrangeiros): 37007.55479695446
Coeficiente de Variação (estrangeiros): 352.9020508929105%

In [225]:
print(f'Variância (brasileiras): {variancia_brasileiras}')
print(f'Desvio Padrão (brasileiras): {desvio_padrao_brasileiras}')
print(f'Coeficiente de Variação (brasileiras): {coeficiente_variacao_brasileiras}%')

Variância (brasileiras): 862765014176.1343
Desvio Padrão (brasileiras): 928851.4489282634
Coeficiente de Variação (brasileiras): 438.8123474722551%

In [226]:
print(f'Variância (estrangeiras): {variancia_estrangeiras}')
print(f'Desvio Padrão (estrangeiras): {desvio_padrao_estrangeiras}')
print(f'Coeficiente de Variação (estrangeiras): {coeficiente_variacao_estrangeiras}%')

Variância (estrangeiras): 180684748.74380162
Desvio Padrão (estrangeiras): 13441.902720366697
Coeficiente de Variação (estrangeiras): 230.51404640189836%

In [227]:
media_brasileiros = np.mean(diferenca_brasileiros)
media_brasileiros

42421.181818181816

In [228]:
media_estrangeiros = np.mean(diferenca_estrangeiros)
media_estrangeiros

10486.636363636364

In [229]:
media_brasileiras = np.mean(diferenca_brasileiras)
media_brasileiras

211673.95454545456

In [230]:
media_estrangeiras = np.mean(diferenca_estrangeiras)
media_estrangeiras

5831.272727272727

In [231]:
outlier_inferior_brasileiros = media_brasileiros - (3 * desvio_padrao_brasileiros)
outlier_superior_brasileiros = media_brasileiros + (3 * desvio_padrao_brasileiros)

print(outlier_inferior_brasileiros, outlier_superior_brasileiros)

-349625.4117085115 434467.7753448752

In [232]:
outlier_inferior_estrangeiros = media_estrangeiros - (3 * desvio_padrao_estrangeiros)
outlier_superior_estrangeiros = media_estrangeiros + (3 * desvio_padrao_estrangeiros)

print(outlier_inferior_estrangeiros, outlier_superior_estrangeiros)

-100536.028027227 121509.30075449974

In [233]:
outlier_inferior_brasileiras = media_brasileiras - (3 * desvio_padrao_brasileiras)
outlier_superior_brasileiras = media_brasileiras + (3 * desvio_padrao_brasileiras)

print(outlier_inferior_brasileiras, outlier_superior_brasileiras)

-2574880.3922393355 2998228.3013302446

In [234]:
outlier_inferior_estrangeiras = media_estrangeiras - (3 * desvio_padrao_estrangeiras)
outlier_superior_estrangeiras = media_estrangeiras + (3 * desvio_padrao_estrangeiras)

print(outlier_inferior_estrangeiras, outlier_superior_estrangeiras)

-34494.43543382736 46156.98088837282

# Grau de instrução

In [235]:
instrucao = df[['Unnamed: 0','Instrução', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35']]

instrucao_header = instrucao.iloc[2]
instrucao.columns = instrucao_header
instrucao = instrucao[3:]

columns_multiindex = pd.MultiIndex.from_tuples([
    ('', '', '', 'Províncias e Município Neutro'),
    ('Instrução', '', 'Homens', 'Sabem ler e escrever'),
    ('Instrução', '', 'Homens', 'Analfabetos'),
    ('Instrução', '', 'Mulheres', 'Sabem ler e escrever'),
    ('Instrução', '', 'Mulheres', 'Analfabetas'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninos', 'Frequentam escolas'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninos', 'Não frequentam'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninos', 'Total'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninas', 'Frequentam escolas'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninas', 'Não frequentam'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninas', 'Total')
])

instrucao.columns = columns_multiindex

instrucao

                                            Instrução              \

                                               Homens
   Províncias e Município Neutro Sabem ler e escrever Analfabetos
3                       Amazonas                 6160       24823
4                           Pará                39718       88871
5                       Maranhão                44375       97567
6                          Piauí                17677       72645
7                          Ceará                58657      292249
8            Rio Grande do Norte                23602       39119
9                        Paraíba                29224      150209
10                    Pernambuco                92664      288901
11                       Alagoas                26046      129538
12                       Sergipe                18687       56052
13                         Bahia               161937      468416
14                Espírito Santo                 7229       22378
15              Município Neutro                65164       68714
16                Rio de Janeiro                69997      185809
17                     São Paulo                92977      255327
18                        Paraná                19014       40299
19                Santa Catarina                12927       59161
20             Rio Grande do Sul                 5592      134060
21                  Minas Gerais               145297      702295
22                         Goiás                15699       59299
23                   Mato Grosso                 7114       20877
24                         Total              1012097     3306602

                                                                      \
                                    População escolar de 6 a 15 anos
               Mulheres                                      Meninos
   Sabem ler e escrever Analfabetas               Frequentam escolas
3                  1453       24195                              824
4                 20677       98513                             5768
5                 24196      117963                             8739
6                 10093       78012                             1777
7                 20903      317964                            10021
8                 16220       92018                             2643
9                 11988      163279                             6630
10                54659      316287                            14069
11                15814      140870                             5455
12                10447       68434                             3402
13                37135      494304                            22260
14                 2503       27368                             1564
15                33992       58101                             5788
16                44603      189678                            12622
17                48090      284348                            15069
18                12802       44056                             2558
19                 7999       63731                             3100
20                38341      137659                             9947
21                78271      743413                            19968
22                 6987       67788                             2566
23                 3808       21951                              881
24               550981     3549992                           155651



                                     Meninas
   Não frequentam   Total Frequentam escolas Não frequentam   Total
3            5056    5880                371           3269    3640
4           25753   31521               3441          25020   28461
5           28142   36881               4844          29567   34411
6           15960   17737               1024          16968   17992
7           83808   93829               5399          85087   90486
8           18662   21305               2058          19857   21915
9           44061   50691               3894          45830   49724
10          82133   96202               9301          80960   90261
11          34261   39716               4028          34726   38754
12          14934   18336               1832          17333   19165
13         119426  141686              81743         113313  195056
14           5323    6887                722           5101    6823
15          10449   22237               4258          15019   19277
16          32019   44641               8194          33089   41283
17          71271   86340               8544          73915   82458
18           9666   12224               1866          10762   12628
19          15676   18776               2114          15473   17587
20          36222   46169               7947          33292   41239
21          66983  125012              11940         112824  124764
22          16864   19430               1240          16982   18222
23           5401    6282                338           6187    6525
24         786131  941782             165098         795574  960672

# Grau de instrução (adultos)

In [236]:
instrucao_adultos = df[['Unnamed: 0','Instrução', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29']]

instrucao_adultos_header = instrucao_adultos.iloc[2]
instrucao_adultos.columns = instrucao_adultos_header
instrucao_adultos = instrucao_adultos[3:]

columns_multiindex = pd.MultiIndex.from_tuples([
    ('', '', 'Províncias e Município Neutro'),
    ('Instrução', 'Homens', 'Sabem ler e escrever'),
    ('Instrução', 'Homens', 'Analfabetos'),
    ('Instrução', 'Mulheres', 'Sabem ler e escrever'),
    ('Instrução', 'Mulheres', 'Analfabetas')
])

instrucao_adultos.columns = columns_multiindex

instrucao_adultos

                                            Instrução              \
                                               Homens
   Províncias e Município Neutro Sabem ler e escrever Analfabetos
3                       Amazonas                 6160       24823
4                           Pará                39718       88871
5                       Maranhão                44375       97567
6                          Piauí                17677       72645
7                          Ceará                58657      292249
8            Rio Grande do Norte                23602       39119
9                        Paraíba                29224      150209
10                    Pernambuco                92664      288901
11                       Alagoas                26046      129538
12                       Sergipe                18687       56052
13                         Bahia               161937      468416
14                Espírito Santo                 7229       22378
15              Município Neutro                65164       68714
16                Rio de Janeiro                69997      185809
17                     São Paulo                92977      255327
18                        Paraná                19014       40299
19                Santa Catarina                12927       59161
20             Rio Grande do Sul                 5592      134060
21                  Minas Gerais               145297      702295
22                         Goiás                15699       59299
23                   Mato Grosso                 7114       20877
24                         Total              1012097     3306602


               Mulheres
   Sabem ler e escrever Analfabetas
3                  1453       24195
4                 20677       98513
5                 24196      117963
6                 10093       78012
7                 20903      317964
8                 16220       92018
9                 11988      163279
10                54659      316287
11                15814      140870
12                10447       68434
13                37135      494304
14                 2503       27368
15                33992       58101
16                44603      189678
17                48090      284348
18                12802       44056
19                 7999       63731
20                38341      137659
21                78271      743413
22                 6987       67788
23                 3808       21951
24               550981     3549992

In [237]:
print(df.columns)
print(df.iloc[3:25, 26])
print(df2.columns)
print(df2.iloc[:, 25])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        6160
4       39718
5       44375
6       17677
7       58657
8       23602
9       29224
10      92664
11      26046
12      18687
13     161937
14       7229
15      65164
16      69997
17      92977
18      19014
19      12927
20       5592
21     145297
22      15699
23       7114
24    1012097
Name: Instrução, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0           0
1      897131
2       42375
3           0
4       58657
5       23602
6           0
7        2664
8        6016
9       18087
10    1619871
11        228
12      65164
13      69997
14      92977
15      19014
16     129271
17       5592
18     145297
19      15609
20          4
21    1012097
Name: 25, dtype: int64

In [238]:
print(df.columns)
print(df.iloc[3:25, 27])
print(df2.columns)
print(df2.iloc[:, 26])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       24823
4       88871
5       97567
6       72645
7      292249
8       39119
9      150209
10     288901
11     129538
12      56052
13     468416
14      22378
15      68714
16     185809
17     255327
18      40299
19      59161
20     134060
21     702295
22      59299
23      20877
24    3306602
Name: Unnamed: 27, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0           0
1       88871
2       97567
3        2648
4           0
5           0
6      150209
7       28901
8      129588
9       56052
10          0
11       2287
12          0
13    1858091
14    2559271
15      40209
16      59161
17     124060
18    7022954
19      59299
20          0
21          0
Name: 26, dtype: int64

In [239]:
print(df.columns)
print(df.iloc[3:25, 28])
print(df2.columns)
print(df2.iloc[:, 27])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       1453
4      20677
5      24196
6      10093
7      20903
8      16220
9      11988
10     54659
11     15814
12     10447
13     37135
14      2503
15     33992
16     44603
17     48090
18     12802
19      7999
20     38341
21     78271
22      6987
23      3808
24    550981
Name: Unnamed: 28, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0       1452
1      20877
2      24196
3      10023
4      20008
5      36220
6      11088
7     545591
8      16814
9      10447
10     87135
11      2503
12     89082
13     14603
14     48090
15     12803
16       999
17       841
18         0
19         0
20      2508
21         0
Name: 27, dtype: int64

In [240]:
print(df.columns)
print(df.iloc[3:25, 29])
print(df2.columns)
print(df2.iloc[:, 28])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       24195
4       98513
5      117963
6       78012
7      317964
8       92018
9      163279
10     316287
11     140870
12      68434
13     494304
14      27368
15      58101
16     189678
17     284348
18      44056
19      63731
20     137659
21     743413
22      67788
23      21951
24    3549992
Name: Unnamed: 29, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0           1
1        9814
2      717003
3        7012
4          74
5           0
6      165279
7      168877
8       10870
9           0
10        440
11      21308
12      58101
13     180678
14     234348
15      44056
16      63733
17     197659
18      42413
19          0
20          0
21    8549002
Name: 28, dtype: int64

In [241]:
tabela_manual_alfabetizados = pd.to_numeric(df.iloc[3:25, 26])
tabela_ocr_alfabetizados = pd.to_numeric(df2.iloc[:, 25])

diferenca_alfabetizados = tabela_manual_alfabetizados.values - tabela_ocr_alfabetizados.values
diferenca_alfabetizados

array([    6160,  -857413,     2000,    17677,        0,        0,
          29224,    90000,    20030,      600, -1457934,     7001,
              0,        0,        0,        0,  -116344,        0,
              0,       90,     7110,        0])

In [242]:
for i in range(tabela_manual_alfabetizados.size):
    if tabela_manual_alfabetizados.iloc[i] - tabela_ocr_alfabetizados.iloc[i] == 0 and tabela_manual_alfabetizados.iloc[i] != 0:
        vp += 1
    if tabela_manual_alfabetizados.iloc[i] - tabela_ocr_alfabetizados.iloc[i] != 0 and tabela_manual_alfabetizados.iloc[i] > 0 and tabela_ocr_alfabetizados.iloc[i] > 0:
        fp += 1
    if tabela_manual_alfabetizados.iloc[i] - tabela_ocr_alfabetizados.iloc[i] == 0 and tabela_manual_alfabetizados.iloc[i] == 0:
        vn += 1
    if tabela_manual_alfabetizados.iloc[i] > 0 and tabela_ocr_alfabetizados.iloc[i] == 0:
        fn += 1

print(vp, fp, vn, fn)

162 277 5 128

In [243]:
tabela_manual_analfabetos = pd.to_numeric(df.iloc[3:25, 27])
tabela_ocr_analfabetos = pd.to_numeric(df2.iloc[:, 26])

diferenca_analfabetos = tabela_manual_analfabetos.values - tabela_ocr_analfabetos.values
diferenca_analfabetos

array([   24823,        0,        0,    69997,   292249,    39119,
              0,   260000,      -50,        0,   468416,    20091,
          68714, -1672282, -2303944,       90,        0,    10000,
       -6320659,        0,    20877,  3306602])

In [244]:
for i in range(tabela_manual_analfabetos.size):
    if tabela_manual_analfabetos.iloc[i] - tabela_ocr_analfabetos.iloc[i] == 0 and tabela_manual_analfabetos.iloc[i] != 0:
        vp += 1
    if tabela_manual_analfabetos.iloc[i] - tabela_ocr_analfabetos.iloc[i] != 0 and tabela_manual_analfabetos.iloc[i] > 0 and tabela_ocr_analfabetos.iloc[i] > 0:
        fp += 1
    if tabela_manual_analfabetos.iloc[i] - tabela_ocr_analfabetos.iloc[i] == 0 and tabela_manual_analfabetos.iloc[i] == 0:
        vn += 1
    if tabela_manual_analfabetos.iloc[i] > 0 and tabela_ocr_analfabetos.iloc[i] == 0:
        fn += 1

print(vp, fp, vn, fn)

168 286 5 135

In [245]:
tabela_manual_alfabetizadas = pd.to_numeric(df.iloc[3:25, 28])
tabela_ocr_alfabetizadas = pd.to_numeric(df2.iloc[:, 27])

diferenca_alfabetizadas = tabela_manual_alfabetizadas.values - tabela_ocr_alfabetizadas.values
diferenca_alfabetizadas

array([      1,    -200,       0,      70,     895,  -20000,     900,
       -490932,   -1000,       0,  -50000,       0,  -55090,   30000,
             0,      -1,    7000,   37500,   78271,    6987,    1300,
        550981])

In [246]:
for i in range(tabela_manual_alfabetizadas.size):
    if tabela_manual_alfabetizadas.iloc[i] - tabela_ocr_alfabetizadas.iloc[i] == 0 and tabela_manual_alfabetizadas.iloc[i] != 0:
        vp += 1
    if tabela_manual_alfabetizadas.iloc[i] - tabela_ocr_alfabetizadas.iloc[i] != 0 and tabela_manual_alfabetizadas.iloc[i] > 0 and tabela_ocr_alfabetizadas.iloc[i] > 0:
        fp += 1
    if tabela_manual_alfabetizadas.iloc[i] - tabela_ocr_alfabetizadas.iloc[i] == 0 and tabela_manual_alfabetizadas.iloc[i] == 0:
        vn += 1
    if tabela_manual_alfabetizadas.iloc[i] > 0 and tabela_ocr_alfabetizadas.iloc[i] == 0:
        fn += 1

print(vp, fp, vn, fn)

172 301 5 138

In [247]:
tabela_manual_analfabetas = pd.to_numeric(df.iloc[3:25, 29])
tabela_ocr_analfabetas = pd.to_numeric(df2.iloc[:, 28])

diferenca_analfabetas = tabela_manual_analfabetas.values - tabela_ocr_analfabetas.values
diferenca_analfabetas

array([   24194,    88699,  -599040,    71000,   317890,    92018,
          -2000,   147410,   130000,    68434,   493864,     6060,
              0,     9000,    50000,        0,       -2,   -60000,
         701000,    67788,    21951, -4999010])

In [248]:
for i in range(tabela_manual_analfabetas.size):
    if tabela_manual_analfabetas.iloc[i] - tabela_ocr_analfabetas.iloc[i] == 0 and tabela_manual_analfabetas.iloc[i] != 0:
        vp += 1
    if tabela_manual_analfabetas.iloc[i] - tabela_ocr_analfabetas.iloc[i] != 0 and tabela_manual_analfabetas.iloc[i] > 0 and tabela_ocr_analfabetas.iloc[i] > 0:
        fp += 1
    if tabela_manual_analfabetas.iloc[i] - tabela_ocr_analfabetas.iloc[i] == 0 and tabela_manual_analfabetas.iloc[i] == 0:
        vn += 1
    if tabela_manual_analfabetas.iloc[i] > 0 and tabela_ocr_analfabetas.iloc[i] == 0:
        fn += 1

print(vp, fp, vn, fn)

174 317 5 142

In [249]:
variancia_alfabetizados = np.var(diferenca_alfabetizados)
variancia_alfabetizados

120617834805.52272

In [250]:
variancia_analfabetos = np.var(diferenca_analfabetos)
variancia_analfabetos

2631321083941.539

In [251]:
variancia_alfabetizadas = np.var(diferenca_alfabetizadas)
variancia_alfabetizadas

25392685472.2314

In [252]:
variancia_analfabetas = np.var(diferenca_analfabetas)
variancia_analfabetas

1170246763421.9585

In [253]:
desvio_padrao_alfabetizados = np.std(diferenca_alfabetizados)
desvio_padrao_alfabetizados

347300.7843433739

In [254]:
desvio_padrao_analfabetos = np.std(diferenca_analfabetos)
desvio_padrao_analfabetos

1622134.7305145585

In [255]:
desvio_padrao_alfabetizadas = np.std(diferenca_alfabetizadas)
desvio_padrao_alfabetizadas

159350.8251382195

In [256]:
desvio_padrao_analfabetas = np.std(diferenca_analfabetas)
desvio_padrao_analfabetas

1081779.4430575757

In [257]:
coeficiente_variacao_alfabetizados = desvio_padrao_alfabetizados / np.mean(diferenca_alfabetizados) * 100
coeficiente_variacao_alfabetizados

-339.3116905884684

In [258]:
coeficiente_variacao_analfabetos = desvio_padrao_analfabetos / np.mean(diferenca_analfabetos) * 100
coeficiente_variacao_analfabetos

-624.3392676208076

In [259]:
coeficiente_variacao_alfabetizadas = desvio_padrao_alfabetizadas / np.mean(diferenca_alfabetizadas) * 100
coeficiente_variacao_alfabetizadas

3626.0298225531415

In [260]:
coeficiente_variacao_analfabetas = desvio_padrao_analfabetas / np.mean(diferenca_analfabetas) * 100
coeficiente_variacao_analfabetas

-706.050288816554

In [261]:
print(f'Variância (alfabetizados): {variancia_alfabetizados}')
print(f'Desvio Padrão (alfabetizados): {desvio_padrao_alfabetizados}')
print(f'Coeficiente de Variação (alfabetizados): {coeficiente_variacao_alfabetizados}%')

Variância (alfabetizados): 120617834805.52272
Desvio Padrão (alfabetizados): 347300.7843433739
Coeficiente de Variação (alfabetizados): -339.3116905884684%

In [262]:
print(f'Variância (analfabetos): {variancia_analfabetos}')
print(f'Desvio Padrão (analfabetos): {desvio_padrao_analfabetos}')
print(f'Coeficiente de Variação (analfabetos): {coeficiente_variacao_analfabetos}%')

Variância (analfabetos): 2631321083941.539
Desvio Padrão (analfabetos): 1622134.7305145585
Coeficiente de Variação (analfabetos): -624.3392676208076%

In [263]:
print(f'Variância (alfabetizadas): {variancia_alfabetizadas}')
print(f'Desvio Padrão (alfabetizadas): {desvio_padrao_alfabetizadas}')
print(f'Coeficiente de Variação (alfabetizadas): {coeficiente_variacao_alfabetizadas}%')

Variância (alfabetizadas): 25392685472.2314
Desvio Padrão (alfabetizadas): 159350.8251382195
Coeficiente de Variação (alfabetizadas): 3626.0298225531415%

In [264]:
print(f'Variância (analfabetas): {variancia_analfabetas}')
print(f'Desvio Padrão (analfabetas): {desvio_padrao_analfabetas}')
print(f'Coeficiente de Variação (analfabetas): {coeficiente_variacao_analfabetas}%')

Variância (analfabetas): 1170246763421.9585
Desvio Padrão (analfabetas): 1081779.4430575757
Coeficiente de Variação (analfabetas): -706.050288816554%

In [265]:
media_alfabetizados = np.mean(diferenca_alfabetizados)
media_alfabetizados

-102354.5

In [266]:
media_analfabetos = np.mean(diferenca_analfabetos)
media_analfabetos

-259816.22727272726

In [267]:
media_alfabetizadas = np.mean(diferenca_alfabetizadas)
media_alfabetizadas

4394.636363636364

In [268]:
media_analfabetas = np.mean(diferenca_analfabetas)
media_analfabetas

-153215.63636363635

In [269]:
outlier_inferior_alfabetizados = media_alfabetizados - (3 * desvio_padrao_alfabetizados)
outlier_superior_alfabetizados = media_alfabetizados + (3 * desvio_padrao_alfabetizados)

print(outlier_inferior_alfabetizados, outlier_superior_alfabetizados)

-1144256.8530301217 939547.8530301217

In [270]:
outlier_inferior_analfabetos = media_analfabetos - (3 * desvio_padrao_analfabetos)
outlier_superior_analfabetos = media_analfabetos + (3 * desvio_padrao_analfabetos)

print(outlier_inferior_analfabetos, outlier_superior_analfabetos)

-5126220.4188164035 4606587.964270948

In [271]:
outlier_inferior_alfabetizadas = media_alfabetizadas - (3 * desvio_padrao_alfabetizadas)
outlier_superior_alfabetizadas = media_alfabetizadas + (3 * desvio_padrao_alfabetizadas)

print(outlier_inferior_alfabetizadas, outlier_superior_alfabetizadas)

-473657.8390510221 482447.1117782948

In [272]:
outlier_inferior_analfabetas = media_analfabetas - (3 * desvio_padrao_analfabetas)
outlier_superior_analfabetas = media_analfabetas + (3 * desvio_padrao_analfabetas)

print(outlier_inferior_analfabetas, outlier_superior_analfabetas)

-3398553.9655363634 3092122.692809091

# Grau de instrução (jovens)

In [273]:
instrucao_jovens = df[['Unnamed: 0', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35']]

instrucao_jovens_header = instrucao_jovens.iloc[2]
instrucao_jovens.columns = instrucao_jovens_header
instrucao_jovens = instrucao_jovens[3:]

columns_multiindex = pd.MultiIndex.from_tuples([
    ('', '', '', 'Províncias e Município Neutro'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninos', 'Frequentam escolas'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninos', 'Não frequentam'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninos', 'Total'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninas', 'Frequentam escolas'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninas', 'Não frequentam'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninas', 'Total')
])

instrucao_jovens.columns = columns_multiindex

instrucao_jovens

                                                        Instrução  \
                                 População escolar de 6 a 15 anos
                                                          Meninos
   Províncias e Município Neutro               Frequentam escolas
3                       Amazonas                              824
4                           Pará                             5768
5                       Maranhão                             8739
6                          Piauí                             1777
7                          Ceará                            10021
8            Rio Grande do Norte                             2643
9                        Paraíba                             6630
10                    Pernambuco                            14069
11                       Alagoas                             5455
12                       Sergipe                             3402
13                         Bahia                            22260
14                Espírito Santo                             1564
15              Município Neutro                             5788
16                Rio de Janeiro                            12622
17                     São Paulo                            15069
18                        Paraná                             2558
19                Santa Catarina                             3100
20             Rio Grande do Sul                             9947
21                  Minas Gerais                            19968
22                         Goiás                             2566
23                   Mato Grosso                              881
24                         Total                           155651



                                     Meninas
   Não frequentam   Total Frequentam escolas Não frequentam   Total
3            5056    5880                371           3269    3640
4           25753   31521               3441          25020   28461
5           28142   36881               4844          29567   34411
6           15960   17737               1024          16968   17992
7           83808   93829               5399          85087   90486
8           18662   21305               2058          19857   21915
9           44061   50691               3894          45830   49724
10          82133   96202               9301          80960   90261
11          34261   39716               4028          34726   38754
12          14934   18336               1832          17333   19165
13         119426  141686              81743         113313  195056
14           5323    6887                722           5101    6823
15          10449   22237               4258          15019   19277
16          32019   44641               8194          33089   41283
17          71271   86340               8544          73915   82458
18           9666   12224               1866          10762   12628
19          15676   18776               2114          15473   17587
20          36222   46169               7947          33292   41239
21          66983  125012              11940         112824  124764
22          16864   19430               1240          16982   18222
23           5401    6282                338           6187    6525
24         786131  941782             165098         795574  960672

In [274]:
print(df.columns)
print(df.iloc[3:25, 30])
print(df2.columns)
print(df2.iloc[:, 29])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        824
4       5768
5       8739
6       1777
7      10021
8       2643
9       6630
10     14069
11      5455
12      3402
13     22260
14      1564
15      5788
16     12622
17     15069
18      2558
19      3100
20      9947
21     19968
22      2566
23       881
24    155651
Name: Unnamed: 30, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0       824
1         0
2         0
3         0
4         4
5        64
6         6
7     11069
8       455
9         0
10      220
11     1564
12        0
13    12623
14    15069
15     2568
16     3100
17     9947
18    19068
19      256
20      881
21        0
Name: 29, dtype: int64

In [275]:
print(df.columns)
print(df.iloc[3:25, 31])
print(df2.columns)
print(df2.iloc[:, 30])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       5056
4      25753
5      28142
6      15960
7      83808
8      18662
9      44061
10     82133
11     34261
12     14934
13    119426
14      5323
15     10449
16     32019
17     71271
18      9666
19     15676
20     36222
21     66983
22     16864
23      5401
24    786131
Name: Unnamed: 31, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0         0
1      2575
2      2842
3      1596
4       805
5     18603
6     41061
7     82133
8     34201
9         1
10    71426
11        0
12    10449
13    32019
14        2
15      666
16    15676
17    36229
18    66983
19    10804
20     5401
21        0
Name: 30, dtype: int64

In [276]:
print(df.columns)
print(df.iloc[3:25, 32])
print(df2.columns)
print(df2.iloc[:, 31])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       5880
4      31521
5      36881
6      17737
7      93829
8      21305
9      50691
10     96202
11     39716
12     18336
13    141686
14      6887
15     22237
16     44641
17     86340
18     12224
19     18776
20     46169
21    125012
22     19430
23      6282
24    941782
Name: Unnamed: 32, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0          0
1       1621
2       6881
3         73
4      93529
5     219081
6          0
7     962092
8      39716
9      18836
10    141086
11      6837
12     22287
13     44641
14      6340
15      2224
16     18776
17     46169
18    125019
19     18480
20       289
21         0
Name: 31, dtype: int64

In [277]:
print(df.columns)
print(df.iloc[3:25, 33])
print(df2.columns)
print(df2.iloc[:, 32])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        371
4       3441
5       4844
6       1024
7       5399
8       2058
9       3894
10      9301
11      4028
12      1832
13     81743
14       722
15      4258
16      8194
17      8544
18      1866
19      2114
20      7947
21     11940
22      1240
23       338
24    165098
Name: Unnamed: 33, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0          0
1          0
2         84
3          0
4          0
5          0
6        894
7          0
8       4028
9      19891
10         7
11         0
12         0
13         0
14         0
15         0
16         0
17         0
18         0
19         0
20         0
21    165088
Name: 32, dtype: int64

In [278]:
print(df.columns)
print(df.iloc[3:25, 34])
print(df2.columns)
print(df2.iloc[:, 33])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       3269
4      25020
5      29567
6      16968
7      85087
8      19857
9      45830
10     80960
11     34726
12     17333
13    113313
14      5101
15     15019
16     33089
17     73915
18     10762
19     15473
20     33292
21    112824
22     16982
23      6187
24    795574
Name: Unnamed: 34, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0          0
1      25020
2      20507
3          0
4          0
5          0
6          0
7          0
8      34720
9      17983
10    113818
11       101
12     15019
13     93089
14     73016
15     10762
16     15473
17      3299
18     12824
19     16989
20      6187
21         0
Name: 33, dtype: int64

In [279]:
print(df.columns)
print(df.iloc[3:25, 35])
print(df2.columns)
print(df2.iloc[:, 34])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       3640
4      28461
5      34411
6      17992
7      90486
8      21915
9      49724
10     90261
11     38754
12     19165
13    195056
14      6823
15     19277
16     41283
17     82458
18     12628
19     17587
20     41239
21    124764
22     18222
23      6525
24    960672
Name: Unnamed: 35, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0        300
1      28401
2        841
3      17992
4      90159
5          1
6      49724
7      96281
8          0
9      19105
10    195056
11         0
12      1277
13     41983
14         0
15     12698
16     17587
17         0
18         0
19         0
20         0
21         0
Name: 34, dtype: int64

In [280]:
tabela_manual_meninos_alfabetizados = pd.to_numeric(df.iloc[3:25, 30])
tabela_ocr_meninos_alfabetizados = pd.to_numeric(df2.iloc[:, 29])

diferenca_meninos_alfabetizados = tabela_manual_meninos_alfabetizados.values - tabela_ocr_meninos_alfabetizados.values
diferenca_meninos_alfabetizados

array([     0,   5768,   8739,   1777,  10017,   2579,   6624,   3000,
         5000,   3402,  22040,      0,   5788,     -1,      0,    -10,
            0,      0,    900,   2310,      0, 155651])

In [281]:
for i in range(tabela_manual_meninos_alfabetizados.size):
    if tabela_manual_meninos_alfabetizados.iloc[i] - tabela_ocr_meninos_alfabetizados.iloc[i] == 0 and tabela_manual_meninos_alfabetizados.iloc[i] != 0:
        vp += 1
    if tabela_manual_meninos_alfabetizados.iloc[i] - tabela_ocr_meninos_alfabetizados.iloc[i] != 0 and tabela_manual_meninos_alfabetizados.iloc[i] > 0 and tabela_ocr_meninos_alfabetizados.iloc[i] > 0:
        fp += 1
    if tabela_manual_meninos_alfabetizados.iloc[i] - tabela_ocr_meninos_alfabetizados.iloc[i] == 0 and tabela_manual_meninos_alfabetizados.iloc[i] == 0:
        vn += 1
    if tabela_manual_meninos_alfabetizados.iloc[i] > 0 and tabela_ocr_meninos_alfabetizados.iloc[i] == 0:
        fn += 1

print(vp, fp, vn, fn)

180 327 5 148

In [282]:
tabela_manual_meninos_analfabetos = pd.to_numeric(df.iloc[3:25, 31])
tabela_ocr_meninos_analfabetos = pd.to_numeric(df2.iloc[:, 30])

diferenca_meninos_analfabetos = tabela_manual_meninos_analfabetos.values - tabela_ocr_meninos_analfabetos.values
diferenca_meninos_analfabetos

array([  5056,  23178,  25300,  14364,  83003,     59,   3000,      0,
           60,  14933,  48000,   5323,      0,      0,  71269,   9000,
            0,     -7,      0,   6060,      0, 786131])

In [283]:
for i in range(tabela_manual_meninos_analfabetos.size):
    if tabela_manual_meninos_analfabetos.iloc[i] - tabela_ocr_meninos_analfabetos.iloc[i] == 0 and tabela_manual_meninos_analfabetos.iloc[i] != 0:
        vp += 1
    if tabela_manual_meninos_analfabetos.iloc[i] - tabela_ocr_meninos_analfabetos.iloc[i] != 0 and tabela_manual_meninos_analfabetos.iloc[i] > 0 and tabela_ocr_meninos_analfabetos.iloc[i] > 0:
        fp += 1
    if tabela_manual_meninos_analfabetos.iloc[i] - tabela_ocr_meninos_analfabetos.iloc[i] == 0 and tabela_manual_meninos_analfabetos.iloc[i] == 0:
        vn += 1
    if tabela_manual_meninos_analfabetos.iloc[i] > 0 and tabela_ocr_meninos_analfabetos.iloc[i] == 0:
        fn += 1

print(vp, fp, vn, fn)

186 340 5 151

In [284]:
tabela_manual_meninos_total = pd.to_numeric(df.iloc[3:25, 32])
tabela_ocr_meninos_total = pd.to_numeric(df2.iloc[:, 31])

diferenca_meninos_total = tabela_manual_meninos_total.values - tabela_ocr_meninos_total.values
diferenca_meninos_total

array([   5880,   29900,   30000,   17664,     300, -197776,   50691,
       -865890,       0,    -500,     600,      50,     -50,       0,
         80000,   10000,       0,       0,      -7,     950,    5993,
        941782])

In [285]:
for i in range(tabela_manual_meninos_total.size):
    if tabela_manual_meninos_total.iloc[i] - tabela_ocr_meninos_total.iloc[i] == 0 and tabela_manual_meninos_total.iloc[i] != 0:
        vp += 1
    if tabela_manual_meninos_total.iloc[i] - tabela_ocr_meninos_total.iloc[i] != 0 and tabela_manual_meninos_total.iloc[i] > 0 and tabela_ocr_meninos_total.iloc[i] > 0:
        fp += 1
    if tabela_manual_meninos_total.iloc[i] - tabela_ocr_meninos_total.iloc[i] == 0 and tabela_manual_meninos_total.iloc[i] == 0:
        vn += 1
    if tabela_manual_meninos_total.iloc[i] > 0 and tabela_ocr_meninos_total.iloc[i] == 0:
        fn += 1

print(vp, fp, vn, fn)

190 355 5 154

In [286]:
tabela_manual_meninas_alfabetizadas = pd.to_numeric(df.iloc[3:25, 33])
tabela_ocr_meninas_alfabetizadas = pd.to_numeric(df2.iloc[:, 32])

diferenca_meninas_alfabetizadas = tabela_manual_meninas_alfabetizadas.values - tabela_ocr_meninas_alfabetizadas.values
diferenca_meninas_alfabetizadas

array([   371,   3441,   4760,   1024,   5399,   2058,   3000,   9301,
            0, -18059,  81736,    722,   4258,   8194,   8544,   1866,
         2114,   7947,  11940,   1240,    338,     10])

In [287]:
for i in range(tabela_manual_meninas_alfabetizadas.size):
    if tabela_manual_meninas_alfabetizadas.iloc[i] - tabela_ocr_meninas_alfabetizadas.iloc[i] == 0 and tabela_manual_meninas_alfabetizadas.iloc[i] != 0:
        vp += 1
    if tabela_manual_meninas_alfabetizadas.iloc[i] - tabela_ocr_meninas_alfabetizadas.iloc[i] != 0 and tabela_manual_meninas_alfabetizadas.iloc[i] > 0 and tabela_ocr_meninas_alfabetizadas.iloc[i] > 0:
        fp += 1
    if tabela_manual_meninas_alfabetizadas.iloc[i] - tabela_ocr_meninas_alfabetizadas.iloc[i] == 0 and tabela_manual_meninas_alfabetizadas.iloc[i] == 0:
        vn += 1
    if tabela_manual_meninas_alfabetizadas.iloc[i] > 0 and tabela_ocr_meninas_alfabetizadas.iloc[i] == 0:
        fn += 1

print(vp, fp, vn, fn)

191 360 5 170

In [288]:
tabela_manual_meninas_analfabetas = pd.to_numeric(df.iloc[3:25, 34])
tabela_ocr_meninas_analfabetas = pd.to_numeric(df2.iloc[:, 33])

diferenca_meninas_analfabetas = tabela_manual_meninas_analfabetas.values - tabela_ocr_meninas_analfabetas.values
diferenca_meninas_analfabetas

array([  3269,      0,   9060,  16968,  85087,  19857,  45830,  80960,
            6,   -650,   -505,   5000,      0, -60000,    899,      0,
            0,  29993, 100000,     -7,      0, 795574])

In [289]:
for i in range(tabela_manual_meninas_analfabetas.size):
    if tabela_manual_meninas_analfabetas.iloc[i] - tabela_ocr_meninas_analfabetas.iloc[i] == 0 and tabela_manual_meninas_analfabetas.iloc[i] != 0:
        vp += 1
    if tabela_manual_meninas_analfabetas.iloc[i] - tabela_ocr_meninas_analfabetas.iloc[i] != 0 and tabela_manual_meninas_analfabetas.iloc[i] > 0 and tabela_ocr_meninas_analfabetas.iloc[i] > 0:
        fp += 1
    if tabela_manual_meninas_analfabetas.iloc[i] - tabela_ocr_meninas_analfabetas.iloc[i] == 0 and tabela_manual_meninas_analfabetas.iloc[i] == 0:
        vn += 1
    if tabela_manual_meninas_analfabetas.iloc[i] > 0 and tabela_ocr_meninas_analfabetas.iloc[i] == 0:
        fn += 1

print(vp, fp, vn, fn)

196 370 5 177

In [290]:
tabela_manual_meninas_total = pd.to_numeric(df.iloc[3:25, 35])
tabela_ocr_meninas_total = pd.to_numeric(df2.iloc[:, 34])

diferenca_meninas_total = tabela_manual_meninas_total.values - tabela_ocr_meninas_total.values
diferenca_meninas_total

array([  3340,     60,  33570,      0,    327,  21914,      0,  -6020,
        38754,     60,      0,   6823,  18000,   -700,  82458,    -70,
            0,  41239, 124764,  18222,   6525, 960672])

In [291]:
for i in range(tabela_manual_meninas_total.size):
    if tabela_manual_meninas_total.iloc[i] - tabela_ocr_meninas_total.iloc[i] == 0 and tabela_manual_meninas_total.iloc[i] != 0:
        vp += 1
    if tabela_manual_meninas_total.iloc[i] - tabela_ocr_meninas_total.iloc[i] != 0 and tabela_manual_meninas_total.iloc[i] > 0 and tabela_ocr_meninas_total.iloc[i] > 0:
        fp += 1
    if tabela_manual_meninas_total.iloc[i] - tabela_ocr_meninas_total.iloc[i] == 0 and tabela_manual_meninas_total.iloc[i] == 0:
        vn += 1
    if tabela_manual_meninas_total.iloc[i] > 0 and tabela_ocr_meninas_total.iloc[i] == 0:
        fn += 1

print(vp, fp, vn, fn)

200 380 5 185

In [292]:
variancia_meninos_alfabetizados = np.var(diferenca_meninos_alfabetizados)
variancia_meninos_alfabetizados

1026446146.7024792

In [293]:
variancia_meninos_analfabetos = np.var(diferenca_meninos_analfabetos)
variancia_meninos_analfabetos

26344900523.241737

In [294]:
variancia_meninos_total = np.var(diferenca_meninos_total)
variancia_meninos_total

76660727200.9938

In [295]:
variancia_meninas_alfabetizadas = np.var(diferenca_meninas_alfabetizadas)
variancia_meninas_alfabetizadas

302367546.355372

In [296]:
variancia_meninas_analfabetas = np.var(diferenca_meninas_analfabetas)
variancia_meninas_analfabetas

27543409033.42355

In [297]:
variancia_meninas_total = np.var(diferenca_meninas_total)
variancia_meninas_total

39455710912.23966

In [298]:
desvio_padrao_meninos_alfabetizados = np.std(diferenca_meninos_alfabetizados)
desvio_padrao_meninos_alfabetizados

32038.198243697774

In [299]:
desvio_padrao_meninos_analfabetos = np.std(diferenca_meninos_analfabetos)
desvio_padrao_meninos_analfabetos

162311.12261099587

In [300]:
desvio_padrao_meninos_total = np.std(diferenca_meninos_total)
desvio_padrao_meninos_total

276876.73647490464

In [301]:
desvio_padrao_meninas_alfabetizadas = np.std(diferenca_meninas_alfabetizadas)
desvio_padrao_meninas_alfabetizadas

17388.718939455317

In [302]:
desvio_padrao_meninas_analfabetas = np.std(diferenca_meninas_analfabetas)
desvio_padrao_meninas_analfabetas

165962.0710687341

In [303]:
desvio_padrao_meninas_total = np.std(diferenca_meninas_total)
desvio_padrao_meninas_total

198634.61660103372

In [304]:
coeficiente_variacao_meninos_alfabetizados = desvio_padrao_meninos_alfabetizados / np.mean(diferenca_meninos_alfabetizados) * 100
coeficiente_variacao_meninos_alfabetizados

301.7502745741793

In [305]:
coeficiente_variacao_meninos_analfabetos = desvio_padrao_meninos_analfabetos / np.mean(diferenca_meninos_analfabetos) * 100
coeficiente_variacao_meninos_analfabetos

326.18526570885666

In [306]:
coeficiente_variacao_meninos_total = desvio_padrao_meninos_total / np.mean(diferenca_meninos_total) * 100
coeficiente_variacao_meninos_total

5558.404010008397

In [307]:
coeficiente_variacao_meninas_alfabetizadas = desvio_padrao_meninas_alfabetizadas / np.mean(diferenca_meninas_alfabetizadas) * 100
coeficiente_variacao_meninas_alfabetizadas

272.8537107842979

In [308]:
coeficiente_variacao_meninas_analfabetas = desvio_padrao_meninas_analfabetas / np.mean(diferenca_meninas_analfabetas) * 100
coeficiente_variacao_meninas_analfabetas

322.72900597716784

In [309]:
coeficiente_variacao_meninas_total = desvio_padrao_meninas_total / np.mean(diferenca_meninas_total) * 100
coeficiente_variacao_meninas_total

323.71572362751044

In [310]:
print(f'Variância (meninos alfabetizados): {variancia_meninos_alfabetizados}')
print(f'Desvio Padrão (meninos alfabetizados): {desvio_padrao_meninos_alfabetizados}')
print(f'Coeficiente de Variação (meninos alfabetizados): {coeficiente_variacao_meninos_alfabetizados}%')

Variância (meninos alfabetizados): 1026446146.7024792
Desvio Padrão (meninos alfabetizados): 32038.198243697774
Coeficiente de Variação (meninos alfabetizados): 301.7502745741793%

In [311]:
print(f'Variância (meninos analfabetos): {variancia_meninos_analfabetos}')
print(f'Desvio Padrão (meninos analfabetos): {desvio_padrao_meninos_analfabetos}')
print(f'Coeficiente de Variação (meninos analfabetos): {coeficiente_variacao_meninos_analfabetos}%')

Variância (meninos analfabetos): 26344900523.241737
Desvio Padrão (meninos analfabetos): 162311.12261099587
Coeficiente de Variação (meninos analfabetos): 326.18526570885666%

In [312]:
print(f'Variância (meninos total): {variancia_meninos_total}')
print(f'Desvio Padrão (meninos total): {desvio_padrao_meninos_total}')
print(f'Coeficiente de Variação (meninos total): {coeficiente_variacao_meninos_total}%')

Variância (meninos total): 76660727200.9938
Desvio Padrão (meninos total): 276876.73647490464
Coeficiente de Variação (meninos total): 5558.404010008397%

In [313]:
print(f'Variância (meninas alfabetizadas): {variancia_meninas_alfabetizadas}')
print(f'Desvio Padrão (meninas alfabetizadas): {desvio_padrao_meninas_alfabetizadas}')
print(f'Coeficiente de Variação (meninas alfabetizadas): {coeficiente_variacao_meninas_alfabetizadas}%')

Variância (meninas alfabetizadas): 302367546.355372
Desvio Padrão (meninas alfabetizadas): 17388.718939455317
Coeficiente de Variação (meninas alfabetizadas): 272.8537107842979%

In [314]:
print(f'Variância (meninas alfabetizadas): {variancia_meninas_alfabetizadas}')
print(f'Desvio Padrão (meninas alfabetizadas): {desvio_padrao_meninas_alfabetizadas}')
print(f'Coeficiente de Variação (meninas alfabetizadas): {coeficiente_variacao_meninas_alfabetizadas}%')

Variância (meninas alfabetizadas): 302367546.355372
Desvio Padrão (meninas alfabetizadas): 17388.718939455317
Coeficiente de Variação (meninas alfabetizadas): 272.8537107842979%

In [315]:
print(f'Variância (meninas total): {variancia_meninas_total}')
print(f'Desvio Padrão (meninas total): {desvio_padrao_meninas_total}')
print(f'Coeficiente de Variação (meninas total): {coeficiente_variacao_meninas_total}%')

Variância (meninas total): 39455710912.23966
Desvio Padrão (meninas total): 198634.61660103372
Coeficiente de Variação (meninas total): 323.71572362751044%

In [316]:
media_meninos_alfabetizados = np.mean(diferenca_meninos_alfabetizados)
media_meninos_alfabetizados

10617.454545454546

In [317]:
media_meninos_analfabetos = np.mean(diferenca_meninos_analfabetos)
media_meninos_analfabetos

49760.40909090909

In [318]:
media_meninos_total = np.mean(diferenca_meninos_total)
media_meninos_total

4981.227272727273

In [319]:
media_meninas_alfabetizadas = np.mean(diferenca_meninas_alfabetizadas)
media_meninas_alfabetizadas

6372.909090909091

In [320]:
media_meninas_analfabetas = np.mean(diferenca_meninas_analfabetas)
media_meninas_analfabetas

51424.59090909091

In [321]:
media_meninas_total = np.mean(diferenca_meninas_total)
media_meninas_total

61360.818181818184

In [322]:
outlier_inferior_meninos_alfabetizados = media_meninos_alfabetizados - (3 * desvio_padrao_meninos_alfabetizados)
outlier_superior_meninos_alfabetizados = media_meninos_alfabetizados + (3 * desvio_padrao_meninos_alfabetizados)

print(outlier_inferior_meninos_alfabetizados, outlier_superior_meninos_alfabetizados)

-85497.14018563878 106732.04927654787

In [323]:
outlier_inferior_meninos_analfabetos = media_meninos_analfabetos - (3 * desvio_padrao_meninos_analfabetos)
outlier_superior_meninos_analfabetos = media_meninos_analfabetos + (3 * desvio_padrao_meninos_analfabetos)

print(outlier_inferior_meninos_analfabetos, outlier_superior_meninos_analfabetos)

-437172.9587420785 536693.7769238966

In [324]:
outlier_inferior_meninos_total = media_meninos_total - (3 * desvio_padrao_meninos_total)
outlier_superior_meninos_total = media_meninos_total + (3 * desvio_padrao_meninos_total)

print(outlier_inferior_meninos_total, outlier_superior_meninos_total)

-825648.9821519866 835611.4366974412

In [325]:
outlier_inferior_meninas_alfabetizadas = media_meninas_alfabetizadas - (3 * desvio_padrao_meninas_alfabetizadas)
outlier_superior_meninas_alfabetizadas = media_meninas_alfabetizadas + (3 * desvio_padrao_meninas_alfabetizadas)

print(outlier_inferior_meninas_alfabetizadas, outlier_superior_meninas_alfabetizadas)

-45793.24772745687 58539.06590927504

In [326]:
outlier_inferior_meninas_analfabetas = media_meninas_analfabetas - (3 * desvio_padrao_meninas_analfabetas)
outlier_superior_meninas_analfabetas = media_meninas_analfabetas + (3 * desvio_padrao_meninas_analfabetas)

print(outlier_inferior_meninas_analfabetas, outlier_superior_meninas_analfabetas)

-446461.62229711143 549310.8041152932

In [327]:
outlier_inferior_meninas_total = media_meninas_total - (3 * desvio_padrao_meninas_total)
outlier_superior_meninas_total = media_meninas_total + (3 * desvio_padrao_meninas_total)

print(outlier_inferior_meninas_total, outlier_superior_meninas_total)

-534543.0316212829 657264.6679849194

# Casas

In [328]:
casas = df[['Unnamed: 0','Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38']]

casas_header = casas.iloc[2]
casas.columns = casas_header
casas = casas[3:]

columns_multiindex = pd.MultiIndex.from_tuples([
    ('', 'Províncias e Município Neutro'),
    ('Casas', 'Habitadas'),
    ('Casas', 'Desabitadas'),
    ('Casas', 'Total')
])

casas.columns = columns_multiindex

casas

                                     Casas
   Províncias e Município Neutro Habitadas Desabitadas    Total
3                       Amazonas      7661         229     7890
4                           Pará     38978        2077    41055
5                       Maranhão     47166        1405    48571
6                          Piauí     29208         223    29431
7                          Ceará     99901        2989   102890
8            Rio Grande do Norte     36710         706    37416
9                        Paraíba     43767         522    44289
10                    Pernambuco    133920        4381   188301
11                       Alagoas     55894        2030    57924
12                       Sergipe     25542         567    26109
13                         Bahia    176032        5479   181511
14                Espírito Santo     10742        1079    11821
15              Município Neutro     29045        1873    80918
16                Rio de Janeiro     88698        2844    91542
17                     São Paulo     65778        1000    66778
18                        Paraná     18903         259    19162
19                Santa Catarina     19608         528    20136
20             Rio Grande do Sul     60199        1741    61940
21                  Minas Gerais    275611        3629   279240
22                         Goiás     25196         487    25683
23                   Mato Grosso      7501         102     7603
24                         Total   1296060       34150  1330210

In [329]:
print(df.columns)
print(df.iloc[3:25, 36])
print(df2.columns)
print(df2.iloc[:, 35])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        7661
4       38978
5       47166
6       29208
7       99901
8       36710
9       43767
10     133920
11      55894
12      25542
13     176032
14      10742
15      29045
16      88698
17      65778
18      18903
19      19608
20      60199
21     275611
22      25196
23       7501
24    1296060
Name: Unnamed: 36, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0           0
1           0
2           0
3           0
4           9
5       86710
6         370
7      123020
8       55894
9       25642
10          0
11      10742
12         45
13          0
14     657781
15      18908
16          0
17        109
18     275611
19      25198
20       7502
21    1298000
Name: 35, dtype: int64

In [330]:
print(df.columns)
print(df.iloc[3:25, 37])
print(df2.columns)
print(df2.iloc[:, 36])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       229
4      2077
5      1405
6       223
7      2989
8       706
9       522
10     4381
11     2030
12      567
13     5479
14     1079
15     1873
16     2844
17     1000
18      259
19      528
20     1741
21     3629
22      487
23      102
24    34150
Name: Unnamed: 37, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
Name: 36, dtype: int64

In [331]:
print(df.columns)
print(df.iloc[3:25, 38])
print(df2.columns)
print(df2.iloc[:, 37])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        7890
4       41055
5       48571
6       29431
7      102890
8       37416
9       44289
10     188301
11      57924
12      26109
13     181511
14      11821
15      80918
16      91542
17      66778
18      19162
19      20136
20      61940
21     279240
22      25683
23       7603
24    1330210
Name: Unnamed: 38, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0        7800
1       41055
2       48571
3       29191
4     4102890
5           1
6       44989
7      188901
8        7924
9       29109
10         15
11      11821
12      20918
13      91542
14        778
15      19162
16      20138
17      41910
18          0
19      25083
20       7608
21    1880214
Name: 37, dtype: int64

In [332]:
tabela_manual_casas_habitadas = pd.to_numeric(df.iloc[3:25, 36])
tabela_ocr_casas_habitadas = pd.to_numeric(df2.iloc[:, 35])

diferenca_casas_habitadas = tabela_manual_casas_habitadas.values - tabela_ocr_casas_habitadas.values
diferenca_casas_habitadas

array([   7661,   38978,   47166,   29208,   99892,  -50000,   43397,
         10900,       0,    -100,  176032,       0,   29000,   88698,
       -592003,      -5,   19608,   60090,       0,      -2,      -1,
         -1940])

In [333]:
for i in range(tabela_manual_casas_habitadas.size):
    if tabela_manual_casas_habitadas.iloc[i] - tabela_ocr_casas_habitadas.iloc[i] == 0 and tabela_manual_casas_habitadas.iloc[i] != 0:
        vp += 1
    if tabela_manual_casas_habitadas.iloc[i] - tabela_ocr_casas_habitadas.iloc[i] != 0 and tabela_manual_casas_habitadas.iloc[i] > 0 and tabela_ocr_casas_habitadas.iloc[i] > 0:
        fp += 1
    if tabela_manual_casas_habitadas.iloc[i] - tabela_ocr_casas_habitadas.iloc[i] == 0 and tabela_manual_casas_habitadas.iloc[i] == 0:
        vn += 1
    if tabela_manual_casas_habitadas.iloc[i] > 0 and tabela_ocr_casas_habitadas.iloc[i] == 0:
        fn += 1

print(vp, fp, vn, fn)

203 392 5 192

In [334]:
tabela_manual_casas_desabitadas = pd.to_numeric(df.iloc[3:25, 37])
tabela_ocr_casas_desabitadas = pd.to_numeric(df2.iloc[:, 36])

diferenca_casas_desabitadas = tabela_manual_casas_desabitadas.values - tabela_ocr_casas_desabitadas.values
diferenca_casas_desabitadas

array([  229,  2077,  1405,   223,  2989,   706,   522,  4381,  2030,
         567,  5479,  1079,  1873,  2844,  1000,   259,   528,  1741,
        3629,   487,   102, 34150])

In [335]:
for i in range(tabela_manual_casas_desabitadas.size):
    if tabela_manual_casas_desabitadas.iloc[i] - tabela_ocr_casas_desabitadas.iloc[i] == 0 and tabela_manual_casas_desabitadas.iloc[i] != 0:
        vp += 1
    if tabela_manual_casas_desabitadas.iloc[i] - tabela_ocr_casas_desabitadas.iloc[i] != 0 and tabela_manual_casas_desabitadas.iloc[i] > 0 and tabela_ocr_casas_desabitadas.iloc[i] > 0:
        fp += 1
    if tabela_manual_casas_desabitadas.iloc[i] - tabela_ocr_casas_desabitadas.iloc[i] == 0 and tabela_manual_casas_desabitadas.iloc[i] == 0:
        vn += 1
    if tabela_manual_casas_desabitadas.iloc[i] > 0 and tabela_ocr_casas_desabitadas.iloc[i] == 0:
        fn += 1

print(vp, fp, vn, fn)

203 392 5 214

In [336]:
tabela_manual_casas_total = pd.to_numeric(df.iloc[3:25, 38])
tabela_ocr_casas_total = pd.to_numeric(df2.iloc[:, 37])

diferenca_casas_total = tabela_manual_casas_total.values - tabela_ocr_casas_total.values
diferenca_casas_total

array([      90,        0,        0,      240, -4000000,    37415,
           -700,     -600,    50000,    -3000,   181496,        0,
          60000,        0,    66000,        0,       -2,    20030,
         279240,      600,       -5,  -550004])

In [337]:
for i in range(tabela_manual_casas_total.size):
    if tabela_manual_casas_total.iloc[i] - tabela_ocr_casas_total.iloc[i] == 0 and tabela_manual_casas_total.iloc[i] != 0:
        vp += 1
    if tabela_manual_casas_total.iloc[i] - tabela_ocr_casas_total.iloc[i] != 0 and tabela_manual_casas_total.iloc[i] > 0 and tabela_ocr_casas_total.iloc[i] > 0:
        fp += 1
    if tabela_manual_casas_total.iloc[i] - tabela_ocr_casas_total.iloc[i] == 0 and tabela_manual_casas_total.iloc[i] == 0:
        vn += 1
    if tabela_manual_casas_total.iloc[i] > 0 and tabela_ocr_casas_total.iloc[i] == 0:
        fn += 1

print(vp, fp, vn, fn)

208 408 5 215

In [338]:
variancia_casas_habitadas = np.var(diferenca_casas_habitadas)
variancia_casas_habitadas

18786203441.316116

In [339]:
variancia_casas_desabitadas = np.var(diferenca_casas_desabitadas)
variancia_casas_desabitadas

47931230.33884297

In [340]:
variancia_casas_total = np.var(diferenca_casas_total)
variancia_casas_total

715850622146.0579

In [341]:
desvio_padrao_casas_habitadas = np.std(diferenca_casas_habitadas)
desvio_padrao_casas_habitadas

137062.77190147628

In [342]:
desvio_padrao_casas_desabitadas = np.std(diferenca_casas_desabitadas)
desvio_padrao_casas_desabitadas

6923.238428571052

In [343]:
desvio_padrao_casas_total = np.std(diferenca_casas_total)
desvio_padrao_casas_total

846079.5601750807

In [344]:
coeficiente_variacao_casas_habitadas = desvio_padrao_casas_habitadas / np.mean(diferenca_casas_habitadas) * 100
coeficiente_variacao_casas_habitadas

45833.42425645961

In [345]:
coeficiente_variacao_casas_desabitadas = desvio_padrao_casas_desabitadas / np.mean(diferenca_casas_desabitadas) * 100
coeficiente_variacao_casas_desabitadas

223.003287596725

In [346]:
coeficiente_variacao_casas_total = desvio_padrao_casas_total / np.mean(diferenca_casas_total) * 100
coeficiente_variacao_casas_total

-482.32147398040456

In [347]:
print(f'Variância (casas habitadas): {variancia_casas_habitadas}')
print(f'Desvio Padrão (casas habitadas): {desvio_padrao_casas_habitadas}')
print(f'Coeficiente de Variação (casas habitadas): {coeficiente_variacao_casas_habitadas}%')

Variância (casas habitadas): 18786203441.316116
Desvio Padrão (casas habitadas): 137062.77190147628
Coeficiente de Variação (casas habitadas): 45833.42425645961%

In [348]:
print(f'Variância (casas desabitadas): {variancia_casas_desabitadas}')
print(f'Desvio Padrão (casas desabitadas): {desvio_padrao_casas_desabitadas}')
print(f'Coeficiente de Variação (casas desabitadas): {coeficiente_variacao_casas_desabitadas}%')

Variância (casas desabitadas): 47931230.33884297
Desvio Padrão (casas desabitadas): 6923.238428571052
Coeficiente de Variação (casas desabitadas): 223.003287596725%

In [349]:
print(f'Variância (casas total): {variancia_casas_total}')
print(f'Desvio Padrão (casas total): {desvio_padrao_casas_total}')
print(f'Coeficiente de Variação (casas total): {coeficiente_variacao_casas_total}%')

Variância (casas total): 715850622146.0579
Desvio Padrão (casas total): 846079.5601750807
Coeficiente de Variação (casas total): -482.32147398040456%

In [350]:
media_casas_habitadas = np.mean(diferenca_casas_habitadas)
media_casas_habitadas

299.04545454545456

In [351]:
media_casas_desabitadas = np.mean(diferenca_casas_desabitadas)
media_casas_desabitadas

3104.5454545454545

In [352]:
media_casas_total = np.mean(diferenca_casas_total)
media_casas_total

-175418.18181818182

In [353]:
outlier_inferior_casas_habitadas = media_casas_habitadas - (3 * desvio_padrao_casas_habitadas)
outlier_superior_casas_habitadas = media_casas_habitadas + (3 * desvio_padrao_casas_habitadas)

print(outlier_inferior_casas_habitadas, outlier_superior_casas_habitadas)

-410889.27024988335 411487.3611589743

In [354]:
outlier_inferior_casas_desabitadas = media_casas_desabitadas - (3 * desvio_padrao_casas_desabitadas)
outlier_superior_casas_desabitadas = media_casas_desabitadas + (3 * desvio_padrao_casas_desabitadas)

print(outlier_inferior_casas_desabitadas, outlier_superior_casas_desabitadas)

-17665.169831167703 23874.260740258615

In [355]:
outlier_inferior_casas_total = media_casas_total - (3 * desvio_padrao_casas_total)
outlier_superior_casas_total = media_casas_total + (3 * desvio_padrao_casas_total)

print(outlier_inferior_casas_total, outlier_superior_casas_total)

-2713656.8623434235 2362820.4987070602

# Fogos

In [356]:
fogos = df[['Unnamed: 0', 'Unnamed: 39']]

fogos_header = fogos.iloc[2]
fogos.columns = fogos_header
fogos = fogos[3:]

fogos

2  Províncias e Município Neutro Número de fogos
3                       Amazonas            7811
4                           Pará           39521
5                       Maranhão           49282
6                          Piauí           30770
7                          Ceará          100207
8            Rio Grande do Norte           37320
9                        Paraíba           44438
10                    Pernambuco          134765
11                       Alagoas           60386
12                       Sergipe           24950
13                         Bahia          180307
14                Espírito Santo           10774
15              Município Neutro           44211
16                Rio de Janeiro           90232
17                     São Paulo           65960
18                        Paraná           22026
19                Santa Catarina           14457
20             Rio Grande do Sul           61394
21                  Minas Gerais          280660
22                         Goiás           25222
23                   Mato Grosso            7581
24                         Total         1332274

In [357]:
print(df.columns)
print(df.iloc[3:25, 39])
print(df2.columns)
print(df2.iloc[:, 38])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        7811
4       39521
5       49282
6       30770
7      100207
8       37320
9       44438
10     134765
11      60386
12      24950
13     180307
14      10774
15      44211
16      90232
17      65960
18      22026
19      14457
20      61394
21     280660
22      25222
23       7581
24    1332274
Name: Unnamed: 39, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
Name: 38, dtype: int64

In [358]:
tabela_manual_fogos = pd.to_numeric(df.iloc[3:25, 39])
tabela_ocr_fogos = pd.to_numeric(df2.iloc[:, 38])

diferenca_fogos = tabela_manual_fogos.values - tabela_ocr_fogos.values
diferenca_fogos

array([   7811,   39521,   49282,   30770,  100207,   37320,   44438,
        134765,   60386,   24950,  180307,   10774,   44211,   90232,
         65960,   22026,   14457,   61394,  280660,   25222,    7581,
       1332274])

In [359]:
for i in range(tabela_manual_fogos.size):
    if tabela_manual_fogos.iloc[i] - tabela_ocr_fogos.iloc[i] == 0 and tabela_manual_fogos.iloc[i] != 0:
        vp += 1
    if tabela_manual_fogos.iloc[i] - tabela_ocr_fogos.iloc[i] != 0 and tabela_manual_fogos.iloc[i] > 0 and tabela_ocr_fogos.iloc[i] > 0:
        fp += 1
    if tabela_manual_fogos.iloc[i] - tabela_ocr_fogos.iloc[i] == 0 and tabela_manual_fogos.iloc[i] == 0:
        vn += 1
    if tabela_manual_fogos.iloc[i] > 0 and tabela_ocr_fogos.iloc[i] == 0:
        fn += 1

print(vp, fp, vn, fn)

208 408 5 237

In [360]:
precision = vp / (vp + fp)
recall = vp / (vp + fn)
f1 = (2 * vp) / ((2 * vp) + fp + fn)

print("Precisão: " + str(round(precision, 3)))
print("Sensibilidade: " + str(round(recall, 3)))
print("F1-score: " + str(round(f1, 3)))

Precisão: 0.338
Sensibilidade: 0.467
F1-score: 0.392

In [361]:
variancia_fogos = np.var(diferenca_fogos)
variancia_fogos

73821542629.4215

In [362]:
desvio_padrao_fogos = np.std(diferenca_fogos)
desvio_padrao_fogos

271701.2010084267

In [363]:
coeficiente_variacao_fogos = desvio_padrao_fogos / np.mean(diferenca_fogos) * 100
coeficiente_variacao_fogos

224.33172238538725

In [364]:
print(f'Variância (fogos): {variancia_fogos}')
print(f'Desvio Padrão (fogos): {desvio_padrao_fogos}')
print(f'Coeficiente de Variação (fogos): {coeficiente_variacao_fogos}%')

Variância (fogos): 73821542629.4215
Desvio Padrão (fogos): 271701.2010084267
Coeficiente de Variação (fogos): 224.33172238538725%

In [365]:
media_fogos = np.mean(diferenca_fogos)
media_fogos

121115.81818181818

In [366]:
outlier_inferior_fogos = media_fogos - (3 * desvio_padrao_fogos)
outlier_superior_fogos = media_fogos + (3 * desvio_padrao_fogos)

print(outlier_inferior_fogos, outlier_superior_fogos)

-693987.784843462 936219.4212070983