In [1]:
import pandas as pd
import numpy as np
import pathfinder as pf

In [2]:
filename = "censo_1872-003_p1.csv"
folder = "planilhas"
path = pf.find_file(filename, folder)
df = pd.read_csv(path)
print(df.columns)

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')

In [3]:
filename = "marcado.csv"
folder = "resultados_ocr"
path = pf.find_file(filename, folder)
df2 = pd.read_csv(path, header=None)
print(df2.columns)

Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')

# Gêneros

In [4]:
sexos = df[['Unnamed: 0','Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3']]
sexos_header = sexos.iloc[1]
sexos.columns = sexos_header
sexos = sexos[2:]

sexos_header = sexos.iloc[0]
sexos.columns = sexos_header
sexos = sexos[1:]

columns_multiindex = pd.MultiIndex.from_tuples([
    #('Gêneros', 'Províncias e Município Neutro'),
    ('', 'Províncias e Município Neutro'),
    ('Gêneros', 'Homens'),
    ('Gêneros', 'Mulheres'),
    ('Gêneros', 'Total')
])

# Atribuindo o MultiIndex às colunas do DataFrame
sexos.columns = columns_multiindex

#print(sexos)
sexos

                                  Gêneros
   Províncias e Município Neutro   Homens Mulheres    Total
3                       Amazonas    30983     2564    56631
4                           Pará   128589    11919   247779
5                       Maranhão   141942    14215   284101
6                          Piauí    90322     8810   178427
7                          Ceará   350906    33886   689773
8            Rio Grande do Norte   112721    10823   220959
9                        Paraíba   179433    17526   354700
10                    Pernambuco   381565    37094   752511
11                       Alagoas   155584    15667   312268
12                       Sergipe    74739     7888   153620
13                         Bahia   630353    58143  1211792
14                Espírito Santo    29607    29871    59478
15              Município Neutro   133880    92153   226033
16                Rio de Janeiro   255806   234281   499087
17                     São Paulo   348304   332438   680742
18                        Paraná    59384    56858   116162
19                Santa Catarina    73088    71730   144818
20             Rio Grande do Sul   191022   176000   367022
21                  Minas Gerais   847592   821684  1669276
22                         Goiás    74968    74775   149743
23                   Mato Grosso    27991    25759    53750
24                         Total  4318699  4100973  8419672

In [5]:
print(df.columns)
print(df.iloc[3:25, 1])
print(df2.columns)
print(df2.iloc[:, 0])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       30983
4      128589
5      141942
6       90322
7      350906
8      112721
9      179433
10     381565
11     155584
12      74739
13     630353
14      29607
15     133880
16     255806
17     348304
18      59384
19      73088
20     191022
21     847592
22      74968
23      27991
24    4318699
Name: Unnamed: 1, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0       30983
1      128580
2      141942
3       90828
4      850906
5      112721
6      179493
7      381565
8      155584
9       78730
10     630858
11      29607
12     133880
13     255806
14     348804
15      69284
16      73088
17     191022
18         42
19      74968
20      27991
21    4318699
Name: 0, dtype: int64

In [6]:
print(df.columns)
print(df.iloc[3:25, 2])
print(df2.columns)
print(df2.iloc[:, 1])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        2564
4       11919
5       14215
6        8810
7       33886
8       10823
9       17526
10      37094
11      15667
12       7888
13      58143
14      29871
15      92153
16     234281
17     332438
18      56858
19      71730
20     176000
21     821684
22      74775
23      25759
24    4100973
Name: Unnamed: 2, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0        2604
1       11919
2       14915
3        8810
4      133884
5       10824
6      117626
7       87004
8        1506
9        7888
10      68143
11       2087
12       2158
13     934981
14     882439
15      56858
16      71730
17    1760001
18     821688
19          0
20      25759
21    4100973
Name: 1, dtype: int64

In [7]:
print(df.columns)
print(df.iloc[3:25, 3])
print(df2.columns)
print(df2.iloc[:, 2])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       56631
4      247779
5      284101
6      178427
7      689773
8      220959
9      354700
10     752511
11     312268
12     153620
13    1211792
14      59478
15     226033
16     499087
17     680742
18     116162
19     144818
20     367022
21    1669276
22     149743
23      53750
24    8419672
Name: Unnamed: 3, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0           0
1          29
2        8401
3           7
4           0
5      220959
6           0
7           0
8      812268
9      153620
10          0
11          0
12      26038
13     409087
14     680742
15     116169
16     124818
17     307092
18    1669276
19     140743
20      83760
21    8419672
Name: 2, dtype: int64

In [8]:
tabela_manual_homens = pd.to_numeric(df.iloc[3:25, 1])
tabela_ocr_homens = pd.to_numeric(df2.iloc[:, 0])

diferenca_homens = tabela_manual_homens.values - tabela_ocr_homens.values
diferenca_homens

array([      0,       9,       0,    -506, -500000,       0,     -60,
             0,       0,   -3991,    -505,       0,       0,       0,
          -500,   -9900,       0,       0,  847550,       0,       0,
             0])

In [9]:
tabela_manual_mulheres = pd.to_numeric(df.iloc[3:25, 2])
tabela_ocr_mulheres = pd.to_numeric(df2.iloc[:, 1])

diferenca_mulheres = tabela_manual_mulheres.values - tabela_ocr_mulheres.values
diferenca_mulheres

array([     -40,        0,     -700,        0,   -99998,       -1,
        -100100,   -49910,    14161,        0,   -10000,    27784,
          89995,  -700700,  -550001,        0,        0, -1584001,
             -4,    74775,        0,        0])

In [10]:
tabela_manual_total = pd.to_numeric(df.iloc[3:25, 3])
tabela_ocr_total = pd.to_numeric(df2.iloc[:, 2])

diferenca_total = tabela_manual_total.values - tabela_ocr_total.values
diferenca_total

array([  56631,  247750,  275700,  178420,  689773,       0,  354700,
        752511, -500000,       0, 1211792,   59478,  199995,   90000,
             0,      -7,   20000,   59930,       0,    9000,  -30010,
             0])

In [11]:
variancia_homens = np.var(diferenca_homens)
variancia_homens

43792845247.30785

In [12]:
variancia_mulheres = np.var(diferenca_mulheres)
variancia_mulheres

134568400366.32228

In [13]:
variancia_total = np.var(diferenca_total)
variancia_total

113692642128.42357

In [14]:
desvio_padrao_homens = np.std(diferenca_homens)
desvio_padrao_homens

209267.4013010814

In [15]:
desvio_padrao_mulheres = np.std(diferenca_mulheres)
desvio_padrao_mulheres

366835.6585261611

In [16]:
desvio_padrao_total = np.std(diferenca_total)
desvio_padrao_total

337183.3953925127

In [17]:
coeficiente_variacao_homens = desvio_padrao_homens / np.mean(diferenca_homens) * 100
coeficiente_variacao_homens

1386.3066599890367

In [18]:
coeficiente_variacao_mulheres = desvio_padrao_mulheres / np.mean(diferenca_mulheres) * 100
coeficiente_variacao_mulheres

-279.37386153047845

In [19]:
coeficiente_variacao_total = desvio_padrao_total / np.mean(diferenca_total) * 100
coeficiente_variacao_total

201.81487526563996

In [20]:
print(f'Variância (homens): {variancia_homens}')
print(f'Desvio Padrão (homens): {desvio_padrao_homens}')
print(f'Coeficiente de Variação (homens): {coeficiente_variacao_homens}%')

Variância (homens): 43792845247.30785
Desvio Padrão (homens): 209267.4013010814
Coeficiente de Variação (homens): 1386.3066599890367%

In [21]:
print(f'Variância (mulheres): {variancia_mulheres}')
print(f'Desvio Padrão (mulheres): {desvio_padrao_mulheres}')
print(f'Coeficiente de Variação (mulheres): {coeficiente_variacao_mulheres}%')

Variância (mulheres): 134568400366.32228
Desvio Padrão (mulheres): 366835.6585261611
Coeficiente de Variação (mulheres): -279.37386153047845%

In [22]:
print(f'Variância (total): {variancia_total}')
print(f'Desvio Padrão (total): {desvio_padrao_total}')
print(f'Coeficiente de Variação (total): {coeficiente_variacao_total}%')

Variância (total): 113692642128.42357
Desvio Padrão (total): 337183.3953925127
Coeficiente de Variação (total): 201.81487526563996%

In [23]:
media_homens = np.mean(diferenca_homens)
media_homens

15095.318181818182

In [24]:
media_mulheres = np.mean(diferenca_mulheres)
media_mulheres

-131306.36363636365

In [25]:
media_total = np.mean(diferenca_total)
media_total

167075.5909090909

In [26]:
outlier_inferior_homens = media_homens - (3 * desvio_padrao_homens)
outlier_superior_homens = media_homens + (3 * desvio_padrao_homens)

print(outlier_inferior_homens, outlier_superior_homens)

-612706.885721426 642897.5220850625

In [27]:
outlier_inferior_mulheres = media_mulheres - (3 * desvio_padrao_mulheres)
outlier_superior_mulheres = media_mulheres + (3 * desvio_padrao_mulheres)

print(outlier_inferior_mulheres, outlier_superior_mulheres)

-1231813.339214847 969200.6119421195

In [28]:
outlier_inferior_total = media_total - (3 * desvio_padrao_total)
outlier_superior_total = media_total + (3 * desvio_padrao_total)

print(outlier_inferior_total, outlier_superior_total)

-844474.5952684473 1178625.777086629

# Estados civis

In [29]:
estados_civis = df[['Unnamed: 0','Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9']]

estados_civis_header = estados_civis.iloc[2]
estados_civis.columns = estados_civis_header
estados_civis = estados_civis[3:]

columns_multiindex = pd.MultiIndex.from_tuples([
    #('Gêneros', 'Províncias e Município Neutro'),
    ('', '', 'Províncias e Município Neutro'),
    ('Estados civis', 'dos Homens', 'Solteiros'),
    ('Estados civis', 'dos Homens', 'Casados'),
    ('Estados civis', 'dos Homens', 'Viúvos'),
    ('Estados civis', 'das Mulheres', 'Solteiras'),
    ('Estados civis', 'das Mulheres', 'Casadas'),
    ('Estados civis', 'das Mulheres', 'Viúvas')
])

# Atribuindo o MultiIndex às colunas do DataFrame
estados_civis.columns = columns_multiindex

estados_civis

                                 Estados civis                                \
                                    dos Homens                  das Mulheres
   Províncias e Município Neutro     Solteiros  Casados  Viúvos    Solteiras
3                       Amazonas         24959     5105     919        19214
4                           Pará         94848    28935    4806        86825
5                       Maranhão        103283    33644    5015       102302
6                          Piauí         63294    23323    3705        59547
7                          Ceará        241692    99915    9299       224509
8            Rio Grande do Norte         80803    26832    5086        75915
9                        Paraíba        119403    53474    6556       112332
10                    Pernambuco        258936   111189   11440       240239
11                       Alagoas        102729    47865    4990        99772
12                       Sergipe         48013    24027    2699        50746
13                         Bahia        440556   160204   29593       398473
14                Espírito Santo         19415     9298     894        19251
15              Município Neutro        104036    25763    4081        64074
16                Rio de Janeiro        168391    71842   15573       148840
17                     São Paulo        234386    98864   15054       218684
18                        Paraná         37977    18649    2678        35006
19                Santa Catarina         49985    21351    1752        47122
20             Rio Grande do Sul        139899    45104    6019       124864
21                  Minas Gerais        572728   231947   42917       557389
22                         Goiás         51886    20696    2386        50125
23                   Mato Grosso         18227     7839    1925        17353
24                         Total       2975446  1165866  177387      2752582



    Casadas  Viúvas
3      4714    1720
4     26280    6085
5     32337    7520
6     23371    5187
7     99849   14509
8     26735    5588
9     53274    9661
10   111465   19242
11    46743   10169
12    24795    3340
13   151883   31083
14     9449    1171
15    20174    7905
16    68726   16715
17    96290   17464
18    18332    3520
19    20412    4196
20    41525    9611
21   217353   46942
22    20340    4310
23     6953    1453
24  1121000  227391

In [30]:
print(df.columns)
print(df.iloc[3:25, 4])
print(df2.columns)
print(df2.iloc[:, 3])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       24959
4       94848
5      103283
6       63294
7      241692
8       80803
9      119403
10     258936
11     102729
12      48013
13     440556
14      19415
15     104036
16     168391
17     234386
18      37977
19      49985
20     139899
21     572728
22      51886
23      18227
24    2975446
Name: Unnamed: 4, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0       24959
1       94848
2      103283
3       63294
4      241699
5       80803
6      119408
7      258936
8      102729
9       48018
10     440556
11      19415
12     104036
13     168391
14     234386
15      37977
16      49985
17     139899
18     572728
19      51886
20      18227
21    2975446
Name: 3, dtype: int64

In [31]:
print(df.columns)
print(df.iloc[3:25, 5])
print(df2.columns)
print(df2.iloc[:, 4])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        5105
4       28935
5       33644
6       23323
7       99915
8       26832
9       53474
10     111189
11      47865
12      24027
13     160204
14       9298
15      25763
16      71842
17      98864
18      18649
19      21351
20      45104
21     231947
22      20696
23       7839
24    1165866
Name: Unnamed: 5, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0        5105
1       28935
2       83644
3       23323
4       99915
5       26882
6        5874
7      111189
8       47865
9       24027
10     160204
11       9298
12      25763
13      71842
14      98864
15      18649
16      21851
17      45104
18     231947
19      20696
20       7839
21    1165866
Name: 4, dtype: int64

In [32]:
print(df.columns)
print(df.iloc[3:25, 6])
print(df2.columns)
print(df2.iloc[:, 5])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        919
4       4806
5       5015
6       3705
7       9299
8       5086
9       6556
10     11440
11      4990
12      2699
13     29593
14       894
15      4081
16     15573
17     15054
18      2678
19      1752
20      6019
21     42917
22      2386
23      1925
24    177387
Name: Unnamed: 6, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0        919
1       4806
2       5015
3       8705
4       9299
5       5086
6       6556
7      11440
8       4990
9       2699
10     29593
11       894
12      4081
13     15578
14     15054
15      2078
16      1752
17      6019
18     42917
19      9386
20      1925
21    177387
Name: 5, dtype: int64

In [33]:
print(df.columns)
print(df.iloc[3:25, 7])
print(df2.columns)
print(df2.iloc[:, 6])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       19214
4       86825
5      102302
6       59547
7      224509
8       75915
9      112332
10     240239
11      99772
12      50746
13     398473
14      19251
15      64074
16     148840
17     218684
18      35006
19      47122
20     124864
21     557389
22      50125
23      17353
24    2752582
Name: Unnamed: 7, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0       19214
1       86825
2      102302
3       50547
4      224509
5       75015
6      112339
7      240289
8       99772
9       80746
10     398473
11      19251
12      64074
13     148840
14     218684
15      35006
16      47122
17     124864
18     557389
19      50125
20      17353
21    2752562
Name: 6, dtype: int64

In [34]:
print(df.columns)
print(df.iloc[3:25, 8])
print(df2.columns)
print(df2.iloc[:, 7])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        4714
4       26280
5       32337
6       23371
7       99849
8       26735
9       53274
10     111465
11      46743
12      24795
13     151883
14       9449
15      20174
16      68726
17      96290
18      18332
19      20412
20      41525
21     217353
22      20340
23       6953
24    1121000
Name: Unnamed: 8, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0           0
1       26280
2       32331
3       23871
4       99819
5       26738
6       53274
7      111465
8       46748
9       24795
10     161888
11       9149
12      20174
13      68726
14      96200
15      18832
16      20419
17      41525
18     217353
19      20340
20       6953
21    1121000
Name: 7, dtype: int64

In [35]:
print(df.columns)
print(df.iloc[3:25, 9])
print(df2.columns)
print(df2.iloc[:, 8])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       1720
4       6085
5       7520
6       5187
7      14509
8       5588
9       9661
10     19242
11     10169
12      3340
13     31083
14      1171
15      7905
16     16715
17     17464
18      3520
19      4196
20      9611
21     46942
22      4310
23      1453
24    227391
Name: Unnamed: 9, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0       1720
1       6089
2       1520
3        518
4       1450
5        658
6       9661
7      19242
8      10169
9       2340
10     31083
11      1171
12      7905
13     16715
14     17464
15      3520
16      4196
17      9611
18       404
19      4310
20      1453
21    227891
Name: 8, dtype: int64

In [36]:
tabela_manual_solteiros = pd.to_numeric(df.iloc[3:25, 4])
tabela_ocr_solteiros = pd.to_numeric(df2.iloc[:, 3])

diferenca_solteiros = tabela_manual_solteiros.values - tabela_ocr_solteiros.values
diferenca_solteiros

array([ 0,  0,  0,  0, -7,  0, -5,  0,  0, -5,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0])

In [37]:
tabela_manual_casados = pd.to_numeric(df.iloc[3:25, 5])
tabela_ocr_casados = pd.to_numeric(df2.iloc[:, 4])

diferenca_casados = tabela_manual_casados.values - tabela_ocr_casados.values
diferenca_casados

array([     0,      0, -50000,      0,      0,    -50,  47600,      0,
            0,      0,      0,      0,      0,      0,      0,      0,
         -500,      0,      0,      0,      0,      0])

In [38]:
tabela_manual_viuvos = pd.to_numeric(df.iloc[3:25, 6])
tabela_ocr_viuvos = pd.to_numeric(df2.iloc[:, 5])

diferenca_viuvos = tabela_manual_viuvos.values - tabela_ocr_viuvos.values
diferenca_viuvos

array([    0,     0,     0, -5000,     0,     0,     0,     0,     0,
           0,     0,     0,     0,    -5,     0,   600,     0,     0,
           0, -7000,     0,     0])

In [39]:
tabela_manual_solteiras = pd.to_numeric(df.iloc[3:25, 7])
tabela_ocr_solteiras = pd.to_numeric(df2.iloc[:, 6])

diferenca_solteiras = tabela_manual_solteiras.values - tabela_ocr_solteiras.values
diferenca_solteiras

array([     0,      0,      0,   9000,      0,    900,     -7,    -50,
            0, -30000,      0,      0,      0,      0,      0,      0,
            0,      0,      0,      0,      0,     20])

In [40]:
tabela_manual_casadas = pd.to_numeric(df.iloc[3:25, 8])
tabela_ocr_casadas = pd.to_numeric(df2.iloc[:, 7])

diferenca_casadas = tabela_manual_casadas.values - tabela_ocr_casadas.values
diferenca_casadas

array([  4714,      0,      6,   -500,     30,     -3,      0,      0,
           -5,      0, -10005,    300,      0,      0,     90,   -500,
           -7,      0,      0,      0,      0,      0])

In [41]:
tabela_manual_viuvas = pd.to_numeric(df.iloc[3:25, 9])
tabela_ocr_viuvas = pd.to_numeric(df2.iloc[:, 8])

diferenca_viuvas = tabela_manual_viuvas.values - tabela_ocr_viuvas.values
diferenca_viuvas

array([    0,    -4,  6000,  4669, 13059,  4930,     0,     0,     0,
        1000,     0,     0,     0,     0,     0,     0,     0,     0,
       46538,     0,     0,  -500])

In [42]:
variancia_solteiros = np.var(diferenca_solteiros)
variancia_solteiros

3.9028925619834696

In [43]:
variancia_casados = np.var(diferenca_casados)
variancia_casados

216618951.44628093

In [44]:
variancia_viuvos = np.var(diferenca_viuvos)
variancia_viuvos

3111253.1508264462

In [45]:
variancia_solteiras = np.var(diferenca_solteiras)
variancia_solteiras

43790053.94421487

In [46]:
variancia_casadas = np.var(diferenca_casadas)
variancia_casadas

5515880.743801652

In [47]:
variancia_viuvas = np.var(diferenca_viuvas)
variancia_viuvas

98147983.42975207

In [48]:
desvio_padrao_solteiros = np.std(diferenca_solteiros)
desvio_padrao_solteiros

1.975573982918248

In [49]:
desvio_padrao_casados = np.std(diferenca_casados)
desvio_padrao_casados

14717.980549188158

In [50]:
desvio_padrao_viuvos = np.std(diferenca_viuvos)
desvio_padrao_viuvos

1763.874471391444

In [51]:
desvio_padrao_solteiras = np.std(diferenca_solteiras)
desvio_padrao_solteiras

6617.405378561515

In [52]:
desvio_padrao_casadas = np.std(diferenca_casadas)
desvio_padrao_casadas

2348.5912253522647

In [53]:
desvio_padrao_viuvas = np.std(diferenca_viuvas)
desvio_padrao_viuvas

9906.966409035213

In [54]:
coeficiente_variacao_solteiros = desvio_padrao_solteiros / np.mean(diferenca_solteiros) * 100
coeficiente_variacao_solteiros

-255.66251543647917

In [55]:
coeficiente_variacao_casados = desvio_padrao_casados / np.mean(diferenca_casados) * 100
coeficiente_variacao_casados

-10976.121087530151

In [56]:
coeficiente_variacao_viuvos = desvio_padrao_viuvos / np.mean(diferenca_viuvos) * 100
coeficiente_variacao_viuvos

-340.24759641044955

In [57]:
coeficiente_variacao_solteiras = desvio_padrao_solteiras / np.mean(diferenca_solteiras) * 100
coeficiente_variacao_solteiras

-722.962299887537

In [58]:
coeficiente_variacao_casadas = desvio_padrao_casadas / np.mean(diferenca_casadas) * 100
coeficiente_variacao_casadas

-878.724608124997

In [59]:
coeficiente_variacao_viuvas = desvio_padrao_viuvas / np.mean(diferenca_viuvas) * 100
coeficiente_variacao_viuvas

287.9475519193239

In [60]:
print(f'Variância (solteiros): {variancia_solteiros}')
print(f'Desvio Padrão (solteiros): {desvio_padrao_solteiros}')
print(f'Coeficiente de Variação (solteiros): {coeficiente_variacao_solteiros}%')

Variância (solteiros): 3.9028925619834696
Desvio Padrão (solteiros): 1.975573982918248
Coeficiente de Variação (solteiros): -255.66251543647917%

In [61]:
print(f'Variância (casados): {variancia_casados}')
print(f'Desvio Padrão (casados): {desvio_padrao_casados}')
print(f'Coeficiente de Variação (casados): {coeficiente_variacao_casados}%')

Variância (casados): 216618951.44628093
Desvio Padrão (casados): 14717.980549188158
Coeficiente de Variação (casados): -10976.121087530151%

In [62]:
print(f'Variância (viúvos): {variancia_viuvos}')
print(f'Desvio Padrão (viúvos): {desvio_padrao_viuvos}')
print(f'Coeficiente de Variação (viúvos): {coeficiente_variacao_viuvos}%')

Variância (viúvos): 3111253.1508264462
Desvio Padrão (viúvos): 1763.874471391444
Coeficiente de Variação (viúvos): -340.24759641044955%

In [63]:
print(f'Variância (solteiras): {variancia_solteiras}')
print(f'Desvio Padrão (solteiras): {desvio_padrao_solteiras}')
print(f'Coeficiente de Variação (solteiras): {coeficiente_variacao_solteiras}%')

Variância (solteiras): 43790053.94421487
Desvio Padrão (solteiras): 6617.405378561515
Coeficiente de Variação (solteiras): -722.962299887537%

In [64]:
print(f'Variância (casadas): {variancia_casadas}')
print(f'Desvio Padrão (casadas): {desvio_padrao_casadas}')
print(f'Coeficiente de Variação (casadas): {coeficiente_variacao_casadas}%')

Variância (casadas): 5515880.743801652
Desvio Padrão (casadas): 2348.5912253522647
Coeficiente de Variação (casadas): -878.724608124997%

In [65]:
print(f'Variância (viúvas): {variancia_viuvas}')
print(f'Desvio Padrão (viúvas): {desvio_padrao_viuvas}')
print(f'Coeficiente de Variação (viúvas): {coeficiente_variacao_viuvas}%')

Variância (viúvas): 98147983.42975207
Desvio Padrão (viúvas): 9906.966409035213
Coeficiente de Variação (viúvas): 287.9475519193239%

In [66]:
media_solteiros = np.mean(diferenca_solteiros)
media_solteiros

-0.7727272727272727

In [67]:
media_casados = np.mean(diferenca_casados)
media_casados

-134.0909090909091

In [68]:
media_viuvos = np.mean(diferenca_viuvos)
media_viuvos

-518.4090909090909

In [69]:
media_solteiras = np.mean(diferenca_solteiras)
media_solteiras

-915.3181818181819

In [70]:
media_casadas = np.mean(diferenca_casadas)
media_casadas

-267.27272727272725

In [71]:
media_viuvas = np.mean(diferenca_viuvas)
media_viuvas

3440.5454545454545

In [72]:
outlier_inferior_solteiros = media_solteiros - (3 * desvio_padrao_solteiros)
outlier_superior_solteiros = media_solteiros + (3 * desvio_padrao_solteiros)

print(outlier_inferior_solteiros, outlier_superior_solteiros)

-6.699449221482016 5.153994676027471

In [73]:
outlier_inferior_casados = media_casados - (3 * desvio_padrao_casados)
outlier_superior_casados = media_casados + (3 * desvio_padrao_casados)

print(outlier_inferior_casados, outlier_superior_casados)

-44288.03255665539 44019.850738473564

In [74]:
outlier_inferior_viuvos = media_viuvos - (3 * desvio_padrao_viuvos)
outlier_superior_viuvos = media_viuvos + (3 * desvio_padrao_viuvos)

print(outlier_inferior_viuvos, outlier_superior_viuvos)

-5810.0325050834235 4773.214323265242

In [75]:
outlier_inferior_solteiras = media_solteiras - (3 * desvio_padrao_solteiras)
outlier_superior_solteiras = media_solteiras + (3 * desvio_padrao_solteiras)

print(outlier_inferior_solteiras, outlier_superior_solteiras)

-20767.534317502726 18936.897953866366

In [76]:
outlier_inferior_casadas = media_casadas - (3 * desvio_padrao_casadas)
outlier_superior_casadas = media_casadas + (3 * desvio_padrao_casadas)

print(outlier_inferior_casadas, outlier_superior_casadas)

-7313.046403329521 6778.500948784067

In [77]:
outlier_inferior_viuvas = media_viuvas - (3 * desvio_padrao_viuvas)
outlier_superior_viuvas = media_viuvas + (3 * desvio_padrao_viuvas)

print(outlier_inferior_viuvas, outlier_superior_viuvas)

-26280.353772560182 33161.44468165109

# Raças

In [78]:
racas = df[['Unnamed: 0','Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17']]

columns_multiindex = pd.MultiIndex.from_tuples([
    ('', '', 'Províncias e Município Neutro'),
    ('Raças', 'dos Homens', 'Brancos'),
    ('Raças', 'dos Homens', 'Pardos'),
    ('Raças', 'dos Homens', 'Pretos'),
    ('Raças', 'dos Homens', 'Caboclos'),
    ('Raças', 'das Mulheres', 'Brancas'),
    ('Raças', 'das Mulheres', 'Pardas'),
    ('Raças', 'das Mulheres', 'Pretas'),
    ('Raças', 'das Mulheres', 'Caboclas')
])

racas.columns = columns_multiindex

racas

                                        Raças                             \
                                   dos Homens
    Províncias e Município Neutro     Brancos   Pardos  Pretos  Caboclos
0                             NaN       Raças      NaN     NaN       NaN
1                             NaN  dos Homens      NaN     NaN       NaN
2   Províncias e Município Neutro     Brancos   Pardos  Pretos  Caboclos
3                        Amazonas        6911     4210     711     19151
4                            Pará       49663    46899    9200     22827
5                        Maranhão       52267    71662   12504      5509
6                           Piauí       22208    53474    7505      7135
7                           Ceará      136940   172841   14424     26701
8             Rio Grande do Norte       52835    42213   12202      5471
9                         Paraíba       73475    89921   11155      4882
10                     Pernambuco      149930   194897   30795      5943
11                        Alagoas       45343    98916    8220      3105
12                        Sergipe       24358    39524    9321      1536
13                          Bahia      178605   287131  137574     27043
14                 Espírito Santo       13555     9648    3395      3009
15               Município Neutro       96255    22762   14198       665
16                 Rio de Janeiro      160595    61542   29517      4152
17                      São Paulo      221260    76288   29512     21244
18                         Paraná       35936    15358    3292      4718
19                 Santa Catarina       63502     5941    2199      1446
20              Rio Grande do Sul      136094    24487   17828     12613
21                   Minas Gerais      421861   302948  105507     17276
22                          Goiás       21152    42482    9088      2246
23                    Mato Grosso        9027    10827    3861      4276
24                          Total     1971772  1673971  472008    200948


    das Mulheres
         Brancas   Pardas  Pretas  Caboclas
0            NaN      NaN     NaN       NaN
1   das Mulheres      NaN     NaN       NaN
2        Brancas   Pardas  Pretas  Caboclas
3           4300     3046     625     17677
4          42971    46828    7629     21762
5          51246    72699   12780      5434
6          21239    53191    7357      6318
7         131896   166325   14510     26136
8          49630    41877   11163      5568
9          71246    88675   10661      4685
10        141229   192954   30901      5862
11         43455   101283    8687      3259
12         25420    42059    9851      1551
13        152874   278573  127153     22839
14         13027    10881    3443      2520
15         55544    22083   14268       258
16        142680    59703   28198      3700
17        212172    75018   27027     18221
18         33762    15278    3449      4369
19         62440     5796    2048      1446
20        122273    24179   16444     13104
21        409126   295865  101647     15046
22         20777    43907    8087      2004
23          8210    10087    3214      4248
24       1815517  1650307  449142    186007

In [79]:
print(df.columns)
print(df.iloc[3:25, 10])
print(df2.columns)
print(df2.iloc[:, 9])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        6911
4       49663
5       52267
6       22208
7      136940
8       52835
9       73475
10     149930
11      45343
12      24358
13     178605
14      13555
15      96255
16     160595
17     221260
18      35936
19      63502
20     136094
21     421861
22      21152
23       9027
24    1971772
Name: Unnamed: 10, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0        690
1      49603
2      52267
3      22208
4     136949
5      52835
6          0
7     149930
8          0
9      24358
10    178605
11     13555
12     96255
13    180595
14    221260
15     85926
16     63502
17    136094
18    425861
19     21152
20        90
21      1772
Name: 9, dtype: int64

In [80]:
print(df.columns)
print(df.iloc[3:25, 11])
print(df2.columns)
print(df2.iloc[:, 10])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        4210
4       46899
5       71662
6       53474
7      172841
8       42213
9       89921
10     194897
11      98916
12      39524
13     287131
14       9648
15      22762
16      61542
17      76288
18      15358
19       5941
20      24487
21     302948
22      42482
23      10827
24    1673971
Name: Unnamed: 11, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0        4210
1       46899
2       71662
3       58474
4      172841
5       42213
6       39921
7      194897
8       98916
9       39524
10     287181
11       9648
12      22762
13      61542
14      76288
15      15358
16         94
17          0
18     302048
19       4242
20      10827
21    4073971
Name: 10, dtype: int64

In [81]:
print(df.columns)
print(df.iloc[3:25, 12])
print(df2.columns)
print(df2.iloc[:, 11])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        711
4       9200
5      12504
6       7505
7      14424
8      12202
9      11155
10     30795
11      8220
12      9321
13    137574
14      3395
15     14198
16     29517
17     29512
18      3292
19      2199
20     17828
21    105507
22      9088
23      3861
24    472008
Name: Unnamed: 12, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0          0
1       9200
2      12504
3       7505
4      14423
5      12202
6          0
7          0
8       8220
9       9321
10    137574
11      3895
12     14198
13     29517
14     29512
15      3209
16      2199
17     17828
18    105507
19      9088
20      8861
21    472008
Name: 11, dtype: int64

In [82]:
print(df.columns)
print(df.iloc[3:25, 13])
print(df2.columns)
print(df2.iloc[:, 12])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3      19151
4      22827
5       5509
6       7135
7      26701
8       5471
9       4882
10      5943
11      3105
12      1536
13     27043
14      3009
15       665
16      4152
17     21244
18      4718
19      1446
20     12613
21     17276
22      2246
23      4276
24    200948
Name: Unnamed: 13, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0      19151
1     228927
2       5509
3       7135
4      26701
5       5471
6       4882
7       5043
8       3105
9       1536
10     27018
11      3008
12       665
13       452
14       212
15      4718
16      1446
17     12618
18     17276
19      2246
20      4276
21    200948
Name: 12, dtype: int64

In [83]:
print(df.columns)
print(df.iloc[3:25, 14])
print(df2.columns)
print(df2.iloc[:, 13])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        4300
4       42971
5       51246
6       21239
7      131896
8       49630
9       71246
10     141229
11      43455
12      25420
13     152874
14      13027
15      55544
16     142680
17     212172
18      33762
19      62440
20     122273
21     409126
22      20777
23       8210
24    1815517
Name: Unnamed: 14, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0        4300
1       42977
2       51246
3       21239
4      121896
5       49630
6       71246
7      141229
8       43455
9       25420
10     152874
11      19027
12      55544
13     142080
14     212179
15      38762
16          2
17     122278
18     409126
19      20777
20       8210
21    1815617
Name: 13, dtype: int64

In [84]:
print(df.columns)
print(df.iloc[3:25, 15])
print(df2.columns)
print(df2.iloc[:, 14])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        3046
4       46828
5       72699
6       53191
7      166325
8       41877
9       88675
10     192954
11     101283
12      42059
13     278573
14      10881
15      22083
16      59703
17      75018
18      15278
19       5796
20      24179
21     295865
22      43907
23      10087
24    1650307
Name: Unnamed: 15, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0         3046
1        40898
2        72699
3         3191
4       160325
5        41877
6        88675
7       192054
8       101283
9        42059
10           0
11       10881
12       22083
13       59703
14       78018
15       16278
16        5796
17       24179
18      298865
19       43907
20       10087
21    10508074
Name: 14, dtype: int64

In [85]:
print(df.columns)
print(df.iloc[3:25, 16])
print(df2.columns)
print(df2.iloc[:, 15])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        625
4       7629
5      12780
6       7357
7      14510
8      11163
9      10661
10     30901
11      8687
12      9851
13    127153
14      3443
15     14268
16     28198
17     27027
18      3449
19      2048
20     16444
21    101647
22      8087
23      3214
24    449142
Name: Unnamed: 16, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0        625
1       7629
2      12780
3       7357
4      14510
5      12163
6      10661
7      80901
8       8687
9       9851
10    127163
11      3443
12     14268
13     28198
14     27027
15      3419
16      2048
17     16444
18    101647
19         7
20      3214
21         0
Name: 15, dtype: int64

In [86]:
print(df.columns)
print(df.iloc[3:25, 17])
print(df2.columns)
print(df2.iloc[:, 16])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3      17677
4      21762
5       5434
6       6318
7      26136
8       5568
9       4685
10      5862
11      3259
12      1551
13     22839
14      2520
15       258
16      3700
17     18221
18      4369
19      1446
20     13104
21     15046
22      2004
23      4248
24    186007
Name: Unnamed: 17, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0        677
1      21762
2       5434
3       6318
4      25186
5       6568
6       4685
7       5862
8       3259
9       1551
10     22889
11      2520
12       258
13      3700
14     18221
15      4369
16      1446
17     18104
18     15046
19      2004
20      4248
21    186007
Name: 16, dtype: int64

In [87]:
tabela_manual_brancos = pd.to_numeric(df.iloc[3:25, 10])
tabela_ocr_brancos = pd.to_numeric(df2.iloc[:, 9])

diferenca_brancos = tabela_manual_brancos.values - tabela_ocr_brancos.values
diferenca_brancos

array([   6221,      60,       0,       0,      -9,       0,   73475,
             0,   45343,       0,       0,       0,       0,  -20000,
             0,  -49990,       0,       0,   -4000,       0,    8937,
       1970000])

In [88]:
tabela_manual_pardos = pd.to_numeric(df.iloc[3:25, 11])
tabela_ocr_pardos = pd.to_numeric(df2.iloc[:, 10])

diferenca_pardos = tabela_manual_pardos.values - tabela_ocr_pardos.values
diferenca_pardos

array([       0,        0,        0,    -5000,        0,        0,
          50000,        0,        0,        0,      -50,        0,
              0,        0,        0,        0,     5847,    24487,
            900,    38240,        0, -2400000])

In [89]:
tabela_manual_pretos = pd.to_numeric(df.iloc[3:25, 12])
tabela_ocr_pretos = pd.to_numeric(df2.iloc[:, 11])

diferenca_pretos = tabela_manual_pretos.values - tabela_ocr_pretos.values
diferenca_pretos

array([  711,     0,     0,     0,     1,     0, 11155, 30795,     0,
           0,     0,  -500,     0,     0,     0,    83,     0,     0,
           0,     0, -5000,     0])

In [90]:
tabela_manual_caboclos = pd.to_numeric(df.iloc[3:25, 13])
tabela_ocr_caboclos = pd.to_numeric(df2.iloc[:, 12])

diferenca_caboclos = tabela_manual_caboclos.values - tabela_ocr_caboclos.values
diferenca_caboclos

array([      0, -206100,       0,       0,       0,       0,       0,
           900,       0,       0,      25,       1,       0,    3700,
         21032,       0,       0,      -5,       0,       0,       0,
             0])

In [91]:
tabela_manual_brancas = pd.to_numeric(df.iloc[3:25, 14])
tabela_ocr_brancas = pd.to_numeric(df2.iloc[:, 13])

diferenca_brancas = tabela_manual_brancas.values - tabela_ocr_brancas.values
diferenca_brancas

array([    0,    -6,     0,     0, 10000,     0,     0,     0,     0,
           0,     0, -6000,     0,   600,    -7, -5000, 62438,    -5,
           0,     0,     0,  -100])

In [92]:
tabela_manual_pardas = pd.to_numeric(df.iloc[3:25, 15])
tabela_ocr_pardas = pd.to_numeric(df2.iloc[:, 14])

diferenca_pardas = tabela_manual_pardas.values - tabela_ocr_pardas.values
diferenca_pardas

array([       0,     5930,        0,    50000,     6000,        0,
              0,      900,        0,        0,   278573,        0,
              0,        0,    -3000,    -1000,        0,        0,
          -3000,        0,        0, -8857767])

In [93]:
tabela_manual_pretas = pd.to_numeric(df.iloc[3:25, 16])
tabela_ocr_pretas = pd.to_numeric(df2.iloc[:, 15])

diferenca_pretas = tabela_manual_pretas.values - tabela_ocr_pretas.values
diferenca_pretas

array([     0,      0,      0,      0,      0,  -1000,      0, -50000,
            0,      0,    -10,      0,      0,      0,      0,     30,
            0,      0,      0,   8080,      0, 449142])

In [94]:
tabela_manual_caboclas = pd.to_numeric(df.iloc[3:25, 17])
tabela_ocr_caboclas = pd.to_numeric(df2.iloc[:, 16])

diferenca_caboclas = tabela_manual_caboclas.values - tabela_ocr_caboclas.values
diferenca_caboclas

array([17000,     0,     0,     0,   950, -1000,     0,     0,     0,
           0,   -50,     0,     0,     0,     0,     0,     0, -5000,
           0,     0,     0,     0])

In [95]:
variancia_brancos = np.var(diferenca_brancos)
variancia_brancos

168366712420.78717

In [96]:
variancia_pardos = np.var(diferenca_pardos)
variancia_pardos

251235174345.33054

In [97]:
variancia_pretos = np.var(diferenca_pretos)
variancia_pretos

47067016.770661175

In [98]:
variancia_caboclos = np.var(diferenca_caboclos)
variancia_caboclos

1884272944.2995875

In [99]:
variancia_brancas = np.var(diferenca_brancas)
variancia_brancas

176618059.06611574

In [100]:
variancia_pardas = np.var(diferenca_pardas)
variancia_pardas

3419911836175.4126

In [101]:
variancia_pretas = np.var(diferenca_pretas)
variancia_pretas

8945151974.884296

In [102]:
variancia_caboclas = np.var(diferenca_caboclas)
variancia_caboclas

14066735.537190082

In [103]:
desvio_padrao_brancos = np.std(diferenca_brancos)
desvio_padrao_brancos

410325.13013558794

In [104]:
desvio_padrao_pardos = np.std(diferenca_pardos)
desvio_padrao_pardos

501233.65244697063

In [105]:
desvio_padrao_pretos = np.std(diferenca_pretos)
desvio_padrao_pretos

6860.54055965426

In [106]:
desvio_padrao_caboclos = np.std(diferenca_caboclos)
desvio_padrao_caboclos

43408.2128669171

In [107]:
desvio_padrao_brancas = np.std(diferenca_brancas)
desvio_padrao_brancas

13289.772724396596

In [108]:
desvio_padrao_pardas = np.std(diferenca_pardas)
desvio_padrao_pardas

1849300.3639688748

In [109]:
desvio_padrao_pretas = np.std(diferenca_pretas)
desvio_padrao_pretas

94578.81356246913

In [110]:
desvio_padrao_caboclas = np.std(diferenca_caboclas)
desvio_padrao_caboclas

3750.5646957745016

In [111]:
coeficiente_variacao_brancos = desvio_padrao_brancos / np.mean(diferenca_brancos) * 100
coeficiente_variacao_brancos

444.6792281610106

In [112]:
coeficiente_variacao_pardos = desvio_padrao_pardos / np.mean(diferenca_pardos) * 100
coeficiente_variacao_pardos

-482.46657970828164

In [113]:
coeficiente_variacao_pretos = desvio_padrao_pretos / np.mean(diferenca_pretos) * 100
coeficiente_variacao_pretos

405.24068280948774

In [114]:
coeficiente_variacao_caboclos = desvio_padrao_caboclos / np.mean(diferenca_caboclos) * 100
coeficiente_variacao_caboclos

-529.2305680184077

In [115]:
coeficiente_variacao_brancas = desvio_padrao_brancas / np.mean(diferenca_brancas) * 100
coeficiente_variacao_brancas

472.18184744303153

In [116]:
coeficiente_variacao_pardas = desvio_padrao_pardas / np.mean(diferenca_pardas) * 100
coeficiente_variacao_pardas

-477.33040624940156

In [117]:
coeficiente_variacao_pretas = desvio_padrao_pretas / np.mean(diferenca_pretas) * 100
coeficiente_variacao_pretas

512.1907381251375

In [118]:
coeficiente_variacao_caboclas = desvio_padrao_caboclas / np.mean(diferenca_caboclas) * 100
coeficiente_variacao_caboclas

693.381708462513

In [119]:
print(f'Variância (brancos): {variancia_brancos}')
print(f'Desvio Padrão (brancos): {desvio_padrao_brancos}')
print(f'Coeficiente de Variação (brancos): {coeficiente_variacao_brancos}%')

Variância (brancos): 168366712420.78717
Desvio Padrão (brancos): 410325.13013558794
Coeficiente de Variação (brancos): 444.6792281610106%

In [120]:
print(f'Variância (pardos): {variancia_pardos}')
print(f'Desvio Padrão (pardos): {desvio_padrao_pardos}')
print(f'Coeficiente de Variação (pardos): {coeficiente_variacao_pardos}%')

Variância (pardos): 251235174345.33054
Desvio Padrão (pardos): 501233.65244697063
Coeficiente de Variação (pardos): -482.46657970828164%

In [121]:
print(f'Variância (pretos): {variancia_pretos}')
print(f'Desvio Padrão (pretos): {desvio_padrao_pretos}')
print(f'Coeficiente de Variação (pretos): {coeficiente_variacao_pretos}%')

Variância (pretos): 47067016.770661175
Desvio Padrão (pretos): 6860.54055965426
Coeficiente de Variação (pretos): 405.24068280948774%

In [122]:
print(f'Variância (caboclos): {variancia_caboclos}')
print(f'Desvio Padrão (caboclos): {desvio_padrao_caboclos}')
print(f'Coeficiente de Variação (caboclos): {coeficiente_variacao_caboclos}%')

Variância (caboclos): 1884272944.2995875
Desvio Padrão (caboclos): 43408.2128669171
Coeficiente de Variação (caboclos): -529.2305680184077%

In [123]:
print(f'Variância (brancas): {variancia_brancas}')
print(f'Desvio Padrão (brancas): {desvio_padrao_brancas}')
print(f'Coeficiente de Variação (brancas): {coeficiente_variacao_brancas}%')

Variância (brancas): 176618059.06611574
Desvio Padrão (brancas): 13289.772724396596
Coeficiente de Variação (brancas): 472.18184744303153%

In [124]:
print(f'Variância (pardas): {variancia_pardas}')
print(f'Desvio Padrão (pardas): {desvio_padrao_pardas}')
print(f'Coeficiente de Variação (pardas): {coeficiente_variacao_pardas}%')

Variância (pardas): 3419911836175.4126
Desvio Padrão (pardas): 1849300.3639688748
Coeficiente de Variação (pardas): -477.33040624940156%

In [125]:
print(f'Variância (pretas): {variancia_pretas}')
print(f'Desvio Padrão (pretas): {desvio_padrao_pretas}')
print(f'Coeficiente de Variação (pretas): {coeficiente_variacao_pretas}%')

Variância (pretas): 8945151974.884296
Desvio Padrão (pretas): 94578.81356246913
Coeficiente de Variação (pretas): 512.1907381251375%

In [126]:
print(f'Variância (caboclas): {variancia_caboclas}')
print(f'Desvio Padrão (caboclas): {desvio_padrao_caboclas}')
print(f'Coeficiente de Variação (caboclas): {coeficiente_variacao_caboclas}%')

Variância (caboclas): 14066735.537190082
Desvio Padrão (caboclas): 3750.5646957745016
Coeficiente de Variação (caboclas): 693.381708462513%

In [127]:
media_brancos = np.mean(diferenca_brancos)
media_brancos

92274.40909090909

In [128]:
media_pardos = np.mean(diferenca_pardos)
media_pardos

-103889.81818181818

In [129]:
media_pretos = np.mean(diferenca_pretos)
media_pretos

1692.9545454545455

In [130]:
media_caboclos = np.mean(diferenca_caboclos)
media_caboclos

-8202.136363636364

In [131]:
media_brancas = np.mean(diferenca_brancas)
media_brancas

2814.5454545454545

In [132]:
media_pardas = np.mean(diferenca_pardas)
media_pardas

-387425.63636363635

In [133]:
media_pretas = np.mean(diferenca_pretas)
media_pretas

18465.545454545456

In [134]:
media_caboclas = np.mean(diferenca_caboclas)
media_caboclas

540.9090909090909

In [135]:
outlier_inferior_brancos = media_brancos - (3 * desvio_padrao_brancos)
outlier_superior_brancos = media_brancos + (3 * desvio_padrao_brancos)

print(outlier_inferior_brancos, outlier_superior_brancos)

-1138700.9813158547 1323249.799497673

In [136]:
outlier_inferior_pardos = media_pardos - (3 * desvio_padrao_pardos)
outlier_superior_pardos = media_pardos + (3 * desvio_padrao_pardos)

print(outlier_inferior_pardos, outlier_superior_pardos)

-1607590.77552273 1399811.1391590938

In [137]:
outlier_inferior_pretos = media_pretos - (3 * desvio_padrao_pretos)
outlier_superior_pretos = media_pretos + (3 * desvio_padrao_pretos)

print(outlier_inferior_pretos, outlier_superior_pretos)

-18888.667133508236 22274.576224417324

In [138]:
outlier_inferior_caboclos = media_caboclos - (3 * desvio_padrao_caboclos)
outlier_superior_caboclos = media_caboclos + (3 * desvio_padrao_caboclos)

print(outlier_inferior_caboclos, outlier_superior_caboclos)

-138426.77496438765 122022.50223711492

In [139]:
outlier_inferior_brancas = media_brancas - (3 * desvio_padrao_brancas)
outlier_superior_brancas = media_brancas + (3 * desvio_padrao_brancas)

print(outlier_inferior_brancas, outlier_superior_brancas)

-37054.77271864434 42683.86362773525

In [140]:
outlier_inferior_pardas = media_pardas - (3 * desvio_padrao_pardas)
outlier_superior_pardas = media_pardas + (3 * desvio_padrao_pardas)

print(outlier_inferior_pardas, outlier_superior_pardas)

-5935326.728270261 5160475.455542987

In [141]:
outlier_inferior_pretas = media_pretas - (3 * desvio_padrao_pretas)
outlier_superior_pretas = media_pretas + (3 * desvio_padrao_pretas)

print(outlier_inferior_pretas, outlier_superior_pretas)

-265270.8952328619 302201.98614195286

In [142]:
outlier_inferior_caboclas = media_caboclas - (3 * desvio_padrao_caboclas)
outlier_superior_caboclas = media_caboclas + (3 * desvio_padrao_caboclas)

print(outlier_inferior_caboclas, outlier_superior_caboclas)

-10710.784996414415 11792.603178232595

# Religião

In [143]:
religiao = df[['Unnamed: 0','Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21']]

religiao_header = religiao.iloc[2]
religiao.columns = religiao_header
religiao = religiao[3:]

columns_multiindex = pd.MultiIndex.from_tuples([
    ('', '', 'Províncias e Município Neutro'),
    ('Religião', 'dos Homens', 'Católicos'),
    ('Religião', 'dos Homens', 'Acatólicos'),
    ('Religião', 'das Mulheres', 'Católicas'),
    ('Religião', 'das Mulheres', 'Acatólicas')
])

religiao.columns = columns_multiindex

religiao

                                   Religião
                                 dos Homens            das Mulheres
   Províncias e Município Neutro  Católicos Acatólicos    Católicas Acatólicas
3                       Amazonas      30903         80        25641          7
4                           Pará     128396        193       119169         21
5                       Maranhão     141865         77       142100         59
6                          Piauí      90313          9        88105          0
7                          Ceará     350868         38       338857         10
8            Rio Grande do Norte     112717          4       108238          0
9                        Paraíba     179429          4       175266          1
10                    Pernambuco     381361        204       370906         40
11                       Alagoas     155557         27       156683          1
12                       Sergipe      74739          0        78881          0
13                         Bahia     630196        157       581384         55
14                Espírito Santo      29377        230        29687        184
15              Município Neutro     132552       1328        91553        600
16                Rio de Janeiro     255433        373       234066        215
17                     São Paulo     346326       1973       331217       1221
18                        Paraná      58755        549        56594        264
19                Santa Catarina      67635       5453        66742       4988
20             Rio Grande do Sul     187182       3840       173617       2383
21                  Minas Gerais     845840       1752       820290       1394
22                         Goiás      74967          1        74775          0
23                   Mato Grosso      27975         16        25749         10
24                         Total    4302386      16313      4089520      11453

In [144]:
print(df.columns)
print(df.iloc[3:25, 18])
print(df2.columns)
print(df2.iloc[:, 17])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       30903
4      128396
5      141865
6       90313
7      350868
8      112717
9      179429
10     381361
11     155557
12      74739
13     630196
14      29377
15     132552
16     255433
17     346326
18      58755
19      67635
20     187182
21     845840
22      74967
23      27975
24    4302386
Name: Unnamed: 18, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0       30903
1      128396
2      141865
3       90813
4      350868
5       12717
6      179429
7      381361
8     1556517
9       74739
10     630196
11      29377
12     132652
13     256433
14     346320
15      58755
16      67635
17     187182
18     845840
19       4967
20          9
21          0
Name: 17, dtype: int64

In [145]:
print(df.columns)
print(df.iloc[3:25, 19])
print(df2.columns)
print(df2.iloc[:, 18])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        80
4       193
5        77
6         9
7        38
8         4
9         4
10      204
11       27
12        0
13      157
14      230
15     1328
16      373
17     1973
18      549
19     5453
20     3840
21     1752
22        1
23       16
24    16313
Name: Unnamed: 19, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0        0
1      193
2        0
3        0
4        0
5        0
6        0
7      204
8       27
9        0
10     157
11     230
12    1328
13     378
14    1973
15       0
16    5453
17    3840
18    4762
19       0
20       0
21       0
Name: 18, dtype: int64

In [146]:
print(df.columns)
print(df.iloc[3:25, 20])
print(df2.columns)
print(df2.iloc[:, 19])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       25641
4      119169
5      142100
6       88105
7      338857
8      108238
9      175266
10     370906
11     156683
12      78881
13     581384
14      29687
15      91553
16     234066
17     331217
18      56594
19      66742
20     173617
21     820290
22      74775
23      25749
24    4089520
Name: Unnamed: 20, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0       25641
1      119169
2      142100
3           0
4      338857
5      108238
6      175266
7      370906
8      156683
9       78881
10     681384
11     129687
12      91583
13     234066
14     831217
15      56594
16          0
17     173617
18     820290
19          0
20      25749
21    4089520
Name: 19, dtype: int64

In [147]:
print(df.columns)
print(df.iloc[3:25, 21])
print(df2.columns)
print(df2.iloc[:, 20])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3         7
4        21
5        59
6         0
7        10
8         0
9         1
10       40
11        1
12        0
13       55
14      184
15      600
16      215
17     1221
18      264
19     4988
20     2383
21     1394
22        0
23       10
24    11453
Name: Unnamed: 21, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0         7
1         2
2        59
3         0
4        10
5         0
6         1
7        40
8         1
9         0
10       55
11      184
12      600
13      215
14     1221
15      264
16     4988
17     2383
18     1394
19        0
20       10
21    11453
Name: 20, dtype: int64

In [148]:
tabela_manual_catolicos = pd.to_numeric(df.iloc[3:25, 18])
tabela_ocr_catolicos = pd.to_numeric(df2.iloc[:, 17])

diferenca_catolicos = tabela_manual_catolicos.values - tabela_ocr_catolicos.values
diferenca_catolicos

array([       0,        0,        0,     -500,        0,   100000,
              0,        0, -1400960,        0,        0,        0,
           -100,    -1000,        6,        0,        0,        0,
              0,    70000,    27966,  4302386])

In [149]:
tabela_manual_acatolicos = pd.to_numeric(df.iloc[3:25, 19])
tabela_ocr_acatolicos = pd.to_numeric(df2.iloc[:, 18])

diferenca_acatolicos = tabela_manual_acatolicos.values - tabela_ocr_acatolicos.values
diferenca_acatolicos

array([   80,     0,    77,     9,    38,     4,     4,     0,     0,
           0,     0,     0,     0,    -5,     0,   549,     0,     0,
       -3010,     1,    16, 16313])

In [150]:
tabela_manual_catolicas = pd.to_numeric(df.iloc[3:25, 20])
tabela_ocr_catolicas = pd.to_numeric(df2.iloc[:, 19])

diferenca_catolicas = tabela_manual_catolicas.values - tabela_ocr_catolicas.values
diferenca_catolicas

array([      0,       0,       0,   88105,       0,       0,       0,
             0,       0,       0, -100000, -100000,     -30,       0,
       -500000,       0,   66742,       0,       0,   74775,       0,
             0])

In [151]:
tabela_manual_acatolicas = pd.to_numeric(df.iloc[3:25, 21])
tabela_ocr_acatolicas = pd.to_numeric(df2.iloc[:, 20])

diferenca_acatolicas = tabela_manual_acatolicas.values - tabela_ocr_acatolicas.values
diferenca_acatolicas

array([ 0, 19,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0])

In [152]:
variancia_catolicos = np.var(diferenca_catolicos)
variancia_catolicos

911486351509.3636

In [153]:
variancia_acatolicos = np.var(diferenca_acatolicos)
variancia_acatolicos

12112888.966942148

In [154]:
variancia_catolicas = np.var(diferenca_catolicas)
variancia_catolicas

12624997169.512398

In [155]:
variancia_acatolicas = np.var(diferenca_acatolicas)
variancia_acatolicas

15.663223140495864

In [156]:
desvio_padrao_catolicos = np.std(diferenca_catolicos)
desvio_padrao_catolicos

954717.9434311286

In [157]:
desvio_padrao_acatolicos = np.std(diferenca_acatolicos)
desvio_padrao_acatolicos

3480.3575918204365

In [158]:
desvio_padrao_catolicas = np.std(diferenca_catolicas)
desvio_padrao_catolicas

112361.01267571595

In [159]:
desvio_padrao_acatolicas = np.std(diferenca_acatolicas)
desvio_padrao_acatolicas

3.957679009280043

In [160]:
coeficiente_variacao_catolicos = desvio_padrao_catolicos / np.mean(diferenca_catolicos) * 100
coeficiente_variacao_catolicos

678.0233816241353

In [161]:
coeficiente_variacao_acatolicos = desvio_padrao_acatolicos / np.mean(diferenca_acatolicos) * 100
coeficiente_variacao_acatolicos

543.960407928741

In [162]:
coeficiente_variacao_catolicas = desvio_padrao_catolicas / np.mean(diferenca_catolicas) * 100
coeficiente_variacao_catolicas

-525.4889965446486

In [163]:
coeficiente_variacao_acatolicas = desvio_padrao_acatolicas / np.mean(diferenca_acatolicas) * 100
coeficiente_variacao_acatolicas

458.2575694955839

In [164]:
print(f'Variância (católicos): {variancia_catolicos}')
print(f'Desvio Padrão (católicos): {desvio_padrao_catolicos}')
print(f'Coeficiente de Variação (católicos): {coeficiente_variacao_catolicos}%')

Variância (católicos): 911486351509.3636
Desvio Padrão (católicos): 954717.9434311286
Coeficiente de Variação (católicos): 678.0233816241353%

In [165]:
print(f'Variância (acatólicos): {variancia_acatolicos}')
print(f'Desvio Padrão (acatólicos): {desvio_padrao_acatolicos}')
print(f'Coeficiente de Variação (acatólicos): {coeficiente_variacao_acatolicos}%')

Variância (acatólicos): 12112888.966942148
Desvio Padrão (acatólicos): 3480.3575918204365
Coeficiente de Variação (acatólicos): 543.960407928741%

In [166]:
print(f'Variância (católicas): {variancia_catolicas}')
print(f'Desvio Padrão (católicas): {desvio_padrao_catolicas}')
print(f'Coeficiente de Variação (católicas): {coeficiente_variacao_catolicas}%')

Variância (católicas): 12624997169.512398
Desvio Padrão (católicas): 112361.01267571595
Coeficiente de Variação (católicas): -525.4889965446486%

In [167]:
print(f'Variância (acatólicas): {variancia_acatolicas}')
print(f'Desvio Padrão (acatólicas): {desvio_padrao_acatolicas}')
print(f'Coeficiente de Variação (acatólicas): {coeficiente_variacao_acatolicas}%')

Variância (acatólicas): 15.663223140495864
Desvio Padrão (acatólicas): 3.957679009280043
Coeficiente de Variação (acatólicas): 458.2575694955839%

In [168]:
media_catolicos = np.mean(diferenca_catolicos)
media_catolicos

140809.0

In [169]:
media_acatolicos = np.mean(diferenca_acatolicos)
media_acatolicos

639.8181818181819

In [170]:
media_catolicas = np.mean(diferenca_catolicas)
media_catolicas

-21382.18181818182

In [171]:
media_acatolicas = np.mean(diferenca_acatolicas)
media_acatolicas

0.8636363636363636

In [172]:
outlier_inferior_catolicos = media_catolicos - (3 * desvio_padrao_catolicos)
outlier_superior_catolicos = media_catolicos + (3 * desvio_padrao_catolicos)

print(outlier_inferior_catolicos, outlier_superior_catolicos)

-2723344.830293386 3004962.830293386

In [173]:
outlier_inferior_acatolicos = media_acatolicos - (3 * desvio_padrao_acatolicos)
outlier_superior_acatolicos = media_acatolicos + (3 * desvio_padrao_acatolicos)

print(outlier_inferior_acatolicos, outlier_superior_acatolicos)

-9801.254593643127 11080.890957279491

In [174]:
outlier_inferior_catolicas = media_catolicas - (3 * desvio_padrao_catolicas)
outlier_superior_catolicas = media_catolicas + (3 * desvio_padrao_catolicas)

print(outlier_inferior_catolicas, outlier_superior_catolicas)

-358465.21984532964 315700.856208966

In [175]:
outlier_inferior_acatolicas = media_acatolicas - (3 * desvio_padrao_acatolicas)
outlier_superior_acatolicas = media_acatolicas + (3 * desvio_padrao_acatolicas)

print(outlier_inferior_acatolicas, outlier_superior_acatolicas)

-11.009400664203767 12.736673391476494

# Nacionalidades

In [176]:
nacionalidade = df[['Unnamed: 0','Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25']]

nacionalidade_header = nacionalidade.iloc[2]
nacionalidade.columns = nacionalidade_header
nacionalidade = nacionalidade[3:]

columns_multiindex = pd.MultiIndex.from_tuples([
    ('', '', 'Províncias e Município Neutro'),
    ('Nacionalidades', 'dos Homens', 'Brasileiros'),
    ('Nacionalidades', 'dos Homens', 'Estrangeiros'),
    ('Nacionalidades', 'das Mulheres', 'Brasileiras'),
    ('Nacionalidades', 'das Mulheres', 'Estrangeiras')
])

nacionalidade.columns = columns_multiindex

nacionalidade

                                 Nacionalidades                            \
                                     dos Homens              das Mulheres
   Províncias e Município Neutro    Brasileiros Estrangeiros  Brasileiras
3                       Amazonas          29223         1760        25222
4                           Pará         123365         5224       118437
5                       Maranhão         139413         2529       141191
6                          Piauí          90022          300        88001
7                          Ceará         349805         1101       338475
8            Rio Grande do Norte         112305          416       108078
9                        Paraíba         178940          493       175102
10                    Pernambuco         373530         8035       368621
11                       Alagoas         154606          978       156321
12                       Sergipe          74352          387        78723
13                         Bahia         622447         7906       577229
14                Espírito Santo          28190         1417        29359
15              Município Neutro          77872        56008        74851
16                Rio de Janeiro         225843        29963       225860
17                     São Paulo         336473        11831       327702
18                        Paraná          57224         2080        56049
19                Santa Catarina          64731         8357        65241
20             Rio Grande do Sul         166042        24980       164522
21                  Minas Gerais         833175        14417       817692
22                         Goiás          74818          150        74698
23                   Mato Grosso          26986         1005        25455
24                         Total        4139362       179337      4036829



   Estrangeiras
3           426
4           753
5           968
6           104
7           392
8           160
9           165
10         2325
11          363
12          158
13         4210
14          512
15        17302
16         8421
17         4736
18          809
19         6489
20        11478
21         3992
22           77
23          304
24        64144

In [177]:
print(df.columns)
print(df.iloc[3:25, 22])
print(df2.columns)
print(df2.iloc[:, 21])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       29223
4      123365
5      139413
6       90022
7      349805
8      112305
9      178940
10     373530
11     154606
12      74352
13     622447
14      28190
15      77872
16     225843
17     336473
18      57224
19      64731
20     166042
21     833175
22      74818
23      26986
24    4139362
Name: Unnamed: 22, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0       29223
1      128365
2     1139413
3       90022
4      849805
5      112305
6      178940
7      373530
8      154606
9        7438
10       2247
11      28190
12     771872
13     225843
14     836173
15      57224
16          0
17    1166042
18     833175
19      74818
20      26986
21    4139369
Name: 21, dtype: int64

In [178]:
print(df.columns)
print(df.iloc[3:25, 23])
print(df2.columns)
print(df2.iloc[:, 22])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       1760
4       5224
5       2529
6        300
7       1101
8        416
9        493
10      8035
11       978
12       387
13      7906
14      1417
15     56008
16     29963
17     11831
18      2080
19      8357
20     24980
21     14417
22       150
23      1005
24    179337
Name: Unnamed: 23, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0       1760
1        224
2       2528
3        300
4       1101
5        416
6        493
7       8085
8        978
9        381
10      7906
11       141
12     56008
13     20963
14     11831
15      2080
16      8357
17     24980
18     14417
19       150
20      1005
21    179337
Name: 22, dtype: int64

In [179]:
print(df.columns)
print(df.iloc[3:25, 24])
print(df2.columns)
print(df2.iloc[:, 23])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       25222
4      118437
5      141191
6       88001
7      338475
8      108078
9      175102
10     368621
11     156321
12      78723
13     577229
14      29359
15      74851
16     225860
17     327702
18      56049
19      65241
20     164522
21     817692
22      74698
23      25455
24    4036829
Name: Unnamed: 24, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0      25292
1     118437
2     141191
3      88001
4     838475
5     108078
6     175102
7     368621
8     156321
9      78728
10    577229
11     29369
12     74881
13    225860
14    897702
15     56049
16     65241
17    164522
18    817692
19    740698
20     25455
21         0
Name: 23, dtype: int64

In [180]:
print(df.columns)
print(df.iloc[3:25, 25])
print(df2.columns)
print(df2.iloc[:, 24])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       426
4       753
5       968
6       104
7       392
8       160
9       165
10     2325
11      363
12      158
13     4210
14      512
15    17302
16     8421
17     4736
18      809
19     6489
20    11478
21     3992
22       77
23      304
24    64144
Name: Unnamed: 25, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0         0
1      7581
2       968
3       104
4      3021
5       160
6       165
7     23201
8       363
9       158
10     4210
11      512
12    17302
13     3421
14     4736
15      809
16     6489
17        0
18     3993
19       77
20      304
21    64144
Name: 24, dtype: int64

In [181]:
tabela_manual_brasileiros = pd.to_numeric(df.iloc[3:25, 22])
tabela_ocr_brasileiros = pd.to_numeric(df2.iloc[:, 21])

diferenca_brasileiros = tabela_manual_brasileiros.values - tabela_ocr_brasileiros.values
diferenca_brasileiros

array([       0,    -5000, -1000000,        0,  -500000,        0,
              0,        0,        0,    66914,   620200,        0,
        -694000,        0,  -499700,        0,    64731, -1000000,
              0,        0,        0,       -7])

In [182]:
tabela_manual_estrangeiros = pd.to_numeric(df.iloc[3:25, 23])
tabela_ocr_estrangeiros = pd.to_numeric(df2.iloc[:, 22])

diferenca_estrangeiros = tabela_manual_estrangeiros.values - tabela_ocr_estrangeiros.values
diferenca_estrangeiros

array([   0, 5000,    1,    0,    0,    0,    0,  -50,    0,    6,    0,
       1276,    0, 9000,    0,    0,    0,    0,    0,    0,    0,    0])

In [183]:
tabela_manual_brasileiras = pd.to_numeric(df.iloc[3:25, 24])
tabela_ocr_brasileiras = pd.to_numeric(df2.iloc[:, 23])

diferenca_brasileiras = tabela_manual_brasileiras.values - tabela_ocr_brasileiras.values
diferenca_brasileiras

array([    -70,       0,       0,       0, -500000,       0,       0,
             0,       0,      -5,       0,     -10,     -30,       0,
       -570000,       0,       0,       0,       0, -666000,       0,
       4036829])

In [184]:
tabela_manual_estrangeiras = pd.to_numeric(df.iloc[3:25, 25])
tabela_ocr_estrangeiras = pd.to_numeric(df2.iloc[:, 24])

diferenca_estrangeiras = tabela_manual_estrangeiras.values - tabela_ocr_estrangeiras.values
diferenca_estrangeiras

array([   426,  -6828,      0,      0,  -2629,      0,      0, -20876,
            0,      0,      0,      0,      0,   5000,      0,      0,
            0,  11478,     -1,      0,      0,      0])

In [185]:
variancia_brasileiros = np.var(diferenca_brasileiros)
variancia_brasileiros

135452256406.38017

In [186]:
variancia_estrangeiros = np.var(diferenca_estrangeiros)
variancia_estrangeiros

4412874.787190085

In [187]:
variancia_brasileiras = np.var(diferenca_brasileiras)
variancia_brasileiras

776083660074.0825

In [188]:
variancia_estrangeiras = np.var(diferenca_estrangeiras)
variancia_estrangeiras

29003098.06611571

In [189]:
desvio_padrao_brasileiros = np.std(diferenca_brasileiros)
desvio_padrao_brasileiros

368038.3898540751

In [190]:
desvio_padrao_estrangeiros = np.std(diferenca_estrangeiros)
desvio_padrao_estrangeiros

2100.6843616283923

In [191]:
desvio_padrao_brasileiras = np.std(diferenca_brasileiras)
desvio_padrao_brasileiras

880956.1056454984

In [192]:
desvio_padrao_estrangeiras = np.std(diferenca_estrangeiras)
desvio_padrao_estrangeiras

5385.452447670085

In [193]:
coeficiente_variacao_brasileiros = desvio_padrao_brasileiros / np.mean(diferenca_brasileiros) * 100
coeficiente_variacao_brasileiros

-274.76157949675456

In [194]:
coeficiente_variacao_estrangeiros = desvio_padrao_estrangeiros / np.mean(diferenca_estrangeiros) * 100
coeficiente_variacao_estrangeiros

303.38774998900175

In [195]:
coeficiente_variacao_brasileiras = desvio_padrao_brasileiras / np.mean(diferenca_brasileiras) * 100
coeficiente_variacao_brasileiras

842.3921584430296

In [196]:
coeficiente_variacao_estrangeiras = desvio_padrao_estrangeiras / np.mean(diferenca_estrangeiras) * 100
coeficiente_variacao_estrangeiras

-882.2036772058219

In [197]:
print(f'Variância (brasileiros): {variancia_brasileiros}')
print(f'Desvio Padrão (brasileiros): {desvio_padrao_brasileiros}')
print(f'Coeficiente de Variação (brasileiros): {coeficiente_variacao_brasileiros}%')

Variância (brasileiros): 135452256406.38017
Desvio Padrão (brasileiros): 368038.3898540751
Coeficiente de Variação (brasileiros): -274.76157949675456%

In [198]:
print(f'Variância (estrangeiros): {variancia_estrangeiros}')
print(f'Desvio Padrão (estrangeiros): {desvio_padrao_estrangeiros}')
print(f'Coeficiente de Variação (estrangeiros): {coeficiente_variacao_estrangeiros}%')

Variância (estrangeiros): 4412874.787190085
Desvio Padrão (estrangeiros): 2100.6843616283923
Coeficiente de Variação (estrangeiros): 303.38774998900175%

In [199]:
print(f'Variância (brasileiras): {variancia_brasileiras}')
print(f'Desvio Padrão (brasileiras): {desvio_padrao_brasileiras}')
print(f'Coeficiente de Variação (brasileiras): {coeficiente_variacao_brasileiras}%')

Variância (brasileiras): 776083660074.0825
Desvio Padrão (brasileiras): 880956.1056454984
Coeficiente de Variação (brasileiras): 842.3921584430296%

In [200]:
print(f'Variância (estrangeiras): {variancia_estrangeiras}')
print(f'Desvio Padrão (estrangeiras): {desvio_padrao_estrangeiras}')
print(f'Coeficiente de Variação (estrangeiras): {coeficiente_variacao_estrangeiras}%')

Variância (estrangeiras): 29003098.06611571
Desvio Padrão (estrangeiras): 5385.452447670085
Coeficiente de Variação (estrangeiras): -882.2036772058219%

In [201]:
media_brasileiros = np.mean(diferenca_brasileiros)
media_brasileiros

-133948.27272727274

In [202]:
media_estrangeiros = np.mean(diferenca_estrangeiros)
media_estrangeiros

692.4090909090909

In [203]:
media_brasileiras = np.mean(diferenca_brasileiras)
media_brasileiras

104577.90909090909

In [204]:
media_estrangeiras = np.mean(diferenca_estrangeiras)
media_estrangeiras

-610.4545454545455

In [205]:
outlier_inferior_brasileiros = media_brasileiros - (3 * desvio_padrao_brasileiros)
outlier_superior_brasileiros = media_brasileiros + (3 * desvio_padrao_brasileiros)

print(outlier_inferior_brasileiros, outlier_superior_brasileiros)

-1238063.442289498 970166.8968349525

In [206]:
outlier_inferior_estrangeiros = media_estrangeiros - (3 * desvio_padrao_estrangeiros)
outlier_superior_estrangeiros = media_estrangeiros + (3 * desvio_padrao_estrangeiros)

print(outlier_inferior_estrangeiros, outlier_superior_estrangeiros)

-5609.643993976086 6994.462175794268

In [207]:
outlier_inferior_brasileiras = media_brasileiras - (3 * desvio_padrao_brasileiras)
outlier_superior_brasileiras = media_brasileiras + (3 * desvio_padrao_brasileiras)

print(outlier_inferior_brasileiras, outlier_superior_brasileiras)

-2538290.407845586 2747446.2260274044

In [208]:
outlier_inferior_estrangeiras = media_estrangeiras - (3 * desvio_padrao_estrangeiras)
outlier_superior_estrangeiras = media_estrangeiras + (3 * desvio_padrao_estrangeiras)

print(outlier_inferior_estrangeiras, outlier_superior_estrangeiras)

-16766.8118884648 15545.90279755571

# Grau de instrução

In [209]:
instrucao = df[['Unnamed: 0','Instrução', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35']]

instrucao_header = instrucao.iloc[2]
instrucao.columns = instrucao_header
instrucao = instrucao[3:]

columns_multiindex = pd.MultiIndex.from_tuples([
    ('', '', '', 'Províncias e Município Neutro'),
    ('Instrução', '', 'Homens', 'Sabem ler e escrever'),
    ('Instrução', '', 'Homens', 'Analfabetos'),
    ('Instrução', '', 'Mulheres', 'Sabem ler e escrever'),
    ('Instrução', '', 'Mulheres', 'Analfabetas'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninos', 'Frequentam escolas'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninos', 'Não frequentam'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninos', 'Total'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninas', 'Frequentam escolas'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninas', 'Não frequentam'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninas', 'Total')
])

instrucao.columns = columns_multiindex

instrucao

                                            Instrução              \

                                               Homens
   Províncias e Município Neutro Sabem ler e escrever Analfabetos
3                       Amazonas                 6160       24823
4                           Pará                39718       88871
5                       Maranhão                44375       97567
6                          Piauí                17677       72645
7                          Ceará                58657      292249
8            Rio Grande do Norte                23602       39119
9                        Paraíba                29224      150209
10                    Pernambuco                92664      288901
11                       Alagoas                26046      129538
12                       Sergipe                18687       56052
13                         Bahia               161937      468416
14                Espírito Santo                 7229       22378
15              Município Neutro                65164       68714
16                Rio de Janeiro                69997      185809
17                     São Paulo                92977      255327
18                        Paraná                19014       40299
19                Santa Catarina                12927       59161
20             Rio Grande do Sul                 5592      134060
21                  Minas Gerais               145297      702295
22                         Goiás                15699       59299
23                   Mato Grosso                 7114       20877
24                         Total              1012097     3306602

                                                                      \
                                    População escolar de 6 a 15 anos
               Mulheres                                      Meninos
   Sabem ler e escrever Analfabetas               Frequentam escolas
3                  1453       24195                              824
4                 20677       98513                             5768
5                 24196      117963                             8739
6                 10093       78012                             1777
7                 20903      317964                            10021
8                 16220       92018                             2643
9                 11988      163279                             6630
10                54659      316287                            14069
11                15814      140870                             5455
12                10447       68434                             3402
13                37135      494304                            22260
14                 2503       27368                             1564
15                33992       58101                             5788
16                44603      189678                            12622
17                48090      284348                            15069
18                12802       44056                             2558
19                 7999       63731                             3100
20                38341      137659                             9947
21                78271      743413                            19968
22                 6987       67788                             2566
23                 3808       21951                              881
24               550981     3549992                           155651



                                     Meninas
   Não frequentam   Total Frequentam escolas Não frequentam   Total
3            5056    5880                371           3269    3640
4           25753   31521               3441          25020   28461
5           28142   36881               4844          29567   34411
6           15960   17737               1024          16968   17992
7           83808   93829               5399          85087   90486
8           18662   21305               2058          19857   21915
9           44061   50691               3894          45830   49724
10          82133   96202               9301          80960   90261
11          34261   39716               4028          34726   38754
12          14934   18336               1832          17333   19165
13         119426  141686              81743         113313  195056
14           5323    6887                722           5101    6823
15          10449   22237               4258          15019   19277
16          32019   44641               8194          33089   41283
17          71271   86340               8544          73915   82458
18           9666   12224               1866          10762   12628
19          15676   18776               2114          15473   17587
20          36222   46169               7947          33292   41239
21          66983  125012              11940         112824  124764
22          16864   19430               1240          16982   18222
23           5401    6282                338           6187    6525
24         786131  941782             165098         795574  960672

# Grau de instrução (adultos)

In [210]:
instrucao_adultos = df[['Unnamed: 0','Instrução', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29']]

instrucao_adultos_header = instrucao_adultos.iloc[2]
instrucao_adultos.columns = instrucao_adultos_header
instrucao_adultos = instrucao_adultos[3:]

columns_multiindex = pd.MultiIndex.from_tuples([
    ('', '', 'Províncias e Município Neutro'),
    ('Instrução', 'Homens', 'Sabem ler e escrever'),
    ('Instrução', 'Homens', 'Analfabetos'),
    ('Instrução', 'Mulheres', 'Sabem ler e escrever'),
    ('Instrução', 'Mulheres', 'Analfabetas')
])

instrucao_adultos.columns = columns_multiindex

instrucao_adultos

                                            Instrução              \
                                               Homens
   Províncias e Município Neutro Sabem ler e escrever Analfabetos
3                       Amazonas                 6160       24823
4                           Pará                39718       88871
5                       Maranhão                44375       97567
6                          Piauí                17677       72645
7                          Ceará                58657      292249
8            Rio Grande do Norte                23602       39119
9                        Paraíba                29224      150209
10                    Pernambuco                92664      288901
11                       Alagoas                26046      129538
12                       Sergipe                18687       56052
13                         Bahia               161937      468416
14                Espírito Santo                 7229       22378
15              Município Neutro                65164       68714
16                Rio de Janeiro                69997      185809
17                     São Paulo                92977      255327
18                        Paraná                19014       40299
19                Santa Catarina                12927       59161
20             Rio Grande do Sul                 5592      134060
21                  Minas Gerais               145297      702295
22                         Goiás                15699       59299
23                   Mato Grosso                 7114       20877
24                         Total              1012097     3306602


               Mulheres
   Sabem ler e escrever Analfabetas
3                  1453       24195
4                 20677       98513
5                 24196      117963
6                 10093       78012
7                 20903      317964
8                 16220       92018
9                 11988      163279
10                54659      316287
11                15814      140870
12                10447       68434
13                37135      494304
14                 2503       27368
15                33992       58101
16                44603      189678
17                48090      284348
18                12802       44056
19                 7999       63731
20                38341      137659
21                78271      743413
22                 6987       67788
23                 3808       21951
24               550981     3549992

In [211]:
print(df.columns)
print(df.iloc[3:25, 26])
print(df2.columns)
print(df2.iloc[:, 25])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        6160
4       39718
5       44375
6       17677
7       58657
8       23602
9       29224
10      92664
11      26046
12      18687
13     161937
14       7229
15      65164
16      69997
17      92977
18      19014
19      12927
20       5592
21     145297
22      15699
23       7114
24    1012097
Name: Instrução, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0        6160
1       39718
2         375
3       17677
4       58657
5       23602
6      292241
7       92664
8       26046
9       18687
10    1619871
11       7229
12       6564
13      69997
14      92977
15      19014
16      12927
17       5592
18     145297
19      15699
20        714
21    1012097
Name: 25, dtype: int64

In [212]:
print(df.columns)
print(df.iloc[3:25, 27])
print(df2.columns)
print(df2.iloc[:, 26])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       24823
4       88871
5       97567
6       72645
7      292249
8       39119
9      150209
10     288901
11     129538
12      56052
13     468416
14      22378
15      68714
16     185809
17     255327
18      40299
19      59161
20     134060
21     702295
22      59299
23      20877
24    3306602
Name: Unnamed: 27, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0           0
1           0
2           0
3           0
4           0
5       89119
6      150209
7      288901
8      129538
9       56052
10     468416
11      20878
12      68714
13     185809
14     255827
15      40299
16      59163
17     184060
18     702295
19      59299
20      20877
21    3306602
Name: 26, dtype: int64

In [213]:
print(df.columns)
print(df.iloc[3:25, 28])
print(df2.columns)
print(df2.iloc[:, 27])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       1453
4      20677
5      24196
6      10093
7      20903
8      16220
9      11988
10     54659
11     15814
12     10447
13     37135
14      2503
15     33992
16     44603
17     48090
18     12802
19      7999
20     38341
21     78271
22      6987
23      3808
24    550981
Name: Unnamed: 28, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0      1453
1     20677
2     24196
3     10093
4     20908
5     16220
6     11988
7     54459
8     16814
9     10427
10    87135
11     2508
12    32992
13    44603
14    48090
15    12802
16     7999
17    38341
18     2271
19     6987
20     3808
21     5098
Name: 27, dtype: int64

In [214]:
print(df.columns)
print(df.iloc[3:25, 29])
print(df2.columns)
print(df2.iloc[:, 28])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       24195
4       98513
5      117963
6       78012
7      317964
8       92018
9      163279
10     316287
11     140870
12      68434
13     494304
14      27368
15      58101
16     189678
17     284348
18      44056
19      63731
20     137659
21     743413
22      67788
23      21951
24    3549992
Name: Unnamed: 29, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0           2
1       98513
2      117963
3       78012
4     3817964
5       92018
6      163279
7      316287
8      140870
9       68434
10     494304
11      27388
12      58101
13     189678
14     284348
15      44056
16      68731
17     187659
18     743413
19      67788
20          0
21    3549992
Name: 28, dtype: int64

In [215]:
tabela_manual_alfabetizados = pd.to_numeric(df.iloc[3:25, 26])
tabela_ocr_alfabetizados = pd.to_numeric(df2.iloc[:, 25])

diferenca_alfabetizados = tabela_manual_alfabetizados.values - tabela_ocr_alfabetizados.values
diferenca_alfabetizados

array([       0,        0,    44000,        0,        0,        0,
        -263017,        0,        0,        0, -1457934,        0,
          58600,        0,        0,        0,        0,        0,
              0,        0,     6400,        0])

In [216]:
tabela_manual_analfabetos = pd.to_numeric(df.iloc[3:25, 27])
tabela_ocr_analfabetos = pd.to_numeric(df2.iloc[:, 26])

diferenca_analfabetos = tabela_manual_analfabetos.values - tabela_ocr_analfabetos.values
diferenca_analfabetos

array([ 24823,  88871,  97567,  72645, 292249, -50000,      0,      0,
            0,      0,      0,   1500,      0,      0,   -500,      0,
           -2, -50000,      0,      0,      0,      0])

In [217]:
tabela_manual_alfabetizadas = pd.to_numeric(df.iloc[3:25, 28])
tabela_ocr_alfabetizadas = pd.to_numeric(df2.iloc[:, 27])

diferenca_alfabetizadas = tabela_manual_alfabetizadas.values - tabela_ocr_alfabetizadas.values
diferenca_alfabetizadas

array([     0,      0,      0,      0,     -5,      0,      0,    200,
        -1000,     20, -50000,     -5,   1000,      0,      0,      0,
            0,      0,  76000,      0,      0, 545883])

In [218]:
tabela_manual_analfabetas = pd.to_numeric(df.iloc[3:25, 29])
tabela_ocr_analfabetas = pd.to_numeric(df2.iloc[:, 28])

diferenca_analfabetas = tabela_manual_analfabetas.values - tabela_ocr_analfabetas.values
diferenca_analfabetas

array([   24193,        0,        0,        0, -3500000,        0,
              0,        0,        0,        0,        0,      -20,
              0,        0,        0,        0,    -5000,   -50000,
              0,        0,    21951,        0])

In [219]:
variancia_alfabetizados = np.var(diferenca_alfabetizados)
variancia_alfabetizados

94638725222.70454

In [220]:
variancia_analfabetos = np.var(diferenca_analfabetos)
variancia_analfabetos

4698816659.811982

In [221]:
variancia_alfabetizadas = np.var(diferenca_alfabetizadas)
variancia_alfabetizadas

13244975170.266527

In [222]:
variancia_analfabetas = np.var(diferenca_analfabetas)
variancia_analfabetas

531543009243.2315

In [223]:
desvio_padrao_alfabetizados = np.std(diferenca_alfabetizados)
desvio_padrao_alfabetizados

307634.0768229432

In [224]:
desvio_padrao_analfabetos = np.std(diferenca_analfabetos)
desvio_padrao_analfabetos

68547.91506539045

In [225]:
desvio_padrao_alfabetizadas = np.std(diferenca_alfabetizadas)
desvio_padrao_alfabetizadas

115086.81579688669

In [226]:
desvio_padrao_analfabetas = np.std(diferenca_analfabetas)
desvio_padrao_analfabetas

729069.9618302975

In [227]:
coeficiente_variacao_alfabetizados = desvio_padrao_alfabetizados / np.mean(diferenca_alfabetizados) * 100
coeficiente_variacao_alfabetizados

-419.86075818090944

In [228]:
coeficiente_variacao_analfabetos = desvio_padrao_analfabetos / np.mean(diferenca_analfabetos) * 100
coeficiente_variacao_analfabetos

316.0525306219577

In [229]:
coeficiente_variacao_alfabetizadas = desvio_padrao_alfabetizadas / np.mean(diferenca_alfabetizadas) * 100
coeficiente_variacao_alfabetizadas

442.5696429656554

In [230]:
coeficiente_variacao_analfabetas = desvio_padrao_analfabetas / np.mean(diferenca_analfabetas) * 100
coeficiente_variacao_analfabetas

-457.1133080868786

In [231]:
print(f'Variância (alfabetizados): {variancia_alfabetizados}')
print(f'Desvio Padrão (alfabetizados): {desvio_padrao_alfabetizados}')
print(f'Coeficiente de Variação (alfabetizados): {coeficiente_variacao_alfabetizados}%')

Variância (alfabetizados): 94638725222.70454
Desvio Padrão (alfabetizados): 307634.0768229432
Coeficiente de Variação (alfabetizados): -419.86075818090944%

In [232]:
print(f'Variância (analfabetos): {variancia_analfabetos}')
print(f'Desvio Padrão (analfabetos): {desvio_padrao_analfabetos}')
print(f'Coeficiente de Variação (analfabetos): {coeficiente_variacao_analfabetos}%')

Variância (analfabetos): 4698816659.811982
Desvio Padrão (analfabetos): 68547.91506539045
Coeficiente de Variação (analfabetos): 316.0525306219577%

In [233]:
print(f'Variância (alfabetizadas): {variancia_alfabetizadas}')
print(f'Desvio Padrão (alfabetizadas): {desvio_padrao_alfabetizadas}')
print(f'Coeficiente de Variação (alfabetizadas): {coeficiente_variacao_alfabetizadas}%')

Variância (alfabetizadas): 13244975170.266527
Desvio Padrão (alfabetizadas): 115086.81579688669
Coeficiente de Variação (alfabetizadas): 442.5696429656554%

In [234]:
print(f'Variância (analfabetas): {variancia_analfabetas}')
print(f'Desvio Padrão (analfabetas): {desvio_padrao_analfabetas}')
print(f'Coeficiente de Variação (analfabetas): {coeficiente_variacao_analfabetas}%')

Variância (analfabetas): 531543009243.2315
Desvio Padrão (analfabetas): 729069.9618302975
Coeficiente de Variação (analfabetas): -457.1133080868786%

In [235]:
media_alfabetizados = np.mean(diferenca_alfabetizados)
media_alfabetizados

-73270.5

In [236]:
media_analfabetos = np.mean(diferenca_analfabetos)
media_analfabetos

21688.772727272728

In [237]:
media_alfabetizadas = np.mean(diferenca_alfabetizadas)
media_alfabetizadas

26004.227272727272

In [238]:
media_analfabetas = np.mean(diferenca_analfabetas)
media_analfabetas

-159494.36363636365

In [239]:
outlier_inferior_alfabetizados = media_alfabetizados - (3 * desvio_padrao_alfabetizados)
outlier_superior_alfabetizados = media_alfabetizados + (3 * desvio_padrao_alfabetizados)

print(outlier_inferior_alfabetizados, outlier_superior_alfabetizados)

-996172.7304688296 849631.7304688296

In [240]:
outlier_inferior_analfabetos = media_analfabetos - (3 * desvio_padrao_analfabetos)
outlier_superior_analfabetos = media_analfabetos + (3 * desvio_padrao_analfabetos)

print(outlier_inferior_analfabetos, outlier_superior_analfabetos)

-183954.9724688986 227332.51792344407

In [241]:
outlier_inferior_alfabetizadas = media_alfabetizadas - (3 * desvio_padrao_alfabetizadas)
outlier_superior_alfabetizadas = media_alfabetizadas + (3 * desvio_padrao_alfabetizadas)

print(outlier_inferior_alfabetizadas, outlier_superior_alfabetizadas)

-319256.22011793277 371264.67466338736

In [242]:
outlier_inferior_analfabetas = media_analfabetas - (3 * desvio_padrao_analfabetas)
outlier_superior_analfabetas = media_analfabetas + (3 * desvio_padrao_analfabetas)

print(outlier_inferior_analfabetas, outlier_superior_analfabetas)

-2346704.249127256 2027715.5218545287

# Grau de instrução (jovens)

In [243]:
instrucao_jovens = df[['Unnamed: 0', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35']]

instrucao_jovens_header = instrucao_jovens.iloc[2]
instrucao_jovens.columns = instrucao_jovens_header
instrucao_jovens = instrucao_jovens[3:]

columns_multiindex = pd.MultiIndex.from_tuples([
    ('', '', '', 'Províncias e Município Neutro'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninos', 'Frequentam escolas'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninos', 'Não frequentam'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninos', 'Total'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninas', 'Frequentam escolas'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninas', 'Não frequentam'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninas', 'Total')
])

instrucao_jovens.columns = columns_multiindex

instrucao_jovens

                                                        Instrução  \
                                 População escolar de 6 a 15 anos
                                                          Meninos
   Províncias e Município Neutro               Frequentam escolas
3                       Amazonas                              824
4                           Pará                             5768
5                       Maranhão                             8739
6                          Piauí                             1777
7                          Ceará                            10021
8            Rio Grande do Norte                             2643
9                        Paraíba                             6630
10                    Pernambuco                            14069
11                       Alagoas                             5455
12                       Sergipe                             3402
13                         Bahia                            22260
14                Espírito Santo                             1564
15              Município Neutro                             5788
16                Rio de Janeiro                            12622
17                     São Paulo                            15069
18                        Paraná                             2558
19                Santa Catarina                             3100
20             Rio Grande do Sul                             9947
21                  Minas Gerais                            19968
22                         Goiás                             2566
23                   Mato Grosso                              881
24                         Total                           155651



                                     Meninas
   Não frequentam   Total Frequentam escolas Não frequentam   Total
3            5056    5880                371           3269    3640
4           25753   31521               3441          25020   28461
5           28142   36881               4844          29567   34411
6           15960   17737               1024          16968   17992
7           83808   93829               5399          85087   90486
8           18662   21305               2058          19857   21915
9           44061   50691               3894          45830   49724
10          82133   96202               9301          80960   90261
11          34261   39716               4028          34726   38754
12          14934   18336               1832          17333   19165
13         119426  141686              81743         113313  195056
14           5323    6887                722           5101    6823
15          10449   22237               4258          15019   19277
16          32019   44641               8194          33089   41283
17          71271   86340               8544          73915   82458
18           9666   12224               1866          10762   12628
19          15676   18776               2114          15473   17587
20          36222   46169               7947          33292   41239
21          66983  125012              11940         112824  124764
22          16864   19430               1240          16982   18222
23           5401    6282                338           6187    6525
24         786131  941782             165098         795574  960672

In [244]:
print(df.columns)
print(df.iloc[3:25, 30])
print(df2.columns)
print(df2.iloc[:, 29])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        824
4       5768
5       8739
6       1777
7      10021
8       2643
9       6630
10     14069
11      5455
12      3402
13     22260
14      1564
15      5788
16     12622
17     15069
18      2558
19      3100
20      9947
21     19968
22      2566
23       881
24    155651
Name: Unnamed: 30, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0        824
1       5768
2       8739
3        177
4      10021
5       2643
6       6630
7      14069
8       5455
9       3409
10     22280
11      1564
12      5788
13     12622
14     15069
15      2558
16      3100
17      9947
18     19968
19      2566
20         0
21    155651
Name: 29, dtype: int64

In [245]:
print(df.columns)
print(df.iloc[3:25, 31])
print(df2.columns)
print(df2.iloc[:, 30])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       5056
4      25753
5      28142
6      15960
7      83808
8      18662
9      44061
10     82133
11     34261
12     14934
13    119426
14      5323
15     10449
16     32019
17     71271
18      9666
19     15676
20     36222
21     66983
22     16864
23      5401
24    786131
Name: Unnamed: 31, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0        5056
1       25758
2       28142
3       15960
4       83808
5       18602
6       44061
7       82133
8       34261
9       14934
10    3419426
11       5398
12       1049
13      32019
14      71271
15       9666
16      18676
17     362201
18      66983
19      10864
20       5401
21          6
Name: 30, dtype: int64

In [246]:
print(df.columns)
print(df.iloc[3:25, 32])
print(df2.columns)
print(df2.iloc[:, 31])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       5880
4      31521
5      36881
6      17737
7      93829
8      21305
9      50691
10     96202
11     39716
12     18336
13    141686
14      6887
15     22237
16     44641
17     86340
18     12224
19     18776
20     46169
21    125012
22     19430
23      6282
24    941782
Name: Unnamed: 32, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0       5880
1      31591
2      30881
3       1773
4      93829
5      21305
6      50691
7      96202
8      30716
9      18336
10    141086
11      6887
12     92987
13     44641
14     86340
15     12224
16     18776
17     46169
18    125012
19     19480
20       289
21    941789
Name: 31, dtype: int64

In [247]:
print(df.columns)
print(df.iloc[3:25, 33])
print(df2.columns)
print(df2.iloc[:, 32])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        371
4       3441
5       4844
6       1024
7       5399
8       2058
9       3894
10      9301
11      4028
12      1832
13     81743
14       722
15      4258
16      8194
17      8544
18      1866
19      2114
20      7947
21     11940
22      1240
23       338
24    165098
Name: Unnamed: 33, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0          0
1         48
2          0
3       1024
4       5899
5       2058
6       3904
7       9301
8       4028
9       1832
10     81748
11       722
12      4258
13        94
14         0
15      1866
16      2114
17      7947
18    119401
19      1240
20       888
21    165098
Name: 32, dtype: int64

In [248]:
print(df.columns)
print(df.iloc[3:25, 34])
print(df2.columns)
print(df2.iloc[:, 33])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       3269
4      25020
5      29567
6      16968
7      85087
8      19857
9      45830
10     80960
11     34726
12     17333
13    113313
14      5101
15     15019
16     33089
17     73915
18     10762
19     15473
20     33292
21    112824
22     16982
23      6187
24    795574
Name: Unnamed: 34, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0      3269
1     25020
2     29507
3     10968
4     85087
5         0
6     45830
7     80960
8     34726
9     17333
10    13818
11       10
12    15019
13    33089
14    13915
15    10762
16    15473
17    93299
18     2824
19    16982
20        0
21        9
Name: 33, dtype: int64

In [249]:
print(df.columns)
print(df.iloc[3:25, 35])
print(df2.columns)
print(df2.iloc[:, 34])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       3640
4      28461
5      34411
6      17992
7      90486
8      21915
9      49724
10     90261
11     38754
12     19165
13    195056
14      6823
15     19277
16     41283
17     82458
18     12628
19     17587
20     41239
21    124764
22     18222
23      6525
24    960672
Name: Unnamed: 35, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0       3640
1      28461
2       3411
3      17992
4      90486
5      21916
6      40794
7      90281
8      38754
9      19165
10    195056
11      6823
12     19277
13     41288
14     82458
15     12628
16     17587
17     41289
18    124764
19     19992
20        82
21    960872
Name: 34, dtype: int64

In [250]:
tabela_manual_meninos_alfabetizados = pd.to_numeric(df.iloc[3:25, 30])
tabela_ocr_meninos_alfabetizados = pd.to_numeric(df2.iloc[:, 29])

diferenca_meninos_alfabetizados = tabela_manual_meninos_alfabetizados.values - tabela_ocr_meninos_alfabetizados.values
diferenca_meninos_alfabetizados

array([   0,    0,    0, 1600,    0,    0,    0,    0,    0,   -7,  -20,
          0,    0,    0,    0,    0,    0,    0,    0,    0,  881,    0])

In [251]:
tabela_manual_meninos_analfabetos = pd.to_numeric(df.iloc[3:25, 31])
tabela_ocr_meninos_analfabetos = pd.to_numeric(df2.iloc[:, 30])

diferenca_meninos_analfabetos = tabela_manual_meninos_analfabetos.values - tabela_ocr_meninos_analfabetos.values
diferenca_meninos_analfabetos

array([       0,       -5,        0,        0,        0,       60,
              0,        0,        0,        0, -3300000,      -75,
           9400,        0,        0,        0,    -3000,  -325979,
              0,     6000,        0,   786125])

In [252]:
tabela_manual_meninos_total = pd.to_numeric(df.iloc[3:25, 32])
tabela_ocr_meninos_total = pd.to_numeric(df2.iloc[:, 31])

diferenca_meninos_total = tabela_manual_meninos_total.values - tabela_ocr_meninos_total.values
diferenca_meninos_total

array([     0,    -70,   6000,  15964,      0,      0,      0,      0,
         9000,      0,    600,      0, -70750,      0,      0,      0,
            0,      0,      0,    -50,   5993,     -7])

In [253]:
tabela_manual_meninas_alfabetizadas = pd.to_numeric(df.iloc[3:25, 33])
tabela_ocr_meninas_alfabetizadas = pd.to_numeric(df2.iloc[:, 32])

diferenca_meninas_alfabetizadas = tabela_manual_meninas_alfabetizadas.values - tabela_ocr_meninas_alfabetizadas.values
diferenca_meninas_alfabetizadas

array([    371,    3393,    4844,       0,    -500,       0,     -10,
             0,       0,       0,      -5,       0,       0,    8100,
          8544,       0,       0,       0, -107461,       0,    -550,
             0])

In [254]:
tabela_manual_meninas_analfabetas = pd.to_numeric(df.iloc[3:25, 34])
tabela_ocr_meninas_analfabetas = pd.to_numeric(df2.iloc[:, 33])

diferenca_meninas_analfabetas = tabela_manual_meninas_analfabetas.values - tabela_ocr_meninas_analfabetas.values
diferenca_meninas_analfabetas

array([     0,      0,     60,   6000,      0,  19857,      0,      0,
            0,      0,  99495,   5091,      0,      0,  60000,      0,
            0, -60007, 110000,      0,   6187, 795565])

In [255]:
tabela_manual_meninas_total = pd.to_numeric(df.iloc[3:25, 35])
tabela_ocr_meninas_total = pd.to_numeric(df2.iloc[:, 34])

diferenca_meninas_total = tabela_manual_meninas_total.values - tabela_ocr_meninas_total.values
diferenca_meninas_total

array([    0,     0, 31000,     0,     0,    -1,  8930,   -20,     0,
           0,     0,     0,     0,    -5,     0,     0,     0,   -50,
           0, -1770,  6443,  -200])

In [256]:
variancia_meninos_alfabetizados = np.var(diferenca_meninos_alfabetizados)
variancia_meninos_alfabetizados

139221.70247933886

In [257]:
variancia_meninos_analfabetos = np.var(diferenca_meninos_analfabetos)
variancia_meninos_analfabetos

511408948413.7934

In [258]:
variancia_meninos_total = np.var(diferenca_meninos_total)
variancia_meninos_total

243783210.88429755

In [259]:
variancia_meninas_alfabetizadas = np.var(diferenca_meninas_alfabetizadas)
variancia_meninas_alfabetizadas

518497103.51239663

In [260]:
variancia_meninas_analfabetas = np.var(diferenca_meninas_analfabetas)
variancia_meninas_analfabetas

27874630061.26446

In [261]:
variancia_meninas_total = np.var(diferenca_meninas_total)
variancia_meninas_total

45278187.02685951

In [262]:
desvio_padrao_meninos_alfabetizados = np.std(diferenca_meninos_alfabetizados)
desvio_padrao_meninos_alfabetizados

373.1242453651851

In [263]:
desvio_padrao_meninos_analfabetos = np.std(diferenca_meninos_analfabetos)
desvio_padrao_meninos_analfabetos

715128.6236851335

In [264]:
desvio_padrao_meninos_total = np.std(diferenca_meninos_total)
desvio_padrao_meninos_total

15613.558559287423

In [265]:
desvio_padrao_meninas_alfabetizadas = np.std(diferenca_meninas_alfabetizadas)
desvio_padrao_meninas_alfabetizadas

22770.531471891398

In [266]:
desvio_padrao_meninas_analfabetas = np.std(diferenca_meninas_analfabetas)
desvio_padrao_meninas_analfabetas

166956.97068785256

In [267]:
desvio_padrao_meninas_total = np.std(diferenca_meninas_total)
desvio_padrao_meninas_total

6728.90682257226

In [268]:
coeficiente_variacao_meninos_alfabetizados = desvio_padrao_meninos_alfabetizados / np.mean(diferenca_meninos_alfabetizados) * 100
coeficiente_variacao_meninos_alfabetizados

334.5042134488212

In [269]:
coeficiente_variacao_meninos_analfabetos = desvio_padrao_meninos_analfabetos / np.mean(diferenca_meninos_analfabetos) * 100
coeficiente_variacao_meninos_analfabetos

-556.4270342034246

In [270]:
coeficiente_variacao_meninos_total = desvio_padrao_meninos_total / np.mean(diferenca_meninos_total) * 100
coeficiente_variacao_meninos_total

-1030.9072278040915

In [271]:
coeficiente_variacao_meninas_alfabetizadas = desvio_padrao_meninas_alfabetizadas / np.mean(diferenca_meninas_alfabetizadas) * 100
coeficiente_variacao_meninas_alfabetizadas

-601.5703489463828

In [272]:
coeficiente_variacao_meninas_analfabetas = desvio_padrao_meninas_analfabetas / np.mean(diferenca_meninas_analfabetas) * 100
coeficiente_variacao_meninas_analfabetas

352.41644552282725

In [273]:
coeficiente_variacao_meninas_total = desvio_padrao_meninas_total / np.mean(diferenca_meninas_total) * 100
coeficiente_variacao_meninas_total

333.96338596473873

In [274]:
print(f'Variância (meninos alfabetizados): {variancia_meninos_alfabetizados}')
print(f'Desvio Padrão (meninos alfabetizados): {desvio_padrao_meninos_alfabetizados}')
print(f'Coeficiente de Variação (meninos alfabetizados): {coeficiente_variacao_meninos_alfabetizados}%')

Variância (meninos alfabetizados): 139221.70247933886
Desvio Padrão (meninos alfabetizados): 373.1242453651851
Coeficiente de Variação (meninos alfabetizados): 334.5042134488212%

In [275]:
print(f'Variância (meninos analfabetos): {variancia_meninos_analfabetos}')
print(f'Desvio Padrão (meninos analfabetos): {desvio_padrao_meninos_analfabetos}')
print(f'Coeficiente de Variação (meninos analfabetos): {coeficiente_variacao_meninos_analfabetos}%')

Variância (meninos analfabetos): 511408948413.7934
Desvio Padrão (meninos analfabetos): 715128.6236851335
Coeficiente de Variação (meninos analfabetos): -556.4270342034246%

In [276]:
print(f'Variância (meninos total): {variancia_meninos_total}')
print(f'Desvio Padrão (meninos total): {desvio_padrao_meninos_total}')
print(f'Coeficiente de Variação (meninos total): {coeficiente_variacao_meninos_total}%')

Variância (meninos total): 243783210.88429755
Desvio Padrão (meninos total): 15613.558559287423
Coeficiente de Variação (meninos total): -1030.9072278040915%

In [277]:
print(f'Variância (meninas alfabetizadas): {variancia_meninas_alfabetizadas}')
print(f'Desvio Padrão (meninas alfabetizadas): {desvio_padrao_meninas_alfabetizadas}')
print(f'Coeficiente de Variação (meninas alfabetizadas): {coeficiente_variacao_meninas_alfabetizadas}%')

Variância (meninas alfabetizadas): 518497103.51239663
Desvio Padrão (meninas alfabetizadas): 22770.531471891398
Coeficiente de Variação (meninas alfabetizadas): -601.5703489463828%

In [278]:
print(f'Variância (meninas alfabetizadas): {variancia_meninas_alfabetizadas}')
print(f'Desvio Padrão (meninas alfabetizadas): {desvio_padrao_meninas_alfabetizadas}')
print(f'Coeficiente de Variação (meninas alfabetizadas): {coeficiente_variacao_meninas_alfabetizadas}%')

Variância (meninas alfabetizadas): 518497103.51239663
Desvio Padrão (meninas alfabetizadas): 22770.531471891398
Coeficiente de Variação (meninas alfabetizadas): -601.5703489463828%

In [279]:
print(f'Variância (meninas total): {variancia_meninas_total}')
print(f'Desvio Padrão (meninas total): {desvio_padrao_meninas_total}')
print(f'Coeficiente de Variação (meninas total): {coeficiente_variacao_meninas_total}%')

Variância (meninas total): 45278187.02685951
Desvio Padrão (meninas total): 6728.90682257226
Coeficiente de Variação (meninas total): 333.96338596473873%

In [280]:
media_meninos_alfabetizados = np.mean(diferenca_meninos_alfabetizados)
media_meninos_alfabetizados

111.54545454545455

In [281]:
media_meninos_analfabetos = np.mean(diferenca_meninos_analfabetos)
media_meninos_analfabetos

-128521.54545454546

In [282]:
media_meninos_total = np.mean(diferenca_meninos_total)
media_meninos_total

-1514.5454545454545

In [283]:
media_meninas_alfabetizadas = np.mean(diferenca_meninas_alfabetizadas)
media_meninas_alfabetizadas

-3785.181818181818

In [284]:
media_meninas_analfabetas = np.mean(diferenca_meninas_analfabetas)
media_meninas_analfabetas

47374.90909090909

In [285]:
media_meninas_total = np.mean(diferenca_meninas_total)
media_meninas_total

2014.8636363636363

In [286]:
outlier_inferior_meninos_alfabetizados = media_meninos_alfabetizados - (3 * desvio_padrao_meninos_alfabetizados)
outlier_superior_meninos_alfabetizados = media_meninos_alfabetizados + (3 * desvio_padrao_meninos_alfabetizados)

print(outlier_inferior_meninos_alfabetizados, outlier_superior_meninos_alfabetizados)

-1007.8272815501009 1230.91819064101

In [287]:
outlier_inferior_meninos_analfabetos = media_meninos_analfabetos - (3 * desvio_padrao_meninos_analfabetos)
outlier_superior_meninos_analfabetos = media_meninos_analfabetos + (3 * desvio_padrao_meninos_analfabetos)

print(outlier_inferior_meninos_analfabetos, outlier_superior_meninos_analfabetos)

-2273907.416509946 2016864.325600855

In [288]:
outlier_inferior_meninos_total = media_meninos_total - (3 * desvio_padrao_meninos_total)
outlier_superior_meninos_total = media_meninos_total + (3 * desvio_padrao_meninos_total)

print(outlier_inferior_meninos_total, outlier_superior_meninos_total)

-48355.22113240772 45326.13022331681

In [289]:
outlier_inferior_meninas_alfabetizadas = media_meninas_alfabetizadas - (3 * desvio_padrao_meninas_alfabetizadas)
outlier_superior_meninas_alfabetizadas = media_meninas_alfabetizadas + (3 * desvio_padrao_meninas_alfabetizadas)

print(outlier_inferior_meninas_alfabetizadas, outlier_superior_meninas_alfabetizadas)

-72096.77623385601 64526.41259749237

In [290]:
outlier_inferior_meninas_analfabetas = media_meninas_analfabetas - (3 * desvio_padrao_meninas_analfabetas)
outlier_superior_meninas_analfabetas = media_meninas_analfabetas + (3 * desvio_padrao_meninas_analfabetas)

print(outlier_inferior_meninas_analfabetas, outlier_superior_meninas_analfabetas)

-453496.0029726486 548245.8211544667

In [291]:
outlier_inferior_meninas_total = media_meninas_total - (3 * desvio_padrao_meninas_total)
outlier_superior_meninas_total = media_meninas_total + (3 * desvio_padrao_meninas_total)

print(outlier_inferior_meninas_total, outlier_superior_meninas_total)

-18171.856831353147 22201.58410408042

# Casas

In [292]:
casas = df[['Unnamed: 0','Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38']]

casas_header = casas.iloc[2]
casas.columns = casas_header
casas = casas[3:]

columns_multiindex = pd.MultiIndex.from_tuples([
    ('', 'Províncias e Município Neutro'),
    ('Casas', 'Habitadas'),
    ('Casas', 'Desabitadas'),
    ('Casas', 'Total')
])

casas.columns = columns_multiindex

casas

                                     Casas
   Províncias e Município Neutro Habitadas Desabitadas    Total
3                       Amazonas      7661         229     7890
4                           Pará     38978        2077    41055
5                       Maranhão     47166        1405    48571
6                          Piauí     29208         223    29431
7                          Ceará     99901        2989   102890
8            Rio Grande do Norte     36710         706    37416
9                        Paraíba     43767         522    44289
10                    Pernambuco    133920        4381   188301
11                       Alagoas     55894        2030    57924
12                       Sergipe     25542         567    26109
13                         Bahia    176032        5479   181511
14                Espírito Santo     10742        1079    11821
15              Município Neutro     29045        1873    80918
16                Rio de Janeiro     88698        2844    91542
17                     São Paulo     65778        1000    66778
18                        Paraná     18903         259    19162
19                Santa Catarina     19608         528    20136
20             Rio Grande do Sul     60199        1741    61940
21                  Minas Gerais    275611        3629   279240
22                         Goiás     25196         487    25683
23                   Mato Grosso      7501         102     7603
24                         Total   1296060       34150  1330210

In [293]:
print(df.columns)
print(df.iloc[3:25, 36])
print(df2.columns)
print(df2.iloc[:, 35])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        7661
4       38978
5       47166
6       29208
7       99901
8       36710
9       43767
10     133920
11      55894
12      25542
13     176032
14      10742
15      29045
16      88698
17      65778
18      18903
19      19608
20      60199
21     275611
22      25196
23       7501
24    1296060
Name: Unnamed: 36, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0        7661
1       38978
2       27166
3       29208
4       99907
5       36710
6       43767
7      183020
8       55804
9       25542
10     176032
11      10742
12      29045
13      88608
14      65778
15      18903
16      19608
17      60199
18     276611
19      25196
20       7501
21    1296060
Name: 35, dtype: int64

In [294]:
print(df.columns)
print(df.iloc[3:25, 37])
print(df2.columns)
print(df2.iloc[:, 36])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       229
4      2077
5      1405
6       223
7      2989
8       706
9       522
10     4381
11     2030
12      567
13     5479
14     1079
15     1873
16     2844
17     1000
18      259
19      528
20     1741
21     3629
22      487
23      102
24    34150
Name: Unnamed: 37, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0       220
1      2077
2      1405
3         0
4      2989
5       706
6       522
7      4381
8      2080
9       567
10     5479
11     1079
12     1873
13     2844
14     1000
15      259
16      528
17      741
18     3629
19      487
20      302
21    84150
Name: 36, dtype: int64

In [295]:
print(df.columns)
print(df.iloc[3:25, 38])
print(df2.columns)
print(df2.iloc[:, 37])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        7890
4       41055
5       48571
6       29431
7      102890
8       37416
9       44289
10     188301
11      57924
12      26109
13     181511
14      11821
15      80918
16      91542
17      66778
18      19162
19      20136
20      61940
21     279240
22      25683
23       7603
24    1330210
Name: Unnamed: 38, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0        7890
1       41055
2       48571
3       29431
4      102890
5        3416
6       44989
7      188301
8       57924
9       26109
10     181511
11       1820
12      20918
13      91549
14          0
15      19162
16      20136
17      61940
18     279240
19      25088
20       7605
21    1330214
Name: 37, dtype: int64

In [296]:
tabela_manual_casas_habitadas = pd.to_numeric(df.iloc[3:25, 36])
tabela_ocr_casas_habitadas = pd.to_numeric(df2.iloc[:, 35])

diferenca_casas_habitadas = tabela_manual_casas_habitadas.values - tabela_ocr_casas_habitadas.values
diferenca_casas_habitadas

array([     0,      0,  20000,      0,     -6,      0,      0, -49100,
           90,      0,      0,      0,      0,     90,      0,      0,
            0,      0,  -1000,      0,      0,      0])

In [297]:
tabela_manual_casas_desabitadas = pd.to_numeric(df.iloc[3:25, 37])
tabela_ocr_casas_desabitadas = pd.to_numeric(df2.iloc[:, 36])

diferenca_casas_desabitadas = tabela_manual_casas_desabitadas.values - tabela_ocr_casas_desabitadas.values
diferenca_casas_desabitadas

array([     9,      0,      0,    223,      0,      0,      0,      0,
          -50,      0,      0,      0,      0,      0,      0,      0,
            0,   1000,      0,      0,   -200, -50000])

In [298]:
tabela_manual_casas_total = pd.to_numeric(df.iloc[3:25, 38])
tabela_ocr_casas_total = pd.to_numeric(df2.iloc[:, 37])

diferenca_casas_total = tabela_manual_casas_total.values - tabela_ocr_casas_total.values
diferenca_casas_total

array([    0,     0,     0,     0,     0, 34000,  -700,     0,     0,
           0,     0, 10001, 60000,    -7, 66778,     0,     0,     0,
           0,   595,    -2,    -4])

In [299]:
variancia_casas_habitadas = np.var(diferenca_casas_habitadas)
variancia_casas_habitadas

125959941.56198344

In [300]:
variancia_casas_desabitadas = np.var(diferenca_casas_desabitadas)
variancia_casas_desabitadas

108721624.99173552

In [301]:
variancia_casas_total = np.var(diferenca_casas_total)
variancia_casas_total

363286077.30785125

In [302]:
desvio_padrao_casas_habitadas = np.std(diferenca_casas_habitadas)
desvio_padrao_casas_habitadas

11223.187673828832

In [303]:
desvio_padrao_casas_desabitadas = np.std(diferenca_casas_desabitadas)
desvio_padrao_casas_desabitadas

10426.966241037491

In [304]:
desvio_padrao_casas_total = np.std(diferenca_casas_total)
desvio_padrao_casas_total

19060.064986978698

In [305]:
coeficiente_variacao_casas_habitadas = desvio_padrao_casas_habitadas / np.mean(diferenca_casas_habitadas) * 100
coeficiente_variacao_casas_habitadas

-825.0689327816424

In [306]:
coeficiente_variacao_casas_desabitadas = desvio_padrao_casas_desabitadas / np.mean(diferenca_casas_desabitadas) * 100
coeficiente_variacao_casas_desabitadas

-467.97759456286434

In [307]:
coeficiente_variacao_casas_total = desvio_padrao_casas_total / np.mean(diferenca_casas_total) * 100
coeficiente_variacao_casas_total

245.70430837363625

In [308]:
print(f'Variância (casas habitadas): {variancia_casas_habitadas}')
print(f'Desvio Padrão (casas habitadas): {desvio_padrao_casas_habitadas}')
print(f'Coeficiente de Variação (casas habitadas): {coeficiente_variacao_casas_habitadas}%')

Variância (casas habitadas): 125959941.56198344
Desvio Padrão (casas habitadas): 11223.187673828832
Coeficiente de Variação (casas habitadas): -825.0689327816424%

In [309]:
print(f'Variância (casas desabitadas): {variancia_casas_desabitadas}')
print(f'Desvio Padrão (casas desabitadas): {desvio_padrao_casas_desabitadas}')
print(f'Coeficiente de Variação (casas desabitadas): {coeficiente_variacao_casas_desabitadas}%')

Variância (casas desabitadas): 108721624.99173552
Desvio Padrão (casas desabitadas): 10426.966241037491
Coeficiente de Variação (casas desabitadas): -467.97759456286434%

In [310]:
print(f'Variância (casas total): {variancia_casas_total}')
print(f'Desvio Padrão (casas total): {desvio_padrao_casas_total}')
print(f'Coeficiente de Variação (casas total): {coeficiente_variacao_casas_total}%')

Variância (casas total): 363286077.30785125
Desvio Padrão (casas total): 19060.064986978698
Coeficiente de Variação (casas total): 245.70430837363625%

In [311]:
media_casas_habitadas = np.mean(diferenca_casas_habitadas)
media_casas_habitadas

-1360.2727272727273

In [312]:
media_casas_desabitadas = np.mean(diferenca_casas_desabitadas)
media_casas_desabitadas

-2228.090909090909

In [313]:
media_casas_total = np.mean(diferenca_casas_total)
media_casas_total

7757.318181818182

In [314]:
outlier_inferior_casas_habitadas = media_casas_habitadas - (3 * desvio_padrao_casas_habitadas)
outlier_superior_casas_habitadas = media_casas_habitadas + (3 * desvio_padrao_casas_habitadas)

print(outlier_inferior_casas_habitadas, outlier_superior_casas_habitadas)

-35029.83574875922 32309.290294213766

In [315]:
outlier_inferior_casas_desabitadas = media_casas_desabitadas - (3 * desvio_padrao_casas_desabitadas)
outlier_superior_casas_desabitadas = media_casas_desabitadas + (3 * desvio_padrao_casas_desabitadas)

print(outlier_inferior_casas_desabitadas, outlier_superior_casas_desabitadas)

-33508.98963220338 29052.807814021566

In [316]:
outlier_inferior_casas_total = media_casas_total - (3 * desvio_padrao_casas_total)
outlier_superior_casas_total = media_casas_total + (3 * desvio_padrao_casas_total)

print(outlier_inferior_casas_total, outlier_superior_casas_total)

-49422.876779117905 64937.51314275427

# Fogos

In [317]:
fogos = df[['Unnamed: 0', 'Unnamed: 39']]

fogos_header = fogos.iloc[2]
fogos.columns = fogos_header
fogos = fogos[3:]

fogos

2  Províncias e Município Neutro Número de fogos
3                       Amazonas            7811
4                           Pará           39521
5                       Maranhão           49282
6                          Piauí           30770
7                          Ceará          100207
8            Rio Grande do Norte           37320
9                        Paraíba           44438
10                    Pernambuco          134765
11                       Alagoas           60386
12                       Sergipe           24950
13                         Bahia          180307
14                Espírito Santo           10774
15              Município Neutro           44211
16                Rio de Janeiro           90232
17                     São Paulo           65960
18                        Paraná           22026
19                Santa Catarina           14457
20             Rio Grande do Sul           61394
21                  Minas Gerais          280660
22                         Goiás           25222
23                   Mato Grosso            7581
24                         Total         1332274

In [318]:
print(df.columns)
print(df.iloc[3:25, 39])
print(df2.columns)
print(df2.iloc[:, 38])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        7811
4       39521
5       49282
6       30770
7      100207
8       37320
9       44438
10     134765
11      60386
12      24950
13     180307
14      10774
15      44211
16      90232
17      65960
18      22026
19      14457
20      61394
21     280660
22      25222
23       7581
24    1332274
Name: Unnamed: 39, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0       7311
1      39521
2      49289
3      30770
4     100207
5      87320
6          0
7     184765
8        608
9      24950
10    180307
11     10774
12       211
13     90232
14     65960
15     22026
16      4457
17     61394
18         0
19     25222
20         0
21    392074
Name: 38, dtype: int64

In [319]:
tabela_manual_fogos = pd.to_numeric(df.iloc[3:25, 39])
tabela_ocr_fogos = pd.to_numeric(df2.iloc[:, 38])

diferenca_fogos = tabela_manual_fogos.values - tabela_ocr_fogos.values
diferenca_fogos

array([   500,      0,     -7,      0,      0, -50000,  44438, -50000,
        59778,      0,      0,      0,  44000,      0,      0,      0,
        10000,      0, 280660,      0,   7581, 940200])

In [320]:
variancia_fogos = np.var(diferenca_fogos)
variancia_fogos

40912767787.057846

In [321]:
desvio_padrao_fogos = np.std(diferenca_fogos)
desvio_padrao_fogos

202269.048020348

In [322]:
coeficiente_variacao_fogos = desvio_padrao_fogos / np.mean(diferenca_fogos) * 100
coeficiente_variacao_fogos

345.7187628829318

In [323]:
print(f'Variância (fogos): {variancia_fogos}')
print(f'Desvio Padrão (fogos): {desvio_padrao_fogos}')
print(f'Coeficiente de Variação (fogos): {coeficiente_variacao_fogos}%')

Variância (fogos): 40912767787.057846
Desvio Padrão (fogos): 202269.048020348
Coeficiente de Variação (fogos): 345.7187628829318%

In [324]:
media_fogos = np.mean(diferenca_fogos)
media_fogos

58506.818181818184

In [325]:
outlier_inferior_fogos = media_fogos - (3 * desvio_padrao_fogos)
outlier_superior_fogos = media_fogos + (3 * desvio_padrao_fogos)

print(outlier_inferior_fogos, outlier_superior_fogos)

-548300.3258792259 665313.9622428623