In [1]:
import pandas as pd
import numpy as np
import pathfinder as pf

In [2]:
filename = "censo_1872-003_p1.csv"
folder = "planilhas"
path = pf.find_file(filename, folder)
df = pd.read_csv(path)
print(df.columns)

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')

In [3]:
filename = "marcado.csv"
folder = "resultados_ocr"
path = pf.find_file(filename, folder)
df2 = pd.read_csv(path, header=None)
print(df2.columns)

Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')

In [4]:
sexos = df[['Unnamed: 0','Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3']]
sexos_header = sexos.iloc[1]
sexos.columns = sexos_header
sexos = sexos[2:]

sexos_header = sexos.iloc[0]
sexos.columns = sexos_header
sexos = sexos[1:]

columns_multiindex = pd.MultiIndex.from_tuples([
    #('Gêneros', 'Províncias e Município Neutro'),
    ('', 'Províncias e Município Neutro'),
    ('Gêneros', 'Homens'),
    ('Gêneros', 'Mulheres'),
    ('Gêneros', 'Total')
])

# Atribuindo o MultiIndex às colunas do DataFrame
sexos.columns = columns_multiindex

#print(sexos)
sexos

                                  Gêneros
   Províncias e Município Neutro   Homens Mulheres    Total
3                       Amazonas    30983     2564    56631
4                           Pará   128589    11919   247779
5                       Maranhão   141942    14215   284101
6                          Piauí    90322     8810   178427
7                          Ceará   350906    33886   689773
8            Rio Grande do Norte   112721    10823   220959
9                        Paraíba   179433    17526   354700
10                    Pernambuco   381565    37094   752511
11                       Alagoas   155584    15667   312268
12                       Sergipe    74739     7888   153620
13                         Bahia   630353    58143  1211792
14                Espírito Santo    29607    29871    59478
15              Município Neutro   133880    92153   226033
16                Rio de Janeiro   255806   234281   499087
17                     São Paulo   348304   332438   680742
18                        Paraná    59384    56858   116162
19                Santa Catarina    73088    71730   144818
20             Rio Grande do Sul   191022   176000   367022
21                  Minas Gerais   847592   821684  1669276
22                         Goiás    74968    74775   149743
23                   Mato Grosso    27991    25759    53750
24                         Total  4318699  4100973  8419672

In [5]:
print(df.columns)
print(df.iloc[3:25, 1])
print(df2.columns)
print(df2.iloc[:, 0])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       30983
4      128589
5      141942
6       90322
7      350906
8      112721
9      179433
10     381565
11     155584
12      74739
13     630353
14      29607
15     133880
16     255806
17     348304
18      59384
19      73088
20     191022
21     847592
22      74968
23      27991
24    4318699
Name: Unnamed: 1, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0       30983
1      128580
2      141942
3       90828
4      850906
5      112721
6      179493
7      381565
8      155584
9       78730
10     630858
11      29607
12     133880
13     255806
14     348804
15      69284
16      73088
17     191022
18         42
19      74968
20      27991
21    4318699
Name: 0, dtype: int64

In [6]:
estados_civis = df[['Unnamed: 0','Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9']]

estados_civis_header = estados_civis.iloc[2]
estados_civis.columns = estados_civis_header
estados_civis = estados_civis[3:]

columns_multiindex = pd.MultiIndex.from_tuples([
    #('Gêneros', 'Províncias e Município Neutro'),
    ('', '', 'Províncias e Município Neutro'),
    ('Estados civis', 'dos Homens', 'Solteiros'),
    ('Estados civis', 'dos Homens', 'Casados'),
    ('Estados civis', 'dos Homens', 'Viúvos'),
    ('Estados civis', 'das Mulheres', 'Solteiras'),
    ('Estados civis', 'das Mulheres', 'Casadas'),
    ('Estados civis', 'das Mulheres', 'Viúvas')
])

# Atribuindo o MultiIndex às colunas do DataFrame
estados_civis.columns = columns_multiindex

estados_civis

                                 Estados civis                                \
                                    dos Homens                  das Mulheres
   Províncias e Município Neutro     Solteiros  Casados  Viúvos    Solteiras
3                       Amazonas         24959     5105     919        19214
4                           Pará         94848    28935    4806        86825
5                       Maranhão        103283    33644    5015       102302
6                          Piauí         63294    23323    3705        59547
7                          Ceará        241692    99915    9299       224509
8            Rio Grande do Norte         80803    26832    5086        75915
9                        Paraíba        119403    53474    6556       112332
10                    Pernambuco        258936   111189   11440       240239
11                       Alagoas        102729    47865    4990        99772
12                       Sergipe         48013    24027    2699        50746
13                         Bahia        440556   160204   29593       398473
14                Espírito Santo         19415     9298     894        19251
15              Município Neutro        104036    25763    4081        64074
16                Rio de Janeiro        168391    71842   15573       148840
17                     São Paulo        234386    98864   15054       218684
18                        Paraná         37977    18649    2678        35006
19                Santa Catarina         49985    21351    1752        47122
20             Rio Grande do Sul        139899    45104    6019       124864
21                  Minas Gerais        572728   231947   42917       557389
22                         Goiás         51886    20696    2386        50125
23                   Mato Grosso         18227     7839    1925        17353
24                         Total       2975446  1165866  177387      2752582



    Casadas  Viúvas
3      4714    1720
4     26280    6085
5     32337    7520
6     23371    5187
7     99849   14509
8     26735    5588
9     53274    9661
10   111465   19242
11    46743   10169
12    24795    3340
13   151883   31083
14     9449    1171
15    20174    7905
16    68726   16715
17    96290   17464
18    18332    3520
19    20412    4196
20    41525    9611
21   217353   46942
22    20340    4310
23     6953    1453
24  1121000  227391

In [7]:
racas = df[['Unnamed: 0','Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17']]

columns_multiindex = pd.MultiIndex.from_tuples([
    ('', '', 'Províncias e Município Neutro'),
    ('Raças', 'dos Homens', 'Brancos'),
    ('Raças', 'dos Homens', 'Pardos'),
    ('Raças', 'dos Homens', 'Pretos'),
    ('Raças', 'dos Homens', 'Caboclos'),
    ('Raças', 'das Mulheres', 'Brancas'),
    ('Raças', 'das Mulheres', 'Pardas'),
    ('Raças', 'das Mulheres', 'Pretas'),
    ('Raças', 'das Mulheres', 'Caboclas')
])

racas.columns = columns_multiindex

racas

                                        Raças                             \
                                   dos Homens
    Províncias e Município Neutro     Brancos   Pardos  Pretos  Caboclos
0                             NaN       Raças      NaN     NaN       NaN
1                             NaN  dos Homens      NaN     NaN       NaN
2   Províncias e Município Neutro     Brancos   Pardos  Pretos  Caboclos
3                        Amazonas        6911     4210     711     19151
4                            Pará       49663    46899    9200     22827
5                        Maranhão       52267    71662   12504      5509
6                           Piauí       22208    53474    7505      7135
7                           Ceará      136940   172841   14424     26701
8             Rio Grande do Norte       52835    42213   12202      5471
9                         Paraíba       73475    89921   11155      4882
10                     Pernambuco      149930   194897   30795      5943
11                        Alagoas       45343    98916    8220      3105
12                        Sergipe       24358    39524    9321      1536
13                          Bahia      178605   287131  137574     27043
14                 Espírito Santo       13555     9648    3395      3009
15               Município Neutro       96255    22762   14198       665
16                 Rio de Janeiro      160595    61542   29517      4152
17                      São Paulo      221260    76288   29512     21244
18                         Paraná       35936    15358    3292      4718
19                 Santa Catarina       63502     5941    2199      1446
20              Rio Grande do Sul      136094    24487   17828     12613
21                   Minas Gerais      421861   302948  105507     17276
22                          Goiás       21152    42482    9088      2246
23                    Mato Grosso        9027    10827    3861      4276
24                          Total     1971772  1673971  472008    200948


    das Mulheres
         Brancas   Pardas  Pretas  Caboclas
0            NaN      NaN     NaN       NaN
1   das Mulheres      NaN     NaN       NaN
2        Brancas   Pardas  Pretas  Caboclas
3           4300     3046     625     17677
4          42971    46828    7629     21762
5          51246    72699   12780      5434
6          21239    53191    7357      6318
7         131896   166325   14510     26136
8          49630    41877   11163      5568
9          71246    88675   10661      4685
10        141229   192954   30901      5862
11         43455   101283    8687      3259
12         25420    42059    9851      1551
13        152874   278573  127153     22839
14         13027    10881    3443      2520
15         55544    22083   14268       258
16        142680    59703   28198      3700
17        212172    75018   27027     18221
18         33762    15278    3449      4369
19         62440     5796    2048      1446
20        122273    24179   16444     13104
21        409126   295865  101647     15046
22         20777    43907    8087      2004
23          8210    10087    3214      4248
24       1815517  1650307  449142    186007

In [8]:
religiao = df[['Unnamed: 0','Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21']]

religiao_header = religiao.iloc[2]
religiao.columns = religiao_header
religiao = religiao[3:]

columns_multiindex = pd.MultiIndex.from_tuples([
    ('', '', 'Províncias e Município Neutro'),
    ('Religião', 'dos Homens', 'Católicos'),
    ('Religião', 'dos Homens', 'Acatólicos'),
    ('Religião', 'das Mulheres', 'Católicas'),
    ('Religião', 'das Mulheres', 'Acatólicas')
])

religiao.columns = columns_multiindex

religiao

                                   Religião
                                 dos Homens            das Mulheres
   Províncias e Município Neutro  Católicos Acatólicos    Católicas Acatólicas
3                       Amazonas      30903         80        25641          7
4                           Pará     128396        193       119169         21
5                       Maranhão     141865         77       142100         59
6                          Piauí      90313          9        88105          0
7                          Ceará     350868         38       338857         10
8            Rio Grande do Norte     112717          4       108238          0
9                        Paraíba     179429          4       175266          1
10                    Pernambuco     381361        204       370906         40
11                       Alagoas     155557         27       156683          1
12                       Sergipe      74739          0        78881          0
13                         Bahia     630196        157       581384         55
14                Espírito Santo      29377        230        29687        184
15              Município Neutro     132552       1328        91553        600
16                Rio de Janeiro     255433        373       234066        215
17                     São Paulo     346326       1973       331217       1221
18                        Paraná      58755        549        56594        264
19                Santa Catarina      67635       5453        66742       4988
20             Rio Grande do Sul     187182       3840       173617       2383
21                  Minas Gerais     845840       1752       820290       1394
22                         Goiás      74967          1        74775          0
23                   Mato Grosso      27975         16        25749         10
24                         Total    4302386      16313      4089520      11453

In [9]:
nacionalidade = df[['Unnamed: 0','Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25']]

nacionalidade_header = nacionalidade.iloc[2]
nacionalidade.columns = nacionalidade_header
nacionalidade = nacionalidade[3:]

columns_multiindex = pd.MultiIndex.from_tuples([
    ('', '', 'Províncias e Município Neutro'),
    ('Nacionalidades', 'dos Homens', 'Brasileiros'),
    ('Nacionalidades', 'dos Homens', 'Estrangeiros'),
    ('Nacionalidades', 'das Mulheres', 'Brasileiras'),
    ('Nacionalidades', 'das Mulheres', 'Estrangeiras')
])

nacionalidade.columns = columns_multiindex

nacionalidade

                                 Nacionalidades                            \
                                     dos Homens              das Mulheres
   Províncias e Município Neutro    Brasileiros Estrangeiros  Brasileiras
3                       Amazonas          29223         1760        25222
4                           Pará         123365         5224       118437
5                       Maranhão         139413         2529       141191
6                          Piauí          90022          300        88001
7                          Ceará         349805         1101       338475
8            Rio Grande do Norte         112305          416       108078
9                        Paraíba         178940          493       175102
10                    Pernambuco         373530         8035       368621
11                       Alagoas         154606          978       156321
12                       Sergipe          74352          387        78723
13                         Bahia         622447         7906       577229
14                Espírito Santo          28190         1417        29359
15              Município Neutro          77872        56008        74851
16                Rio de Janeiro         225843        29963       225860
17                     São Paulo         336473        11831       327702
18                        Paraná          57224         2080        56049
19                Santa Catarina          64731         8357        65241
20             Rio Grande do Sul         166042        24980       164522
21                  Minas Gerais         833175        14417       817692
22                         Goiás          74818          150        74698
23                   Mato Grosso          26986         1005        25455
24                         Total        4139362       179337      4036829



   Estrangeiras
3           426
4           753
5           968
6           104
7           392
8           160
9           165
10         2325
11          363
12          158
13         4210
14          512
15        17302
16         8421
17         4736
18          809
19         6489
20        11478
21         3992
22           77
23          304
24        64144

In [10]:
instrucao = df[['Unnamed: 0','Instrução', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35']]

instrucao_header = instrucao.iloc[2]
instrucao.columns = instrucao_header
instrucao = instrucao[3:]

columns_multiindex = pd.MultiIndex.from_tuples([
    ('', '', '', 'Províncias e Município Neutro'),
    ('Instrução', '', 'Homens', 'Sabem ler e escrever'),
    ('Instrução', '', 'Homens', 'Analfabetos'),
    ('Instrução', '', 'Mulheres', 'Sabem ler e escrever'),
    ('Instrução', '', 'Mulheres', 'Analfabetas'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninos', 'Frequentam escolas'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninos', 'Não frequentam'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninos', 'Total'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninas', 'Frequentam escolas'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninas', 'Não frequentam'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninas', 'Total')
])

instrucao.columns = columns_multiindex

instrucao

                                            Instrução              \

                                               Homens
   Províncias e Município Neutro Sabem ler e escrever Analfabetos
3                       Amazonas                 6160       24823
4                           Pará                39718       88871
5                       Maranhão                44375       97567
6                          Piauí                17677       72645
7                          Ceará                58657      292249
8            Rio Grande do Norte                23602       39119
9                        Paraíba                29224      150209
10                    Pernambuco                92664      288901
11                       Alagoas                26046      129538
12                       Sergipe                18687       56052
13                         Bahia               161937      468416
14                Espírito Santo                 7229       22378
15              Município Neutro                65164       68714
16                Rio de Janeiro                69997      185809
17                     São Paulo                92977      255327
18                        Paraná                19014       40299
19                Santa Catarina                12927       59161
20             Rio Grande do Sul                 5592      134060
21                  Minas Gerais               145297      702295
22                         Goiás                15699       59299
23                   Mato Grosso                 7114       20877
24                         Total              1012097     3306602

                                                                      \
                                    População escolar de 6 a 15 anos
               Mulheres                                      Meninos
   Sabem ler e escrever Analfabetas               Frequentam escolas
3                  1453       24195                              824
4                 20677       98513                             5768
5                 24196      117963                             8739
6                 10093       78012                             1777
7                 20903      317964                            10021
8                 16220       92018                             2643
9                 11988      163279                             6630
10                54659      316287                            14069
11                15814      140870                             5455
12                10447       68434                             3402
13                37135      494304                            22260
14                 2503       27368                             1564
15                33992       58101                             5788
16                44603      189678                            12622
17                48090      284348                            15069
18                12802       44056                             2558
19                 7999       63731                             3100
20                38341      137659                             9947
21                78271      743413                            19968
22                 6987       67788                             2566
23                 3808       21951                              881
24               550981     3549992                           155651



                                     Meninas
   Não frequentam   Total Frequentam escolas Não frequentam   Total
3            5056    5880                371           3269    3640
4           25753   31521               3441          25020   28461
5           28142   36881               4844          29567   34411
6           15960   17737               1024          16968   17992
7           83808   93829               5399          85087   90486
8           18662   21305               2058          19857   21915
9           44061   50691               3894          45830   49724
10          82133   96202               9301          80960   90261
11          34261   39716               4028          34726   38754
12          14934   18336               1832          17333   19165
13         119426  141686              81743         113313  195056
14           5323    6887                722           5101    6823
15          10449   22237               4258          15019   19277
16          32019   44641               8194          33089   41283
17          71271   86340               8544          73915   82458
18           9666   12224               1866          10762   12628
19          15676   18776               2114          15473   17587
20          36222   46169               7947          33292   41239
21          66983  125012              11940         112824  124764
22          16864   19430               1240          16982   18222
23           5401    6282                338           6187    6525
24         786131  941782             165098         795574  960672

In [11]:
instrucao_adultos = df[['Unnamed: 0','Instrução', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29']]

instrucao_adultos_header = instrucao_adultos.iloc[2]
instrucao_adultos.columns = instrucao_adultos_header
instrucao_adultos = instrucao_adultos[3:]

columns_multiindex = pd.MultiIndex.from_tuples([
    ('', '', 'Províncias e Município Neutro'),
    ('Instrução', 'Homens', 'Sabem ler e escrever'),
    ('Instrução', 'Homens', 'Analfabetos'),
    ('Instrução', 'Mulheres', 'Sabem ler e escrever'),
    ('Instrução', 'Mulheres', 'Analfabetas')
])

instrucao_adultos.columns = columns_multiindex

instrucao_adultos

                                            Instrução              \
                                               Homens
   Províncias e Município Neutro Sabem ler e escrever Analfabetos
3                       Amazonas                 6160       24823
4                           Pará                39718       88871
5                       Maranhão                44375       97567
6                          Piauí                17677       72645
7                          Ceará                58657      292249
8            Rio Grande do Norte                23602       39119
9                        Paraíba                29224      150209
10                    Pernambuco                92664      288901
11                       Alagoas                26046      129538
12                       Sergipe                18687       56052
13                         Bahia               161937      468416
14                Espírito Santo                 7229       22378
15              Município Neutro                65164       68714
16                Rio de Janeiro                69997      185809
17                     São Paulo                92977      255327
18                        Paraná                19014       40299
19                Santa Catarina                12927       59161
20             Rio Grande do Sul                 5592      134060
21                  Minas Gerais               145297      702295
22                         Goiás                15699       59299
23                   Mato Grosso                 7114       20877
24                         Total              1012097     3306602


               Mulheres
   Sabem ler e escrever Analfabetas
3                  1453       24195
4                 20677       98513
5                 24196      117963
6                 10093       78012
7                 20903      317964
8                 16220       92018
9                 11988      163279
10                54659      316287
11                15814      140870
12                10447       68434
13                37135      494304
14                 2503       27368
15                33992       58101
16                44603      189678
17                48090      284348
18                12802       44056
19                 7999       63731
20                38341      137659
21                78271      743413
22                 6987       67788
23                 3808       21951
24               550981     3549992

In [12]:
instrucao_jovens = df[['Unnamed: 0', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35']]

instrucao_jovens_header = instrucao_jovens.iloc[2]
instrucao_jovens.columns = instrucao_jovens_header
instrucao_jovens = instrucao_jovens[3:]

columns_multiindex = pd.MultiIndex.from_tuples([
    ('', '', '', 'Províncias e Município Neutro'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninos', 'Frequentam escolas'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninos', 'Não frequentam'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninos', 'Total'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninas', 'Frequentam escolas'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninas', 'Não frequentam'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninas', 'Total')
])

instrucao_jovens.columns = columns_multiindex

instrucao_jovens

                                                        Instrução  \
                                 População escolar de 6 a 15 anos
                                                          Meninos
   Províncias e Município Neutro               Frequentam escolas
3                       Amazonas                              824
4                           Pará                             5768
5                       Maranhão                             8739
6                          Piauí                             1777
7                          Ceará                            10021
8            Rio Grande do Norte                             2643
9                        Paraíba                             6630
10                    Pernambuco                            14069
11                       Alagoas                             5455
12                       Sergipe                             3402
13                         Bahia                            22260
14                Espírito Santo                             1564
15              Município Neutro                             5788
16                Rio de Janeiro                            12622
17                     São Paulo                            15069
18                        Paraná                             2558
19                Santa Catarina                             3100
20             Rio Grande do Sul                             9947
21                  Minas Gerais                            19968
22                         Goiás                             2566
23                   Mato Grosso                              881
24                         Total                           155651



                                     Meninas
   Não frequentam   Total Frequentam escolas Não frequentam   Total
3            5056    5880                371           3269    3640
4           25753   31521               3441          25020   28461
5           28142   36881               4844          29567   34411
6           15960   17737               1024          16968   17992
7           83808   93829               5399          85087   90486
8           18662   21305               2058          19857   21915
9           44061   50691               3894          45830   49724
10          82133   96202               9301          80960   90261
11          34261   39716               4028          34726   38754
12          14934   18336               1832          17333   19165
13         119426  141686              81743         113313  195056
14           5323    6887                722           5101    6823
15          10449   22237               4258          15019   19277
16          32019   44641               8194          33089   41283
17          71271   86340               8544          73915   82458
18           9666   12224               1866          10762   12628
19          15676   18776               2114          15473   17587
20          36222   46169               7947          33292   41239
21          66983  125012              11940         112824  124764
22          16864   19430               1240          16982   18222
23           5401    6282                338           6187    6525
24         786131  941782             165098         795574  960672

In [13]:
casas = df[['Unnamed: 0','Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38']]

casas_header = casas.iloc[2]
casas.columns = casas_header
casas = casas[3:]

columns_multiindex = pd.MultiIndex.from_tuples([
    ('', 'Províncias e Município Neutro'),
    ('Casas', 'Habitadas'),
    ('Casas', 'Desabitadas'),
    ('Casas', 'Total')
])

casas.columns = columns_multiindex

casas

                                     Casas
   Províncias e Município Neutro Habitadas Desabitadas    Total
3                       Amazonas      7661         229     7890
4                           Pará     38978        2077    41055
5                       Maranhão     47166        1405    48571
6                          Piauí     29208         223    29431
7                          Ceará     99901        2989   102890
8            Rio Grande do Norte     36710         706    37416
9                        Paraíba     43767         522    44289
10                    Pernambuco    133920        4381   188301
11                       Alagoas     55894        2030    57924
12                       Sergipe     25542         567    26109
13                         Bahia    176032        5479   181511
14                Espírito Santo     10742        1079    11821
15              Município Neutro     29045        1873    80918
16                Rio de Janeiro     88698        2844    91542
17                     São Paulo     65778        1000    66778
18                        Paraná     18903         259    19162
19                Santa Catarina     19608         528    20136
20             Rio Grande do Sul     60199        1741    61940
21                  Minas Gerais    275611        3629   279240
22                         Goiás     25196         487    25683
23                   Mato Grosso      7501         102     7603
24                         Total   1296060       34150  1330210

In [14]:
fogos = df[['Unnamed: 0', 'Unnamed: 39']]

fogos_header = fogos.iloc[2]
fogos.columns = fogos_header
fogos = fogos[3:]

fogos

2  Províncias e Município Neutro Número de fogos
3                       Amazonas            7811
4                           Pará           39521
5                       Maranhão           49282
6                          Piauí           30770
7                          Ceará          100207
8            Rio Grande do Norte           37320
9                        Paraíba           44438
10                    Pernambuco          134765
11                       Alagoas           60386
12                       Sergipe           24950
13                         Bahia          180307
14                Espírito Santo           10774
15              Município Neutro           44211
16                Rio de Janeiro           90232
17                     São Paulo           65960
18                        Paraná           22026
19                Santa Catarina           14457
20             Rio Grande do Sul           61394
21                  Minas Gerais          280660
22                         Goiás           25222
23                   Mato Grosso            7581
24                         Total         1332274