In [1]:
import pandas as pd
import numpy as np
import pathfinder as pf

In [2]:
filename = "censo_1872-003_p1.csv"
folder = "planilhas"
path = pf.find_file(filename, folder)
df = pd.read_csv(path)
print(df.columns)

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')

In [3]:
filename = "conversor.csv"
folder = "resultados_ocr"
path = pf.find_file(filename, folder)
df2 = pd.read_csv(path, header=None)
print(df2.columns)

Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')

# Gêneros

In [4]:
sexos = df[['Unnamed: 0','Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3']]
sexos_header = sexos.iloc[1]
sexos.columns = sexos_header
sexos = sexos[2:]

sexos_header = sexos.iloc[0]
sexos.columns = sexos_header
sexos = sexos[1:]

columns_multiindex = pd.MultiIndex.from_tuples([
    #('Gêneros', 'Províncias e Município Neutro'),
    ('', 'Províncias e Município Neutro'),
    ('Gêneros', 'Homens'),
    ('Gêneros', 'Mulheres'),
    ('Gêneros', 'Total')
])

# Atribuindo o MultiIndex às colunas do DataFrame
sexos.columns = columns_multiindex

#print(sexos)
sexos

                                  Gêneros
   Províncias e Município Neutro   Homens Mulheres    Total
3                       Amazonas    30983     2564    56631
4                           Pará   128589    11919   247779
5                       Maranhão   141942    14215   284101
6                          Piauí    90322     8810   178427
7                          Ceará   350906    33886   689773
8            Rio Grande do Norte   112721    10823   220959
9                        Paraíba   179433    17526   354700
10                    Pernambuco   381565    37094   752511
11                       Alagoas   155584    15667   312268
12                       Sergipe    74739     7888   153620
13                         Bahia   630353    58143  1211792
14                Espírito Santo    29607    29871    59478
15              Município Neutro   133880    92153   226033
16                Rio de Janeiro   255806   234281   499087
17                     São Paulo   348304   332438   680742
18                        Paraná    59384    56858   116162
19                Santa Catarina    73088    71730   144818
20             Rio Grande do Sul   191022   176000   367022
21                  Minas Gerais   847592   821684  1669276
22                         Goiás    74968    74775   149743
23                   Mato Grosso    27991    25759    53750
24                         Total  4318699  4100973  8419672

In [5]:
print(df.columns)
print(df.iloc[3:25, 1])
print(df2.columns)
print(df2.iloc[:, 0])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       30983
4      128589
5      141942
6       90322
7      350906
8      112721
9      179433
10     381565
11     155584
12      74739
13     630353
14      29607
15     133880
16     255806
17     348304
18      59384
19      73088
20     191022
21     847592
22      74968
23      27991
24    4318699
Name: Unnamed: 1, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0       30983
1      128589
2      141942
3       90322
4      350906
5           0
6      179433
7      381565
8      155584
9       14730
10     630358
11      29607
12     133880
13     265808
14     349304
15      59984
16      73088
17     191022
18     847592
19      74908
20      27991
21    4318699
Name: 0, dtype: int64

In [6]:
print(df.columns)
print(df.iloc[3:25, 2])
print(df2.columns)
print(df2.iloc[:, 1])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        2564
4       11919
5       14215
6        8810
7       33886
8       10823
9       17526
10      37094
11      15667
12       7888
13      58143
14      29871
15      92153
16     234281
17     332438
18      56858
19      71730
20     176000
21     821684
22      74775
23      25759
24    4100973
Name: Unnamed: 2, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0         2564
1         1919
2           25
3         8810
4            1
5        10822
6        17598
7        37001
8        15067
9         7883
10       68143
11       42087
12       92154
13          21
14      332439
15       60858
16       71730
17      176000
18       21684
19           4
20       25759
21    41009731
Name: 1, dtype: int64

In [7]:
print(df.columns)
print(df.iloc[3:25, 3])
print(df2.columns)
print(df2.iloc[:, 2])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       56631
4      247779
5      284101
6      178427
7      689773
8      220959
9      354700
10     752511
11     312268
12     153620
13    1211792
14      59478
15     226033
16     499087
17     680742
18     116162
19     144818
20     367022
21    1669276
22     149743
23      53750
24    8419672
Name: Unnamed: 3, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0        86631
1       212779
2          284
3       178497
4       689778
5       220959
6       361700
7       752611
8       312268
9       153620
10           0
11       59478
12      266033
13      499087
14       63074
15      116162
16      144818
17     3070221
18     1669276
19          74
20       52750
21    84196072
Name: 2, dtype: int64

In [8]:
tabela_manual_homens = pd.to_numeric(df.iloc[3:25, 1])
tabela_ocr_homens = pd.to_numeric(df2.iloc[:, 0])

diferenca_homens = tabela_manual_homens.values - tabela_ocr_homens.values
diferenca_homens

array([     0,      0,      0,      0,      0, 112721,      0,      0,
            0,  60009,     -5,      0,      0, -10002,  -1000,   -600,
            0,      0,      0,     60,      0,      0])

In [9]:
tabela_manual_mulheres = pd.to_numeric(df.iloc[3:25, 2])
tabela_ocr_mulheres = pd.to_numeric(df2.iloc[:, 1])

diferenca_mulheres = tabela_manual_mulheres.values - tabela_ocr_mulheres.values
diferenca_mulheres

array([        0,     10000,     14190,         0,     33885,         1,
             -72,        93,       600,         5,    -10000,    -12216,
              -1,    234260,        -1,     -4000,         0,         0,
          800000,     74771,         0, -36908758])

In [10]:
tabela_manual_total = pd.to_numeric(df.iloc[3:25, 3])
tabela_ocr_total = pd.to_numeric(df2.iloc[:, 2])

diferenca_total = tabela_manual_total.values - tabela_ocr_total.values
diferenca_total

array([   -30000,     35000,    283817,       -70,        -5,         0,
           -7000,      -100,         0,         0,   1211792,         0,
          -40000,         0,    617668,         0,         0,  -2703199,
               0,    149669,      1000, -75776400])

In [11]:
variancia_homens = np.var(diferenca_homens)
variancia_homens

692163650.0681819

In [12]:
variancia_mulheres = np.var(diferenca_mulheres)
variancia_mulheres

59309490792811.55

In [13]:
variancia_total = np.var(diferenca_total)
variancia_total

249408951367144.3

In [14]:
desvio_padrao_homens = np.std(diferenca_homens)
desvio_padrao_homens

26309.003213124244

In [15]:
desvio_padrao_mulheres = np.std(diferenca_mulheres)
desvio_padrao_mulheres

7701265.531898738

In [16]:
desvio_padrao_total = np.std(diferenca_total)
desvio_padrao_total

15792686.641833438

In [17]:
coeficiente_variacao_homens = desvio_padrao_homens / np.mean(diferenca_homens) * 100
coeficiente_variacao_homens

359.0937448048078

In [18]:
coeficiente_variacao_mulheres = desvio_padrao_mulheres / np.mean(diferenca_mulheres) * 100
coeficiente_variacao_mulheres

-473.6955590951537

In [19]:
coeficiente_variacao_total = desvio_padrao_total / np.mean(diferenca_total) * 100
coeficiente_variacao_total

-455.6110700141311

In [20]:
print(f'Variância (homens): {variancia_homens}')
print(f'Desvio Padrão (homens): {desvio_padrao_homens}')
print(f'Coeficiente de Variação (homens): {coeficiente_variacao_homens}%')

Variância (homens): 692163650.0681819
Desvio Padrão (homens): 26309.003213124244
Coeficiente de Variação (homens): 359.0937448048078%

In [21]:
print(f'Variância (mulheres): {variancia_mulheres}')
print(f'Desvio Padrão (mulheres): {desvio_padrao_mulheres}')
print(f'Coeficiente de Variação (mulheres): {coeficiente_variacao_mulheres}%')

Variância (mulheres): 59309490792811.55
Desvio Padrão (mulheres): 7701265.531898738
Coeficiente de Variação (mulheres): -473.6955590951537%

In [22]:
print(f'Variância (total): {variancia_total}')
print(f'Desvio Padrão (total): {desvio_padrao_total}')
print(f'Coeficiente de Variação (total): {coeficiente_variacao_total}%')

Variância (total): 249408951367144.3
Desvio Padrão (total): 15792686.641833438
Coeficiente de Variação (total): -455.6110700141311%

In [23]:
media_homens = np.mean(diferenca_homens)
media_homens

7326.5

In [24]:
media_mulheres = np.mean(diferenca_mulheres)
media_mulheres

-1625783.7727272727

In [25]:
media_total = np.mean(diferenca_total)
media_total

-3466264.909090909

In [26]:
outlier_inferior_homens = media_homens - (3 * desvio_padrao_homens)
outlier_superior_homens = media_homens + (3 * desvio_padrao_homens)

print(outlier_inferior_homens, outlier_superior_homens)

-71600.50963937273 86253.50963937273

In [27]:
outlier_inferior_mulheres = media_mulheres - (3 * desvio_padrao_mulheres)
outlier_superior_mulheres = media_mulheres + (3 * desvio_padrao_mulheres)

print(outlier_inferior_mulheres, outlier_superior_mulheres)

-24729580.368423488 21478012.82296894

In [28]:
outlier_inferior_total = media_total - (3 * desvio_padrao_total)
outlier_superior_total = media_total + (3 * desvio_padrao_total)

print(outlier_inferior_total, outlier_superior_total)

-50844324.83459122 43911795.016409405

# Estados civis

In [29]:
estados_civis = df[['Unnamed: 0','Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9']]

estados_civis_header = estados_civis.iloc[2]
estados_civis.columns = estados_civis_header
estados_civis = estados_civis[3:]

columns_multiindex = pd.MultiIndex.from_tuples([
    #('Gêneros', 'Províncias e Município Neutro'),
    ('', '', 'Províncias e Município Neutro'),
    ('Estados civis', 'dos Homens', 'Solteiros'),
    ('Estados civis', 'dos Homens', 'Casados'),
    ('Estados civis', 'dos Homens', 'Viúvos'),
    ('Estados civis', 'das Mulheres', 'Solteiras'),
    ('Estados civis', 'das Mulheres', 'Casadas'),
    ('Estados civis', 'das Mulheres', 'Viúvas')
])

# Atribuindo o MultiIndex às colunas do DataFrame
estados_civis.columns = columns_multiindex

estados_civis

                                 Estados civis                                \
                                    dos Homens                  das Mulheres
   Províncias e Município Neutro     Solteiros  Casados  Viúvos    Solteiras
3                       Amazonas         24959     5105     919        19214
4                           Pará         94848    28935    4806        86825
5                       Maranhão        103283    33644    5015       102302
6                          Piauí         63294    23323    3705        59547
7                          Ceará        241692    99915    9299       224509
8            Rio Grande do Norte         80803    26832    5086        75915
9                        Paraíba        119403    53474    6556       112332
10                    Pernambuco        258936   111189   11440       240239
11                       Alagoas        102729    47865    4990        99772
12                       Sergipe         48013    24027    2699        50746
13                         Bahia        440556   160204   29593       398473
14                Espírito Santo         19415     9298     894        19251
15              Município Neutro        104036    25763    4081        64074
16                Rio de Janeiro        168391    71842   15573       148840
17                     São Paulo        234386    98864   15054       218684
18                        Paraná         37977    18649    2678        35006
19                Santa Catarina         49985    21351    1752        47122
20             Rio Grande do Sul        139899    45104    6019       124864
21                  Minas Gerais        572728   231947   42917       557389
22                         Goiás         51886    20696    2386        50125
23                   Mato Grosso         18227     7839    1925        17353
24                         Total       2975446  1165866  177387      2752582



    Casadas  Viúvas
3      4714    1720
4     26280    6085
5     32337    7520
6     23371    5187
7     99849   14509
8     26735    5588
9     53274    9661
10   111465   19242
11    46743   10169
12    24795    3340
13   151883   31083
14     9449    1171
15    20174    7905
16    68726   16715
17    96290   17464
18    18332    3520
19    20412    4196
20    41525    9611
21   217353   46942
22    20340    4310
23     6953    1453
24  1121000  227391

In [30]:
print(df.columns)
print(df.iloc[3:25, 4])
print(df2.columns)
print(df2.iloc[:, 3])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       24959
4       94848
5      103283
6       63294
7      241692
8       80803
9      119403
10     258936
11     102729
12      48013
13     440556
14      19415
15     104036
16     168391
17     234386
18      37977
19      49985
20     139899
21     572728
22      51886
23      18227
24    2975446
Name: Unnamed: 4, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0       24959
1       94843
2      103283
3       63294
4      241692
5           0
6      119403
7      238936
8      102729
9       43013
10     440556
11      19415
12     104036
13     168391
14      24350
15      37977
16      49985
17     139899
18     572728
19      51886
20      18227
21    2975416
Name: 3, dtype: int64

In [31]:
print(df.columns)
print(df.iloc[3:25, 5])
print(df2.columns)
print(df2.iloc[:, 4])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        5105
4       28935
5       33644
6       23323
7       99915
8       26832
9       53474
10     111189
11      47865
12      24027
13     160204
14       9298
15      25763
16      71842
17      98864
18      18649
19      21351
20      45104
21     231947
22      20696
23       7839
24    1165866
Name: Unnamed: 5, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0        5105
1       28935
2       33044
3       23323
4       99915
5       20832
6        5374
7       11189
8       47865
9       24027
10     160204
11       9293
12      25763
13      71842
14      98864
15      18619
16      21951
17      45104
18     231947
19      20696
20       7839
21    1165866
Name: 4, dtype: int64

In [32]:
print(df.columns)
print(df.iloc[3:25, 6])
print(df2.columns)
print(df2.iloc[:, 5])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        919
4       4806
5       5015
6       3705
7       9299
8       5086
9       6556
10     11440
11      4990
12      2699
13     29593
14       894
15      4081
16     15573
17     15054
18      2678
19      1752
20      6019
21     42917
22      2386
23      1925
24    177387
Name: Unnamed: 6, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0        919
1       4806
2       5015
3       3705
4       9299
5       5086
6       6556
7      11440
8       4990
9       2699
10     29593
11       894
12      4081
13      1557
14     15054
15      2678
16      1752
17      6019
18     42917
19      2380
20      1925
21    177387
Name: 5, dtype: int64

In [33]:
print(df.columns)
print(df.iloc[3:25, 7])
print(df2.columns)
print(df2.iloc[:, 6])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       19214
4       86825
5      102302
6       59547
7      224509
8       75915
9      112332
10     240239
11      99772
12      50746
13     398473
14      19251
15      64074
16     148840
17     218684
18      35006
19      47122
20     124864
21     557389
22      50125
23      17353
24    2752582
Name: Unnamed: 7, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0       19214
1       86825
2      102302
3       59547
4      224509
5       75915
6      112332
7      240239
8       99772
9       50746
10     308473
11      19251
12      64074
13     148810
14     218684
15      35006
16      47122
17     124864
18     557389
19      50125
20      17363
21    2752582
Name: 6, dtype: int64

In [34]:
print(df.columns)
print(df.iloc[3:25, 8])
print(df2.columns)
print(df2.iloc[:, 7])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        4714
4       26280
5       32337
6       23371
7       99849
8       26735
9       53274
10     111465
11      46743
12      24795
13     151883
14       9449
15      20174
16      68726
17      96290
18      18332
19      20412
20      41525
21     217353
22      20340
23       6953
24    1121000
Name: Unnamed: 8, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0        4714
1       26280
2       32337
3       23371
4       99849
5       26735
6       63274
7      111465
8       46743
9       24795
10     151883
11       9449
12      20174
13      68726
14      96290
15      18332
16      20412
17      41525
18     217353
19      20340
20       6953
21    1121000
Name: 7, dtype: int64

In [35]:
print(df.columns)
print(df.iloc[3:25, 9])
print(df2.columns)
print(df2.iloc[:, 8])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       1720
4       6085
5       7520
6       5187
7      14509
8       5588
9       9661
10     19242
11     10169
12      3340
13     31083
14      1171
15      7905
16     16715
17     17464
18      3520
19      4196
20      9611
21     46942
22      4310
23      1453
24    227391
Name: Unnamed: 9, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0       1124
1       6085
2         16
3          0
4      14505
5        658
6       9601
7       1924
8      10169
9       2340
10     31083
11       171
12      7905
13     16715
14     17464
15      3520
16      4196
17        96
18      4694
19      4310
20      1453
21    227391
Name: 8, dtype: int64

In [36]:
tabela_manual_solteiros = pd.to_numeric(df.iloc[3:25, 4])
tabela_ocr_solteiros = pd.to_numeric(df2.iloc[:, 3])

diferenca_solteiros = tabela_manual_solteiros.values - tabela_ocr_solteiros.values
diferenca_solteiros

array([     0,      5,      0,      0,      0,  80803,      0,  20000,
            0,   5000,      0,      0,      0,      0, 210036,      0,
            0,      0,      0,      0,      0,     30])

In [37]:
tabela_manual_casados = pd.to_numeric(df.iloc[3:25, 5])
tabela_ocr_casados = pd.to_numeric(df2.iloc[:, 4])

diferenca_casados = tabela_manual_casados.values - tabela_ocr_casados.values
diferenca_casados

array([     0,      0,    600,      0,      0,   6000,  48100, 100000,
            0,      0,      0,      5,      0,      0,      0,     30,
         -600,      0,      0,      0,      0,      0])

In [38]:
tabela_manual_viuvos = pd.to_numeric(df.iloc[3:25, 6])
tabela_ocr_viuvos = pd.to_numeric(df2.iloc[:, 5])

diferenca_viuvos = tabela_manual_viuvos.values - tabela_ocr_viuvos.values
diferenca_viuvos

array([    0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0, 14016,     0,     0,     0,     0,
           0,     6,     0,     0])

In [39]:
tabela_manual_solteiras = pd.to_numeric(df.iloc[3:25, 7])
tabela_ocr_solteiras = pd.to_numeric(df2.iloc[:, 6])

diferenca_solteiras = tabela_manual_solteiras.values - tabela_ocr_solteiras.values
diferenca_solteiras

array([    0,     0,     0,     0,     0,     0,     0,     0,     0,
           0, 90000,     0,     0,    30,     0,     0,     0,     0,
           0,     0,   -10,     0])

In [40]:
tabela_manual_casadas = pd.to_numeric(df.iloc[3:25, 8])
tabela_ocr_casadas = pd.to_numeric(df2.iloc[:, 7])

diferenca_casadas = tabela_manual_casadas.values - tabela_ocr_casadas.values
diferenca_casadas

array([     0,      0,      0,      0,      0,      0, -10000,      0,
            0,      0,      0,      0,      0,      0,      0,      0,
            0,      0,      0,      0,      0,      0])

In [41]:
tabela_manual_viuvas = pd.to_numeric(df.iloc[3:25, 9])
tabela_ocr_viuvas = pd.to_numeric(df2.iloc[:, 8])

diferenca_viuvas = tabela_manual_viuvas.values - tabela_ocr_viuvas.values
diferenca_viuvas

array([  596,     0,  7504,  5187,     4,  4930,    60, 17318,     0,
        1000,     0,  1000,     0,     0,     0,     0,     0,  9515,
       42248,     0,     0,     0])

In [42]:
variancia_solteiros = np.var(diferenca_solteiros)
variancia_solteiros

2115179856.9917345

In [43]:
variancia_casados = np.var(diferenca_casados)
variancia_casados

512292731.66322327

In [44]:
variancia_viuvos = np.var(diferenca_viuvos)
variancia_viuvos

8523235.413223138

In [45]:
variancia_solteiras = np.var(diferenca_solteiras)
variancia_solteiras

351438887.6033059

In [46]:
variancia_casadas = np.var(diferenca_casadas)
variancia_casadas

4338842.975206612

In [47]:
variancia_viuvas = np.var(diferenca_viuvas)
variancia_viuvas

87374556.80991735

In [48]:
desvio_padrao_solteiros = np.std(diferenca_solteiros)
desvio_padrao_solteiros

45991.084538111674

In [49]:
desvio_padrao_casados = np.std(diferenca_casados)
desvio_padrao_casados

22633.884590657948

In [50]:
desvio_padrao_viuvos = np.std(diferenca_viuvos)
desvio_padrao_viuvos

2919.458068413235

In [51]:
desvio_padrao_solteiras = np.std(diferenca_solteiras)
desvio_padrao_solteiras

18746.703379616

In [52]:
desvio_padrao_casadas = np.std(diferenca_casadas)
desvio_padrao_casadas

2082.9889522526546

In [53]:
desvio_padrao_viuvas = np.std(diferenca_viuvas)
desvio_padrao_viuvas

9347.43584144429

In [54]:
coeficiente_variacao_solteiros = desvio_padrao_solteiros / np.mean(diferenca_solteiros) * 100
coeficiente_variacao_solteiros

320.31881694550896

In [55]:
coeficiente_variacao_casados = desvio_padrao_casados / np.mean(diferenca_casados) * 100
coeficiente_variacao_casados

323.05800823594564

In [56]:
coeficiente_variacao_viuvos = desvio_padrao_viuvos / np.mean(diferenca_viuvos) * 100
coeficiente_variacao_viuvos

458.0521858871143

In [57]:
coeficiente_variacao_solteiras = desvio_padrao_solteiras / np.mean(diferenca_solteiras) * 100
coeficiente_variacao_solteiras

458.1509379599555

In [58]:
coeficiente_variacao_casadas = desvio_padrao_casadas / np.mean(diferenca_casadas) * 100
coeficiente_variacao_casadas

-458.257569495584

In [59]:
coeficiente_variacao_viuvas = desvio_padrao_viuvas / np.mean(diferenca_viuvas) * 100
coeficiente_variacao_viuvas

230.1242010158394

In [60]:
print(f'Variância (solteiros): {variancia_solteiros}')
print(f'Desvio Padrão (solteiros): {desvio_padrao_solteiros}')
print(f'Coeficiente de Variação (solteiros): {coeficiente_variacao_solteiros}%')

Variância (solteiros): 2115179856.9917345
Desvio Padrão (solteiros): 45991.084538111674
Coeficiente de Variação (solteiros): 320.31881694550896%

In [61]:
print(f'Variância (casados): {variancia_casados}')
print(f'Desvio Padrão (casados): {desvio_padrao_casados}')
print(f'Coeficiente de Variação (casados): {coeficiente_variacao_casados}%')

Variância (casados): 512292731.66322327
Desvio Padrão (casados): 22633.884590657948
Coeficiente de Variação (casados): 323.05800823594564%

In [62]:
print(f'Variância (viúvos): {variancia_viuvos}')
print(f'Desvio Padrão (viúvos): {desvio_padrao_viuvos}')
print(f'Coeficiente de Variação (viúvos): {coeficiente_variacao_viuvos}%')

Variância (viúvos): 8523235.413223138
Desvio Padrão (viúvos): 2919.458068413235
Coeficiente de Variação (viúvos): 458.0521858871143%

In [63]:
print(f'Variância (solteiras): {variancia_solteiras}')
print(f'Desvio Padrão (solteiras): {desvio_padrao_solteiras}')
print(f'Coeficiente de Variação (solteiras): {coeficiente_variacao_solteiras}%')

Variância (solteiras): 351438887.6033059
Desvio Padrão (solteiras): 18746.703379616
Coeficiente de Variação (solteiras): 458.1509379599555%

In [64]:
print(f'Variância (casadas): {variancia_casadas}')
print(f'Desvio Padrão (casadas): {desvio_padrao_casadas}')
print(f'Coeficiente de Variação (casadas): {coeficiente_variacao_casadas}%')

Variância (casadas): 4338842.975206612
Desvio Padrão (casadas): 2082.9889522526546
Coeficiente de Variação (casadas): -458.257569495584%

In [65]:
print(f'Variância (viúvas): {variancia_viuvas}')
print(f'Desvio Padrão (viúvas): {desvio_padrao_viuvas}')
print(f'Coeficiente de Variação (viúvas): {coeficiente_variacao_viuvas}%')

Variância (viúvas): 87374556.80991735
Desvio Padrão (viúvas): 9347.43584144429
Coeficiente de Variação (viúvas): 230.1242010158394%

In [66]:
media_solteiros = np.mean(diferenca_solteiros)
media_solteiros

14357.90909090909

In [67]:
media_casados = np.mean(diferenca_casados)
media_casados

7006.136363636364

In [68]:
media_viuvos = np.mean(diferenca_viuvos)
media_viuvos

637.3636363636364

In [69]:
media_solteiras = np.mean(diferenca_solteiras)
media_solteiras

4091.818181818182

In [70]:
media_casadas = np.mean(diferenca_casadas)
media_casadas

-454.54545454545456

In [71]:
media_viuvas = np.mean(diferenca_viuvas)
media_viuvas

4061.909090909091

In [72]:
outlier_inferior_solteiros = media_solteiros - (3 * desvio_padrao_solteiros)
outlier_superior_solteiros = media_solteiros + (3 * desvio_padrao_solteiros)

print(outlier_inferior_solteiros, outlier_superior_solteiros)

-123615.34452342594 152331.16270524412

In [73]:
outlier_inferior_casados = media_casados - (3 * desvio_padrao_casados)
outlier_superior_casados = media_casados + (3 * desvio_padrao_casados)

print(outlier_inferior_casados, outlier_superior_casados)

-60895.51740833747 74907.79013561021

In [74]:
outlier_inferior_viuvos = media_viuvos - (3 * desvio_padrao_viuvos)
outlier_superior_viuvos = media_viuvos + (3 * desvio_padrao_viuvos)

print(outlier_inferior_viuvos, outlier_superior_viuvos)

-8121.0105688760705 9395.737841603343

In [75]:
outlier_inferior_solteiras = media_solteiras - (3 * desvio_padrao_solteiras)
outlier_superior_solteiras = media_solteiras + (3 * desvio_padrao_solteiras)

print(outlier_inferior_solteiras, outlier_superior_solteiras)

-52148.29195702982 60331.928320666186

In [76]:
outlier_inferior_casadas = media_casadas - (3 * desvio_padrao_casadas)
outlier_superior_casadas = media_casadas + (3 * desvio_padrao_casadas)

print(outlier_inferior_casadas, outlier_superior_casadas)

-6703.512311303419 5794.421402212509

In [77]:
outlier_inferior_viuvas = media_viuvas - (3 * desvio_padrao_viuvas)
outlier_superior_viuvas = media_viuvas + (3 * desvio_padrao_viuvas)

print(outlier_inferior_viuvas, outlier_superior_viuvas)

-23980.39843342378 32104.216615241963

# Raças

In [78]:
racas = df[['Unnamed: 0','Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17']]

columns_multiindex = pd.MultiIndex.from_tuples([
    ('', '', 'Províncias e Município Neutro'),
    ('Raças', 'dos Homens', 'Brancos'),
    ('Raças', 'dos Homens', 'Pardos'),
    ('Raças', 'dos Homens', 'Pretos'),
    ('Raças', 'dos Homens', 'Caboclos'),
    ('Raças', 'das Mulheres', 'Brancas'),
    ('Raças', 'das Mulheres', 'Pardas'),
    ('Raças', 'das Mulheres', 'Pretas'),
    ('Raças', 'das Mulheres', 'Caboclas')
])

racas.columns = columns_multiindex

racas

                                        Raças                             \
                                   dos Homens
    Províncias e Município Neutro     Brancos   Pardos  Pretos  Caboclos
0                             NaN       Raças      NaN     NaN       NaN
1                             NaN  dos Homens      NaN     NaN       NaN
2   Províncias e Município Neutro     Brancos   Pardos  Pretos  Caboclos
3                        Amazonas        6911     4210     711     19151
4                            Pará       49663    46899    9200     22827
5                        Maranhão       52267    71662   12504      5509
6                           Piauí       22208    53474    7505      7135
7                           Ceará      136940   172841   14424     26701
8             Rio Grande do Norte       52835    42213   12202      5471
9                         Paraíba       73475    89921   11155      4882
10                     Pernambuco      149930   194897   30795      5943
11                        Alagoas       45343    98916    8220      3105
12                        Sergipe       24358    39524    9321      1536
13                          Bahia      178605   287131  137574     27043
14                 Espírito Santo       13555     9648    3395      3009
15               Município Neutro       96255    22762   14198       665
16                 Rio de Janeiro      160595    61542   29517      4152
17                      São Paulo      221260    76288   29512     21244
18                         Paraná       35936    15358    3292      4718
19                 Santa Catarina       63502     5941    2199      1446
20              Rio Grande do Sul      136094    24487   17828     12613
21                   Minas Gerais      421861   302948  105507     17276
22                          Goiás       21152    42482    9088      2246
23                    Mato Grosso        9027    10827    3861      4276
24                          Total     1971772  1673971  472008    200948


    das Mulheres
         Brancas   Pardas  Pretas  Caboclas
0            NaN      NaN     NaN       NaN
1   das Mulheres      NaN     NaN       NaN
2        Brancas   Pardas  Pretas  Caboclas
3           4300     3046     625     17677
4          42971    46828    7629     21762
5          51246    72699   12780      5434
6          21239    53191    7357      6318
7         131896   166325   14510     26136
8          49630    41877   11163      5568
9          71246    88675   10661      4685
10        141229   192954   30901      5862
11         43455   101283    8687      3259
12         25420    42059    9851      1551
13        152874   278573  127153     22839
14         13027    10881    3443      2520
15         55544    22083   14268       258
16        142680    59703   28198      3700
17        212172    75018   27027     18221
18         33762    15278    3449      4369
19         62440     5796    2048      1446
20        122273    24179   16444     13104
21        409126   295865  101647     15046
22         20777    43907    8087      2004
23          8210    10087    3214      4248
24       1815517  1650307  449142    186007

In [79]:
print(df.columns)
print(df.iloc[3:25, 10])
print(df2.columns)
print(df2.iloc[:, 9])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        6911
4       49663
5       52267
6       22208
7      136940
8       52835
9       73475
10     149930
11      45343
12      24358
13     178605
14      13555
15      96255
16     160595
17     221260
18      35936
19      63502
20     136094
21     421861
22      21152
23       9027
24    1971772
Name: Unnamed: 10, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0          61
1        9663
2       52267
3       22208
4      136949
5        5285
6           0
7     1491230
8      450431
9       24953
10     178605
11      33555
12       9635
13     160595
14          0
15          0
16      63502
17       1309
18     421861
19      21154
20          0
21          0
Name: 9, dtype: int64

In [80]:
print(df.columns)
print(df.iloc[3:25, 11])
print(df2.columns)
print(df2.iloc[:, 10])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        4210
4       46899
5       71662
6       53474
7      172841
8       42213
9       89921
10     194897
11      98916
12      39524
13     287131
14       9648
15      22762
16      61542
17      76288
18      15358
19       5941
20      24487
21     302948
22      42482
23      10827
24    1673971
Name: Unnamed: 11, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0         4210
1        46899
2        71662
3        53474
4        12841
5        42213
6        89921
7       194897
8        98916
9        39524
10      287131
11        9648
12       22762
13       61542
14       76288
15       15358
16          94
17       24487
18      302948
19       42482
20       10827
21    16739711
Name: 10, dtype: int64

In [81]:
print(df.columns)
print(df.iloc[3:25, 12])
print(df2.columns)
print(df2.iloc[:, 11])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        711
4       9200
5      12504
6       7505
7      14424
8      12202
9      11155
10     30795
11      8220
12      9321
13    137574
14      3395
15     14198
16     29517
17     29512
18      3292
19      2199
20     17828
21    105507
22      9088
23      3861
24    472008
Name: Unnamed: 12, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0          7
1       9200
2      12504
3       7505
4       1442
5      12202
6      11155
7      30795
8       5220
9       9321
10    137574
11      3396
12     14198
13     20517
14     29512
15      3202
16        21
17         0
18    105507
19      9088
20      3861
21    472008
Name: 11, dtype: int64

In [82]:
print(df.columns)
print(df.iloc[3:25, 13])
print(df2.columns)
print(df2.iloc[:, 12])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3      19151
4      22827
5       5509
6       7135
7      26701
8       5471
9       4882
10      5943
11      3105
12      1536
13     27043
14      3009
15       665
16      4152
17     21244
18      4718
19      1446
20     12613
21     17276
22      2246
23      4276
24    200948
Name: Unnamed: 13, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0      19161
1      22827
2       5509
3       7135
4      26701
5       6471
6       4882
7       5943
8       3106
9       1536
10     27043
11      3009
12       665
13      4152
14      1244
15      4718
16      1446
17     12613
18     17276
19      2246
20       420
21    200948
Name: 12, dtype: int64

In [83]:
print(df.columns)
print(df.iloc[3:25, 14])
print(df2.columns)
print(df2.iloc[:, 13])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        4300
4       42971
5       51246
6       21239
7      131896
8       49630
9       71246
10     141229
11      43455
12      25420
13     152874
14      13027
15      55544
16     142680
17     212172
18      33762
19      62440
20     122273
21     409126
22      20777
23       8210
24    1815517
Name: Unnamed: 14, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0        4300
1       42074
2       51246
3      212391
4      131896
5       49630
6        7126
7      141229
8       43455
9       25420
10     152874
11      13027
12      55544
13     142680
14     212172
15      33762
16      62440
17     122273
18     409126
19      20777
20       8210
21    1815517
Name: 13, dtype: int64

In [84]:
print(df.columns)
print(df.iloc[3:25, 15])
print(df2.columns)
print(df2.iloc[:, 14])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        3046
4       46828
5       72699
6       53191
7      166325
8       41877
9       88675
10     192954
11     101283
12      42059
13     278573
14      10881
15      22083
16      59703
17      75018
18      15278
19       5796
20      24179
21     295865
22      43907
23      10087
24    1650307
Name: Unnamed: 15, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0        3046
1       40228
2       72699
3       53191
4      160325
5       41877
6       88675
7      192054
8      101283
9       42059
10     278573
11       1088
12      22083
13      59703
14      75018
15      15278
16       5796
17          2
18     208865
19      43907
20      10087
21    1650307
Name: 14, dtype: int64

In [85]:
print(df.columns)
print(df.iloc[3:25, 16])
print(df2.columns)
print(df2.iloc[:, 15])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        625
4       7629
5      12780
6       7357
7      14510
8      11163
9      10661
10     30901
11      8687
12      9851
13    127153
14      3443
15     14268
16     28198
17     27027
18      3449
19      2048
20     16444
21    101647
22      8087
23      3214
24    449142
Name: Unnamed: 16, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0        625
1       7629
2      12780
3       7357
4      14510
5      11168
6      10661
7      30901
8       8687
9       9851
10    127153
11      3443
12     14208
13     23198
14     27027
15      3449
16      2045
17      1644
18    101647
19         0
20      3214
21    449142
Name: 15, dtype: int64

In [86]:
print(df.columns)
print(df.iloc[3:25, 17])
print(df2.columns)
print(df2.iloc[:, 16])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3      17677
4      21762
5       5434
6       6318
7      26136
8       5568
9       4685
10      5862
11      3259
12      1551
13     22839
14      2520
15       258
16      3700
17     18221
18      4369
19      1446
20     13104
21     15046
22      2004
23      4248
24    186007
Name: Unnamed: 17, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0      17677
1      21762
2       5434
3       6318
4      25136
5       6568
6       4685
7       5862
8       3259
9       1551
10     22839
11      2520
12       258
13      3700
14     18221
15      4369
16      1446
17     13104
18     16046
19      2004
20      4248
21    186007
Name: 16, dtype: int64

In [87]:
tabela_manual_brancos = pd.to_numeric(df.iloc[3:25, 10])
tabela_ocr_brancos = pd.to_numeric(df2.iloc[:, 9])

diferenca_brancos = tabela_manual_brancos.values - tabela_ocr_brancos.values
diferenca_brancos

array([    6850,    40000,        0,        0,       -9,    47550,
          73475, -1341300,  -405088,     -595,        0,   -20000,
          86620,        0,   221260,    35936,        0,   134785,
              0,       -2,     9027,  1971772])

In [88]:
tabela_manual_pardos = pd.to_numeric(df.iloc[3:25, 11])
tabela_ocr_pardos = pd.to_numeric(df2.iloc[:, 10])

diferenca_pardos = tabela_manual_pardos.values - tabela_ocr_pardos.values
diferenca_pardos

array([        0,         0,         0,         0,    160000,         0,
               0,         0,         0,         0,         0,         0,
               0,         0,         0,         0,      5847,         0,
               0,         0,         0, -15065740])

In [89]:
tabela_manual_pretos = pd.to_numeric(df.iloc[3:25, 12])
tabela_ocr_pretos = pd.to_numeric(df2.iloc[:, 11])

diferenca_pretos = tabela_manual_pretos.values - tabela_ocr_pretos.values
diferenca_pretos

array([  704,     0,     0,     0, 12982,     0,     0,     0,  3000,
           0,     0,    -1,     0,  9000,     0,    90,  2178, 17828,
           0,     0,     0,     0])

In [90]:
tabela_manual_caboclos = pd.to_numeric(df.iloc[3:25, 13])
tabela_ocr_caboclos = pd.to_numeric(df2.iloc[:, 12])

diferenca_caboclos = tabela_manual_caboclos.values - tabela_ocr_caboclos.values
diferenca_caboclos

array([  -10,     0,     0,     0,     0, -1000,     0,     0,    -1,
           0,     0,     0,     0,     0, 20000,     0,     0,     0,
           0,     0,  3856,     0])

In [91]:
tabela_manual_brancas = pd.to_numeric(df.iloc[3:25, 14])
tabela_ocr_brancas = pd.to_numeric(df2.iloc[:, 13])

diferenca_brancas = tabela_manual_brancas.values - tabela_ocr_brancas.values
diferenca_brancas

array([      0,     897,       0, -191152,       0,       0,   64120,
             0,       0,       0,       0,       0,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
             0])

In [92]:
tabela_manual_pardas = pd.to_numeric(df.iloc[3:25, 15])
tabela_ocr_pardas = pd.to_numeric(df2.iloc[:, 14])

diferenca_pardas = tabela_manual_pardas.values - tabela_ocr_pardas.values
diferenca_pardas

array([    0,  6600,     0,     0,  6000,     0,     0,   900,     0,
           0,     0,  9793,     0,     0,     0,     0,     0, 24177,
       87000,     0,     0,     0])

In [93]:
tabela_manual_pretas = pd.to_numeric(df.iloc[3:25, 16])
tabela_ocr_pretas = pd.to_numeric(df2.iloc[:, 15])

diferenca_pretas = tabela_manual_pretas.values - tabela_ocr_pretas.values
diferenca_pretas

array([    0,     0,     0,     0,     0,    -5,     0,     0,     0,
           0,     0,     0,    60,  5000,     0,     0,     3, 14800,
           0,  8087,     0,     0])

In [94]:
tabela_manual_caboclas = pd.to_numeric(df.iloc[3:25, 17])
tabela_ocr_caboclas = pd.to_numeric(df2.iloc[:, 16])

diferenca_caboclas = tabela_manual_caboclas.values - tabela_ocr_caboclas.values
diferenca_caboclas

array([    0,     0,     0,     0,  1000, -1000,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
       -1000,     0,     0,     0])

In [95]:
variancia_brancos = np.var(diferenca_brancos)
variancia_brancos

268324199500.67148

In [96]:
variancia_pardos = np.var(diferenca_pardos)
variancia_pardos

9859588056113.117

In [97]:
variancia_pretos = np.var(diferenca_pretos)
variancia_pretos

22106778.588842977

In [98]:
variancia_caboclos = np.var(diferenca_caboclos)
variancia_caboclos

17824835.514462814

In [99]:
variancia_brancas = np.var(diferenca_brancas)
variancia_brancas

1814912843.514463

In [100]:
variancia_pardas = np.var(diferenca_pardas)
variancia_pardas

341267402.92561984

In [101]:
variancia_pretas = np.var(diferenca_pretas)
variancia_pretas

12452122.811983472

In [102]:
variancia_caboclas = np.var(diferenca_caboclas)
variancia_caboclas

134297.520661157

In [103]:
desvio_padrao_brancos = np.std(diferenca_brancos)
desvio_padrao_brancos

518000.1925681799

In [104]:
desvio_padrao_pardos = np.std(diferenca_pardos)
desvio_padrao_pardos

3139998.0981066083

In [105]:
desvio_padrao_pretos = np.std(diferenca_pretos)
desvio_padrao_pretos

4701.784617445059

In [106]:
desvio_padrao_caboclos = np.std(diferenca_caboclos)
desvio_padrao_caboclos

4221.946886741093

In [107]:
desvio_padrao_brancas = np.std(diferenca_brancas)
desvio_padrao_brancas

42601.793900192315

In [108]:
desvio_padrao_pardas = np.std(diferenca_pardas)
desvio_padrao_pardas

18473.42423389935

In [109]:
desvio_padrao_pretas = np.std(diferenca_pretas)
desvio_padrao_pretas

3528.756553232806

In [110]:
desvio_padrao_caboclas = np.std(diferenca_caboclas)
desvio_padrao_caboclas

366.4662612862977

In [111]:
coeficiente_variacao_brancos = desvio_padrao_brancos / np.mean(diferenca_brancos) * 100
coeficiente_variacao_brancos

1324.6839389106535

In [112]:
coeficiente_variacao_pardos = desvio_padrao_pardos / np.mean(diferenca_pardos) * 100
coeficiente_variacao_pardos

-463.62720966080343

In [113]:
coeficiente_variacao_pretos = desvio_padrao_pretos / np.mean(diferenca_pretos) * 100
coeficiente_variacao_pretos

225.9436482029473

In [114]:
coeficiente_variacao_caboclos = desvio_padrao_caboclos / np.mean(diferenca_caboclos) * 100
coeficiente_variacao_caboclos

406.57838261459415

In [115]:
coeficiente_variacao_brancas = desvio_padrao_brancas / np.mean(diferenca_brancas) * 100
coeficiente_variacao_brancas

-743.044726526524

In [116]:
coeficiente_variacao_pardas = desvio_padrao_pardas / np.mean(diferenca_pardas) * 100
coeficiente_variacao_pardas

302.23494693670386

In [117]:
coeficiente_variacao_pretas = desvio_padrao_pretas / np.mean(diferenca_pretas) * 100
coeficiente_variacao_pretas

277.8051321206718

In [118]:
coeficiente_variacao_caboclas = desvio_padrao_caboclas / np.mean(diferenca_caboclas) * 100
coeficiente_variacao_caboclas

-806.2257748298549

In [119]:
print(f'Variância (brancos): {variancia_brancos}')
print(f'Desvio Padrão (brancos): {desvio_padrao_brancos}')
print(f'Coeficiente de Variação (brancos): {coeficiente_variacao_brancos}%')

Variância (brancos): 268324199500.67148
Desvio Padrão (brancos): 518000.1925681799
Coeficiente de Variação (brancos): 1324.6839389106535%

In [120]:
print(f'Variância (pardos): {variancia_pardos}')
print(f'Desvio Padrão (pardos): {desvio_padrao_pardos}')
print(f'Coeficiente de Variação (pardos): {coeficiente_variacao_pardos}%')

Variância (pardos): 9859588056113.117
Desvio Padrão (pardos): 3139998.0981066083
Coeficiente de Variação (pardos): -463.62720966080343%

In [121]:
print(f'Variância (pretos): {variancia_pretos}')
print(f'Desvio Padrão (pretos): {desvio_padrao_pretos}')
print(f'Coeficiente de Variação (pretos): {coeficiente_variacao_pretos}%')

Variância (pretos): 22106778.588842977
Desvio Padrão (pretos): 4701.784617445059
Coeficiente de Variação (pretos): 225.9436482029473%

In [122]:
print(f'Variância (caboclos): {variancia_caboclos}')
print(f'Desvio Padrão (caboclos): {desvio_padrao_caboclos}')
print(f'Coeficiente de Variação (caboclos): {coeficiente_variacao_caboclos}%')

Variância (caboclos): 17824835.514462814
Desvio Padrão (caboclos): 4221.946886741093
Coeficiente de Variação (caboclos): 406.57838261459415%

In [123]:
print(f'Variância (brancas): {variancia_brancas}')
print(f'Desvio Padrão (brancas): {desvio_padrao_brancas}')
print(f'Coeficiente de Variação (brancas): {coeficiente_variacao_brancas}%')

Variância (brancas): 1814912843.514463
Desvio Padrão (brancas): 42601.793900192315
Coeficiente de Variação (brancas): -743.044726526524%

In [124]:
print(f'Variância (pardas): {variancia_pardas}')
print(f'Desvio Padrão (pardas): {desvio_padrao_pardas}')
print(f'Coeficiente de Variação (pardas): {coeficiente_variacao_pardas}%')

Variância (pardas): 341267402.92561984
Desvio Padrão (pardas): 18473.42423389935
Coeficiente de Variação (pardas): 302.23494693670386%

In [125]:
print(f'Variância (pretas): {variancia_pretas}')
print(f'Desvio Padrão (pretas): {desvio_padrao_pretas}')
print(f'Coeficiente de Variação (pretas): {coeficiente_variacao_pretas}%')

Variância (pretas): 12452122.811983472
Desvio Padrão (pretas): 3528.756553232806
Coeficiente de Variação (pretas): 277.8051321206718%

In [126]:
print(f'Variância (caboclas): {variancia_caboclas}')
print(f'Desvio Padrão (caboclas): {desvio_padrao_caboclas}')
print(f'Coeficiente de Variação (caboclas): {coeficiente_variacao_caboclas}%')

Variância (caboclas): 134297.520661157
Desvio Padrão (caboclas): 366.4662612862977
Coeficiente de Variação (caboclas): -806.2257748298549%

In [127]:
media_brancos = np.mean(diferenca_brancos)
media_brancos

39103.681818181816

In [128]:
media_pardos = np.mean(diferenca_pardos)
media_pardos

-677267.8636363636

In [129]:
media_pretos = np.mean(diferenca_pretos)
media_pretos

2080.9545454545455

In [130]:
media_caboclos = np.mean(diferenca_caboclos)
media_caboclos

1038.409090909091

In [131]:
media_brancas = np.mean(diferenca_brancas)
media_brancas

-5733.409090909091

In [132]:
media_pardas = np.mean(diferenca_pardas)
media_pardas

6112.272727272727

In [133]:
media_pretas = np.mean(diferenca_pretas)
media_pretas

1270.2272727272727

In [134]:
media_caboclas = np.mean(diferenca_caboclas)
media_caboclas

-45.45454545454545

In [135]:
outlier_inferior_brancos = media_brancos - (3 * desvio_padrao_brancos)
outlier_superior_brancos = media_brancos + (3 * desvio_padrao_brancos)

print(outlier_inferior_brancos, outlier_superior_brancos)

-1514896.8958863579 1593104.2595227216

In [136]:
outlier_inferior_pardos = media_pardos - (3 * desvio_padrao_pardos)
outlier_superior_pardos = media_pardos + (3 * desvio_padrao_pardos)

print(outlier_inferior_pardos, outlier_superior_pardos)

-10097262.157956189 8742726.430683462

In [137]:
outlier_inferior_pretos = media_pretos - (3 * desvio_padrao_pretos)
outlier_superior_pretos = media_pretos + (3 * desvio_padrao_pretos)

print(outlier_inferior_pretos, outlier_superior_pretos)

-12024.39930688063 16186.308397789722

In [138]:
outlier_inferior_caboclos = media_caboclos - (3 * desvio_padrao_caboclos)
outlier_superior_caboclos = media_caboclos + (3 * desvio_padrao_caboclos)

print(outlier_inferior_caboclos, outlier_superior_caboclos)

-11627.431569314187 13704.24975113237

In [139]:
outlier_inferior_brancas = media_brancas - (3 * desvio_padrao_brancas)
outlier_superior_brancas = media_brancas + (3 * desvio_padrao_brancas)

print(outlier_inferior_brancas, outlier_superior_brancas)

-133538.79079148604 122071.97260966786

In [140]:
outlier_inferior_pardas = media_pardas - (3 * desvio_padrao_pardas)
outlier_superior_pardas = media_pardas + (3 * desvio_padrao_pardas)

print(outlier_inferior_pardas, outlier_superior_pardas)

-49307.99997442532 61532.54542897078

In [141]:
outlier_inferior_pretas = media_pretas - (3 * desvio_padrao_pretas)
outlier_superior_pretas = media_pretas + (3 * desvio_padrao_pretas)

print(outlier_inferior_pretas, outlier_superior_pretas)

-9316.042386971145 11856.496932425689

In [142]:
outlier_inferior_caboclas = media_caboclas - (3 * desvio_padrao_caboclas)
outlier_superior_caboclas = media_caboclas + (3 * desvio_padrao_caboclas)

print(outlier_inferior_caboclas, outlier_superior_caboclas)

-1144.8533293134387 1053.9442384043477

# Religião

In [143]:
religiao = df[['Unnamed: 0','Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21']]

religiao_header = religiao.iloc[2]
religiao.columns = religiao_header
religiao = religiao[3:]

columns_multiindex = pd.MultiIndex.from_tuples([
    ('', '', 'Províncias e Município Neutro'),
    ('Religião', 'dos Homens', 'Católicos'),
    ('Religião', 'dos Homens', 'Acatólicos'),
    ('Religião', 'das Mulheres', 'Católicas'),
    ('Religião', 'das Mulheres', 'Acatólicas')
])

religiao.columns = columns_multiindex

religiao

                                   Religião
                                 dos Homens            das Mulheres
   Províncias e Município Neutro  Católicos Acatólicos    Católicas Acatólicas
3                       Amazonas      30903         80        25641          7
4                           Pará     128396        193       119169         21
5                       Maranhão     141865         77       142100         59
6                          Piauí      90313          9        88105          0
7                          Ceará     350868         38       338857         10
8            Rio Grande do Norte     112717          4       108238          0
9                        Paraíba     179429          4       175266          1
10                    Pernambuco     381361        204       370906         40
11                       Alagoas     155557         27       156683          1
12                       Sergipe      74739          0        78881          0
13                         Bahia     630196        157       581384         55
14                Espírito Santo      29377        230        29687        184
15              Município Neutro     132552       1328        91553        600
16                Rio de Janeiro     255433        373       234066        215
17                     São Paulo     346326       1973       331217       1221
18                        Paraná      58755        549        56594        264
19                Santa Catarina      67635       5453        66742       4988
20             Rio Grande do Sul     187182       3840       173617       2383
21                  Minas Gerais     845840       1752       820290       1394
22                         Goiás      74967          1        74775          0
23                   Mato Grosso      27975         16        25749         10
24                         Total    4302386      16313      4089520      11453

In [144]:
print(df.columns)
print(df.iloc[3:25, 18])
print(df2.columns)
print(df2.iloc[:, 17])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       30903
4      128396
5      141865
6       90313
7      350868
8      112717
9      179429
10     381361
11     155557
12      74739
13     630196
14      29377
15     132552
16     255433
17     346326
18      58755
19      67635
20     187182
21     845840
22      74967
23      27975
24    4302386
Name: Unnamed: 18, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0      30903
1     128396
2     141865
3      90313
4     350808
5     112717
6     179429
7     381361
8     158557
9        473
10    630196
11     29377
12    132562
13    255433
14    346326
15     58765
16     67635
17    187182
18    815340
19       467
20         0
21         0
Name: 17, dtype: int64

In [145]:
print(df.columns)
print(df.iloc[3:25, 19])
print(df2.columns)
print(df2.iloc[:, 18])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        80
4       193
5        77
6         9
7        38
8         4
9         4
10      204
11       27
12        0
13      157
14      230
15     1328
16      373
17     1973
18      549
19     5453
20     3840
21     1752
22        1
23       16
24    16313
Name: Unnamed: 19, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
Name: 18, dtype: int64

In [146]:
print(df.columns)
print(df.iloc[3:25, 20])
print(df2.columns)
print(df2.iloc[:, 19])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       25641
4      119169
5      142100
6       88105
7      338857
8      108238
9      175266
10     370906
11     156683
12      78881
13     581384
14      29687
15      91553
16     234066
17     331217
18      56594
19      66742
20     173617
21     820290
22      74775
23      25749
24    4089520
Name: Unnamed: 20, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0       25641
1      119169
2      142100
3       88105
4      338857
5     1108238
6      175266
7      370906
8      156683
9       78881
10     681384
11      29687
12        155
13     234066
14      31217
15      56501
16        607
17     173617
18    1820200
19       4776
20      25749
21    4089520
Name: 19, dtype: int64

In [147]:
print(df.columns)
print(df.iloc[3:25, 21])
print(df2.columns)
print(df2.iloc[:, 20])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3         7
4        21
5        59
6         0
7        10
8         0
9         1
10       40
11        1
12        0
13       55
14      184
15      600
16      215
17     1221
18      264
19     4988
20     2383
21     1394
22        0
23       10
24    11453
Name: Unnamed: 21, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0         0
1         0
2         0
3         0
4         0
5         0
6         0
7         0
8         0
9         0
10        0
11        0
12        0
13        0
14        0
15        0
16        0
17        0
18        0
19        0
20        0
21    11453
Name: 20, dtype: int64

In [148]:
tabela_manual_catolicos = pd.to_numeric(df.iloc[3:25, 18])
tabela_ocr_catolicos = pd.to_numeric(df2.iloc[:, 17])

diferenca_catolicos = tabela_manual_catolicos.values - tabela_ocr_catolicos.values
diferenca_catolicos

array([      0,       0,       0,       0,      60,       0,       0,
             0,   -3000,   74266,       0,       0,     -10,       0,
             0,     -10,       0,       0,   30500,   74500,   27975,
       4302386])

In [149]:
tabela_manual_acatolicos = pd.to_numeric(df.iloc[3:25, 19])
tabela_ocr_acatolicos = pd.to_numeric(df2.iloc[:, 18])

diferenca_acatolicos = tabela_manual_acatolicos.values - tabela_ocr_acatolicos.values
diferenca_acatolicos

array([   80,   193,    77,     9,    38,     4,     4,   204,    27,
           0,   157,   230,  1328,   373,  1973,   549,  5453,  3840,
        1752,     1,    16, 16313])

In [150]:
tabela_manual_catolicas = pd.to_numeric(df.iloc[3:25, 20])
tabela_ocr_catolicas = pd.to_numeric(df2.iloc[:, 19])

diferenca_catolicas = tabela_manual_catolicas.values - tabela_ocr_catolicas.values
diferenca_catolicas

array([       0,        0,        0,        0,        0, -1000000,
              0,        0,        0,        0,  -100000,        0,
          91398,        0,   300000,       93,    66135,        0,
        -999910,    69999,        0,        0])

In [151]:
tabela_manual_acatolicas = pd.to_numeric(df.iloc[3:25, 21])
tabela_ocr_acatolicas = pd.to_numeric(df2.iloc[:, 20])

diferenca_acatolicas = tabela_manual_acatolicas.values - tabela_ocr_acatolicas.values
diferenca_acatolicas

array([   7,   21,   59,    0,   10,    0,    1,   40,    1,    0,   55,
        184,  600,  215, 1221,  264, 4988, 2383, 1394,    0,   10,    0])

In [152]:
variancia_catolicos = np.var(diferenca_catolicos)
variancia_catolicos

800005857328.5227

In [153]:
variancia_acatolicos = np.var(diferenca_acatolicos)
variancia_acatolicos

12343767.357438017

In [154]:
variancia_catolicas = np.var(diferenca_catolicas)
variancia_catolicas

91140001415.52272

In [155]:
variancia_acatolicas = np.var(diferenca_acatolicas)
variancia_acatolicas

1297688.9690082644

In [156]:
desvio_padrao_catolicos = np.std(diferenca_catolicos)
desvio_padrao_catolicos

894430.4653401083

In [157]:
desvio_padrao_acatolicos = np.std(diferenca_acatolicos)
desvio_padrao_acatolicos

3513.369800837654

In [158]:
desvio_padrao_catolicas = np.std(diferenca_catolicas)
desvio_padrao_catolicas

301894.0234842729

In [159]:
desvio_padrao_acatolicas = np.std(diferenca_acatolicas)
desvio_padrao_acatolicas

1139.1615201578152

In [160]:
coeficiente_variacao_catolicos = desvio_padrao_catolicos / np.mean(diferenca_catolicos) * 100
coeficiente_variacao_catolicos

436.6302244537345

In [161]:
coeficiente_variacao_acatolicos = desvio_padrao_acatolicos / np.mean(diferenca_acatolicos) * 100
coeficiente_variacao_acatolicos

236.94594162787283

In [162]:
coeficiente_variacao_catolicas = desvio_padrao_catolicas / np.mean(diferenca_catolicas) * 100
coeficiente_variacao_catolicas

-422.4214132077838

In [163]:
coeficiente_variacao_acatolicas = desvio_padrao_acatolicas / np.mean(diferenca_acatolicas) * 100
coeficiente_variacao_acatolicas

218.82086303564074

In [164]:
print(f'Variância (católicos): {variancia_catolicos}')
print(f'Desvio Padrão (católicos): {desvio_padrao_catolicos}')
print(f'Coeficiente de Variação (católicos): {coeficiente_variacao_catolicos}%')

Variância (católicos): 800005857328.5227
Desvio Padrão (católicos): 894430.4653401083
Coeficiente de Variação (católicos): 436.6302244537345%

In [165]:
print(f'Variância (acatólicos): {variancia_acatolicos}')
print(f'Desvio Padrão (acatólicos): {desvio_padrao_acatolicos}')
print(f'Coeficiente de Variação (acatólicos): {coeficiente_variacao_acatolicos}%')

Variância (acatólicos): 12343767.357438017
Desvio Padrão (acatólicos): 3513.369800837654
Coeficiente de Variação (acatólicos): 236.94594162787283%

In [166]:
print(f'Variância (católicas): {variancia_catolicas}')
print(f'Desvio Padrão (católicas): {desvio_padrao_catolicas}')
print(f'Coeficiente de Variação (católicas): {coeficiente_variacao_catolicas}%')

Variância (católicas): 91140001415.52272
Desvio Padrão (católicas): 301894.0234842729
Coeficiente de Variação (católicas): -422.4214132077838%

In [167]:
print(f'Variância (acatólicas): {variancia_acatolicas}')
print(f'Desvio Padrão (acatólicas): {desvio_padrao_acatolicas}')
print(f'Coeficiente de Variação (acatólicas): {coeficiente_variacao_acatolicas}%')

Variância (acatólicas): 1297688.9690082644
Desvio Padrão (acatólicas): 1139.1615201578152
Coeficiente de Variação (acatólicas): 218.82086303564074%

In [168]:
media_catolicos = np.mean(diferenca_catolicos)
media_catolicos

204848.5

In [169]:
media_acatolicos = np.mean(diferenca_acatolicos)
media_acatolicos

1482.7727272727273

In [170]:
media_catolicas = np.mean(diferenca_catolicas)
media_catolicas

-71467.5

In [171]:
media_acatolicas = np.mean(diferenca_acatolicas)
media_acatolicas

520.5909090909091

In [172]:
outlier_inferior_catolicos = media_catolicos - (3 * desvio_padrao_catolicos)
outlier_superior_catolicos = media_catolicos + (3 * desvio_padrao_catolicos)

print(outlier_inferior_catolicos, outlier_superior_catolicos)

-2478442.896020325 2888139.896020325

In [173]:
outlier_inferior_acatolicos = media_acatolicos - (3 * desvio_padrao_acatolicos)
outlier_superior_acatolicos = media_acatolicos + (3 * desvio_padrao_acatolicos)

print(outlier_inferior_acatolicos, outlier_superior_acatolicos)

-9057.336675240234 12022.88212978569

In [174]:
outlier_inferior_catolicas = media_catolicas - (3 * desvio_padrao_catolicas)
outlier_superior_catolicas = media_catolicas + (3 * desvio_padrao_catolicas)

print(outlier_inferior_catolicas, outlier_superior_catolicas)

-977149.5704528186 834214.5704528186

In [175]:
outlier_inferior_acatolicas = media_acatolicas - (3 * desvio_padrao_acatolicas)
outlier_superior_acatolicas = media_acatolicas + (3 * desvio_padrao_acatolicas)

print(outlier_inferior_acatolicas, outlier_superior_acatolicas)

-2896.8936513825365 3938.0754695643545

# Nacionalidades

In [176]:
nacionalidade = df[['Unnamed: 0','Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25']]

nacionalidade_header = nacionalidade.iloc[2]
nacionalidade.columns = nacionalidade_header
nacionalidade = nacionalidade[3:]

columns_multiindex = pd.MultiIndex.from_tuples([
    ('', '', 'Províncias e Município Neutro'),
    ('Nacionalidades', 'dos Homens', 'Brasileiros'),
    ('Nacionalidades', 'dos Homens', 'Estrangeiros'),
    ('Nacionalidades', 'das Mulheres', 'Brasileiras'),
    ('Nacionalidades', 'das Mulheres', 'Estrangeiras')
])

nacionalidade.columns = columns_multiindex

nacionalidade

                                 Nacionalidades                            \
                                     dos Homens              das Mulheres
   Províncias e Município Neutro    Brasileiros Estrangeiros  Brasileiras
3                       Amazonas          29223         1760        25222
4                           Pará         123365         5224       118437
5                       Maranhão         139413         2529       141191
6                          Piauí          90022          300        88001
7                          Ceará         349805         1101       338475
8            Rio Grande do Norte         112305          416       108078
9                        Paraíba         178940          493       175102
10                    Pernambuco         373530         8035       368621
11                       Alagoas         154606          978       156321
12                       Sergipe          74352          387        78723
13                         Bahia         622447         7906       577229
14                Espírito Santo          28190         1417        29359
15              Município Neutro          77872        56008        74851
16                Rio de Janeiro         225843        29963       225860
17                     São Paulo         336473        11831       327702
18                        Paraná          57224         2080        56049
19                Santa Catarina          64731         8357        65241
20             Rio Grande do Sul         166042        24980       164522
21                  Minas Gerais         833175        14417       817692
22                         Goiás          74818          150        74698
23                   Mato Grosso          26986         1005        25455
24                         Total        4139362       179337      4036829



   Estrangeiras
3           426
4           753
5           968
6           104
7           392
8           160
9           165
10         2325
11          363
12          158
13         4210
14          512
15        17302
16         8421
17         4736
18          809
19         6489
20        11478
21         3992
22           77
23          304
24        64144

In [177]:
print(df.columns)
print(df.iloc[3:25, 22])
print(df2.columns)
print(df2.iloc[:, 21])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       29223
4      123365
5      139413
6       90022
7      349805
8      112305
9      178940
10     373530
11     154606
12      74352
13     622447
14      28190
15      77872
16     225843
17     336473
18      57224
19      64731
20     166042
21     833175
22      74818
23      26986
24    4139362
Name: Unnamed: 22, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0       29223
1      123365
2      139413
3       90022
4      349805
5      112305
6      178940
7     3736305
8      154606
9       14382
10      29407
11      28190
12         82
13     225843
14          0
15       7224
16       4731
17     166042
18     833175
19      74318
20      26986
21    4139362
Name: 21, dtype: int64

In [178]:
print(df.columns)
print(df.iloc[3:25, 23])
print(df2.columns)
print(df2.iloc[:, 22])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       1760
4       5224
5       2529
6        300
7       1101
8        416
9        493
10      8035
11       978
12       387
13      7906
14      1417
15     56008
16     29963
17     11831
18      2080
19      8357
20     24980
21     14417
22       150
23      1005
24    179337
Name: Unnamed: 23, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0      1760
1       224
2       252
3        30
4       110
5         4
6       493
7      8035
8       978
9       387
10    19061
11        0
12     5608
13    20903
14    11831
15     2030
16     8357
17    24980
18    14417
19      150
20        0
21        0
Name: 22, dtype: int64

In [179]:
print(df.columns)
print(df.iloc[3:25, 24])
print(df2.columns)
print(df2.iloc[:, 23])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       25222
4      118437
5      141191
6       88001
7      338475
8      108078
9      175102
10     368621
11     156321
12      78723
13     577229
14      29359
15      74851
16     225860
17     327702
18      56049
19      65241
20     164522
21     817692
22      74698
23      25455
24    4036829
Name: Unnamed: 24, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0       26222
1      115437
2      141191
3       88012
4      338475
5      108078
6      175102
7      268621
8      156321
9        8120
10          0
11      22359
12      74851
13     225860
14     326102
15       5019
16      65241
17     164522
18          0
19      74608
20      25455
21    1036529
Name: 23, dtype: int64

In [180]:
print(df.columns)
print(df.iloc[3:25, 25])
print(df2.columns)
print(df2.iloc[:, 24])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       426
4       753
5       968
6       104
7       392
8       160
9       165
10     2325
11      363
12      158
13     4210
14      512
15    17302
16     8421
17     4736
18      809
19     6489
20    11478
21     3992
22       77
23      304
24    64144
Name: Unnamed: 25, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
Name: 24, dtype: int64

In [181]:
tabela_manual_brasileiros = pd.to_numeric(df.iloc[3:25, 22])
tabela_ocr_brasileiros = pd.to_numeric(df2.iloc[:, 21])

diferenca_brasileiros = tabela_manual_brasileiros.values - tabela_ocr_brasileiros.values
diferenca_brasileiros

array([       0,        0,        0,        0,        0,        0,
              0, -3362775,        0,    59970,   593040,        0,
          77790,        0,   336473,    50000,    60000,        0,
              0,      500,        0,        0])

In [182]:
tabela_manual_estrangeiros = pd.to_numeric(df.iloc[3:25, 23])
tabela_ocr_estrangeiros = pd.to_numeric(df2.iloc[:, 22])

diferenca_estrangeiros = tabela_manual_estrangeiros.values - tabela_ocr_estrangeiros.values
diferenca_estrangeiros

array([     0,   5000,   2277,    270,    991,    412,      0,      0,
            0,      0, -11155,   1417,  50400,   9060,      0,     50,
            0,      0,      0,      0,   1005, 179337])

In [183]:
tabela_manual_brasileiras = pd.to_numeric(df.iloc[3:25, 24])
tabela_ocr_brasileiras = pd.to_numeric(df2.iloc[:, 23])

diferenca_brasileiras = tabela_manual_brasileiras.values - tabela_ocr_brasileiras.values
diferenca_brasileiras

array([  -1000,    3000,       0,     -11,       0,       0,       0,
        100000,       0,   70603,  577229,    7000,       0,       0,
          1600,   51030,       0,       0,  817692,      90,       0,
       3000300])

In [184]:
tabela_manual_estrangeiras = pd.to_numeric(df.iloc[3:25, 25])
tabela_ocr_estrangeiras = pd.to_numeric(df2.iloc[:, 24])

diferenca_estrangeiras = tabela_manual_estrangeiras.values - tabela_ocr_estrangeiras.values
diferenca_estrangeiras

array([  426,   753,   968,   104,   392,   160,   165,  2325,   363,
         158,  4210,   512, 17302,  8421,  4736,   809,  6489, 11478,
        3992,    77,   304, 64144])

In [185]:
variancia_brasileiros = np.var(diferenca_brasileiros)
variancia_brasileiros

525995615109.47107

In [186]:
variancia_estrangeiros = np.var(diferenca_estrangeiros)
variancia_estrangeiros

1470230329.066116

In [187]:
variancia_brasileiras = np.var(diferenca_brasileiras)
variancia_brasileiras

411268072212.1508

In [188]:
variancia_estrangeiras = np.var(diferenca_estrangeiras)
variancia_estrangeiras

180684748.74380162

In [189]:
desvio_padrao_brasileiros = np.std(diferenca_brasileiros)
desvio_padrao_brasileiros

725255.5515881771

In [190]:
desvio_padrao_estrangeiros = np.std(diferenca_estrangeiros)
desvio_padrao_estrangeiros

38343.58263211872

In [191]:
desvio_padrao_brasileiras = np.std(diferenca_brasileiras)
desvio_padrao_brasileiras

641301.8573278505

In [192]:
desvio_padrao_estrangeiras = np.std(diferenca_estrangeiras)
desvio_padrao_estrangeiras

13441.902720366697

In [193]:
coeficiente_variacao_brasileiros = desvio_padrao_brasileiros / np.mean(diferenca_brasileiros) * 100
coeficiente_variacao_brasileiros

-730.2337542455292

In [194]:
coeficiente_variacao_estrangeiros = desvio_padrao_estrangeiros / np.mean(diferenca_estrangeiros) * 100
coeficiente_variacao_estrangeiros

352.8589908587708

In [195]:
coeficiente_variacao_brasileiras = desvio_padrao_brasileiras / np.mean(diferenca_brasileiras) * 100
coeficiente_variacao_brasileiras

304.884716353459

In [196]:
coeficiente_variacao_estrangeiras = desvio_padrao_estrangeiras / np.mean(diferenca_estrangeiras) * 100
coeficiente_variacao_estrangeiras

230.51404640189836

In [197]:
print(f'Variância (brasileiros): {variancia_brasileiros}')
print(f'Desvio Padrão (brasileiros): {desvio_padrao_brasileiros}')
print(f'Coeficiente de Variação (brasileiros): {coeficiente_variacao_brasileiros}%')

Variância (brasileiros): 525995615109.47107
Desvio Padrão (brasileiros): 725255.5515881771
Coeficiente de Variação (brasileiros): -730.2337542455292%

In [198]:
print(f'Variância (estrangeiros): {variancia_estrangeiros}')
print(f'Desvio Padrão (estrangeiros): {desvio_padrao_estrangeiros}')
print(f'Coeficiente de Variação (estrangeiros): {coeficiente_variacao_estrangeiros}%')

Variância (estrangeiros): 1470230329.066116
Desvio Padrão (estrangeiros): 38343.58263211872
Coeficiente de Variação (estrangeiros): 352.8589908587708%

In [199]:
print(f'Variância (brasileiras): {variancia_brasileiras}')
print(f'Desvio Padrão (brasileiras): {desvio_padrao_brasileiras}')
print(f'Coeficiente de Variação (brasileiras): {coeficiente_variacao_brasileiras}%')

Variância (brasileiras): 411268072212.1508
Desvio Padrão (brasileiras): 641301.8573278505
Coeficiente de Variação (brasileiras): 304.884716353459%

In [200]:
print(f'Variância (estrangeiras): {variancia_estrangeiras}')
print(f'Desvio Padrão (estrangeiras): {desvio_padrao_estrangeiras}')
print(f'Coeficiente de Variação (estrangeiras): {coeficiente_variacao_estrangeiras}%')

Variância (estrangeiras): 180684748.74380162
Desvio Padrão (estrangeiras): 13441.902720366697
Coeficiente de Variação (estrangeiras): 230.51404640189836%

In [201]:
media_brasileiros = np.mean(diferenca_brasileiros)
media_brasileiros

-99318.27272727272

In [202]:
media_estrangeiros = np.mean(diferenca_estrangeiros)
media_estrangeiros

10866.545454545454

In [203]:
media_brasileiras = np.mean(diferenca_brasileiras)
media_brasileiras

210342.4090909091

In [204]:
media_estrangeiras = np.mean(diferenca_estrangeiras)
media_estrangeiras

5831.272727272727

In [205]:
outlier_inferior_brasileiros = media_brasileiros - (3 * desvio_padrao_brasileiros)
outlier_superior_brasileiros = media_brasileiros + (3 * desvio_padrao_brasileiros)

print(outlier_inferior_brasileiros, outlier_superior_brasileiros)

-2275084.927491804 2076448.3820372585

In [206]:
outlier_inferior_estrangeiros = media_estrangeiros - (3 * desvio_padrao_estrangeiros)
outlier_superior_estrangeiros = media_estrangeiros + (3 * desvio_padrao_estrangeiros)

print(outlier_inferior_estrangeiros, outlier_superior_estrangeiros)

-104164.2024418107 125897.29335090161

In [207]:
outlier_inferior_brasileiras = media_brasileiras - (3 * desvio_padrao_brasileiras)
outlier_superior_brasileiras = media_brasileiras + (3 * desvio_padrao_brasileiras)

print(outlier_inferior_brasileiras, outlier_superior_brasileiras)

-1713563.1628926424 2134247.981074461

In [208]:
outlier_inferior_estrangeiras = media_estrangeiras - (3 * desvio_padrao_estrangeiras)
outlier_superior_estrangeiras = media_estrangeiras + (3 * desvio_padrao_estrangeiras)

print(outlier_inferior_estrangeiras, outlier_superior_estrangeiras)

-34494.43543382736 46156.98088837282

# Grau de instrução

In [209]:
instrucao = df[['Unnamed: 0','Instrução', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35']]

instrucao_header = instrucao.iloc[2]
instrucao.columns = instrucao_header
instrucao = instrucao[3:]

columns_multiindex = pd.MultiIndex.from_tuples([
    ('', '', '', 'Províncias e Município Neutro'),
    ('Instrução', '', 'Homens', 'Sabem ler e escrever'),
    ('Instrução', '', 'Homens', 'Analfabetos'),
    ('Instrução', '', 'Mulheres', 'Sabem ler e escrever'),
    ('Instrução', '', 'Mulheres', 'Analfabetas'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninos', 'Frequentam escolas'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninos', 'Não frequentam'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninos', 'Total'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninas', 'Frequentam escolas'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninas', 'Não frequentam'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninas', 'Total')
])

instrucao.columns = columns_multiindex

instrucao

                                            Instrução              \

                                               Homens
   Províncias e Município Neutro Sabem ler e escrever Analfabetos
3                       Amazonas                 6160       24823
4                           Pará                39718       88871
5                       Maranhão                44375       97567
6                          Piauí                17677       72645
7                          Ceará                58657      292249
8            Rio Grande do Norte                23602       39119
9                        Paraíba                29224      150209
10                    Pernambuco                92664      288901
11                       Alagoas                26046      129538
12                       Sergipe                18687       56052
13                         Bahia               161937      468416
14                Espírito Santo                 7229       22378
15              Município Neutro                65164       68714
16                Rio de Janeiro                69997      185809
17                     São Paulo                92977      255327
18                        Paraná                19014       40299
19                Santa Catarina                12927       59161
20             Rio Grande do Sul                 5592      134060
21                  Minas Gerais               145297      702295
22                         Goiás                15699       59299
23                   Mato Grosso                 7114       20877
24                         Total              1012097     3306602

                                                                      \
                                    População escolar de 6 a 15 anos
               Mulheres                                      Meninos
   Sabem ler e escrever Analfabetas               Frequentam escolas
3                  1453       24195                              824
4                 20677       98513                             5768
5                 24196      117963                             8739
6                 10093       78012                             1777
7                 20903      317964                            10021
8                 16220       92018                             2643
9                 11988      163279                             6630
10                54659      316287                            14069
11                15814      140870                             5455
12                10447       68434                             3402
13                37135      494304                            22260
14                 2503       27368                             1564
15                33992       58101                             5788
16                44603      189678                            12622
17                48090      284348                            15069
18                12802       44056                             2558
19                 7999       63731                             3100
20                38341      137659                             9947
21                78271      743413                            19968
22                 6987       67788                             2566
23                 3808       21951                              881
24               550981     3549992                           155651



                                     Meninas
   Não frequentam   Total Frequentam escolas Não frequentam   Total
3            5056    5880                371           3269    3640
4           25753   31521               3441          25020   28461
5           28142   36881               4844          29567   34411
6           15960   17737               1024          16968   17992
7           83808   93829               5399          85087   90486
8           18662   21305               2058          19857   21915
9           44061   50691               3894          45830   49724
10          82133   96202               9301          80960   90261
11          34261   39716               4028          34726   38754
12          14934   18336               1832          17333   19165
13         119426  141686              81743         113313  195056
14           5323    6887                722           5101    6823
15          10449   22237               4258          15019   19277
16          32019   44641               8194          33089   41283
17          71271   86340               8544          73915   82458
18           9666   12224               1866          10762   12628
19          15676   18776               2114          15473   17587
20          36222   46169               7947          33292   41239
21          66983  125012              11940         112824  124764
22          16864   19430               1240          16982   18222
23           5401    6282                338           6187    6525
24         786131  941782             165098         795574  960672

# Grau de instrução (adultos)

In [210]:
instrucao_adultos = df[['Unnamed: 0','Instrução', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29']]

instrucao_adultos_header = instrucao_adultos.iloc[2]
instrucao_adultos.columns = instrucao_adultos_header
instrucao_adultos = instrucao_adultos[3:]

columns_multiindex = pd.MultiIndex.from_tuples([
    ('', '', 'Províncias e Município Neutro'),
    ('Instrução', 'Homens', 'Sabem ler e escrever'),
    ('Instrução', 'Homens', 'Analfabetos'),
    ('Instrução', 'Mulheres', 'Sabem ler e escrever'),
    ('Instrução', 'Mulheres', 'Analfabetas')
])

instrucao_adultos.columns = columns_multiindex

instrucao_adultos

                                            Instrução              \
                                               Homens
   Províncias e Município Neutro Sabem ler e escrever Analfabetos
3                       Amazonas                 6160       24823
4                           Pará                39718       88871
5                       Maranhão                44375       97567
6                          Piauí                17677       72645
7                          Ceará                58657      292249
8            Rio Grande do Norte                23602       39119
9                        Paraíba                29224      150209
10                    Pernambuco                92664      288901
11                       Alagoas                26046      129538
12                       Sergipe                18687       56052
13                         Bahia               161937      468416
14                Espírito Santo                 7229       22378
15              Município Neutro                65164       68714
16                Rio de Janeiro                69997      185809
17                     São Paulo                92977      255327
18                        Paraná                19014       40299
19                Santa Catarina                12927       59161
20             Rio Grande do Sul                 5592      134060
21                  Minas Gerais               145297      702295
22                         Goiás                15699       59299
23                   Mato Grosso                 7114       20877
24                         Total              1012097     3306602


               Mulheres
   Sabem ler e escrever Analfabetas
3                  1453       24195
4                 20677       98513
5                 24196      117963
6                 10093       78012
7                 20903      317964
8                 16220       92018
9                 11988      163279
10                54659      316287
11                15814      140870
12                10447       68434
13                37135      494304
14                 2503       27368
15                33992       58101
16                44603      189678
17                48090      284348
18                12802       44056
19                 7999       63731
20                38341      137659
21                78271      743413
22                 6987       67788
23                 3808       21951
24               550981     3549992

In [211]:
print(df.columns)
print(df.iloc[3:25, 26])
print(df2.columns)
print(df2.iloc[:, 25])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        6160
4       39718
5       44375
6       17677
7       58657
8       23602
9       29224
10      92664
11      26046
12      18687
13     161937
14       7229
15      65164
16      69997
17      92977
18      19014
19      12927
20       5592
21     145297
22      15699
23       7114
24    1012097
Name: Instrução, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0         6160
1        39718
2        44375
3        11977
4        68057
5        23602
6            0
7        92664
8        26046
9       186871
10      161937
11        7229
12       65164
13       69997
14       92977
15       19014
16      129271
17        5592
18      145297
19       15699
20           4
21    10120971
Name: 25, dtype: int64

In [212]:
print(df.columns)
print(df.iloc[3:25, 27])
print(df2.columns)
print(df2.iloc[:, 26])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       24823
4       88871
5       97567
6       72645
7      292249
8       39119
9      150209
10     288901
11     129538
12      56052
13     468416
14      22378
15      68714
16     185809
17     255327
18      40299
19      59161
20     134060
21     702295
22      59299
23      20877
24    3306602
Name: Unnamed: 27, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0       24823
1       88871
2       97667
3       72645
4      292249
5       39119
6      150209
7        2889
8      129538
9       56057
10     468416
11      22378
12      68714
13     185809
14    2552071
15      40299
16      59101
17     134060
18     702295
19      59299
20      20877
21    8000021
Name: 26, dtype: int64

In [213]:
print(df.columns)
print(df.iloc[3:25, 28])
print(df2.columns)
print(df2.iloc[:, 27])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       1453
4      20677
5      24196
6      10093
7      20903
8      16220
9      11988
10     54659
11     15814
12     10447
13     37135
14      2503
15     33992
16     44603
17     48090
18     12802
19      7999
20     38341
21     78271
22      6987
23      3808
24    550981
Name: Unnamed: 28, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0       1458
1      20677
2      24196
3      10023
4      20903
5      36220
6      11988
7     546659
8      15814
9      10447
10     87135
11      2508
12     33992
13     44603
14     48090
15     12302
16      7999
17    383411
18         0
19      6987
20      3808
21    650981
Name: 27, dtype: int64

In [214]:
print(df.columns)
print(df.iloc[3:25, 29])
print(df2.columns)
print(df2.iloc[:, 28])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       24195
4       98513
5      117963
6       78012
7      317964
8       92018
9      163279
10     316287
11     140870
12      68434
13     494304
14      27368
15      58101
16     189678
17     284348
18      44056
19      63731
20     137659
21     743413
22      67788
23      21951
24    3549992
Name: Unnamed: 29, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0       24198
1       98513
2      217063
3       78012
4      317964
5           0
6           0
7          28
8      140370
9       68434
10     493304
11      27368
12      58103
13     189678
14     284348
15      44056
16      63731
17     127659
18          0
19          0
20          0
21    9549992
Name: 28, dtype: int64

In [215]:
tabela_manual_alfabetizados = pd.to_numeric(df.iloc[3:25, 26])
tabela_ocr_alfabetizados = pd.to_numeric(df2.iloc[:, 25])

diferenca_alfabetizados = tabela_manual_alfabetizados.values - tabela_ocr_alfabetizados.values
diferenca_alfabetizados

array([       0,        0,        0,     5700,    -9400,        0,
          29224,        0,        0,  -168184,        0,        0,
              0,        0,        0,        0,  -116344,        0,
              0,        0,     7110, -9108874])

In [216]:
tabela_manual_analfabetos = pd.to_numeric(df.iloc[3:25, 27])
tabela_ocr_analfabetos = pd.to_numeric(df2.iloc[:, 26])

diferenca_analfabetos = tabela_manual_analfabetos.values - tabela_ocr_analfabetos.values
diferenca_analfabetos

array([       0,        0,     -100,        0,        0,        0,
              0,   286012,        0,       -5,        0,        0,
              0,        0, -2296744,        0,       60,        0,
              0,        0,        0, -4693419])

In [217]:
tabela_manual_alfabetizadas = pd.to_numeric(df.iloc[3:25, 28])
tabela_ocr_alfabetizadas = pd.to_numeric(df2.iloc[:, 27])

diferenca_alfabetizadas = tabela_manual_alfabetizadas.values - tabela_ocr_alfabetizadas.values
diferenca_alfabetizadas

array([     -5,       0,       0,      70,       0,  -20000,       0,
       -492000,       0,       0,  -50000,      -5,       0,       0,
             0,     500,       0, -345070,   78271,       0,       0,
       -100000])

In [218]:
tabela_manual_analfabetas = pd.to_numeric(df.iloc[3:25, 29])
tabela_ocr_analfabetas = pd.to_numeric(df2.iloc[:, 28])

diferenca_analfabetas = tabela_manual_analfabetas.values - tabela_ocr_analfabetas.values
diferenca_analfabetas

array([      -3,        0,   -99100,        0,        0,    92018,
         163279,   316259,      500,        0,     1000,        0,
             -2,        0,        0,        0,        0,    10000,
         743413,    67788,    21951, -6000000])

In [219]:
variancia_alfabetizados = np.var(diferenca_alfabetizados)
variancia_alfabetizados

3592342032086.247

In [220]:
variancia_analfabetos = np.var(diferenca_analfabetos)
variancia_analfabetos

1151909395348.4216

In [221]:
variancia_alfabetizadas = np.var(diferenca_alfabetizadas)
variancia_alfabetizadas

15499955296.035124

In [222]:
variancia_analfabetas = np.var(diferenca_analfabetas)
variancia_analfabetas

1623000570341.3164

In [223]:
desvio_padrao_alfabetizados = np.std(diferenca_alfabetizados)
desvio_padrao_alfabetizados

1895347.4700134133

In [224]:
desvio_padrao_analfabetos = np.std(diferenca_analfabetos)
desvio_padrao_analfabetos

1073270.4204199526

In [225]:
desvio_padrao_alfabetizadas = np.std(diferenca_alfabetizadas)
desvio_padrao_alfabetizadas

124498.81644431454

In [226]:
desvio_padrao_analfabetas = np.std(diferenca_analfabetas)
desvio_padrao_analfabetas

1273970.396179329

In [227]:
coeficiente_variacao_alfabetizados = desvio_padrao_alfabetizados / np.mean(diferenca_alfabetizados) * 100
coeficiente_variacao_alfabetizados

-445.4511033741579

In [228]:
coeficiente_variacao_analfabetos = desvio_padrao_analfabetos / np.mean(diferenca_analfabetos) * 100
coeficiente_variacao_analfabetos

-352.19658329259704

In [229]:
coeficiente_variacao_alfabetizadas = desvio_padrao_alfabetizadas / np.mean(diferenca_alfabetizadas) * 100
coeficiente_variacao_alfabetizadas

-295.0720624510411

In [230]:
coeficiente_variacao_analfabetas = desvio_padrao_analfabetas / np.mean(diferenca_analfabetas) * 100
coeficiente_variacao_analfabetas

-598.504488053981

In [231]:
print(f'Variância (alfabetizados): {variancia_alfabetizados}')
print(f'Desvio Padrão (alfabetizados): {desvio_padrao_alfabetizados}')
print(f'Coeficiente de Variação (alfabetizados): {coeficiente_variacao_alfabetizados}%')

Variância (alfabetizados): 3592342032086.247
Desvio Padrão (alfabetizados): 1895347.4700134133
Coeficiente de Variação (alfabetizados): -445.4511033741579%

In [232]:
print(f'Variância (analfabetos): {variancia_analfabetos}')
print(f'Desvio Padrão (analfabetos): {desvio_padrao_analfabetos}')
print(f'Coeficiente de Variação (analfabetos): {coeficiente_variacao_analfabetos}%')

Variância (analfabetos): 1151909395348.4216
Desvio Padrão (analfabetos): 1073270.4204199526
Coeficiente de Variação (analfabetos): -352.19658329259704%

In [233]:
print(f'Variância (alfabetizadas): {variancia_alfabetizadas}')
print(f'Desvio Padrão (alfabetizadas): {desvio_padrao_alfabetizadas}')
print(f'Coeficiente de Variação (alfabetizadas): {coeficiente_variacao_alfabetizadas}%')

Variância (alfabetizadas): 15499955296.035124
Desvio Padrão (alfabetizadas): 124498.81644431454
Coeficiente de Variação (alfabetizadas): -295.0720624510411%

In [234]:
print(f'Variância (analfabetas): {variancia_analfabetas}')
print(f'Desvio Padrão (analfabetas): {desvio_padrao_analfabetas}')
print(f'Coeficiente de Variação (analfabetas): {coeficiente_variacao_analfabetas}%')

Variância (analfabetas): 1623000570341.3164
Desvio Padrão (analfabetas): 1273970.396179329
Coeficiente de Variação (analfabetas): -598.504488053981%

In [235]:
media_alfabetizados = np.mean(diferenca_alfabetizados)
media_alfabetizados

-425489.45454545453

In [236]:
media_analfabetos = np.mean(diferenca_analfabetos)
media_analfabetos

-304736.1818181818

In [237]:
media_alfabetizadas = np.mean(diferenca_alfabetizadas)
media_alfabetizadas

-42192.681818181816

In [238]:
media_analfabetas = np.mean(diferenca_analfabetas)
media_analfabetas

-212858.95454545456

In [239]:
outlier_inferior_alfabetizados = media_alfabetizados - (3 * desvio_padrao_alfabetizados)
outlier_superior_alfabetizados = media_alfabetizados + (3 * desvio_padrao_alfabetizados)

print(outlier_inferior_alfabetizados, outlier_superior_alfabetizados)

-6111531.864585694 5260552.955494786

In [240]:
outlier_inferior_analfabetos = media_analfabetos - (3 * desvio_padrao_analfabetos)
outlier_superior_analfabetos = media_analfabetos + (3 * desvio_padrao_analfabetos)

print(outlier_inferior_analfabetos, outlier_superior_analfabetos)

-3524547.443078039 2915075.079441676

In [241]:
outlier_inferior_alfabetizadas = media_alfabetizadas - (3 * desvio_padrao_alfabetizadas)
outlier_superior_alfabetizadas = media_alfabetizadas + (3 * desvio_padrao_alfabetizadas)

print(outlier_inferior_alfabetizadas, outlier_superior_alfabetizadas)

-415689.1311511254 331303.76751476177

In [242]:
outlier_inferior_analfabetas = media_analfabetas - (3 * desvio_padrao_analfabetas)
outlier_superior_analfabetas = media_analfabetas + (3 * desvio_padrao_analfabetas)

print(outlier_inferior_analfabetas, outlier_superior_analfabetas)

-4034770.1430834415 3609052.2339925324

# Grau de instrução (jovens)

In [243]:
instrucao_jovens = df[['Unnamed: 0', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35']]

instrucao_jovens_header = instrucao_jovens.iloc[2]
instrucao_jovens.columns = instrucao_jovens_header
instrucao_jovens = instrucao_jovens[3:]

columns_multiindex = pd.MultiIndex.from_tuples([
    ('', '', '', 'Províncias e Município Neutro'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninos', 'Frequentam escolas'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninos', 'Não frequentam'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninos', 'Total'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninas', 'Frequentam escolas'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninas', 'Não frequentam'),
    ('Instrução', 'População escolar de 6 a 15 anos', 'Meninas', 'Total')
])

instrucao_jovens.columns = columns_multiindex

instrucao_jovens

                                                        Instrução  \
                                 População escolar de 6 a 15 anos
                                                          Meninos
   Províncias e Município Neutro               Frequentam escolas
3                       Amazonas                              824
4                           Pará                             5768
5                       Maranhão                             8739
6                          Piauí                             1777
7                          Ceará                            10021
8            Rio Grande do Norte                             2643
9                        Paraíba                             6630
10                    Pernambuco                            14069
11                       Alagoas                             5455
12                       Sergipe                             3402
13                         Bahia                            22260
14                Espírito Santo                             1564
15              Município Neutro                             5788
16                Rio de Janeiro                            12622
17                     São Paulo                            15069
18                        Paraná                             2558
19                Santa Catarina                             3100
20             Rio Grande do Sul                             9947
21                  Minas Gerais                            19968
22                         Goiás                             2566
23                   Mato Grosso                              881
24                         Total                           155651



                                     Meninas
   Não frequentam   Total Frequentam escolas Não frequentam   Total
3            5056    5880                371           3269    3640
4           25753   31521               3441          25020   28461
5           28142   36881               4844          29567   34411
6           15960   17737               1024          16968   17992
7           83808   93829               5399          85087   90486
8           18662   21305               2058          19857   21915
9           44061   50691               3894          45830   49724
10          82133   96202               9301          80960   90261
11          34261   39716               4028          34726   38754
12          14934   18336               1832          17333   19165
13         119426  141686              81743         113313  195056
14           5323    6887                722           5101    6823
15          10449   22237               4258          15019   19277
16          32019   44641               8194          33089   41283
17          71271   86340               8544          73915   82458
18           9666   12224               1866          10762   12628
19          15676   18776               2114          15473   17587
20          36222   46169               7947          33292   41239
21          66983  125012              11940         112824  124764
22          16864   19430               1240          16982   18222
23           5401    6282                338           6187    6525
24         786131  941782             165098         795574  960672

In [244]:
print(df.columns)
print(df.iloc[3:25, 30])
print(df2.columns)
print(df2.iloc[:, 29])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        824
4       5768
5       8739
6       1777
7      10021
8       2643
9       6630
10     14069
11      5455
12      3402
13     22260
14      1564
15      5788
16     12622
17     15069
18      2558
19      3100
20      9947
21     19968
22      2566
23       881
24    155651
Name: Unnamed: 30, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0         824
1        5768
2        8730
3          17
4       16921
5        2643
6        6630
7           0
8        5455
9        3402
10      22250
11       1564
12       3788
13      12622
14      15069
15       2558
16       3100
17       9947
18      19968
19       2566
20          8
21    1556511
Name: 29, dtype: int64

In [245]:
print(df.columns)
print(df.iloc[3:25, 31])
print(df2.columns)
print(df2.iloc[:, 30])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       5056
4      25753
5      28142
6      15960
7      83808
8      18662
9      44061
10     82133
11     34261
12     14934
13    119426
14      5323
15     10449
16     32019
17     71271
18      9666
19     15676
20     36222
21     66983
22     16864
23      5401
24    786131
Name: Unnamed: 31, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0         56
1      25153
2        284
3      15969
4       8388
5      18602
6      44061
7       2132
8      34261
9      14934
10    310426
11      5323
12     10449
13     32019
14     71271
15      9666
16     18676
17     36222
18     66983
19     10864
20       540
21         0
Name: 30, dtype: int64

In [246]:
print(df.columns)
print(df.iloc[3:25, 32])
print(df2.columns)
print(df2.iloc[:, 31])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       5880
4      31521
5      36881
6      17737
7      93829
8      21305
9      50691
10     96202
11     39716
12     18336
13    141686
14      6887
15     22237
16     44641
17     86340
18     12224
19     18776
20     46169
21    125012
22     19430
23      6282
24    941782
Name: Unnamed: 32, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0          0
1      31521
2      26881
3      11737
4       3829
5          0
6      50691
7      96209
8      39716
9      18336
10    141086
11       688
12     22237
13     44647
14     86340
15     12224
16     18776
17     46169
18    125012
19     19430
20       289
21         2
Name: 31, dtype: int64

In [247]:
print(df.columns)
print(df.iloc[3:25, 33])
print(df2.columns)
print(df2.iloc[:, 32])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        371
4       3441
5       4844
6       1024
7       5399
8       2058
9       3894
10      9301
11      4028
12      1832
13     81743
14       722
15      4258
16      8194
17      8544
18      1866
19      2114
20      7947
21     11940
22      1240
23       338
24    165098
Name: Unnamed: 33, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0          0
1       3441
2         48
3       1094
4       5399
5       2058
6         34
7       9301
8       4028
9      18321
10     81743
11         0
12         0
13         0
14         0
15      1866
16        24
17      7947
18     11940
19      1240
20         0
21    165098
Name: 32, dtype: int64

In [248]:
print(df.columns)
print(df.iloc[3:25, 34])
print(df2.columns)
print(df2.iloc[:, 33])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       3269
4      25020
5      29567
6      16968
7      85087
8      19857
9      45830
10     80960
11     34726
12     17333
13    113313
14      5101
15     15019
16     33089
17     73915
18     10762
19     15473
20     33292
21    112824
22     16982
23      6187
24    795574
Name: Unnamed: 34, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0       3260
1      25020
2      29507
3      10968
4      85087
5      10857
6      45830
7     809130
8      34726
9      17333
10    113313
11         0
12     15019
13     33089
14     73915
15     10762
16     15473
17     33292
18    112824
19     16982
20      6187
21         0
Name: 33, dtype: int64

In [249]:
print(df.columns)
print(df.iloc[3:25, 35])
print(df2.columns)
print(df2.iloc[:, 34])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       3640
4      28461
5      34411
6      17992
7      90486
8      21915
9      49724
10     90261
11     38754
12     19165
13    195056
14      6823
15     19277
16     41283
17     82458
18     12628
19     17587
20     41239
21    124764
22     18222
23      6525
24    960672
Name: Unnamed: 35, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0       3640
1       2401
2      31411
3      17992
4      90186
5      21915
6      49794
7      90261
8      38754
9      19165
10    195050
11      6823
12     19277
13      4283
14     82908
15     12628
16     17587
17    412391
18        14
19     18222
20      6525
21         0
Name: 34, dtype: int64

In [250]:
tabela_manual_meninos_alfabetizados = pd.to_numeric(df.iloc[3:25, 30])
tabela_ocr_meninos_alfabetizados = pd.to_numeric(df2.iloc[:, 29])

diferenca_meninos_alfabetizados = tabela_manual_meninos_alfabetizados.values - tabela_ocr_meninos_alfabetizados.values
diferenca_meninos_alfabetizados

array([       0,        0,        9,     1760,    -6900,        0,
              0,    14069,        0,        0,       10,        0,
           2000,        0,        0,        0,        0,        0,
              0,        0,      873, -1400860])

In [251]:
tabela_manual_meninos_analfabetos = pd.to_numeric(df.iloc[3:25, 31])
tabela_ocr_meninos_analfabetos = pd.to_numeric(df2.iloc[:, 30])

diferenca_meninos_analfabetos = tabela_manual_meninos_analfabetos.values - tabela_ocr_meninos_analfabetos.values
diferenca_meninos_analfabetos

array([   5000,     600,   27858,      -9,   75420,      60,       0,
         80001,       0,       0, -191000,       0,       0,       0,
             0,       0,   -3000,       0,       0,    6000,    4861,
        786131])

In [252]:
tabela_manual_meninos_total = pd.to_numeric(df.iloc[3:25, 32])
tabela_ocr_meninos_total = pd.to_numeric(df2.iloc[:, 31])

diferenca_meninos_total = tabela_manual_meninos_total.values - tabela_ocr_meninos_total.values
diferenca_meninos_total

array([  5880,      0,  10000,   6000,  90000,  21305,      0,     -7,
            0,      0,    600,   6199,      0,     -6,      0,      0,
            0,      0,      0,      0,   5993, 941780])

In [253]:
tabela_manual_meninas_alfabetizadas = pd.to_numeric(df.iloc[3:25, 33])
tabela_ocr_meninas_alfabetizadas = pd.to_numeric(df2.iloc[:, 32])

diferenca_meninas_alfabetizadas = tabela_manual_meninas_alfabetizadas.values - tabela_ocr_meninas_alfabetizadas.values
diferenca_meninas_alfabetizadas

array([   371,      0,   4796,    -70,      0,      0,   3860,      0,
            0, -16489,      0,    722,   4258,   8194,   8544,      0,
         2090,      0,      0,      0,    338,      0])

In [254]:
tabela_manual_meninas_analfabetas = pd.to_numeric(df.iloc[3:25, 34])
tabela_ocr_meninas_analfabetas = pd.to_numeric(df2.iloc[:, 33])

diferenca_meninas_analfabetas = tabela_manual_meninas_analfabetas.values - tabela_ocr_meninas_analfabetas.values
diferenca_meninas_analfabetas

array([      9,       0,      60,    6000,       0,    9000,       0,
       -728170,       0,       0,       0,    5101,       0,       0,
             0,       0,       0,       0,       0,       0,       0,
        795574])

In [255]:
tabela_manual_meninas_total = pd.to_numeric(df.iloc[3:25, 35])
tabela_ocr_meninas_total = pd.to_numeric(df2.iloc[:, 34])

diferenca_meninas_total = tabela_manual_meninas_total.values - tabela_ocr_meninas_total.values
diferenca_meninas_total

array([      0,   26060,    3000,       0,     300,       0,     -70,
             0,       0,       0,       6,       0,       0,   37000,
          -450,       0,       0, -371152,  124750,       0,       0,
        960672])

In [256]:
variancia_meninos_alfabetizados = np.var(diferenca_meninos_alfabetizados)
variancia_meninos_alfabetizados

85225491476.11775

In [257]:
variancia_meninos_analfabetos = np.var(diferenca_meninos_analfabetos)
variancia_meninos_analfabetos

29042498293.24793

In [258]:
variancia_meninos_total = np.var(diferenca_meninos_total)
variancia_meninos_total

38271250993.35538

In [259]:
variancia_meninas_alfabetizadas = np.var(diferenca_meninas_alfabetizadas)
variancia_meninas_alfabetizadas

20939093.239669416

In [260]:
variancia_meninas_analfabetas = np.var(diferenca_meninas_analfabetas)
variancia_meninas_analfabetas

52861998273.140495

In [261]:
variancia_meninas_total = np.var(diferenca_meninas_total)
variancia_meninas_total

47754623213.785126

In [262]:
desvio_padrao_meninos_alfabetizados = np.std(diferenca_meninos_alfabetizados)
desvio_padrao_meninos_alfabetizados

291934.0532999152

In [263]:
desvio_padrao_meninos_analfabetos = np.std(diferenca_meninos_analfabetos)
desvio_padrao_meninos_analfabetos

170418.5972634675

In [264]:
desvio_padrao_meninos_total = np.std(diferenca_meninos_total)
desvio_padrao_meninos_total

195630.39383836903

In [265]:
desvio_padrao_meninas_alfabetizadas = np.std(diferenca_meninas_alfabetizadas)
desvio_padrao_meninas_alfabetizadas

4575.925397083022

In [266]:
desvio_padrao_meninas_analfabetas = np.std(diferenca_meninas_analfabetas)
desvio_padrao_meninas_analfabetas

229917.3727084156

In [267]:
desvio_padrao_meninas_total = np.std(diferenca_meninas_total)
desvio_padrao_meninas_total

218528.31215607998

In [268]:
coeficiente_variacao_meninos_alfabetizados = desvio_padrao_meninos_alfabetizados / np.mean(diferenca_meninos_alfabetizados) * 100
coeficiente_variacao_meninos_alfabetizados

-462.3735670919344

In [269]:
coeficiente_variacao_meninos_analfabetos = desvio_padrao_meninos_analfabetos / np.mean(diferenca_meninos_analfabetos) * 100
coeficiente_variacao_meninos_analfabetos

473.43161823971116

In [270]:
coeficiente_variacao_meninos_total = desvio_padrao_meninos_total / np.mean(diferenca_meninos_total) * 100
coeficiente_variacao_meninos_total

395.669262661446

In [271]:
coeficiente_variacao_meninas_alfabetizadas = desvio_padrao_meninas_alfabetizadas / np.mean(diferenca_meninas_alfabetizadas) * 100
coeficiente_variacao_meninas_alfabetizadas

605.9369130602292

In [272]:
coeficiente_variacao_meninas_analfabetas = desvio_padrao_meninas_analfabetas / np.mean(diferenca_meninas_analfabetas) * 100
coeficiente_variacao_meninas_analfabetas

5775.894899839157

In [273]:
coeficiente_variacao_meninas_total = desvio_padrao_meninas_total / np.mean(diferenca_meninas_total) * 100
coeficiente_variacao_meninas_total

616.2702556329775

In [274]:
print(f'Variância (meninos alfabetizados): {variancia_meninos_alfabetizados}')
print(f'Desvio Padrão (meninos alfabetizados): {desvio_padrao_meninos_alfabetizados}')
print(f'Coeficiente de Variação (meninos alfabetizados): {coeficiente_variacao_meninos_alfabetizados}%')

Variância (meninos alfabetizados): 85225491476.11775
Desvio Padrão (meninos alfabetizados): 291934.0532999152
Coeficiente de Variação (meninos alfabetizados): -462.3735670919344%

In [275]:
print(f'Variância (meninos analfabetos): {variancia_meninos_analfabetos}')
print(f'Desvio Padrão (meninos analfabetos): {desvio_padrao_meninos_analfabetos}')
print(f'Coeficiente de Variação (meninos analfabetos): {coeficiente_variacao_meninos_analfabetos}%')

Variância (meninos analfabetos): 29042498293.24793
Desvio Padrão (meninos analfabetos): 170418.5972634675
Coeficiente de Variação (meninos analfabetos): 473.43161823971116%

In [276]:
print(f'Variância (meninos total): {variancia_meninos_total}')
print(f'Desvio Padrão (meninos total): {desvio_padrao_meninos_total}')
print(f'Coeficiente de Variação (meninos total): {coeficiente_variacao_meninos_total}%')

Variância (meninos total): 38271250993.35538
Desvio Padrão (meninos total): 195630.39383836903
Coeficiente de Variação (meninos total): 395.669262661446%

In [277]:
print(f'Variância (meninas alfabetizadas): {variancia_meninas_alfabetizadas}')
print(f'Desvio Padrão (meninas alfabetizadas): {desvio_padrao_meninas_alfabetizadas}')
print(f'Coeficiente de Variação (meninas alfabetizadas): {coeficiente_variacao_meninas_alfabetizadas}%')

Variância (meninas alfabetizadas): 20939093.239669416
Desvio Padrão (meninas alfabetizadas): 4575.925397083022
Coeficiente de Variação (meninas alfabetizadas): 605.9369130602292%

In [278]:
print(f'Variância (meninas alfabetizadas): {variancia_meninas_alfabetizadas}')
print(f'Desvio Padrão (meninas alfabetizadas): {desvio_padrao_meninas_alfabetizadas}')
print(f'Coeficiente de Variação (meninas alfabetizadas): {coeficiente_variacao_meninas_alfabetizadas}%')

Variância (meninas alfabetizadas): 20939093.239669416
Desvio Padrão (meninas alfabetizadas): 4575.925397083022
Coeficiente de Variação (meninas alfabetizadas): 605.9369130602292%

In [279]:
print(f'Variância (meninas total): {variancia_meninas_total}')
print(f'Desvio Padrão (meninas total): {desvio_padrao_meninas_total}')
print(f'Coeficiente de Variação (meninas total): {coeficiente_variacao_meninas_total}%')

Variância (meninas total): 47754623213.785126
Desvio Padrão (meninas total): 218528.31215607998
Coeficiente de Variação (meninas total): 616.2702556329775%

In [280]:
media_meninos_alfabetizados = np.mean(diferenca_meninos_alfabetizados)
media_meninos_alfabetizados

-63138.13636363636

In [281]:
media_meninos_analfabetos = np.mean(diferenca_meninos_analfabetos)
media_meninos_analfabetos

35996.454545454544

In [282]:
media_meninos_total = np.mean(diferenca_meninos_total)
media_meninos_total

49442.90909090909

In [283]:
media_meninas_alfabetizadas = np.mean(diferenca_meninas_alfabetizadas)
media_meninas_alfabetizadas

755.1818181818181

In [284]:
media_meninas_analfabetas = np.mean(diferenca_meninas_analfabetas)
media_meninas_analfabetas

3980.6363636363635

In [285]:
media_meninas_total = np.mean(diferenca_meninas_total)
media_meninas_total

35459.818181818184

In [286]:
outlier_inferior_meninos_alfabetizados = media_meninos_alfabetizados - (3 * desvio_padrao_meninos_alfabetizados)
outlier_superior_meninos_alfabetizados = media_meninos_alfabetizados + (3 * desvio_padrao_meninos_alfabetizados)

print(outlier_inferior_meninos_alfabetizados, outlier_superior_meninos_alfabetizados)

-938940.296263382 812664.0235361092

In [287]:
outlier_inferior_meninos_analfabetos = media_meninos_analfabetos - (3 * desvio_padrao_meninos_analfabetos)
outlier_superior_meninos_analfabetos = media_meninos_analfabetos + (3 * desvio_padrao_meninos_analfabetos)

print(outlier_inferior_meninos_analfabetos, outlier_superior_meninos_analfabetos)

-475259.33724494796 547252.2463358571

In [288]:
outlier_inferior_meninos_total = media_meninos_total - (3 * desvio_padrao_meninos_total)
outlier_superior_meninos_total = media_meninos_total + (3 * desvio_padrao_meninos_total)

print(outlier_inferior_meninos_total, outlier_superior_meninos_total)

-537448.272424198 636334.0906060161

In [289]:
outlier_inferior_meninas_alfabetizadas = media_meninas_alfabetizadas - (3 * desvio_padrao_meninas_alfabetizadas)
outlier_superior_meninas_alfabetizadas = media_meninas_alfabetizadas + (3 * desvio_padrao_meninas_alfabetizadas)

print(outlier_inferior_meninas_alfabetizadas, outlier_superior_meninas_alfabetizadas)

-12972.59437306725 14482.958009430886

In [290]:
outlier_inferior_meninas_analfabetas = media_meninas_analfabetas - (3 * desvio_padrao_meninas_analfabetas)
outlier_superior_meninas_analfabetas = media_meninas_analfabetas + (3 * desvio_padrao_meninas_analfabetas)

print(outlier_inferior_meninas_analfabetas, outlier_superior_meninas_analfabetas)

-685771.4817616105 693732.7544888832

In [291]:
outlier_inferior_meninas_total = media_meninas_total - (3 * desvio_padrao_meninas_total)
outlier_superior_meninas_total = media_meninas_total + (3 * desvio_padrao_meninas_total)

print(outlier_inferior_meninas_total, outlier_superior_meninas_total)

-620125.1182864216 691044.7546500581

# Casas

In [292]:
casas = df[['Unnamed: 0','Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38']]

casas_header = casas.iloc[2]
casas.columns = casas_header
casas = casas[3:]

columns_multiindex = pd.MultiIndex.from_tuples([
    ('', 'Províncias e Município Neutro'),
    ('Casas', 'Habitadas'),
    ('Casas', 'Desabitadas'),
    ('Casas', 'Total')
])

casas.columns = columns_multiindex

casas

                                     Casas
   Províncias e Município Neutro Habitadas Desabitadas    Total
3                       Amazonas      7661         229     7890
4                           Pará     38978        2077    41055
5                       Maranhão     47166        1405    48571
6                          Piauí     29208         223    29431
7                          Ceará     99901        2989   102890
8            Rio Grande do Norte     36710         706    37416
9                        Paraíba     43767         522    44289
10                    Pernambuco    133920        4381   188301
11                       Alagoas     55894        2030    57924
12                       Sergipe     25542         567    26109
13                         Bahia    176032        5479   181511
14                Espírito Santo     10742        1079    11821
15              Município Neutro     29045        1873    80918
16                Rio de Janeiro     88698        2844    91542
17                     São Paulo     65778        1000    66778
18                        Paraná     18903         259    19162
19                Santa Catarina     19608         528    20136
20             Rio Grande do Sul     60199        1741    61940
21                  Minas Gerais    275611        3629   279240
22                         Goiás     25196         487    25683
23                   Mato Grosso      7501         102     7603
24                         Total   1296060       34150  1330210

In [293]:
print(df.columns)
print(df.iloc[3:25, 36])
print(df2.columns)
print(df2.iloc[:, 35])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        7661
4       38978
5       47166
6       29208
7       99901
8       36710
9       43767
10     133920
11      55894
12      25542
13     176032
14      10742
15      29045
16      88698
17      65778
18      18903
19      19608
20      60199
21     275611
22      25196
23       7501
24    1296060
Name: Unnamed: 36, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0         661
1         978
2       47166
3       24208
4       99903
5       36710
6       43767
7     1339201
8       55804
9         254
10     176032
11        742
12      29045
13       8698
14     657781
15      18903
16      19608
17      60199
18     275611
19      25196
20       7501
21    1290000
Name: 35, dtype: int64

In [294]:
print(df.columns)
print(df.iloc[3:25, 37])
print(df2.columns)
print(df2.iloc[:, 36])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3       229
4      2077
5      1405
6       223
7      2989
8       706
9       522
10     4381
11     2030
12      567
13     5479
14     1079
15     1873
16     2844
17     1000
18      259
19      528
20     1741
21     3629
22      487
23      102
24    34150
Name: Unnamed: 37, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0       229
1      2077
2      3405
3       223
4      2989
5       706
6       522
7      4381
8      2030
9       567
10      519
11     1079
12     1573
13     2843
14     1000
15      259
16      528
17       74
18     3629
19      487
20       33
21    34150
Name: 36, dtype: int64

In [295]:
print(df.columns)
print(df.iloc[3:25, 38])
print(df2.columns)
print(df2.iloc[:, 37])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        7890
4       41055
5       48571
6       29431
7      102890
8       37416
9       44289
10     188301
11      57924
12      26109
13     181511
14      11821
15      80918
16      91542
17      66778
18      19162
19      20136
20      61940
21     279240
22      25683
23       7603
24    1330210
Name: Unnamed: 38, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0       7809
1      61055
2      48571
3      29431
4     102890
5      37416
6      44989
7          0
8      67924
9      20109
10     18511
11     11821
12     20918
13     91512
14     66778
15     19162
16     20136
17     61940
18        40
19     23083
20      7603
21    138021
Name: 37, dtype: int64

In [296]:
tabela_manual_casas_habitadas = pd.to_numeric(df.iloc[3:25, 36])
tabela_ocr_casas_habitadas = pd.to_numeric(df2.iloc[:, 35])

diferenca_casas_habitadas = tabela_manual_casas_habitadas.values - tabela_ocr_casas_habitadas.values
diferenca_casas_habitadas

array([    7000,    38000,        0,     5000,       -2,        0,
              0, -1205281,       90,    25288,        0,    10000,
              0,    80000,  -592003,        0,        0,        0,
              0,        0,        0,     6060])

In [297]:
tabela_manual_casas_desabitadas = pd.to_numeric(df.iloc[3:25, 37])
tabela_ocr_casas_desabitadas = pd.to_numeric(df2.iloc[:, 36])

diferenca_casas_desabitadas = tabela_manual_casas_desabitadas.values - tabela_ocr_casas_desabitadas.values
diferenca_casas_desabitadas

array([    0,     0, -2000,     0,     0,     0,     0,     0,     0,
           0,  4960,     0,   300,     1,     0,     0,     0,  1667,
           0,     0,    69,     0])

In [298]:
tabela_manual_casas_total = pd.to_numeric(df.iloc[3:25, 38])
tabela_ocr_casas_total = pd.to_numeric(df2.iloc[:, 37])

diferenca_casas_total = tabela_manual_casas_total.values - tabela_ocr_casas_total.values
diferenca_casas_total

array([     81,  -20000,       0,       0,       0,       0,    -700,
        188301,  -10000,    6000,  163000,       0,   60000,      30,
             0,       0,       0,       0,  279200,    2600,       0,
       1192189])

In [299]:
variancia_casas_habitadas = np.var(diferenca_casas_habitadas)
variancia_casas_habitadas

76895924596.05785

In [300]:
variancia_casas_desabitadas = np.var(diferenca_casas_desabitadas)
variancia_casas_desabitadas

1379102.2995867764

In [301]:
variancia_casas_total = np.var(diferenca_casas_total)
variancia_casas_total

64002894330.21694

In [302]:
desvio_padrao_casas_habitadas = np.std(diferenca_casas_habitadas)
desvio_padrao_casas_habitadas

277301.1442386379

In [303]:
desvio_padrao_casas_desabitadas = np.std(diferenca_casas_desabitadas)
desvio_padrao_casas_desabitadas

1174.3518636195781

In [304]:
desvio_padrao_casas_total = np.std(diferenca_casas_total)
desvio_padrao_casas_total

252987.9331711632

In [305]:
coeficiente_variacao_casas_habitadas = desvio_padrao_casas_habitadas / np.mean(diferenca_casas_habitadas) * 100
coeficiente_variacao_casas_habitadas

-375.2272766734672

In [306]:
coeficiente_variacao_casas_desabitadas = desvio_padrao_casas_desabitadas / np.mean(diferenca_casas_desabitadas) * 100
coeficiente_variacao_casas_desabitadas

517.0250350136226

In [307]:
coeficiente_variacao_casas_total = desvio_padrao_casas_total / np.mean(diferenca_casas_total) * 100
coeficiente_variacao_casas_total

299.1203062590707

In [308]:
print(f'Variância (casas habitadas): {variancia_casas_habitadas}')
print(f'Desvio Padrão (casas habitadas): {desvio_padrao_casas_habitadas}')
print(f'Coeficiente de Variação (casas habitadas): {coeficiente_variacao_casas_habitadas}%')

Variância (casas habitadas): 76895924596.05785
Desvio Padrão (casas habitadas): 277301.1442386379
Coeficiente de Variação (casas habitadas): -375.2272766734672%

In [309]:
print(f'Variância (casas desabitadas): {variancia_casas_desabitadas}')
print(f'Desvio Padrão (casas desabitadas): {desvio_padrao_casas_desabitadas}')
print(f'Coeficiente de Variação (casas desabitadas): {coeficiente_variacao_casas_desabitadas}%')

Variância (casas desabitadas): 1379102.2995867764
Desvio Padrão (casas desabitadas): 1174.3518636195781
Coeficiente de Variação (casas desabitadas): 517.0250350136226%

In [310]:
print(f'Variância (casas total): {variancia_casas_total}')
print(f'Desvio Padrão (casas total): {desvio_padrao_casas_total}')
print(f'Coeficiente de Variação (casas total): {coeficiente_variacao_casas_total}%')

Variância (casas total): 64002894330.21694
Desvio Padrão (casas total): 252987.9331711632
Coeficiente de Variação (casas total): 299.1203062590707%

In [311]:
media_casas_habitadas = np.mean(diferenca_casas_habitadas)
media_casas_habitadas

-73902.18181818182

In [312]:
media_casas_desabitadas = np.mean(diferenca_casas_desabitadas)
media_casas_desabitadas

227.13636363636363

In [313]:
media_casas_total = np.mean(diferenca_casas_total)
media_casas_total

84577.31818181818

In [314]:
outlier_inferior_casas_habitadas = media_casas_habitadas - (3 * desvio_padrao_casas_habitadas)
outlier_superior_casas_habitadas = media_casas_habitadas + (3 * desvio_padrao_casas_habitadas)

print(outlier_inferior_casas_habitadas, outlier_superior_casas_habitadas)

-905805.6145340954 758001.2508977319

In [315]:
outlier_inferior_casas_desabitadas = media_casas_desabitadas - (3 * desvio_padrao_casas_desabitadas)
outlier_superior_casas_desabitadas = media_casas_desabitadas + (3 * desvio_padrao_casas_desabitadas)

print(outlier_inferior_casas_desabitadas, outlier_superior_casas_desabitadas)

-3295.919227222371 3750.191954495098

In [316]:
outlier_inferior_casas_total = media_casas_total - (3 * desvio_padrao_casas_total)
outlier_superior_casas_total = media_casas_total + (3 * desvio_padrao_casas_total)

print(outlier_inferior_casas_total, outlier_superior_casas_total)

-674386.4813316714 843541.1176953078

# Fogos

In [317]:
fogos = df[['Unnamed: 0', 'Unnamed: 39']]

fogos_header = fogos.iloc[2]
fogos.columns = fogos_header
fogos = fogos[3:]

fogos

2  Províncias e Município Neutro Número de fogos
3                       Amazonas            7811
4                           Pará           39521
5                       Maranhão           49282
6                          Piauí           30770
7                          Ceará          100207
8            Rio Grande do Norte           37320
9                        Paraíba           44438
10                    Pernambuco          134765
11                       Alagoas           60386
12                       Sergipe           24950
13                         Bahia          180307
14                Espírito Santo           10774
15              Município Neutro           44211
16                Rio de Janeiro           90232
17                     São Paulo           65960
18                        Paraná           22026
19                Santa Catarina           14457
20             Rio Grande do Sul           61394
21                  Minas Gerais          280660
22                         Goiás           25222
23                   Mato Grosso            7581
24                         Total         1332274

In [318]:
print(df.columns)
print(df.iloc[3:25, 39])
print(df2.columns)
print(df2.iloc[:, 38])

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Instrução',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39'],
      dtype='object')
3        7811
4       39521
5       49282
6       30770
7      100207
8       37320
9       44438
10     134765
11      60386
12      24950
13     180307
14      10774
15      44211
16      90232
17      65960
18      22026
19      14457
20      61394
21     280660
22      25222
23       7581
24    1332274
Name: Unnamed: 39, dtype: object
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38],
      dtype='int64')
0           0
1        9521
2       49282
3       30770
4     1002071
5       37320
6       44438
7      184765
8       60386
9       24950
10     120807
11      10774
12      44211
13      90232
14      65960
15      42026
16      11457
17      61394
18     280660
19      25222
20          0
21          0
Name: 38, dtype: int64

In [319]:
tabela_manual_fogos = pd.to_numeric(df.iloc[3:25, 39])
tabela_ocr_fogos = pd.to_numeric(df2.iloc[:, 38])

diferenca_fogos = tabela_manual_fogos.values - tabela_ocr_fogos.values
diferenca_fogos

array([   7811,   30000,       0,       0, -901864,       0,       0,
        -50000,       0,       0,   59500,       0,       0,       0,
             0,  -20000,    3000,       0,       0,       0,    7581,
       1332274])

In [320]:
variancia_fogos = np.var(diferenca_fogos)
variancia_fogos

117536905891.70248

In [321]:
desvio_padrao_fogos = np.std(diferenca_fogos)
desvio_padrao_fogos

342836.55856938957

In [322]:
coeficiente_variacao_fogos = desvio_padrao_fogos / np.mean(diferenca_fogos) * 100
coeficiente_variacao_fogos

1610.585538504335

In [323]:
print(f'Variância (fogos): {variancia_fogos}')
print(f'Desvio Padrão (fogos): {desvio_padrao_fogos}')
print(f'Coeficiente de Variação (fogos): {coeficiente_variacao_fogos}%')

Variância (fogos): 117536905891.70248
Desvio Padrão (fogos): 342836.55856938957
Coeficiente de Variação (fogos): 1610.585538504335%

In [324]:
media_fogos = np.mean(diferenca_fogos)
media_fogos

21286.454545454544

In [325]:
outlier_inferior_fogos = media_fogos - (3 * desvio_padrao_fogos)
outlier_superior_fogos = media_fogos + (3 * desvio_padrao_fogos)

print(outlier_inferior_fogos, outlier_superior_fogos)

-1007223.2211627141 1049796.1302536232